import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { createBusinessSourceEvidence } from "../business-intelligence/evidence.js";
import { applyFounderBusinessReview, applyFounderBusinessReviewFromFiles, parseFounderBusinessReview } from "../business-intelligence/founderValidation.js";
import { validateBusinessIntelligenceObject } from "../business-intelligence/validation.js";

const NOW = "2026-08-15T12:00:00.000Z";
const evidence = createBusinessSourceEvidence({ sourceType: "homepage", sourceUriOrLocation: "https://example.test/", sourceRole: "business_statement", sourceField: "page.statement", rawValue: "Dependable equipment", retrievedAt: NOW, claimClassification: "positioning_claim" });
const fact = (value, refs = [evidence.id]) => ({ value, knowledge_type: "fact", assertion_scope: "objective", evidence_refs: refs, confidence: 0.9, status: "extracted" });
const unknown = () => ({ value: null, knowledge_type: "unknown", assertion_scope: "unknown", evidence_refs: [], confidence: 0, status: "inferred" });
function bioFixture() { return { metadata: { object_id: "bio_example", schema_version: "1.0.0", business_id: "example", primary_domain: "https://example.test", created_at: NOW, updated_at: NOW, source_fingerprint: "fingerprint", ingestion_status: "interpreted" }, business_identity: { business_name: fact("Example Supply"), business_type: fact("retailer"), owned_brand_status: unknown(), geographic_market: unknown() }, catalogue_understanding: { product_focus: fact("Practical equipment"), primary_categories: [fact("Equipment")], catalogue_coherence: fact("focused") }, audience_architecture: { type: unknown(), business_wide_profile_status: unknown() }, customer_understanding: { target_customer_groups: [fact("A broad proposed audience", [evidence.id])], customer_behaviours: [], customer_motivations: [], customer_priorities: [], customer_problems: [], purchase_drivers: [], exclusions: [] }, positioning: { value_proposition: [], positioning_themes: [], differentiators: [], positioning_claims: [], price_value_orientation: unknown() }, category_audiences: [], knowledge_gaps: [], source_evidence: [evidence], conflicts: [], human_validation_decisions: [], human_corrections: [], validation_status: "awaiting_validation", execution_metadata: { deterministic_steps: [], ai_calls: [], external_api_call_count: 0 } }; }
const review = `# Review\n\n- [ ] Yes, this accurately represents the business\n- [x] Mostly, but I need to correct or clarify something\n- [ ] No, there are important misunderstandings\n\n### Anything you'd like to correct or add?\n\nOwn-brand products are the primary focus, although third-party products may also be sold.\nThe primary geographic market is Canada.\nThe business primarily serves one core audience: independent household buyers. Professional contractors are not the intended core audience.\nQuality and results are more important than low price.\n`;

test("completed founder Markdown is parsed with exactly one selected option and preserved clarification", () => { const parsed = parseFounderBusinessReview(review); assert.match(parsed.selected_option, /^Mostly/); assert.match(parsed.clarification_text, /primary geographic market is Canada/); });
test("ambiguous founder selection fails closed", () => { assert.throws(() => parseFounderBusinessReview(review.replace("[ ] Yes", "[x] Yes")), /exactly one/); });
test("founder corrections become effective while original AI knowledge remains auditable", () => { const original = bioFixture(); const before = structuredClone(original); const result = applyFounderBusinessReview({ bio: original, review, reviewer: "owner", createdAt: NOW }); assert.equal(result.bio.validation_status, "validated"); assert.equal(result.bio.business_identity.geographic_market.value, "Canada"); assert.equal(result.bio.business_identity.geographic_market.status, "human_corrected"); assert.equal(result.bio.customer_understanding.target_customer_groups[0].value, "independent household buyers"); assert.ok(result.corrections.length >= 4); assert.equal(result.corrections[0].provenance.source_type, "human_validation"); assert.deepEqual(original, before); assert.deepEqual(result.bio.business_identity.geographic_market.evidence_refs, []); assert.deepEqual(validateBusinessIntelligenceObject(result.bio), []); });
test("explicit founder audience resolves unknown architecture without an AI pass", () => { const result = applyFounderBusinessReview({ bio: bioFixture(), review, createdAt: NOW }); assert.equal(result.bio.audience_architecture.type.value, "focused_business"); assert.equal(result.bio.audience_architecture.business_wide_profile_status.value, "meaningful"); assert.equal(result.bio.audience_architecture.type.status, "human_corrected"); });
test("artifact application writes validated BIO, metadata and deterministic final report", async (t) => { const root = await mkdtemp(path.join(os.tmpdir(), "bio-founder-validation-")); t.after(() => rm(root, { recursive: true, force: true })); const bioPath = path.join(root, "bio.json"); const reviewPath = path.join(root, "review.md"); const outputRoot = path.join(root, "out"); await import("node:fs/promises").then(({ writeFile }) => Promise.all([writeFile(bioPath, JSON.stringify(bioFixture())), writeFile(reviewPath, review)])); const result = await applyFounderBusinessReviewFromFiles({ bioPath, reviewPath, outputRoot, createdAt: NOW }); assert.ok(result.files.businessIntelligence.endsWith("business-intelligence-validated.json")); assert.ok(result.files.metadata.endsWith("founder-validation-metadata.json")); assert.ok(result.files.founderReview.endsWith("founder-review-final.md")); assert.match(await readFile(result.files.founderReview, "utf8"), /Validated audience structure/); assert.equal(result.bio.execution_metadata.ai_calls.length, 0); });
