import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { createBusinessSourceEvidence } from "../business-intelligence/evidence.js";
import { interpretBusinessEvidence } from "../business-intelligence/interpretation.js";
import { businessIntelligenceInterpretationJsonSchema, partitionBusinessInterpretationEvidence, selectRelevantBusinessEvidence } from "../business-intelligence/interpretationPrompt.js";
import { FIELD_EVIDENCE_ELIGIBILITY } from "../business-intelligence/interpretationValidation.js";
import { createOpenAIInterpretationProvider } from "../interpretation/providers/openai.js";
import { createOpenAIResponsesInterpretationProvider } from "../interpretation/providers/openaiResponses.js";
import { interpretBusinessEvidenceInPasses, renderBusinessIntelligenceFounderReview, writeBusinessIntelligenceFounderReview } from "../business-intelligence/multiPassInterpretation.js";

const WHEN = "2026-08-14T10:00:00.000Z";
const identity = createBusinessSourceEvidence({ sourceType: "homepage", sourceUriOrLocation: "https://example.test/", sourceRole: "business_statement", sourceField: "page.title", rawValue: "Northstar Supply", retrievedAt: WHEN, claimClassification: "observed_fact" });
const navigation = createBusinessSourceEvidence({ sourceType: "navigation", sourceUriOrLocation: "https://example.test/", sourceRole: "observed_structure", sourceField: "navigation.link", rawValue: '<a href="/collections/tools">Tools</a>', normalisedValue: { label: "Tools", destination_url: "https://example.test/collections/tools" }, retrievedAt: WHEN, claimClassification: "observed_fact" });
const positioning = createBusinessSourceEvidence({ sourceType: "homepage", sourceUriOrLocation: "https://example.test/", sourceRole: "business_statement", sourceField: "page.statement", rawValue: "Dependable equipment without unnecessary complexity.", retrievedAt: WHEN, claimClassification: "positioning_claim" });
const audience = createBusinessSourceEvidence({ sourceType: "about_page", sourceUriOrLocation: "https://example.test/about/", sourceRole: "business_statement", sourceField: "page.statement", rawValue: "Designed for people tackling practical outdoor projects.", retrievedAt: WHEN, claimClassification: "customer_claim" });
const evidence = [identity, navigation, positioning, audience];
const rawArtifact = { schema_version: "1.0.0", artifact_type: "business_intelligence_raw_evidence", business_url: "https://example.test/", created_at: WHEN, source_fingerprint: "source-hash", evidence, execution_metadata: { ai_calls: 0 } };
const fact = (value, ref = identity.id) => ({ value, knowledge_type: "fact", assertion_scope: "objective", evidence_refs: [ref], confidence: 0.96, status: "extracted" });
const derived = (value, ref = navigation.id, confidence = 0.82) => ({ value, knowledge_type: "derived", assertion_scope: "interpretation", evidence_refs: [ref], confidence, status: "inferred" });
const inferred = (value, ref = audience.id, confidence = 0.7) => ({ value, knowledge_type: "inference", assertion_scope: "interpretation", evidence_refs: [ref], confidence, status: "inferred" });
const unknown = () => ({ value: null, knowledge_type: "unknown", assertion_scope: "unknown", evidence_refs: [], confidence: 0, status: "inferred" });
const claim = (value, ref = positioning.id) => ({ value, knowledge_type: "fact", assertion_scope: "business_claim", evidence_refs: [ref], confidence: 0.95, status: "extracted" });

function proposal() {
  return {
    business_identity: { business_name: fact("Northstar Supply"), business_type: derived("retailer"), owned_brand_status: unknown(), geographic_market: unknown(), sales_channel: derived("Ecommerce website"), business_description: derived("Retailer of practical outdoor equipment") },
    catalogue_understanding: { product_focus: derived("Outdoor project equipment"), primary_categories: [fact("Tools", navigation.id)], catalogue_coherence: derived("focused"), secondary_categories: [], representative_product_refs: [], catalogue_limitations: [] },
    audience_architecture: { type: inferred("focused_business"), business_wide_profile_status: inferred("meaningful") },
    customer_understanding: { target_customer_groups: [inferred("People undertaking practical outdoor projects")], customer_behaviours: [], customer_motivations: [], customer_priorities: [], customer_problems: [], purchase_drivers: [], exclusions: [] },
    positioning: { value_proposition: [derived("Dependable, uncomplicated equipment", positioning.id)], positioning_themes: [claim("Without unnecessary complexity")], differentiators: [], positioning_claims: [claim("Dependable equipment without unnecessary complexity")], price_value_orientation: unknown() },
    category_audiences: [], knowledge_gaps: [{ field: "positioning.price_value_orientation", importance: "medium", reason: "No reliable price-position evidence was supplied.", evidence_refs: [] }], conflicts: [], assumptions: []
  };
}
function provider(output = proposal(), expectedEvidence = evidence) {
  return { id: "mock", model: "mock-business-model", async generate({ userPrompt, responseSchema }) {
    assert.ok(userPrompt.includes(identity.id));
    assert.deepEqual(responseSchema.$defs.evidence_id.enum.sort(), expectedEvidence.map((item) => item.id).sort());
    return { provider: "mock", model: "mock-business-model", rawText: JSON.stringify(output), usage: { prompt_tokens: 120, completion_tokens: 80 }, estimated_cost: 0.001 };
  } };
}

test("valid AI output creates a valid BIO with preserved evidence references", async () => {
  const result = await interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(), writeArtifacts: false, now: () => new Date(WHEN), monotonicNow: (() => { let n = 0; return () => n += 5; })() });
  assert.equal(result.bio.business_identity.business_name.evidence_refs[0], identity.id);
  assert.deepEqual(result.bio.source_evidence, evidence);
  assert.equal(result.validationReport.valid, true);
});
test("unsupported knowledge without evidence is rejected", async () => { const output = proposal(); output.customer_understanding.purchase_drivers.push(inferred("A fabricated driver", audience.id)); output.customer_understanding.purchase_drivers[0].evidence_refs = []; await assert.rejects(() => interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(output), writeArtifacts: false }), /failed validation/); });
test("unknown knowledge is allowed", async () => { const result = await interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(), writeArtifacts: false }); assert.ok(result.validationReport.unknowns_created.length >= 3); });
test("unsupported geography remains unknown and indirect geography inference is rejected", async () => { const valid = await interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(), writeArtifacts: false }); assert.equal(valid.bio.business_identity.geographic_market.knowledge_type, "unknown"); const output = proposal(); output.business_identity.geographic_market = inferred("A market inferred from indirect signals", positioning.id); await assert.rejects(() => interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(output), writeArtifacts: false }), (error) => error.errors.some((item) => item.includes("cannot be inferred from indirect signals"))); });
test("no global audience is forced", async () => { const output = proposal(); output.audience_architecture.type = inferred("unknown"); output.audience_architecture.business_wide_profile_status = inferred("insufficient_evidence"); output.customer_understanding.target_customer_groups = []; const result = await interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(output), writeArtifacts: false }); assert.equal(result.bio.customer_understanding.target_customer_groups.length, 0); });
test("general store output is valid", async () => { const output = proposal(); output.catalogue_understanding.catalogue_coherence = derived("unrelated_general_store"); output.audience_architecture.type = inferred("general_store"); output.audience_architecture.business_wide_profile_status = inferred("not_meaningful"); output.customer_understanding.target_customer_groups = []; const result = await interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(output), writeArtifacts: false }); assert.equal(result.bio.audience_architecture.type.value, "general_store"); });
test("positioning claims stay separate from objective facts", async () => { const result = await interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(), writeArtifacts: false }); assert.equal(result.bio.positioning.positioning_claims[0].assertion_scope, "business_claim"); assert.equal(result.bio.business_identity.business_name.assertion_scope, "objective"); });
test("business claims coexist with objective catalogue structure", async () => { const result = await interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(), writeArtifacts: false }); assert.equal(result.bio.catalogue_understanding.primary_categories[0].assertion_scope, "objective"); assert.equal(result.bio.catalogue_understanding.primary_categories[0].evidence_refs[0], navigation.id); assert.equal(result.bio.positioning.positioning_claims[0].assertion_scope, "business_claim"); assert.equal(result.bio.positioning.positioning_claims[0].evidence_refs[0], positioning.id); });
test("positioning fields cannot become objective even with observed evidence", async () => { const output = proposal(); output.positioning.value_proposition = [fact("Observed positioning", identity.id)]; await assert.rejects(() => interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(output), writeArtifacts: false }), (error) => error.errors.some((item) => item.includes("cannot be objective in this interpretation field"))); });
test("structured-output schema excludes objective scope from positioning", () => { const field = businessIntelligenceInterpretationJsonSchema().properties.positioning.properties.value_proposition.items; assert.deepEqual(field.anyOf[0].properties.assertion_scope.enum, ["business_claim"]); assert.ok(field.anyOf.every((variant) => !variant.properties.assertion_scope.enum.includes("objective"))); });
test("marketing evidence cannot support an objective fact", async () => { const output = proposal(); output.business_identity.business_name = fact("Best supplier", positioning.id); await assert.rejects(() => interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(output), writeArtifacts: false }), (error) => error.errors.some((item) => item.includes("objective fact cannot be supported"))); });
test("evaluative marketing language cannot become an objective catalogue fact", async () => { for (const modifier of ["Premium", "Professional", "Best", "Leading", "Superior", "Advanced", "High-performance", "Luxury", "Ultimate"]) { const output = proposal(); output.catalogue_understanding.primary_categories = [fact(`${modifier} tools`, navigation.id)]; await assert.rejects(() => interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(output), writeArtifacts: false }), (error) => error.errors.some((item) => item.includes("evaluative marketing language"))); } });
test("observable catalogue facts remain objective", async () => { const result = await interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(), writeArtifacts: false }); assert.equal(result.bio.catalogue_understanding.primary_categories[0].value, "Tools"); assert.equal(result.bio.catalogue_understanding.primary_categories[0].assertion_scope, "objective"); });
test("objective representative products reject every claim-classified evidence reference", async () => { const output = proposal(); output.catalogue_understanding.representative_product_refs = [{ ...fact("Tools", navigation.id), evidence_refs: [navigation.id, positioning.id] }]; await assert.rejects(() => interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(output), writeArtifacts: false }), (error) => error.errors.some((item) => item.includes("ineligible for objective_representative_product: positioning_claim"))); });
test("objective representative products accept observed-fact evidence", async () => { const output = proposal(); output.catalogue_understanding.representative_product_refs = [fact("Tools", navigation.id)]; const result = await interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(output), writeArtifacts: false }); assert.equal(result.bio.catalogue_understanding.representative_product_refs[0].evidence_refs[0], navigation.id); });
test("an exact observed product or category name remains objective even when its name contains a restricted modifier", async () => { const named = createBusinessSourceEvidence({ sourceType: "product_sample", sourceUriOrLocation: "https://example.test/product/professional-field-kit/", sourceRole: "business_statement", sourceField: "page.title", rawValue: "Professional Field Kit", retrievedAt: WHEN, claimClassification: "observed_fact" }); const customEvidence = [...evidence, named]; const customArtifact = { ...rawArtifact, evidence: customEvidence }; const output = proposal(); output.catalogue_understanding.representative_product_refs = [fact("Professional Field Kit", named.id)]; const result = await interpretBusinessEvidence({ evidenceArtifact: customArtifact, provider: provider(output, customEvidence), writeArtifacts: false }); assert.equal(result.bio.catalogue_understanding.representative_product_refs[0].assertion_scope, "objective"); });
test("premium and professional wording remains representable as positioning claims", async () => { const stated = createBusinessSourceEvidence({ sourceType: "homepage", sourceUriOrLocation: "https://example.test/", sourceRole: "business_statement", sourceField: "page.statement", rawValue: "Premium, professional equipment for demanding projects.", retrievedAt: WHEN, claimClassification: "positioning_claim" }); const customEvidence = [...evidence, stated]; const customArtifact = { ...rawArtifact, evidence: customEvidence }; const output = proposal(); output.positioning.positioning_claims = [claim("Premium, professional equipment", stated.id)]; const result = await interpretBusinessEvidence({ evidenceArtifact: customArtifact, provider: provider(output, customEvidence), writeArtifacts: false }); assert.equal(result.bio.positioning.positioning_claims[0].assertion_scope, "business_claim"); });
test("positioning business claims reject observed and customer evidence", async () => { for (const ref of [identity.id, audience.id]) { const output = proposal(); output.positioning.positioning_claims = [claim("A positioning statement", ref)]; await assert.rejects(() => interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(output), writeArtifacts: false }), (error) => error.errors.some((item) => item.includes("ineligible for positioning_business_claim"))); } });
test("positioning business claims accept positioning-claim evidence", async () => { const result = await interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(), writeArtifacts: false }); assert.equal(result.bio.positioning.positioning_claims[0].evidence_refs[0], positioning.id); });
test("structured output uses one provider-compatible global evidence ID definition", async () => { const result = await interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(), writeArtifacts: false }); const schema = result.prompts.responseSchema; assert.equal(schema.$defs.evidence_id.type, "string"); assert.deepEqual([...schema.$defs.evidence_id.enum].sort(), evidence.map((item) => item.id).sort()); const references = []; const walk = (value) => { if (!value || typeof value !== "object") return; if (value.properties?.evidence_refs?.items) references.push(value.properties.evidence_refs.items); for (const child of Object.values(value)) walk(child); }; walk(schema); assert.ok(references.length > 0); assert.ok(references.every((item) => item.$ref === "#/$defs/evidence_id" && !Object.hasOwn(item, "enum"))); });
test("OpenAI provider accepts the simplified structured-output request shape", async () => { let requestBody; const openAI = createOpenAIInterpretationProvider({ env: { OPENAI_API_KEY: "fixture-key", OPENAI_INTERPRETATION_MODEL: "gpt-4o-mini" }, fetchImpl: async (_url, options) => { requestBody = JSON.parse(options.body); return { ok: true, status: 200, async text() { return JSON.stringify({ id: "fixture-response", model: "gpt-4o-mini", choices: [{ message: { content: JSON.stringify(proposal()) } }], usage: { prompt_tokens: 120, completion_tokens: 80 } }); } }; } }); const result = await interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: openAI, writeArtifacts: false }); assert.equal(requestBody.response_format.type, "json_schema"); assert.equal(requestBody.response_format.json_schema.strict, true); assert.deepEqual([...requestBody.response_format.json_schema.schema.$defs.evidence_id.enum].sort(), evidence.map((item) => item.id).sort()); assert.equal(result.validationReport.valid, true); });
test("Responses provider preserves the existing prompts and schema in strict output mode", async () => { let requestBody; const responses = createOpenAIResponsesInterpretationProvider({ env: { OPENAI_API_KEY: "fixture-key", OPENAI_INTERPRETATION_MODEL: "gpt-5.6-terra", OPENAI_INTERPRETATION_REASONING_EFFORT: "medium" }, fetchImpl: async (_url, options) => { requestBody = JSON.parse(options.body); return { ok: true, status: 200, async text() { return JSON.stringify({ id: "fixture-response", model: "gpt-5.6-terra", output_text: JSON.stringify(proposal()), usage: { input_tokens: 120, output_tokens: 80, output_tokens_details: { reasoning_tokens: 24 } } }); } }; } }); const result = await interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: responses, writeArtifacts: false }); assert.equal(requestBody.model, "gpt-5.6-terra"); assert.deepEqual(requestBody.reasoning, { effort: "medium" }); assert.equal(requestBody.text.format.type, "json_schema"); assert.equal(requestBody.text.format.strict, true); assert.equal(requestBody.input[0].content, result.prompts.systemPrompt); assert.equal(requestBody.input[1].content, result.prompts.userPrompt); assert.deepEqual(requestBody.text.format.schema, result.prompts.responseSchema); assert.equal(result.bio.execution_metadata.reasoning_tokens, 24); assert.equal(result.validationReport.valid, true); });
test("Responses provider still fails closed through the existing BIO validator", async () => { let calls = 0; const output = proposal(); output.positioning.positioning_claims = [claim("Customer language presented as positioning", audience.id)]; const responses = createOpenAIResponsesInterpretationProvider({ env: { OPENAI_API_KEY: "fixture-key", OPENAI_INTERPRETATION_MODEL: "gpt-5.6-terra" }, fetchImpl: async () => { calls += 1; return { ok: true, status: 200, async text() { return JSON.stringify({ model: "gpt-5.6-terra", output_text: JSON.stringify(output), usage: { input_tokens: 120, output_tokens: 80 } }); } }; } }); await assert.rejects(() => interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: responses, writeArtifacts: false }), (error) => error.errors.some((item) => item.includes("ineligible for positioning_business_claim: customer_claim"))); assert.equal(calls, 1); });
function partialProposal(pass) {
  const output = proposal();
  if (pass === "catalogue") return { business_identity: { ...output.business_identity, business_description: derived("Retailer of practical outdoor equipment", identity.id) }, catalogue_understanding: { ...output.catalogue_understanding, product_focus: derived("Outdoor project equipment", navigation.id), catalogue_coherence: derived("focused", navigation.id) }, knowledge_gaps: [], assumptions: [] };
  if (pass === "positioning") return { positioning: output.positioning, knowledge_gaps: [], assumptions: [] };
  return { customer_understanding: output.customer_understanding, knowledge_gaps: [], assumptions: [] };
}
function multiPassProvider({ mutate } = {}) { let calls = 0; return { id: "mock-multipass", model: "mock-multipass-model", get calls() { return calls; }, async generate({ userPrompt }) { calls += 1; const input = JSON.parse(userPrompt); const output = mutate ? mutate(input.pass, partialProposal(input.pass)) : partialProposal(input.pass); return { provider: "mock-multipass", model: "mock-multipass-model", rawText: JSON.stringify(output), usage: { prompt_tokens: 100, completion_tokens: 50 } }; } }; }
test("multi-pass flow sends catalogue, positioning and customer evidence in separate contexts", async () => { const seen = []; const provider = multiPassProvider({ mutate: (pass, output) => { const original = output; original._pass = pass; return original; } }); const wrapped = { ...provider, async generate(input) { const prompt = JSON.parse(input.userPrompt); seen.push({ pass: prompt.pass, ids: prompt.allowed_evidence_context.evidence.map((item) => item.id), classification: prompt.allowed_evidence_context.claim_classification }); const result = await provider.generate(input); const value = JSON.parse(result.rawText); delete value._pass; return { ...result, rawText: JSON.stringify(value) }; } }; const result = await interpretBusinessEvidenceInPasses({ evidenceArtifact: rawArtifact, provider: wrapped, writeArtifacts: false }); assert.deepEqual(seen.map((item) => item.pass), ["catalogue", "positioning", "customer"]); assert.deepEqual(seen.map((item) => item.classification), ["observed_fact", "positioning_claim", "customer_claim"]); assert.ok(seen[0].ids.every((id) => [identity.id, navigation.id].includes(id))); assert.deepEqual(result.bio.audience_architecture.type.knowledge_type, "unknown"); });
test("valid partial outputs assemble deterministically and preserve evidence references", async () => { const result = await interpretBusinessEvidenceInPasses({ evidenceArtifact: rawArtifact, provider: multiPassProvider(), writeArtifacts: false }); assert.equal(result.bio.validation_status, "awaiting_validation"); assert.equal(result.bio.positioning.positioning_claims[0].evidence_refs[0], positioning.id); assert.equal(result.bio.customer_understanding.target_customer_groups[0].evidence_refs[0], audience.id); assert.equal(result.bio.catalogue_understanding.primary_categories[0].evidence_refs[0], navigation.id); assert.equal(result.bio.audience_architecture.type.value, null); assert.equal(result.bio.execution_metadata.external_api_call_count, 3); });
test("successful multi-pass results persist BIO, validation report and founder review without another AI call", async (t) => { const root = await mkdtemp(path.join(os.tmpdir(), "bio-multipass-success-")); t.after(() => rm(root, { recursive: true, force: true })); const provider = multiPassProvider(); const result = await interpretBusinessEvidenceInPasses({ evidenceArtifact: rawArtifact, provider, outputRoot: root, now: () => new Date(WHEN) }); assert.equal(provider.calls, 3); assert.ok(result.files.businessIntelligence.endsWith("business-intelligence.json")); assert.ok(result.files.validation.endsWith("interpretation-validation-report.json")); assert.ok(result.files.founderReview.endsWith("founder-review.md")); const bio = JSON.parse(await readFile(result.files.businessIntelligence, "utf8")); const report = JSON.parse(await readFile(result.files.validation, "utf8")); const review = await readFile(result.files.founderReview, "utf8"); assert.equal(bio.validation_status, "awaiting_validation"); assert.equal(report.valid, true); assert.equal(report.partial_passes.length, 3); assert.equal(report.evidence_counts.selected_total, 4); assert.equal(report.evidence_counts.supplied_total, 4); assert.match(review, /^# Business Understanding/); assert.match(review, /one core type of customer, or.*several meaningfully different customer groups/); assert.match(review, /Yes, this accurately represents the business/); });
test("founder review rendering is deterministic and does not invoke AI", async () => { const result = await interpretBusinessEvidenceInPasses({ evidenceArtifact: rawArtifact, provider: multiPassProvider(), writeArtifacts: false }); const first = renderBusinessIntelligenceFounderReview(result.bio); const second = renderBusinessIntelligenceFounderReview(result.bio); assert.equal(first, second); assert.match(first, /What your website says/); assert.match(first, /What we understand from that/); assert.match(first, /Based on:/); });
test("client review hides audit metadata and internal identifiers while preserving BIO", async () => { const result = await interpretBusinessEvidenceInPasses({ evidenceArtifact: rawArtifact, provider: multiPassProvider(), writeArtifacts: false }); const before = JSON.stringify(result.bio); const review = renderBusinessIntelligenceFounderReview(result.bio); assert.equal(JSON.stringify(result.bio), before); assert.doesNotMatch(review, /bie_[a-z0-9]+/); assert.doesNotMatch(review, /confidence|knowledge_type|assertion_scope|status:|\[[0-9]+\]|evidence_refs|snake_case/i); });
test("client review filters narrow product operational details generically", async () => { const result = await interpretBusinessEvidenceInPasses({ evidenceArtifact: rawArtifact, provider: multiPassProvider(), writeArtifacts: false }); result.bio.customer_understanding.exclusions = [{ value: "Adapter not included with the product", knowledge_type: "fact", assertion_scope: "business_claim", evidence_refs: [audience.id], confidence: 0.9, status: "extracted" }]; const review = renderBusinessIntelligenceFounderReview(result.bio); assert.doesNotMatch(review, /Adapter not included/); });
test("client review uses generic catalogue and customer language", async () => { const result = await interpretBusinessEvidenceInPasses({ evidenceArtifact: rawArtifact, provider: multiPassProvider(), writeArtifacts: false }); const review = renderBusinessIntelligenceFounderReview(result.bio); assert.match(review, /What you sell/); assert.match(review, /Who we think you're speaking to/); assert.doesNotMatch(review, /Street Kingz|car-care|automotive/); });
test("client review presents identity, catalogue and unknowns without internal field paths", async () => { const result = await interpretBusinessEvidenceInPasses({ evidenceArtifact: rawArtifact, provider: multiPassProvider(), writeArtifacts: false }); const review = renderBusinessIntelligenceFounderReview(result.bio); assert.match(review, /Northstar Supply/); assert.match(review, /Tools/); assert.match(review, /Which geographic market/); assert.doesNotMatch(review, /business_identity|catalogue_understanding|\[0\]/); });
test("client review can be regenerated from an existing BIO without an AI call", async (t) => { const result = await interpretBusinessEvidenceInPasses({ evidenceArtifact: rawArtifact, provider: multiPassProvider(), writeArtifacts: false }); const root = await mkdtemp(path.join(os.tmpdir(), "bio-founder-review-")); t.after(() => rm(root, { recursive: true, force: true })); const outputPath = path.join(root, "founder-review.md"); const written = await writeBusinessIntelligenceFounderReview({ bio: result.bio, outputPath }); assert.equal(written, outputPath); assert.equal(await readFile(outputPath, "utf8"), renderBusinessIntelligenceFounderReview(result.bio)); });
test("client review synthesises customer identity and deduplicates presentation prefixes", async () => { const result = await interpretBusinessEvidenceInPasses({ evidenceArtifact: rawArtifact, provider: multiPassProvider(), writeArtifacts: false }); result.bio.customer_understanding.target_customer_groups = [{ value: "People who complete practical projects", evidence_refs: [audience.id] }, { value: "Practical project customers", evidence_refs: [audience.id] }]; result.bio.customer_understanding.customer_behaviours = [{ value: "The website communicates regular home projects", evidence_refs: [audience.id] }]; result.bio.customer_understanding.customer_priorities = [{ value: "Better results without fuss", evidence_refs: [audience.id] }, { value: "The website communicates better results without fuss", evidence_refs: [audience.id] }]; const review = renderBusinessIntelligenceFounderReview(result.bio); assert.match(review, /Your website primarily speaks to people who complete practical projects/); assert.doesNotMatch(review, /People who complete practical projects, Practical project customers/); assert.equal((review.match(/Better results without fuss/gi) || []).length, 1); });
test("client review suppresses isolated product detail but retains repeated business themes", async () => { const result = await interpretBusinessEvidenceInPasses({ evidenceArtifact: rawArtifact, provider: multiPassProvider(), writeArtifacts: false }); const productEvidence = createBusinessSourceEvidence({ sourceType: "product_sample", sourceUriOrLocation: "https://example.test/products/tool", sourceRole: "business_statement", sourceField: "page.statement", rawValue: "Adapter not included", retrievedAt: WHEN, claimClassification: "customer_claim" }); result.bio.source_evidence = [...result.bio.source_evidence, productEvidence]; result.bio.customer_understanding.customer_problems = [{ value: "Adapter not included", evidence_refs: [productEvidence.id] }, { value: "Better results without fuss", evidence_refs: [audience.id] }]; const review = renderBusinessIntelligenceFounderReview(result.bio); assert.doesNotMatch(review, /Adapter not included/); assert.match(review, /Better results without fuss/); });
test("client review turns important unknowns and audience structure into founder questions", async () => { const result = await interpretBusinessEvidenceInPasses({ evidenceArtifact: rawArtifact, provider: multiPassProvider(), writeArtifacts: false }); const review = renderBusinessIntelligenceFounderReview(result.bio); assert.match(review, /A few things we'd like you to confirm/); assert.match(review, /own-brand products, third-party products, or both/); assert.match(review, /Which geographic market/); assert.match(review, /one core type of customer, or do you have several/); assert.match(review, /Mostly, but I need to correct or clarify something/); assert.doesNotMatch(review, /Owned Brand Status|Geographic Market can currently be established/); });
test("forbidden fields in a partial pass fail closed without a repair or second call", async (t) => { const root = await mkdtemp(path.join(os.tmpdir(), "bio-multipass-invalid-")); t.after(() => rm(root, { recursive: true, force: true })); const provider = multiPassProvider({ mutate: (pass, output) => pass === "positioning" ? { ...output, customer_understanding: {} } : output }); let failure; await assert.rejects(() => interpretBusinessEvidenceInPasses({ evidenceArtifact: rawArtifact, provider, outputRoot: root }), (error) => { failure = error; return error.errors.some((item) => item.includes("forbidden field customer_understanding")) && Boolean(error.diagnostic); }); assert.equal(provider.calls, 2); const diagnostic = JSON.parse(await readFile(failure.diagnostic, "utf8")); assert.equal(diagnostic.validity, "INVALID / REJECTED"); assert.equal(diagnostic.pass, "positioning"); });
test("deterministic eligibility still rejects combinations allowed by the structural API schema", async () => { const output = proposal(); output.positioning.positioning_claims = [claim("Customer language presented as positioning", audience.id)]; await assert.rejects(() => interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(output), writeArtifacts: false }), (error) => error.errors.some((item) => item.includes("ineligible for positioning_business_claim: customer_claim"))); });
test("homepage and about positioning evidence remains valid for business positioning", async () => { const aboutPositioning = createBusinessSourceEvidence({ sourceType: "about_page", sourceUriOrLocation: "https://example.test/about/", sourceRole: "business_statement", sourceField: "page.statement", rawValue: "We position our range around dependable simplicity.", retrievedAt: WHEN, claimClassification: "positioning_claim" }); const customEvidence = [...evidence, aboutPositioning]; const customArtifact = { ...rawArtifact, evidence: customEvidence }; const output = proposal(); output.positioning.positioning_claims = [claim("Dependable simplicity", aboutPositioning.id)]; const result = await interpretBusinessEvidence({ evidenceArtifact: customArtifact, provider: provider(output, customEvidence), writeArtifacts: false }); assert.equal(result.bio.positioning.positioning_claims[0].evidence_refs[0], aboutPositioning.id); });
test("customer claims cannot create positioning interpretations", async () => { const output = proposal(); output.positioning.value_proposition = [derived("A value proposition inferred from customer language", audience.id)]; await assert.rejects(() => interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(output), writeArtifacts: false }), (error) => error.errors.some((item) => item.includes("ineligible for positioning_interpretation: customer_claim"))); });
test("observed product structure cannot create a positioning business claim", async () => { const output = proposal(); output.positioning.positioning_claims = [claim("A claim invented from structure", navigation.id)]; await assert.rejects(() => interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(output), writeArtifacts: false }), (error) => error.errors.some((item) => item.includes("ineligible for positioning_business_claim: observed_fact"))); });
test("human validation remains awaiting and contains no human decisions", async () => { const result = await interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(), writeArtifacts: false }); assert.equal(result.bio.validation_status, "awaiting_validation"); assert.deepEqual(result.bio.human_validation_decisions, []); assert.deepEqual(result.bio.human_corrections, []); });
test("unsupported demographic profiling is rejected", async () => { const output = proposal(); output.customer_understanding.target_customer_groups = [inferred("Affluent men aged 30 to 45")]; await assert.rejects(() => interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(output), writeArtifacts: false }), (error) => error.errors.some((item) => item.includes("demographic profiling"))); });
test("inferred customer identity labels are rejected while direct claims remain representable", async () => { const output = proposal(); output.customer_understanding.target_customer_groups = [inferred("Outdoor hobbyists")]; await assert.rejects(() => interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(output), writeArtifacts: false }), (error) => error.errors.some((item) => item.includes("inferred customer identity label"))); const direct = proposal(); direct.customer_understanding.target_customer_groups = [{ ...claim("Designed for people tackling practical outdoor projects", audience.id) }]; const result = await interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(direct), writeArtifacts: false }); assert.equal(result.bio.customer_understanding.target_customer_groups[0].assertion_scope, "business_claim"); });
test("customer fields enforce claim-specific and interpretation evidence eligibility", async () => { const claimed = proposal(); claimed.customer_understanding.target_customer_groups = [claim("A claimed customer group", positioning.id)]; await assert.rejects(() => interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(claimed), writeArtifacts: false }), (error) => error.errors.some((item) => item.includes("ineligible for customer_business_claim"))); const interpreted = proposal(); interpreted.customer_understanding.customer_motivations = [inferred("A cautious motivation", positioning.id)]; await assert.rejects(() => interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(interpreted), writeArtifacts: false }), (error) => error.errors.some((item) => item.includes("ineligible for customer_interpretation"))); const valid = proposal(); valid.customer_understanding.customer_motivations = [inferred("Completing practical projects", audience.id)]; const result = await interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(valid), writeArtifacts: false }); assert.equal(result.bio.customer_understanding.customer_motivations[0].evidence_refs[0], audience.id); });
test("customer claims remain usable for customer understanding but not company or catalogue interpretation", async () => { const valid = await interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(), writeArtifacts: false }); assert.equal(valid.bio.customer_understanding.target_customer_groups[0].evidence_refs[0], audience.id); for (const mutate of [(output) => { output.business_identity.business_description = inferred("Identity inferred from customers", audience.id); }, (output) => { output.catalogue_understanding.product_focus = inferred("Catalogue inferred from customers", audience.id); }]) { const output = proposal(); mutate(output); await assert.rejects(() => interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(output), writeArtifacts: false }), (error) => error.errors.some((item) => /ineligible for (?:business_identity|catalogue)_interpretation/.test(item))); } });
test("field evidence eligibility policy remains explicit and bounded", () => { assert.deepEqual(FIELD_EVIDENCE_ELIGIBILITY, { objective_representative_product: ["observed_fact"], positioning_business_claim: ["positioning_claim"], positioning_interpretation: ["observed_fact", "positioning_claim"], business_identity_business_claim: ["positioning_claim"], business_identity_interpretation: ["observed_fact", "positioning_claim"], catalogue_business_claim: ["positioning_claim"], catalogue_interpretation: ["observed_fact", "positioning_claim"], customer_business_claim: ["customer_claim"], customer_interpretation: ["observed_fact", "customer_claim"] }); });
test("optional sections may remain empty without forced completion", async () => { const output = proposal(); output.customer_understanding = { target_customer_groups: [], customer_behaviours: [], customer_motivations: [], customer_priorities: [], customer_problems: [], purchase_drivers: [], exclusions: [] }; output.positioning = { value_proposition: [], positioning_themes: [], differentiators: [], positioning_claims: [], price_value_orientation: unknown() }; output.category_audiences = []; const result = await interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(output), writeArtifacts: false }); assert.deepEqual(result.bio.customer_understanding.target_customer_groups, []); assert.deepEqual(result.bio.positioning.positioning_claims, []); assert.equal(result.bio.positioning.price_value_orientation.knowledge_type, "unknown"); });
test("prompt contains no founder validation knowledge or external intelligence objects", async () => { const result = await interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(), writeArtifacts: false }); const prompt = `${result.prompts.systemPrompt}\n${result.prompts.userPrompt}`.toLowerCase(); for (const forbidden of ["founder-known", "professional detailer", "home-user positioning", "brandvoiceprofile", "productintelligenceobject"]) assert.equal(prompt.includes(forbidden), false); });
test("prompt plans interpretation with deterministic field-scoped evidence contexts", async () => { const result = await interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(), writeArtifacts: false }); const input = JSON.parse(result.prompts.userPrompt); assert.deepEqual(input.interpretation_plan.map((item) => item.stage), ["evidence_observation", "claim_classification", "business_interpretation"]); const contexts = input.field_evidence_contexts; assert.deepEqual(contexts.catalogue.evidence.map((item) => item.id).sort(), [identity.id, navigation.id].sort()); assert.deepEqual(contexts.positioning.evidence.map((item) => item.id), [positioning.id]); assert.deepEqual(contexts.customer.evidence.map((item) => item.id), [audience.id]); const ids = Object.values(contexts).flatMap((context) => context.evidence.map((item) => item.id)); assert.equal(new Set(ids).size, evidence.length); });
test("evidence partitioning gives each interpretation field only its eligible classification", () => { const contexts = partitionBusinessInterpretationEvidence(evidence); assert.ok(contexts.catalogue.evidence.every((item) => item.claim_classification === "observed_fact")); assert.ok(contexts.positioning.evidence.every((item) => item.claim_classification === "positioning_claim")); assert.ok(contexts.customer.evidence.every((item) => item.claim_classification === "customer_claim")); assert.deepEqual(contexts.catalogue.used_for, ["catalogue_understanding", "representative_product_refs"]); assert.deepEqual(contexts.positioning.used_for, ["positioning"]); assert.deepEqual(contexts.customer.used_for, ["customer_understanding"]); });
test("catalogue evidence is deterministically prioritised without leaking claims", () => { const productTitle = { ...identity, id: "product-title", source_type: "product_sample", source_field: "page.title", normalised_value: "Utility Towel" }; const productHeading = { ...identity, id: "product-heading", source_type: "product_sample", source_field: "page.heading", normalised_value: "Utility Towel details" }; const contexts = partitionBusinessInterpretationEvidence([productHeading, audience, positioning, navigation, productTitle]); assert.deepEqual(contexts.catalogue.evidence.map((item) => item.id), [productTitle.id, navigation.id, productHeading.id]); assert.equal(contexts.catalogue.evidence.some((item) => item.id === positioning.id || item.id === audience.id), false); });
test("prompt defines representative product references as catalogue identity rather than descriptions", async () => { const result = await interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(), writeArtifacts: false }); const system = result.prompts.systemPrompt; const input = JSON.parse(result.prompts.userPrompt); assert.match(system, /representative_product_refs as catalogue structure, not product descriptions/i); assert.match(system, /Do not include marketing adjectives, positioning, perceived quality, performance claims, customer benefits, or promotional language/i); assert.match(system, /preserve that language separately in a positioning field as a business_claim/i); assert.match(input.field_decision_rules.catalogue_understanding, /identify only observable product\/category names, product types, or catalogue entities/i); assert.match(input.field_decision_rules.catalogue_understanding, /do not duplicate it into representative_product_refs/i); });
test("prompt prioritises direct catalogue evidence for representative products", async () => { const result = await interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(), writeArtifacts: false }); const system = result.prompts.systemPrompt; const rule = JSON.parse(result.prompts.userPrompt).field_decision_rules.catalogue_understanding; assert.match(system, /product title\/name evidence.*product URL or product identifier evidence.*category or product-listing evidence.*product-page structural headings.*other observed catalogue evidence/is); assert.match(system, /Evidence relevance is not the same as evidence authority/i); assert.match(system, /Never cite homepage marketing claims, About-page positioning, brand statements, customer claims, or promotional copy to prove product existence/i); assert.match(rule, /product title\/name; product URL\/identifier; category\/product listing; product-page structural heading; other observed catalogue evidence/i); assert.match(rule, /Positioning and customer claims cannot prove product existence/i); });
test("prompt prioritises business-authored positioning evidence and preserves customer claims for customer understanding", async () => { const result = await interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(), writeArtifacts: false }); const system = result.prompts.systemPrompt; const rule = JSON.parse(result.prompts.userPrompt).field_decision_rules.positioning; assert.match(system, /homepage brand statements.*About-page statements.*category or product marketing copy.*explicit brand messaging/is); assert.match(system, /Never use reviews, testimonials, customer comments, FAQ answers describing customer problems, or customer outcomes to create brand positioning/i); assert.match(system, /may cautiously inform customer understanding; it cannot support.*brand positions itself around quality/is); assert.match(system, /If no eligible positioning_claim evidence exists, emit positioning_claims as an empty array/i); assert.match(rule, /homepage brand statements; About-page statements; category\/product marketing copy; other explicit brand messaging/i); assert.match(rule, /customer-problem FAQs, and customer outcomes remain customer understanding only/i); assert.match(rule, /emit positioning_claims as an empty array/i); });
test("evidence selection is bounded and source-diverse", () => { const many = { ...rawArtifact, evidence: Array.from({ length: 300 }, (_, index) => ({ ...positioning, id: `e${index}`, source_uri_or_location: `https://example.test/page-${index % 20}/`, normalised_value: `Statement ${index}` })) }; assert.ok(selectRelevantBusinessEvidence(many).length <= 240); });
test("artifact writer creates the BIO and requested validation report", async (t) => { const root = await mkdtemp(path.join(os.tmpdir(), "bio-interpretation-")); t.after(() => rm(root, { recursive: true, force: true })); const result = await interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(), outputRoot: root, now: () => new Date(WHEN) }); assert.equal(JSON.parse(await readFile(result.files.businessIntelligence, "utf8")).artifact_type, "business_intelligence_interpretation"); const report = JSON.parse(await readFile(result.files.validation, "utf8")); assert.equal(report.evidence_count_used, 4); assert.equal(report.validation_status, "awaiting_validation"); });
test("mock interpretation performs no network or WordPress access", async () => { let calls = 0; const original = globalThis.fetch; globalThis.fetch = () => { calls += 1; throw new Error("network forbidden"); }; try { await interpretBusinessEvidence({ evidenceArtifact: rawArtifact, provider: provider(), writeArtifacts: false }); assert.equal(calls, 0); } finally { globalThis.fetch = original; } });
test("Business interpretation has no Product Intelligence or BrandVoice module dependency", async () => { const source = await readFile(new URL("../business-intelligence/interpretation.js", import.meta.url), "utf8"); assert.doesNotMatch(source, /product-intelligence|BrandVoiceProfile|brandVoice/i); assert.ok(businessIntelligenceInterpretationJsonSchema().properties.audience_architecture); });
