import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, stat } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import {
  buildCommercialProductEditorInput,
  buildCommercialComparison,
  rankCommercialSellingPoints,
  selectDistinctCommercialSellingPoints,
  validateCommercialProductEditorOutput,
  runCommercialProductEditor
} from "../editorial/commercialProductEditor.js";

const contextPath = "artifacts/editorial-intelligence-context/heavy-duty-drying-towel-1200gsm/2026-08-15T13-45-00.000Z/editorial-intelligence-context.json";
const current = ["1200GSM dual-layer thickness", "Strong water-holding capacity, with a heavier feel once fully saturated", "Soft premium feel", "Suitable for paintwork when used correctly on a clean, shampooed surface", "Ideal for larger vehicles"];
const load = async () => JSON.parse(await readFile(contextPath, "utf8"));
const validOutput = { short_description_bullets: ["High water capacity to make vehicle drying easier", "Soft premium feel for a more comfortable finish", "1200GSM dual-layer construction for substantial coverage", "Ideal for larger vehicles and everyday home washing"] };

test("EditorialIntelligenceContext is accepted as trusted editor input", async () => { const context = await load(); const input = buildCommercialProductEditorInput({ context, currentShortDescription: current }); assert.equal(input.editorial_objective.primary_objective, "persuade_the_intended_customer_to_buy"); assert.ok(input.ranked_selling_points.length > 0); });
test("unvalidated context provenance fails closed", async () => { const context = await load(); const invalid = structuredClone(context); invalid.provenance_summary.business_validation_status = "awaiting_validation"; assert.throws(() => buildCommercialProductEditorInput({ context: invalid, currentShortDescription: current }), /validated Business Intelligence provenance/); });
test("customer-relevant benefits outrank weak caveats", async () => { const context = await load(); const ranked = rankCommercialSellingPoints(context); assert.ok(ranked.findIndex((item) => item.role === "customer_outcome") < ranked.findIndex((item) => item.role === "limitation")); assert.ok(ranked.find((item) => item.role === "limitation" && item.prime_eligible === false)); });
test("duplicate commercial angles are reduced before generation", async () => { const context = await load(); const distinct = selectDistinctCommercialSellingPoints(context); const keys = distinct.selected.map((item) => item.angle_key); assert.equal(new Set(keys).size, keys.length); assert.ok(distinct.rejected.some((item) => item.rejection === "overlapping_commercial_angle")); });
test("product caveats and care instructions remain available but are not prime bullets", async () => { const context = await load(); const ranked = rankCommercialSellingPoints(context); assert.ok(ranked.some((item) => item.role === "objection" && item.prime_eligible === false)); assert.ok(ranked.some((item) => item.role === "care_or_instruction" && item.prime_eligible === false)); });
test("supported derived benefits can be framed persuasively", async () => { const context = await load(); assert.deepEqual(validateCommercialProductEditorOutput(validOutput, { context }), []); });
test("every prime bullet requires meaningful Product Intelligence support", async () => { const context = await load(); const businessOnly = { short_description_bullets: ["For everyday home users who value simple routines", "Premium without unnecessary complexity", "A better value choice for regular drivers"] }; const errors = validateCommercialProductEditorOutput(businessOnly, { context }); assert.ok(errors.some((error) => /Product Intelligence/i.test(error))); });
test("Business Intelligence can influence ranking without appearing literally in copy", async () => { const context = await load(); const output = { short_description_bullets: ["Fast, streak-free drying for a better finish without the fuss", "1200GSM dual-layer construction with strong water-holding capacity", "Ideal for making light work of drying larger vehicles"] }; assert.deepEqual(validateCommercialProductEditorOutput(output, { context }), []); });
test("forced audience or positioning contextualisation is rejected without product grounding", async () => { const context = await load(); const forced = { short_description_bullets: ["The uncomplicated premium upgrade for your regular driveway routine", "For everyday drivers who want quality without compromise", "A better choice for home car care"] }; assert.ok(validateCommercialProductEditorOutput(forced, { context }).some((error) => /Product Intelligence/i.test(error))); });
test("derived benefits cannot become invented measurements or unsupported performance claims", async () => { const context = await load(); const invalid = { short_description_bullets: ["Absorbs 5 litres of water", "Dries your vehicle twice as fast", "Guaranteed swirl-free results"] }; const errors = validateCommercialProductEditorOutput(invalid, { context }); assert.ok(errors.some((error) => /unsupported performance|measurement|guarantee/i.test(error))); });
test("unsupported superlatives and generic filler are rejected", async () => { const context = await load(); const invalid = { short_description_bullets: ["Maximum absorbency for every wash", "A dependable choice for your routine", "1200GSM dual-layer construction"] }; const errors = validateCommercialProductEditorOutput(invalid, { context }); assert.ok(errors.some((error) => /superlative/i.test(error))); assert.ok(errors.some((error) => /generic filler/i.test(error))); });
test("three or four distinct strong bullets are valid; five is not required", async () => { const context = await load(); const output = { short_description_bullets: ["Fast, streak-free drying for a better finish without the fuss", "1200GSM dual-layer construction for substantial coverage", "Ideal for making light work of drying larger vehicles"] }; assert.deepEqual(validateCommercialProductEditorOutput(output, { context }), []); });
test("caveat-led copy is rejected from prime sales bullets", async () => { const context = await load(); const invalid = { short_description_bullets: ["Use only on clean, shampooed paint", "Heavier when fully saturated", "Do not use with fabric softener"] }; assert.ok(validateCommercialProductEditorOutput(invalid, { context }).some((error) => /caveat-led/i.test(error))); });
test("business audience and positioning are included without hardcoded customer rules", async () => { const context = await load(); const input = buildCommercialProductEditorInput({ context, currentShortDescription: current }); assert.match(JSON.stringify(input.audience), /validated_business_audience_is_primary/); assert.match(JSON.stringify(input.business_positioning), /Premium without the fuss/); const generic = structuredClone(context); const replace = (value) => Array.isArray(value) ? value.map(replace) : value && typeof value === "object" ? Object.fromEntries(Object.entries(value).map(([key, child]) => [key, replace(child)])) : typeof value === "string" ? value.replace(/Street Kingz/gi, "Generic Supply") : value; const genericInput = buildCommercialProductEditorInput({ context: replace(generic), currentShortDescription: ["Reliable product"] }); assert.doesNotMatch(JSON.stringify(genericInput), /Street Kingz/i); });
test("quality-over-lowest-price positioning is passed as framing guidance", async () => { const context = await load(); const input = buildCommercialProductEditorInput({ context, currentShortDescription: current }); assert.equal(input.business_positioning.price_value_orientation.value, "quality_over_lowest_price"); assert.doesNotMatch(input.instruction, /discount|cheapest/i); });
test("Business Intelligence is explicitly prioritisation/framing guidance rather than literal product copy", async () => { const context = await load(); const input = buildCommercialProductEditorInput({ context, currentShortDescription: current }); assert.equal(input.business_guidance_use.role, "prioritisation_and_framing_only"); assert.equal(input.business_guidance_use.literal_copy_is_optional, true); assert.match(input.instruction, /invisibly/i); assert.match(input.instruction, /Product Intelligence supplies the product reasons/i); });
test("existing strong copy can remain unchanged", async () => { const context = await load(); const strong = ["High water capacity to make vehicle drying easier", "Soft premium feel for a more comfortable finish", "1200GSM dual-layer construction for substantial coverage", "Ideal for larger vehicles and everyday home washing"]; const comparison = buildCommercialComparison({ context, currentShortDescription: strong, proposedOutput: { short_description_bullets: [...strong] } }); assert.deepEqual(comparison.current_short_description, comparison.proposed_short_description); });
test("audit history is not unnecessarily injected into editor input", async () => { const context = await load(); const input = buildCommercialProductEditorInput({ context, currentShortDescription: current }); assert.equal(Object.hasOwn(input, "source_evidence"), false); assert.equal(Object.hasOwn(input, "human_corrections"), false); assert.equal(JSON.stringify(input).includes("candidates"), false); });
test("comparison explains commercial selection and deferred information", async () => { const context = await load(); const comparison = buildCommercialComparison({ context, currentShortDescription: current, proposedOutput: validOutput }); assert.equal(comparison.wordpress_writes, 0); assert.ok(comparison.bullet_selection.every((item) => item.reason)); assert.ok(comparison.information_deliberately_not_used_in_prime_sales_copy.length > 0); });
test("comparison separates product support from optional business influence", async () => { const context = await load(); const comparison = buildCommercialComparison({ context, currentShortDescription: current, proposedOutput: validOutput }); assert.ok(comparison.bullet_selection.every((item) => item.product_support)); assert.ok(comparison.bullet_selection.some((item) => item.business_influence)); });
test("mock generation uses the context once and performs no network calls", async () => { const context = await load(); let calls = 0; let network = 0; const oldFetch = globalThis.fetch; globalThis.fetch = () => { network += 1; throw new Error("network forbidden"); }; const provider = { model: "fixture-commercial-editor", async generate({ responseSchema }) { calls += 1; assert.equal(responseSchema.properties.short_description_bullets.maxItems, 5); return { provider: "fixture", model: this.model, rawText: JSON.stringify(validOutput), usage: { input_tokens: 100, output_tokens: 40 } }; } }; try { const result = await runCommercialProductEditor({ context, currentShortDescription: current, provider }); assert.equal(calls, 1); assert.equal(network, 0); assert.equal(result.comparison.wordpress_writes, 0); } finally { globalThis.fetch = oldFetch; } });
test("rejected generation persists generated output in a separate invalid diagnostic", async () => { const context = await load(); const root = await mkdtemp(path.join(os.tmpdir(), "commercial-editor-rejected-")); try { const provider = { id: "fixture", model: "fixture-model", settings: { api: "fixture", reasoning: { effort: "low" } }, async generate() { return { provider: "fixture", model: "fixture-model", settings: this.settings, rawText: JSON.stringify({ short_description_bullets: ["Maximum absorbency", "A dependable choice", "Use only on clean, shampooed paint"] }), usage: { input_tokens: 12, output_tokens: 20, total_tokens: 32 } }; } }; await assert.rejects(() => runCommercialProductEditor({ context, currentShortDescription: current, previousCommercialProposal: validOutput.short_description_bullets, provider, outputRoot: root, createdAt: "2026-08-15T16:00:00.000Z" }), (error) => { assert.ok(error.diagnosticPath.endsWith("rejected-diagnostic.json")); return true; }); const diagnostic = JSON.parse(await readFile(path.join(root, "rejected-diagnostic.json"), "utf8")); assert.equal(diagnostic.validity, "INVALID / REJECTED"); assert.equal(diagnostic.generated_bullets.length, 3); assert.ok(diagnostic.validation_errors.length > 0); assert.equal(diagnostic.wordpress_writes, 0); await assert.rejects(() => stat(path.join(root, "editorial-output.json"))); } finally { await rm(root, { recursive: true, force: true }); } });
test("rejected diagnostics exclude request secrets and authorization material", async () => { const context = await load(); const root = await mkdtemp(path.join(os.tmpdir(), "commercial-editor-secret-")); try { const provider = { id: "fixture", model: "fixture-model", settings: { api: "fixture" }, async generate() { return { provider: "fixture", model: "fixture-model", rawText: JSON.stringify({ short_description_bullets: ["Business-only audience wording", "Maximum absorbency", "Use only on clean, shampooed paint"] }), usage: {} }; } }; await assert.rejects(() => runCommercialProductEditor({ context, currentShortDescription: current, provider, outputRoot: root })); const text = await readFile(path.join(root, "rejected-diagnostic.json"), "utf8"); assert.doesNotMatch(text, /api[_-]?key|authorization|bearer|secret/i); assert.doesNotMatch(text, /source_evidence|raw_value|normalised_value/i); } finally { await rm(root, { recursive: true, force: true }); } });
