import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { cornerstoneStrategyJsonSchema } from "../cornerstone/strategy-contracts.js";
import { buildCornerstoneStrategyInput, buildCornerstoneStrategyPrompt } from "../cornerstone/strategy-prompt.js";
import { validateCornerstoneStrategy } from "../cornerstone/strategy-validation.js";
import { renderCornerstoneStrategyMarkdown } from "../cornerstone/strategy-render.js";
import { runControlledCornerstoneStrategy } from "../cornerstone/strategy-run.js";
import { deriveCornerstoneStrategyAllowlists, resolveStrategyEntities } from "../cornerstone/strategy-allowlists.js";
import { reviewCornerstoneStrategyQuality } from "../cornerstone/strategy-quality.js";

const PACKET_PATH = "artifacts/cornerstone/best-car-drying-towel/fixture-v1/research-packet.json";
const loadPacket = () => readFile(PACKET_PATH, "utf8").then(JSON.parse);
const brandRules = { tone: ["plain English", "helpful", "no overhyped nonsense"], constraints: ["answer the reader before presenting products", "do not make unsupported claims"] };
const facts = [{ name: "Heavy Duty Drying Towel – 1200gsm", url: "https://streetkingz.co.uk/product/heavy-duty-drying-towel-1200gsm/", fact_scope: "referenced first-party product facts only" }];
const cite = (statement, ids) => ({ statement, evidence_ids: ids });

function validStrategy(packet, decision = "proceed_with_caveats") {
  const allowlists = deriveCornerstoneStrategyAllowlists(packet);
  const serp = packet.intent.trace.evidence_ids.slice(0, 2);
  const product = packet.streetkingz_relevance.relevant_products[0];
  const productIds = product.evidence_ids;
  const link = packet.streetkingz_relevance.possible_internal_links[0];
  const question = packet.serp.recurring_questions[0];
  const gapIds = packet.competitor_coverage.weak_or_missing_coverage[0].evidence_ids.slice(0, 2);
  return {
    schema_version: "1.1.0", packet_id: packet.packet_id,
    decision: { outcome: decision, rationale: "The query has mixed commercial and informational evidence, but page-level competitor coverage remains unknown.", evidence_ids: [...serp, ...gapIds] },
    strategy: {
      primary_intent_interpretation: cite("Help readers choose a drying method and towel, with comparison before purchase.", serp),
      secondary_intent: cite("Answer practical questions about whether and how drying towels work.", question.evidence_ids),
      recommended_content_angle: cite("A practical choice guide organised around vehicle, towel construction and safe technique rather than a generic product list.", [...serp, ...question.evidence_ids]),
      reader_outcome: cite("The reader can identify suitable criteria and make a considered choice.", serp),
      differentiation_strategy: cite("Differentiate the guide's informational choice intent from product-page transactional intent.", packet.risks.cannibalisation.conflicts[0].evidence_ids.slice(0, 2)),
      commercial_role: cite("Offer a relevant towel only after answering selection criteria.", productIds), confidence: "medium"
    },
    priorities: {
      must_cover_topics: [cite("Selection criteria for a car drying towel.", serp), cite(question.question, question.evidence_ids)],
      secondary_topics: [cite("Alternatives such as blowers may be acknowledged without changing the main towel intent.", packet.search_demand.supporting_queries.find((q) => q.query.includes("blower")).evidence_ids)],
      low_value_topics: [cite("Avoid an exhaustive catalogue of unrelated detailing accessories.", [])],
      questions_requiring_strong_answers: [cite(question.question, question.evidence_ids)]
    },
    structure: { recommended_h1_direction: cite("How to choose the best car drying towel for your car", serp), sections: [
      { heading_direction: "Quick choice framework", purpose: "Set out decision criteria without naming an unsupported universal winner.", evidence_dependencies: serp },
      { heading_direction: "What matters in a drying towel", purpose: "Explain observed concepts and flag claims needing evidence.", evidence_dependencies: productIds },
      { heading_direction: "Practical questions", purpose: "Answer observed searcher questions.", evidence_dependencies: question.evidence_ids },
      { heading_direction: "Relevant Street Kingz options", purpose: "Connect suitable first-party products only after the advice.", evidence_dependencies: productIds }
    ] },
    content_gaps: {
      defensible_gaps: [cite("The packet establishes a need to reconcile informational questions with commercial selection intent.", [...serp, ...question.evidence_ids])],
      uncertain_potential_gaps: [cite("Page-level extraction may reveal useful criteria not visible in snippets.", gapIds)],
      cannot_currently_be_claimed: [cite("Specific omissions by ranking pages cannot be claimed from titles and snippets.", gapIds)]
    },
    streetkingz_integration: {
      genuinely_relevant_products: [{ product_id: product.subject_id, recommended_role: "qualified option", placement_reason: "Its verified product type directly matches the topic.", evidence_ids: productIds }],
      natural_placements: [cite("Introduce a relevant option after the choice framework.", productIds)],
      forced_promotion_areas: [cite("Do not insert products into every practical answer.", [])],
      cta_direction: cite("Invite readers to compare relevant towel specifications after they understand the criteria.", productIds)
    },
    internal_linking: [{ link_id: allowlists.internal_links.find((item) => item.destination_url === link.destination_page).link_id, priority: "high", reasoning: "The product is directly relevant to the guide's selection task.", evidence_ids: link.evidence_ids }],
    cannibalisation: { assessment: "Product pages overlap on query language, so the guide must retain informational comparison intent.", recommended_handling: "differentiate_intent", escalation_required: true, evidence_ids: packet.risks.cannibalisation.conflicts.flatMap((item) => item.evidence_ids.slice(0, 1)) },
    evidence: {
      missing_evidence: [cite("Page-level competitor sections have not been collected.", gapIds)],
      claims_requiring_caution: [cite("Performance and scratch-safety comparisons need first-party or authoritative evidence.", productIds)],
      page_level_competitor_extraction: [cite("Extract ranking pages before asserting content omissions.", gapIds)],
      human_judgement: [cite("Review intent differentiation against the two existing product pages.", packet.risks.cannibalisation.conflicts.flatMap((item) => item.evidence_ids.slice(0, 1)))]
    },
    drafting_guidance: { tone: "Plain English, useful and candid.", complexity: "Accessible to ordinary car owners.", practical_depth: "Give actionable selection criteria without unsupported technical certainty.", what_to_avoid: ["SEO filler", "universal best claims", "forced product promotion"], examples_comparisons_to_consider: [cite("Compare lighter/larger and heavier/plusher choices only where Product Facts support it.", productIds)] },
    open_questions: [cite("Should page-level competitor extraction happen before the strategy is approved for drafting?", gapIds)]
  };
}

async function setup() { const packet = await loadPacket(); return { packet, input: buildCornerstoneStrategyInput({ packet, brandRules, productFacts: facts }) }; }
const has = (result, code) => result.errors.some((item) => item.code === code);

test("strategy prompt is deterministic, bounded and contains the strict schema", async () => { const { input } = await setup(); assert.deepEqual(input, buildCornerstoneStrategyInput({ packet: input.packet, brandRules, productFacts: facts })); assert.equal(buildCornerstoneStrategyPrompt(input), buildCornerstoneStrategyPrompt(input)); assert.equal(cornerstoneStrategyJsonSchema(input.entity_allowlists).additionalProperties, false); assert.equal(input.boundaries.article_drafting_allowed, false); assert.match(buildCornerstoneStrategyPrompt(input), /product registry is exhaustive|entity_allowlists/); });
test("valid fixture passes with explicit warnings", async () => { const { packet, input } = await setup(); const result = validateCornerstoneStrategy(validStrategy(packet), input); assert.equal(result.status, "PASS_WITH_WARNINGS"); assert.equal(result.errors.length, 0); });
test("packet registries become product, evidence and internal-link schema enums", async () => { const { input } = await setup(); const schema = cornerstoneStrategyJsonSchema(input.entity_allowlists); assert.deepEqual(schema.$defs.product_id.enum, input.entity_allowlists.product_ids); assert.deepEqual(schema.$defs.evidence_id.enum, input.entity_allowlists.evidence_ids); assert.deepEqual(schema.$defs.internal_link_id.enum, input.entity_allowlists.internal_link_ids); });
test("different packet derives different enums", async () => { const { packet } = await setup(); const changed = structuredClone(packet); changed.packet_id = "cornerstone_packet_wheels"; changed.streetkingz_relevance.relevant_products = [{ subject_id: "product_wheel_cleaner", name: "Wheel Cleaner", url: "https://streetkingz.co.uk/product/wheel-cleaner/", evidence_ids: [changed.evidence.source_references[0].evidence_id] }]; changed.streetkingz_relevance.possible_internal_links = [{ source_page: "https://streetkingz.co.uk/guides/wheels/", destination_page: "https://streetkingz.co.uk/product/wheel-cleaner/", evidence_ids: [changed.evidence.source_references[0].evidence_id] }]; const other = deriveCornerstoneStrategyAllowlists(changed); const original = deriveCornerstoneStrategyAllowlists(packet); assert.notDeepEqual(other.product_ids, original.product_ids); assert.notDeepEqual(other.internal_link_ids, original.internal_link_ids); });
test("empty product registry permits no structural product selection", async () => { const { packet } = await setup(); const empty = structuredClone(packet); empty.streetkingz_relevance.relevant_products = []; const input = buildCornerstoneStrategyInput({ packet: empty, brandRules, productFacts: [] }); const output = validStrategy(packet); output.packet_id = empty.packet_id; assert.equal(cornerstoneStrategyJsonSchema(input.entity_allowlists).properties.streetkingz_integration.properties.genuinely_relevant_products.maxItems, 0); assert.equal(validateCornerstoneStrategy(output, input).status, "FAIL"); output.streetkingz_integration.genuinely_relevant_products = []; assert.equal(has(validateCornerstoneStrategy(output, input), "INVENTED_PRODUCT"), false); });
test("known product and internal link IDs validate and resolve canonical metadata", async () => { const { packet, input } = await setup(); const output = validStrategy(packet); const validation = validateCornerstoneStrategy(output, input); assert.equal(has(validation, "INVENTED_PRODUCT"), false); assert.equal(has(validation, "INVENTED_URL"), false); const resolved = resolveStrategyEntities(output, input.entity_allowlists); assert.equal(resolved.streetkingz_integration.genuinely_relevant_products[0].canonical_product.name, packet.streetkingz_relevance.relevant_products[0].name); assert.equal(resolved.internal_linking[0].canonical_link.destination_url, packet.streetkingz_relevance.possible_internal_links[0].destination_page); });
test("model cannot override canonical product metadata", async () => { const { packet, input } = await setup(); const output = validStrategy(packet); output.streetkingz_integration.genuinely_relevant_products[0].name = "Override"; output.streetkingz_integration.genuinely_relevant_products[0].url = "https://streetkingz.co.uk/override/"; const result = validateCornerstoneStrategy(output, input); assert.ok(has(result, "SCHEMA_INVALID")); });
test("malformed schema fails", async () => { const { input } = await setup(); assert.equal(validateCornerstoneStrategy({ schema_version: "1.1.0" }, input).status, "FAIL"); });
test("invented keyword metric fails", async () => { const { packet, input } = await setup(); const value = validStrategy(packet); value.decision.rationale = "The query has 9999 monthly searches."; assert.ok(has(validateCornerstoneStrategy(value, input), "INVENTED_METRIC")); });
test("unknown evidence reference fails", async () => { const { packet, input } = await setup(); const value = validStrategy(packet); value.decision.evidence_ids = ["ev_unknown"]; assert.ok(has(validateCornerstoneStrategy(value, input), "UNKNOWN_EVIDENCE_ID")); });
test("unsupported competitor omission claim fails", async () => { const { packet, input } = await setup(); const value = validStrategy(packet); value.content_gaps.defensible_gaps[0].statement = "Competitors fail to explain towel construction."; assert.ok(has(validateCornerstoneStrategy(value, input), "UNSUPPORTED_COMPETITOR_CLAIM")); });
test("explicit rejection of competitor omission claims is not a false positive", async () => { const { packet, input } = await setup(); const value = validStrategy(packet); value.content_gaps.defensible_gaps[0].statement = "This is useful first-party coverage but not evidence that competitors omit those details."; value.content_gaps.cannot_currently_be_claimed[0].statement = "Competitors fail to cover a specific subject."; assert.equal(has(validateCornerstoneStrategy(value, input), "UNSUPPORTED_COMPETITOR_CLAIM"), false); });
test("previous call_001 XL promotion remains rejected and immutable", async () => { const { input } = await setup(); const raw = JSON.parse(await readFile("artifacts/cornerstone/best-car-drying-towel/strategy-v1/gpt-5.6-sol/call_001/strategy-response-raw.json", "utf8")); const output = JSON.parse(raw.raw_text); const result = validateCornerstoneStrategy(output, input); assert.equal(result.status, "FAIL"); assert.ok(has(result, "INVENTED_PRODUCT") || has(result, "SCHEMA_INVALID")); const lifecycle = JSON.parse(await readFile("artifacts/cornerstone/best-car-drying-towel/strategy-v1/gpt-5.6-sol/call_001/call-lifecycle.json", "utf8")); assert.equal(lifecycle.state, "completed"); });
test("invented Street Kingz product fails", async () => { const { packet, input } = await setup(); const value = validStrategy(packet); value.streetkingz_integration.genuinely_relevant_products[0].product_id = "product_invented"; assert.ok(has(validateCornerstoneStrategy(value, input), "INVENTED_PRODUCT")); });
test("invented URL fails", async () => { const { packet, input } = await setup(); const value = validStrategy(packet); value.internal_linking[0].link_id = "internal_link_invented"; assert.ok(has(validateCornerstoneStrategy(value, input), "INVENTED_URL")); });
test("duplicate structure fails", async () => { const { packet, input } = await setup(); const value = validStrategy(packet); value.structure.sections.push(structuredClone(value.structure.sections[0])); assert.ok(has(validateCornerstoneStrategy(value, input), "DUPLICATE_SECTION")); });
test("finished article body fails", async () => { const { packet, input } = await setup(); const value = validStrategy(packet); value.strategy.reader_outcome.statement = "# Draft article\n\n" + "This is drafted prose. ".repeat(100); assert.ok(has(validateCornerstoneStrategy(value, input), "ARTICLE_BODY_DETECTED")); });
test("invalid decision and confidence fail schema enums", async () => { const { packet, input } = await setup(); const value = validStrategy(packet); value.decision.outcome = "publish"; value.strategy.confidence = "certain"; const result = validateCornerstoneStrategy(value, input); assert.ok(has(result, "ENUM_INVALID")); });
test("needs_more_evidence remains valid but blocks progression through warning", async () => { const { packet, input } = await setup(); const result = validateCornerstoneStrategy(validStrategy(packet, "needs_more_evidence"), input); assert.equal(result.status, "PASS_WITH_WARNINGS"); assert.ok(result.warnings.some((item) => item.code === "NON_PROCEED_DECISION")); });
test("reject_topic remains valid but blocks progression through warning", async () => { const { packet, input } = await setup(); const result = validateCornerstoneStrategy(validStrategy(packet, "reject_topic"), input); assert.equal(result.status, "PASS_WITH_WARNINGS"); assert.ok(result.warnings.some((item) => item.code === "NON_PROCEED_DECISION")); });
test("Markdown is concise and contains no article", async () => { const packet = await loadPacket(); const markdown = renderCornerstoneStrategyMarkdown(validStrategy(packet)); assert.match(markdown, /^# Cornerstone Strategy/); assert.match(markdown, /## Cannibalisation/); assert.ok(markdown.length < 7000); });
test("fixture run writes immutable accepted artifacts and records no retry", async (t) => { const packet = await loadPacket(); const root = await mkdtemp(path.join(os.tmpdir(), "cornerstone-strategy-")); t.after(() => rm(root, { recursive: true, force: true })); const output = validStrategy(packet); const provider = { id: "fixture", model: "fixture-model", settings: { api: "fixture" }, requestPayload: ({ responseSchema }) => ({ model: "fixture-model", response_schema: responseSchema }), async generate() { return { provider: "fixture", model: "fixture-model", rawText: JSON.stringify(output), usage: { prompt_tokens: 100, completion_tokens: 50, total_tokens: 150 } }; } }; const result = await runControlledCornerstoneStrategy({ packet, brandRules, productFacts: facts, provider, outputDirectory: root, env: {}, now: () => new Date("2026-08-09T12:00:00.000Z") }); assert.equal(result.accepted, true); assert.equal(result.lifecycle.started_calls, 1); assert.equal(result.lifecycle.completed_calls, 1); assert.equal(result.lifecycle.retries, 0); for (const name of ["strategy-input.json", "strategy-response-raw.json", "strategy.json", "strategy-validation.json", "strategy-quality-review.json", "cornerstone-strategy.md", "run-metadata.json"]) assert.ok(await readFile(path.join(result.callDirectory, name), "utf8")); assert.equal(result.strategy.streetkingz_integration.genuinely_relevant_products[0].canonical_product.name, packet.streetkingz_relevance.relevant_products[0].name); });
test("quality review remains separate and never rewrites strategy", async () => { const { packet, input } = await setup(); const raw = validStrategy(packet); const resolved = resolveStrategyEntities(raw, input.entity_allowlists); const before = structuredClone(resolved); const validation = validateCornerstoneStrategy(raw, input); const review = reviewCornerstoneStrategyQuality(resolved, validation); assert.deepEqual(resolved, before); assert.ok(["PASS", "NEEDS_HUMAN_REVIEW"].includes(review.status)); });
test("invalid fixture is preserved without strategy or Markdown", async (t) => { const packet = await loadPacket(); const root = await mkdtemp(path.join(os.tmpdir(), "cornerstone-strategy-invalid-")); t.after(() => rm(root, { recursive: true, force: true })); const provider = { id: "fixture", model: "fixture-model", settings: {}, requestPayload: () => ({}), async generate() { return { provider: "fixture", model: "fixture-model", rawText: "{}", usage: null }; } }; const result = await runControlledCornerstoneStrategy({ packet, brandRules, productFacts: facts, provider, outputDirectory: root, env: {} }); assert.equal(result.accepted, false); await assert.rejects(readFile(path.join(result.callDirectory, "strategy.json"), "utf8"), (error) => error.code === "ENOENT"); });
test("contracts generalise beyond Product 70, template 2003 and drying towels", async () => { const { packet } = await setup(); const generic = structuredClone(packet); generic.packet_id = "cornerstone_packet_generic"; generic.identity.topic = "How to clean alloy wheels"; generic.identity.primary_query = "how to clean alloy wheels"; generic.identity.proposed_url = "https://streetkingz.co.uk/guides/how-to-clean-alloy-wheels/"; generic.streetkingz_relevance.relevant_products = [{ subject_id: "product_wheel_cleaner", name: "Wheel Cleaner", url: "https://streetkingz.co.uk/product/wheel-cleaner/", evidence_ids: [generic.evidence.source_references[0].evidence_id] }]; generic.streetkingz_relevance.possible_internal_links = [{ source_page: generic.identity.proposed_url, destination_page: "https://streetkingz.co.uk/product/wheel-cleaner/", evidence_ids: [generic.evidence.source_references[0].evidence_id] }]; const input = buildCornerstoneStrategyInput({ packet: generic, brandRules, productFacts: [] }); const schema = cornerstoneStrategyJsonSchema(input.entity_allowlists); assert.deepEqual(schema.$defs.product_id.enum, ["product_wheel_cleaner"]); assert.equal(JSON.stringify(input).includes("template 2003"), false); assert.equal(JSON.stringify(schema).toLowerCase().includes("drying towel"), false); assert.equal(JSON.stringify(schema).includes("Product 70"), false); });
