import assert from "node:assert/strict";
import test from "node:test";
import { buildCreateSeoArticleM4Input, buildArticleBriefAndPagePlan, validateCreateSeoArticleM4Output } from "../workflows/createSeoArticlePlanning.js";
import { streetKingzGuidanceSnapshot } from "../seo-guidance/fixtures/streetkingzSnapshot.js";
import { sha256 } from "../research/core/canonical.js";

const evidence = { evidence_artifact_id: "evidence_1", records: [{ evidence_id: "kw", status: "active" }, { evidence_id: "serp", status: "active" }, { evidence_id: "pf", status: "active" }] };
function context() { const decision = { decision_id: "decision", outcome: "ARTICLE_RECOMMENDED", primary_query: "how to use widget", supporting_queries: [{ query: "widget guide" }], article_type: "how_to", search_intent: "informational", rationale: "evidence" }; const decisionSha = sha256(decision); const plan = { workflow_run_id: "run", workflow_input_sha256: "input", workflow_input: { product_url: "https://example.test/product/widget" }, current_stage: "article_brief", stages: [{ stage_id: "opportunity_decision", result: { artifact_id: `article_opportunity_${decisionSha.slice(0, 16)}`, artifact_sha256: decisionSha, provenance: { decision_id: decision.decision_id, decision_sha256: decisionSha, seo_guidance_snapshot_id: streetKingzGuidanceSnapshot.snapshot_id, seo_guidance_snapshot_sha256: streetKingzGuidanceSnapshot.snapshot_sha256, freshness_status: "CURRENT" } } }] }; return { plan, decision, packet: { product: { subject_id: "product_1", product_name: "Widget", evidence_ids: ["pf"] }, candidates: [{ evidence_ids: ["kw"] }], serp: [{ evidence_id: "serp" }] }, researchState: { research_state_id: "research_1" }, intelligence: { product: {}, business: {}, context: { context_id: "eic_1", business_id: "bio_1", product_object_id: "product_1", validation_status: "validated" } }, status: "article_brief_ready" }; }

test("M4 accepts product_url-only inherited opportunity and preserves guidance lineage", () => { const m3 = context(); const input = buildCreateSeoArticleM4Input({ m3Result: m3, evidence, guidanceSnapshot: streetKingzGuidanceSnapshot }); assert.equal(input.objective, "create_seo_article"); assert.equal(input.opportunity.primary_query, "how to use widget"); assert.equal(input.seo_guidance.snapshot_id, streetKingzGuidanceSnapshot.snapshot_id); assert.deepEqual(Object.keys(input).includes("keyword"), false); });
test("M4 rejects missing or mismatched opportunity lineage", () => { const m3 = context(); assert.throws(() => buildCreateSeoArticleM4Input({ m3Result: { ...m3, status: "paused" }, evidence, guidanceSnapshot: streetKingzGuidanceSnapshot })); const bad = structuredClone(m3); bad.plan.stages[0].result.provenance.seo_guidance_snapshot_id = "other"; assert.throws(() => buildCreateSeoArticleM4Input({ m3Result: bad, evidence, guidanceSnapshot: streetKingzGuidanceSnapshot })); });
test("M4 rejects stale opportunity IDs, hashes and decision fields before planning", () => { for (const mutate of [ (m) => { m.plan.stages[0].result.provenance.decision_id = "other"; }, (m) => { m.plan.stages[0].result.artifact_sha256 = "stale"; }, (m) => { m.decision.primary_query = "other query"; }, (m) => { m.decision.article_type = "comparison"; }, (m) => { m.decision.search_intent = "transactional"; } ]) { const m3 = context(); mutate(m3); assert.throws(() => buildCreateSeoArticleM4Input({ m3Result: m3, evidence, guidanceSnapshot: streetKingzGuidanceSnapshot })); } });
test("M4 output cannot change primary query, type or intent", () => { const input = buildCreateSeoArticleM4Input({ m3Result: context(), evidence, guidanceSnapshot: streetKingzGuidanceSnapshot }); const output = { primary_query: "other", article_type: "supporting_article", search_intent: "mixed", sections: [] }; assert.ok(validateCreateSeoArticleM4Output(output, input).some((item) => /changed/.test(item))); });
test("M4 rejects fabricated evidence, products and URLs", () => { const input = buildCreateSeoArticleM4Input({ m3Result: context(), evidence, guidanceSnapshot: streetKingzGuidanceSnapshot }); const output = { primary_query: input.opportunity.primary_query, article_type: input.opportunity.article_type, search_intent: input.opportunity.search_intent, evidence_ids: ["invented"], sections: [{ heading: "x", purpose: "x", evidence_ids: ["invented"], component_type: "faq" }], cta: { product_id: "invented", purpose: "x", placement: "x", rationale: "x", url: "https://evil.test" } }; const errors = validateCreateSeoArticleM4Output(output, input); assert.ok(errors.some((item) => /Unknown evidence|unknown product|URLs/.test(item))); });
test("brief and page plan are separate, linked and provenance-bound", () => { const input = buildCreateSeoArticleM4Input({ m3Result: context(), evidence, guidanceSnapshot: streetKingzGuidanceSnapshot }); const output = { primary_query: input.opportunity.primary_query, article_type: input.opportunity.article_type, search_intent: input.opportunity.search_intent, working_title: "A useful widget guide", article_purpose: "Help readers", target_reader: "Readers", reader_problem: "A problem", reader_outcome: "An outcome", commercial_objective: "Consideration", product_role: "Optional product example", supporting_queries: ["widget guide"], questions: [], sections: [{ heading: "Criteria", level: "h2", purpose: "Explain criteria", evidence_ids: ["kw"], component_type: "criteria_cards" }, { heading: "How to use it", level: "h2", purpose: "Explain use", evidence_ids: ["pf"], component_type: "rich_text_section" }, { heading: "Next step", level: "h2", purpose: "Offer next step", evidence_ids: ["serp"], component_type: "conclusion" }], cta: { purpose: "Consider", placement: "end", product_id: null, rationale: "natural" }, faq: [], media: [], structured_data: { recommendation: "none", rationale: "not needed" }, target_length: { mode: "coverage-led", rationale: "coverage" }, unknowns: ["GSC unknown"], evidence_ids: ["kw", "pf", "serp"] }; const errors = validateCreateSeoArticleM4Output(output, input); assert.deepEqual(errors, []); const { brief, plan } = buildArticleBriefAndPagePlan({ output, input }); assert.equal(plan.brief_id, brief.brief_id); assert.equal(plan.brief_sha256, brief.brief_sha256); assert.equal(brief.provenance.seo_guidance_snapshot_id, streetKingzGuidanceSnapshot.snapshot_id); });
test("missing cannibalisation evidence remains an explicit unknown", () => { const input = buildCreateSeoArticleM4Input({ m3Result: context(), evidence, guidanceSnapshot: streetKingzGuidanceSnapshot }); assert.ok(input.research.unknowns.some((item) => /Search Console/.test(item))); assert.equal(input.registries.internal_link_coverage, "partial"); });
test("unsupported prose and ranking claims fail closed", () => { const input = buildCreateSeoArticleM4Input({ m3Result: context(), evidence, guidanceSnapshot: streetKingzGuidanceSnapshot }); const output = { primary_query: input.opportunity.primary_query, article_type: input.opportunity.article_type, search_intent: input.opportunity.search_intent, sections: [{ heading: "x", purpose: "word ".repeat(130), evidence_ids: [], component_type: "rich_text_section" }], structured_data: { recommendation: "This guarantees ranking factor", rationale: "rank higher" } }; const errors = validateCreateSeoArticleM4Output(output, input); assert.ok(errors.length >= 2); });
