import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { canonicalJson, sha256 } from "../research/core/canonical.js";
import { deriveCornerstoneStrategyAllowlists } from "../cornerstone/strategy-allowlists.js";
import { COMPONENT_DATA_SCHEMAS, COMPONENT_TYPES, EDITORIAL_PAGE_SCHEMA_VERSION, editorialPageJsonSchema } from "../editorial/contracts.js";
import { buildEditorialPagePlan } from "../editorial/plan.js";
import { renderEditorialPagePlan } from "../editorial/render.js";
import { validateEditorialPagePlan, validateStructuredEditorialPage } from "../editorial/validation.js";

const PACKET = "artifacts/cornerstone/best-car-drying-towel/fixture-v1/research-packet.json";
const STRATEGY = "artifacts/cornerstone/best-car-drying-towel/strategy-v1/gpt-5.6-sol/call_002/strategy.json";
const load = async () => { const [packet, strategy] = await Promise.all([readFile(PACKET, "utf8").then(JSON.parse), readFile(STRATEGY, "utf8").then(JSON.parse)]); const allowlists = deriveCornerstoneStrategyAllowlists(packet); const plan = buildEditorialPagePlan({ packet, strategy }); return { packet, strategy, allowlists, plan }; };
const codes = (errors) => errors.map((item) => item.code);

function componentData(slot) {
  const ev = slot.evidence_ids.slice(0, 2);
  const product = slot.product_ids[0] || null;
  const data = {
    hero: { h1: "A bounded page heading", supporting_copy: "A short reader promise grounded in the approved strategy.", trust_update_note: null },
    quick_answer: { heading: "Quick answer", concise_answer: "Choose according to the verified criteria and your use case.", supporting_points: ["Start with the task", "Check practical fit"] },
    rich_text_section: { heading: slot.required_content[0] || "Useful explanation", paragraphs: ["A bounded semantic paragraph that does not contain HTML."], key_points: ["A practical point"] },
    key_takeaway: { heading: "Care takeaway", takeaway: "Follow the evidenced care instructions.", supporting_points: ["Avoid unsupported additions"] },
    comparison_table: { heading: "What can be compared", columns: ["Criterion", "What is known"], rows: [{ label: "Construction", cells: ["Construction", "Evidence remains bounded"], evidence_ids: ev }], limitations: ["No unsupported performance ranking"] },
    criteria_cards: { heading: "Selection criteria", cards: [{ title: "Practical fit", explanation: "Assess the verified attributes against the intended task.", evidence_ids: ev }] },
    image_text: { heading: "Visual explanation", body: ["Explain the depicted task."], media_requirement_id: slot.media_requirements[0]?.requirement_id || "media_required" },
    product_recommendation: { heading: "A relevant option", product_id: product, recommendation_context: "Consider after understanding the criteria.", relevance_reason: "The product is in the bounded registry.", cta_direction: "Review verified specifications." },
    product_comparison: { heading: "Product comparison", product_ids: slot.product_ids, comparison_points: [{ criterion: "Verified attribute", values: slot.product_ids.map(() => "Bounded value"), evidence_ids: ev }], limitations: ["No unsupported winner"] },
    pros_tradeoffs: { heading: "Pros and tradeoffs", advantages: ["Verified advantage"], tradeoffs: ["Verified tradeoff"], suitable_for: ["Supported use"], not_ideal_for: ["Unsupported use"] },
    founder_note: { heading: "A first-party note", opinion: "This is clearly labelled opinion.", attribution: "Street Kingz", fact_boundary: "Opinion is not independent evidence." },
    faq: { heading: "Questions", items: [{ question: "What should the reader consider?", answer: "Use the evidence-bounded criteria.", evidence_ids: ev, claim_kind: "evidenced_fact" }] },
    related_guides: { heading: "Related guides", links: slot.internal_link_ids.map((internal_link_id) => ({ internal_link_id, context: "Continue with a related bounded page." })) },
    conclusion: { heading: "Conclusion", summary: "Apply the decision framework without inventing certainty.", next_step: "Review the relevant evidence-backed option if appropriate." },
    call_to_action: { heading: "Next step", body: "Take the next useful step.", cta_direction: "Review a bounded destination.", product_id: product, internal_link_id: slot.internal_link_ids[0] || null }
  };
  return data[slot.component_type];
}

function draft(plan) {
  return {
    schema_version: EDITORIAL_PAGE_SCHEMA_VERSION, artifact_type: "structured_semantic_editorial_page", page_type: plan.page_type,
    topic: plan.topic, search_intent: plan.search_intent, title: "A bounded editorial page title", h1: plan.h1_direction,
    introduction_deck: "A concise introduction that explains the reader outcome.",
    components: plan.components.map((slot) => ({ component_id: slot.component_id, component_type: slot.component_type, evidence_ids: slot.evidence_ids, product_ids: slot.product_ids, internal_link_ids: slot.internal_link_ids, media_requirements: slot.media_requirements, conversion_role: slot.conversion_role, data: componentData(slot) })),
    conclusion: "A concise decision summary.",
    validation_metadata: { packet_id: plan.packet_id, strategy_id: plan.strategy_id, page_plan_id: plan.plan_id, page_plan_hash: plan.deterministic_content_sha256 }
  };
}

test("component catalogue is versioned and each supported type has a strict schema", () => { assert.equal(COMPONENT_TYPES.length, 15); assert.deepEqual(Object.keys(COMPONENT_DATA_SCHEMAS).sort(), [...COMPONENT_TYPES].sort()); for (const schema of Object.values(COMPONENT_DATA_SCHEMAS)) assert.equal(schema.additionalProperties, false); });
test("first fixture plan is deterministic, valid and drafting remains unauthorised", async () => { const { packet, strategy, allowlists } = await load(); const first = buildEditorialPagePlan({ packet, strategy }); const second = buildEditorialPagePlan({ packet, strategy }); assert.deepEqual(second, first); assert.deepEqual(validateEditorialPagePlan(first, allowlists), []); assert.equal(first.drafting_authorised, false); assert.equal(first.publication_authorised, false); assert.equal(first.components[0].component_type, "hero"); assert.equal(first.components[1].component_type, "quick_answer"); assert.equal(first.components.at(-1).component_type, "conclusion"); });
test("component requirements belong to each plan rather than a universal article template", async () => { const { plan, allowlists } = await load(); const custom = structuredClone(plan); custom.page_type = "category_guide"; custom.components = custom.components.filter((item) => !["hero", "quick_answer", "conclusion"].includes(item.component_type)); custom.component_sequence = custom.components.map((item) => item.component_id); custom.component_requirements = { policy_id: "category_resource_v1", required_component_types: ["criteria_cards"], ordering_rules: [] }; assert.deepEqual(validateEditorialPagePlan(custom, allowlists), []); const brokenCurrent = structuredClone(plan); brokenCurrent.components.shift(); brokenCurrent.component_sequence = brokenCurrent.components.map((item) => item.component_id); assert.ok(codes(validateEditorialPagePlan(brokenCurrent, allowlists)).includes("REQUIRED_COMPONENT_MISSING")); });
test("valid semantic page follows exact approved component sequence", async () => { const { plan, allowlists } = await load(); assert.deepEqual(validateStructuredEditorialPage(draft(plan), { plan, allowlists }), []); });
test("unknown component type and malformed component fail closed", async () => { const { plan, allowlists } = await load(); const unknown = draft(plan); unknown.components[2].component_type = "magic_block"; assert.ok(codes(validateStructuredEditorialPage(unknown, { plan, allowlists })).includes("COMPONENT_PLAN_DEVIATION")); const malformed = draft(plan); delete malformed.components[1].data.concise_answer; assert.ok(codes(validateStructuredEditorialPage(malformed, { plan, allowlists })).includes("SCHEMA_INVALID")); });
test("duplicate component IDs and altered ordering fail", async () => { const { plan, allowlists } = await load(); const duplicate = structuredClone(plan); duplicate.components[1].component_id = duplicate.components[0].component_id; duplicate.component_sequence = duplicate.components.map((item) => item.component_id); assert.ok(codes(validateEditorialPagePlan(duplicate, allowlists)).includes("DUPLICATE_COMPONENT_ID")); const changed = draft(plan); [changed.components[0], changed.components[1]] = [changed.components[1], changed.components[0]]; assert.ok(codes(validateStructuredEditorialPage(changed, { plan, allowlists })).includes("COMPONENT_PLAN_DEVIATION")); });
test("unknown evidence product and internal-link IDs are rejected", async () => { const { plan, allowlists } = await load(); for (const [field, value, code] of [["evidence_ids", "ev_unknown", "UNKNOWN_EVIDENCE_ID"], ["product_ids", "product_unknown", "UNKNOWN_PRODUCT_ID"], ["internal_link_ids", "link_unknown", "UNKNOWN_INTERNAL_LINK_ID"]]) { const valueDraft = draft(plan); valueDraft.components[0][field] = [value]; assert.ok(codes(validateStructuredEditorialPage(valueDraft, { plan, allowlists })).includes(code)); } });
test("invented URLs and media URLs are rejected", async () => { const { plan, allowlists } = await load(); const url = draft(plan); url.components[1].data.concise_answer = "Visit https://example.com/invented"; assert.ok(codes(validateStructuredEditorialPage(url, { plan, allowlists })).includes("INVENTED_URL")); const media = draft(plan); media.components[0].media_requirements[0].url = "https://example.com/image.jpg"; const result = validateStructuredEditorialPage(media, { plan, allowlists }); assert.ok(codes(result).includes("SCHEMA_INVALID") || codes(result).includes("INVENTED_MEDIA_URL")); });
test("unsupported factual component without evidence is rejected", async () => { const { plan, allowlists } = await load(); const page = draft(plan); page.components.find((item) => item.component_type === "quick_answer").evidence_ids = []; assert.ok(codes(validateStructuredEditorialPage(page, { plan, allowlists })).includes("UNSUPPORTED_FACTUAL_CLAIM")); });
test("product promotion outside registry is impossible", async () => { const { plan, allowlists } = await load(); const page = draft(plan); const product = page.components.find((item) => item.component_type === "product_recommendation"); product.product_ids = ["product_unregistered"]; product.data.product_id = "product_unregistered"; assert.ok(codes(validateStructuredEditorialPage(page, { plan, allowlists })).includes("UNKNOWN_PRODUCT_ID")); });
test("HTML and document-level Markdown cannot escape component contract", async () => { const { plan, allowlists } = await load(); for (const text of ["<section>Arbitrary HTML</section>", "# Entire article\nBody"]) { const page = draft(plan); page.components[1].data.concise_answer = text; assert.ok(codes(validateStructuredEditorialPage(page, { plan, allowlists })).includes("ARBITRARY_HTML_OR_DOCUMENT")); } });
test("unplanned component and strategy binding deviation are rejected", async () => { const { plan, allowlists } = await load(); const extra = draft(plan); extra.components.splice(-1, 0, structuredClone(extra.components[2])); extra.components.at(-2).component_id = "unplanned_component"; assert.ok(codes(validateStructuredEditorialPage(extra, { plan, allowlists })).includes("COMPONENT_PLAN_DEVIATION")); const drift = draft(plan); drift.validation_metadata.strategy_id = "strategy_other"; assert.ok(codes(validateStructuredEditorialPage(drift, { plan, allowlists })).includes("STRATEGY_OR_PLAN_DEVIATION")); });
test("canonicalisation and hashing are deterministic", async () => { const { packet, strategy, plan } = await load(); assert.equal(sha256(buildEditorialPagePlan({ packet, strategy })), sha256(plan)); assert.equal(canonicalJson(draft(plan)), canonicalJson(structuredClone(draft(plan)))); });
test("plan renderer is concise, component-led and contains no drafted article", async () => { const { plan, allowlists } = await load(); const markdown = renderEditorialPagePlan(plan, allowlists); assert.match(markdown, /^# Proposed Component Page Plan/); assert.match(markdown, /Drafting authorised: \*\*NO\*\*/); assert.ok(markdown.length < 12000); });
test("synthetic non-towel topic can omit comparison, products and product recommendation", async () => { const { packet, strategy } = await load(); const p = structuredClone(packet); const s = structuredClone(strategy); p.packet_id = "packet_alloy_wheel_guide"; p.identity = { ...p.identity, topic: "How to clean alloy wheels safely", primary_query: "how to clean alloy wheels", proposed_url: "https://streetkingz.co.uk/guides/clean-alloy-wheels/" }; p.streetkingz_relevance.relevant_products = []; p.streetkingz_relevance.possible_internal_links = []; s.strategy_id = "strategy_alloy_wheels"; s.packet_id = p.packet_id; s.streetkingz_integration.genuinely_relevant_products = []; s.internal_linking = []; s.priorities.must_cover_topics = []; s.priorities.questions_requiring_strong_answers = []; s.structure.recommended_h1_direction = { statement: "How to clean alloy wheels safely", evidence_ids: s.decision.evidence_ids.slice(0, 1) }; s.strategy.reader_outcome = { statement: "The reader should understand a bounded and safe wheel-cleaning process.", evidence_ids: s.decision.evidence_ids.slice(0, 1) }; s.structure.sections = [{ heading_direction: "Assess the wheel condition", purpose: "Help the reader identify the cleaning context before choosing a process.", evidence_dependencies: s.decision.evidence_ids.slice(0, 1) }, { heading_direction: "Use a safe cleaning sequence", purpose: "Present the evidenced process in a practical order.", evidence_dependencies: s.decision.evidence_ids.slice(0, 1) }]; const plan = buildEditorialPagePlan({ packet: p, strategy: s }); assert.equal(plan.components.some((item) => item.component_type === "comparison_table"), false); assert.equal(plan.components.some((item) => item.component_type === "product_recommendation"), false); assert.equal(JSON.stringify(plan).toLowerCase().includes("drying towel"), false); });
test("one and multiple packet-backed products are supported without hard-coded IDs", async () => { const { packet, strategy, plan } = await load(); assert.equal(plan.components.find((item) => item.component_type === "product_recommendation").product_ids.length, 1); const p = structuredClone(packet); const s = structuredClone(strategy); const second = { subject_id: "product_synthetic_second", name: "Synthetic second product", url: "https://streetkingz.co.uk/product/synthetic-second/", evidence_ids: [p.evidence.source_references[0].evidence_id] }; p.streetkingz_relevance.relevant_products.push(second); s.streetkingz_integration.genuinely_relevant_products.push({ product_id: second.subject_id, recommended_role: "alternative", placement_reason: "Synthetic fixture relevance.", evidence_ids: second.evidence_ids, canonical_product: { product_id: second.subject_id, name: second.name, url: second.url, evidence_ids: second.evidence_ids } }); const multi = buildEditorialPagePlan({ packet: p, strategy: s }); assert.equal(multi.components.find((item) => item.component_type === "product_recommendation").product_ids.length, 2); });
test("schema retains packet-derived evidence product and link enums", async () => { const { allowlists } = await load(); const schema = editorialPageJsonSchema(allowlists); assert.deepEqual(schema.$defs.evidence_id.enum, allowlists.evidence_ids); assert.deepEqual(schema.$defs.product_id.enum, allowlists.product_ids); assert.deepEqual(schema.$defs.internal_link_id.enum, allowlists.internal_link_ids); });
