import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { createEditorialIntelligenceContext, validateEditorialIntelligenceContext, writeEditorialIntelligenceArtifacts } from "../editorial-intelligence/context.js";

const businessPath = "artifacts/business-intelligence/streetkingz-co-uk/2026-08-15T06-44-34-338Z/founder-validation/business-intelligence-validated.json";
const productPath = "artifacts/product-intelligence-founder-validation/heavy-duty-drying-towel-1200gsm/2026-08-14T06-34-06-755Z/product-intelligence-corrected.json";
const load = async () => ({ business: JSON.parse(await readFile(businessPath, "utf8")), product: JSON.parse(await readFile(productPath, "utf8")) });

test("validated BIO and PIO produce a bounded editorial context", async () => { const { business, product } = await load(); const context = createEditorialIntelligenceContext({ businessIntelligence: business, productIntelligence: product, createdAt: "2026-08-15T13:00:00.000Z" }); assert.deepEqual(validateEditorialIntelligenceContext(context), []); assert.equal(context.editorial_objective.primary_objective, "persuade_the_intended_customer_to_buy"); assert.ok(JSON.stringify(context).length < 60000); });
test("unvalidated business or product intelligence is rejected", async () => { const { business, product } = await load(); assert.throws(() => createEditorialIntelligenceContext({ businessIntelligence: { ...business, validation_status: "awaiting_validation" }, productIntelligence: product }), /validated Business Intelligence/i); assert.throws(() => createEditorialIntelligenceContext({ businessIntelligence: business, productIntelligence: { ...product, product_intelligence_object: { ...product.product_intelligence_object, validation_status: "awaiting_validation" } } }), /validated Product Intelligence/i); });
test("human-corrected values are projected while superseded history is not used as current fields", async () => { const { business, product } = await load(); const context = createEditorialIntelligenceContext({ businessIntelligence: business, productIntelligence: product }); assert.equal(context.business.identity.owned_brand_status.status, "human_corrected"); assert.equal(context.product.customer_understanding.ideal_customers[0].status, "human_corrected"); assert.equal(context.provenance_summary.superseded_values_included, false); });
test("business audience remains primary and product audience is scoped as refinement", async () => { const { business, product } = await load(); const context = createEditorialIntelligenceContext({ businessIntelligence: business, productIntelligence: product }); assert.match(context.audience.precedence, /validated_business_audience_is_primary/); assert.ok(context.audience.business_wide_primary); assert.ok(context.audience.product_specific_refinement); });
test("meaningful audience conflict is surfaced instead of silently merged", async () => { const { business, product } = await load(); const modified = structuredClone(product); modified.product_intelligence_object.customer_understanding.ideal_customers[0] = { ...modified.product_intelligence_object.customer_understanding.ideal_customers[0], value: "Industrial procurement teams" }; const context = createEditorialIntelligenceContext({ businessIntelligence: business, productIntelligence: modified }); assert.ok(context.conflicts.some((conflict) => conflict.type === "audience_scope_conflict")); });
test("existing intelligence conflicts remain auditable in the editorial context", async () => { const { business, product } = await load(); const context = createEditorialIntelligenceContext({ businessIntelligence: business, productIntelligence: product }); assert.ok(context.conflicts.some((conflict) => conflict.source === "product")); });
test("facts, derived benefits, claims and unknowns remain distinguishable", async () => { const { business, product } = await load(); const context = createEditorialIntelligenceContext({ businessIntelligence: business, productIntelligence: product }); assert.equal(context.product.features[0].knowledge_type, "fact"); assert.equal(context.product.benefits[0].knowledge_type, "derived"); assert.equal(context.business.positioning.positioning_claims[0].assertion_scope, "business_claim"); assert.ok(context.product.identity.brand.knowledge_type === "unknown" || context.product.identity.brand.value === null); });
test("irrelevant gaps are excluded while editorially relevant gaps remain", async () => { const { business, product } = await load(); const modified = structuredClone(business); modified.knowledge_gaps.push({ field: "sampling_method", importance: "low", reason: "Only a bounded sample was used." }); const context = createEditorialIntelligenceContext({ businessIntelligence: modified, productIntelligence: product }); assert.ok(!context.knowledge_gaps.business.some((gap) => gap.field === "sampling_method")); });
test("raw source evidence is not copied into context and persuasion is explicitly permitted", async () => { const { business, product } = await load(); const context = createEditorialIntelligenceContext({ businessIntelligence: business, productIntelligence: product }); const forbiddenKeys = Object.keys(context).filter((key) => key === "source_evidence"); assert.deepEqual(forbiddenKeys, []); assert.equal(context.editorial_boundaries.permitted_persuasion.includes("benefit_led_framing"), true); assert.equal(context.provenance_summary.raw_source_evidence_included, false); });
test("generic context projection has no Street Kingz-specific configuration", async () => { const { business, product } = await load(); const replace = (value) => Array.isArray(value) ? value.map(replace) : value && typeof value === "object" ? Object.fromEntries(Object.entries(value).map(([key, child]) => [key, replace(child)])) : typeof value === "string" ? value.replace(/Street Kingz/gi, "Generic Supply") : value; const genericBusiness = replace(business); genericBusiness.metadata.business_id = "generic-business"; const genericProduct = replace(product); genericProduct.product_intelligence_object.metadata.object_id = "generic-product"; const context = createEditorialIntelligenceContext({ businessIntelligence: genericBusiness, productIntelligence: genericProduct }); assert.equal(context.metadata.business_id, "generic-business"); assert.equal(JSON.stringify(context).includes("Street Kingz"), false); });
test("context artifact writing is deterministic and makes no network calls", async (t) => { const { business, product } = await load(); const root = await mkdtemp("/tmp/editorial-context-"); t.after(() => rm(root, { recursive: true, force: true })); let network = 0; const oldFetch = globalThis.fetch; globalThis.fetch = () => { network += 1; throw new Error("network forbidden"); }; try { const result = await writeEditorialIntelligenceArtifacts({ businessIntelligence: business, productIntelligence: product, outputRoot: `${root}/out`, createdAt: "2026-08-15T13:00:00.000Z" }); assert.ok(result.files.context.endsWith("editorial-intelligence-context.json")); assert.equal(network, 0); } finally { globalThis.fetch = oldFetch; } });
