import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, readdir } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { deriveCornerstoneStrategyAllowlists } from "../cornerstone/strategy-allowlists.js";
import { buildEditorialPagePlan } from "../editorial/plan.js";
import { EDITORIAL_PAGE_SCHEMA_VERSION, editorialPageJsonSchema } from "../editorial/contracts.js";
import { buildEditorialDraftInput, buildEditorialDraftPrompt, EDITORIAL_DRAFT_SYSTEM_PROMPT } from "../editorial/draft-prompt.js";
import { validateStructuredEditorialPage } from "../editorial/validation.js";
import { reviewEditorialDraftQuality } from "../editorial/draft-quality.js";
import { runControlledEditorialDraft } from "../editorial/draft-run.js";
import { renderEditorialDraftMarkdown } from "../editorial/draft-render.js";

const PACKET = "artifacts/cornerstone/best-car-drying-towel/fixture-v1/research-packet.json";
const STRATEGY = "artifacts/cornerstone/best-car-drying-towel/strategy-v1/gpt-5.6-sol/call_002/strategy.json";
const load = async () => { const [packet, strategy] = await Promise.all([readFile(PACKET, "utf8").then(JSON.parse), readFile(STRATEGY, "utf8").then(JSON.parse)]); const allowlists = deriveCornerstoneStrategyAllowlists(packet); const plan = buildEditorialPagePlan({ packet, strategy }); const approval = { status: "APPROVED", plan_id: plan.plan_id, plan_hash: plan.deterministic_content_sha256, semantic_drafting: true, wordpress_publication: false, wordpress_mutation: false }; return { packet, strategy, allowlists, plan, approval }; };

function data(slot) {
  const ev = slot.evidence_ids.slice(0, 2);
  const values = {
    hero: { h1: "Best Car Drying Towel: A Practical Guide to Choosing the Right One", supporting_copy: "Choose a towel that fits your vehicle, routine and handling preferences rather than relying on one specification.", trust_update_note: null },
    quick_answer: { heading: "Quick answer", concise_answer: "The best car drying towel is the one that suits your vehicle size and drying routine, combines suitable construction and dimensions, and remains manageable when wet; GSM is one useful specification, not proof of quality on its own.", supporting_points: ["Check construction, dimensions and edging.", "Consider vehicle size and wet handling."] },
    criteria_cards: { heading: "What to look for", cards: [{ title: "Practical fit", explanation: "Assess construction, dimensions, edging and handling against your own vehicle and routine.", evidence_ids: ev }] },
    comparison_table: { heading: "Comparing common options", columns: ["Option", "Evidence boundary"], rows: [{ label: "Microfibre", cells: ["Microfibre", "Compare verified construction and intended use rather than assuming a universal winner."], evidence_ids: ev }], limitations: ["The packet does not establish an objective performance winner."] },
    rich_text_section: { heading: slot.required_content[0], paragraphs: [`Use the verified guidance for ${slot.required_content[0].toLowerCase()} and keep every practical claim within the supplied evidence.`], key_points: ["Choose for the actual task and vehicle."] },
    product_recommendation: { heading: "A relevant high-GSM option", product_id: slot.product_ids[0], recommendation_context: "This option is relevant after considering the selection criteria and whether its size and wet handling suit your routine.", relevance_reason: "The packet verifies its construction, dimensions, edging, intended uses, care guidance and handling limitation.", cta_direction: "Review the verified specifications and decide whether they fit your vehicle." },
    key_takeaway: { heading: "Care matters", takeaway: "Follow the supplied washing and drying instructions so the towel is maintained as intended.", supporting_points: ["Avoid fabric softener and bleach.", "Air dry rather than tumble dry."] },
    faq: { heading: "Questions car owners ask", items: [{ question: "How should you choose a car drying towel?", answer: "Compare verified construction, size, edging, intended use and manageability when wet against your vehicle and routine instead of treating one number as a complete quality score.", evidence_ids: ev, claim_kind: "evidenced_fact" }] },
    conclusion: { heading: "Choose for the job", summary: "Start with how and what you need to dry, compare the verified practical criteria, then choose an option whose size and handling fit that routine.", next_step: "Review the registered product specifications only if that high-GSM option matches your needs." }
  };
  return values[slot.component_type];
}

function page(plan) {
  return { schema_version: EDITORIAL_PAGE_SCHEMA_VERSION, artifact_type: "structured_semantic_editorial_page", page_type: plan.page_type, topic: plan.topic, search_intent: plan.search_intent, title: plan.title_direction, h1: plan.h1_direction, introduction_deck: "A practical, evidence-bounded way to choose a drying towel without turning car care into a hobby.", components: plan.components.map((slot) => ({ component_id: slot.component_id, component_type: slot.component_type, evidence_ids: slot.evidence_ids, product_ids: slot.product_ids, internal_link_ids: slot.internal_link_ids, media_requirements: slot.media_requirements, conversion_role: slot.conversion_role, data: data(slot) })), conclusion: "Choose according to practical fit and verified specifications.", validation_metadata: { packet_id: plan.packet_id, strategy_id: plan.strategy_id, page_plan_id: plan.plan_id, page_plan_hash: plan.deterministic_content_sha256 } };
}

test("approved draft input is deterministic, bounded and contains no CMS authority", async () => { const { packet, strategy, allowlists, plan, approval } = await load(); const args = { packet, strategy, allowlists, plan, approval, brandRules: { audience: "normal car owners" } }; const first = buildEditorialDraftInput(args); const second = buildEditorialDraftInput(args); assert.deepEqual(second, first); assert.equal(first.authority.wordpress_mutation, false); assert.equal(first.authority.publication, false); const prompt = buildEditorialDraftPrompt(first); assert.match(prompt, /Preserve its component IDs, types, sequence/i); assert.match(EDITORIAL_DRAFT_SYSTEM_PROMPT, /Never return HTML/); });
test("generation schema contains only approved component IDs and exact count", async () => { const { allowlists, plan } = await load(); const schema = editorialPageJsonSchema(allowlists, plan); assert.equal(schema.properties.components.minItems, plan.components.length); assert.equal(schema.properties.components.maxItems, plan.components.length); const ids = schema.properties.components.items.anyOf.map((item) => item.properties.component_id.enum[0]); assert.deepEqual(ids, plan.component_sequence); });
test("valid component draft passes schema and qualitative review", async () => { const { allowlists, plan } = await load(); const value = page(plan); assert.deepEqual(validateStructuredEditorialPage(value, { plan, allowlists }), []); assert.equal(reviewEditorialDraftQuality(value).status, "PASS"); });
test("human-review renderer emits one visible page title/H1 without a repeated hero heading", async () => { const { allowlists, plan } = await load(); const value = page(plan); const markdown = renderEditorialDraftMarkdown(value, allowlists); const h1s = markdown.match(/^# .+$/gm) || []; assert.equal(h1s.length, 1); assert.equal(h1s[0], `# ${value.h1}`); assert.equal((markdown.match(new RegExp(`^## ${value.h1.replace(/[.*+?^${}()|[\\]\\\\]/g, "\\\\$&")}$`, "gm")) || []).length, 0); assert.equal((markdown.match(/^## hero$/gm) || []).length, 0); });
test("quality review rejects filler invented testing weak answers repetition and forced product ordering", async () => { const { plan } = await load(); for (const mutate of [
  (p) => { p.introduction_deck = "In this comprehensive guide we unlock the secrets."; },
  (p) => { p.components[1].data.concise_answer = "We tested every towel and found a winner."; },
  (p) => { p.components[1].data.concise_answer = "It depends."; },
  (p) => { p.components.find((x) => x.component_type === "faq").data.items[0].answer = "It depends."; },
  (p) => { const items = p.components; const product = items.findIndex((x) => x.component_type === "product_recommendation"); const criteria = items.findIndex((x) => x.component_type === "criteria_cards"); [items[product], items[criteria]] = [items[criteria], items[product]]; }
]) { const value = page(plan); mutate(value); assert.equal(reviewEditorialDraftQuality(value).status, "FAIL"); } });
test("validator rejects invented experience and strategy or media-plan deviation", async () => { const { allowlists, plan } = await load(); const experience = page(plan); experience.components[1].data.concise_answer = "We tested these products ourselves and found the answer."; assert.ok(validateStructuredEditorialPage(experience, { plan, allowlists }).some((item) => item.code === "INVENTED_EXPERIENCE")); const media = page(plan); media.components[0].media_requirements = []; assert.ok(validateStructuredEditorialPage(media, { plan, allowlists }).some((item) => item.code === "COMPONENT_PLAN_DEVIATION")); const h1 = page(plan); h1.h1 = "A different strategy"; assert.ok(validateStructuredEditorialPage(h1, { plan, allowlists }).some((item) => item.code === "STRATEGY_OR_PLAN_DEVIATION")); });
test("controlled run makes one zero-retry call and writes immutable accepted artifacts", async () => { const { packet, strategy, allowlists, plan, approval } = await load(); const outputDirectory = await mkdtemp(path.join(os.tmpdir(), "editorial-draft-pass-")); let calls = 0; const valid = page(plan); const provider = { id: "fixture", model: "fixture-model", settings: { strict: true }, requestPayload: () => ({ bounded: true }), generate: async () => { calls += 1; return { provider: "fixture", model: "fixture-model", response_id: "fixture", rawText: JSON.stringify(valid), usage: { input_tokens: 100, output_tokens: 200, total_tokens: 300 } }; } }; const result = await runControlledEditorialDraft({ packet, strategy, plan, approval, allowlists, brandRules: {}, provider, outputDirectory, env: {} }); assert.equal(result.accepted, true); assert.equal(calls, 1); const callRoot = path.join(outputDirectory, "fixture-model"); const callsOnDisk = await readdir(callRoot); assert.deepEqual(callsOnDisk, ["call_001"]); const files = await readdir(path.join(callRoot, "call_001")); for (const name of ["draft-input.json", "draft-response-raw.json", "draft-validation.json", "editorial-quality-review.json", "semantic-page.json", "semantic-page.md", "run-metadata.json"]) assert.ok(files.includes(name)); });
test("invalid response is preserved but cannot produce semantic page", async () => { const { packet, strategy, allowlists, plan, approval } = await load(); const outputDirectory = await mkdtemp(path.join(os.tmpdir(), "editorial-draft-fail-")); const invalid = page(plan); invalid.components[0].component_id = "invented"; const provider = { id: "fixture", model: "fixture-model", settings: {}, requestPayload: () => ({}), generate: async () => ({ provider: "fixture", model: "fixture-model", rawText: JSON.stringify(invalid), usage: {} }) }; const result = await runControlledEditorialDraft({ packet, strategy, plan, approval, allowlists, brandRules: {}, provider, outputDirectory, env: {} }); assert.equal(result.accepted, false); const files = await readdir(path.join(outputDirectory, "fixture-model", "call_001")); assert.ok(files.includes("draft-response-raw.json")); assert.equal(files.includes("semantic-page.json"), false); });
test("drafting requires exact separate human plan approval", async () => { const { packet, strategy, allowlists, plan, approval } = await load(); const provider = { model: "fixture", id: "fixture" }; const outputDirectory = await mkdtemp(path.join(os.tmpdir(), "editorial-approval-")); await assert.rejects(runControlledEditorialDraft({ packet, strategy, plan, approval: { ...approval, plan_hash: "wrong" }, allowlists, brandRules: {}, provider, outputDirectory, env: {} }), /approval/i); });
test("a separately authorised continuation can allocate call_002 without retrying call_001", async () => { const { packet, strategy, allowlists, plan, approval } = await load(); const outputDirectory = await mkdtemp(path.join(os.tmpdir(), "editorial-continuation-")); const valid = page(plan); let calls = 0; const provider = { id: "fixture", model: "fixture-model", settings: {}, requestPayload: () => ({}), generate: async () => { calls += 1; return { provider: "fixture", model: "fixture-model", rawText: JSON.stringify(valid), usage: {} }; } }; await runControlledEditorialDraft({ packet, strategy, plan, approval, allowlists, brandRules: {}, provider, outputDirectory, env: {}, maxCalls: 2 }); await runControlledEditorialDraft({ packet, strategy, plan, approval, allowlists, brandRules: {}, provider, outputDirectory, env: {}, maxCalls: 2 }); assert.equal(calls, 2); assert.deepEqual(await readdir(path.join(outputDirectory, "fixture-model")), ["call_001", "call_002"]); await assert.rejects(runControlledEditorialDraft({ packet, strategy, plan, approval, allowlists, brandRules: {}, provider, outputDirectory, env: {}, maxCalls: 2 }), /limit reached/i); });
