import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, readdir } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { sha256 } from "../research/core/canonical.js";
import { deriveCornerstoneStrategyAllowlists } from "../cornerstone/strategy-allowlists.js";
import { buildEditorialPagePlan } from "../editorial/plan.js";
import { STREET_KINGZ_FOUNDER_VOICE, validateFounderVoice } from "../editorial/founder-voice.js";
import { editorialRevisionJsonSchema } from "../editorial/revision-contracts.js";
import { validateEditorialRevision } from "../editorial/revision-validation.js";
import { reviewFounderRevisionQuality } from "../editorial/revision-quality.js";
import { runControlledFounderRevision } from "../editorial/revision-run.js";
import { buildDryingTowelConceptPolicy, validateConceptOwnership } from "../editorial/concept-ownership.js";
import { bindRevisionToImmediateSource, customerFacingProjection } from "../editorial/revision-lineage.js";

const ROOT = "artifacts/cornerstone/best-car-drying-towel";
const load = async () => { const [packet, strategy, sourcePage] = await Promise.all([readFile(`${ROOT}/fixture-v1/research-packet.json`, "utf8").then(JSON.parse), readFile(`${ROOT}/strategy-v1/gpt-5.6-sol/call_002/strategy.json`, "utf8").then(JSON.parse), readFile(`${ROOT}/component-draft-v1/gpt-5.6-sol/call_003/semantic-page.json`, "utf8").then(JSON.parse)]); const plan = buildEditorialPagePlan({ packet, strategy }); const allowlists = deriveCornerstoneStrategyAllowlists(packet); const conceptPolicy = buildDryingTowelConceptPolicy(plan); return { packet, strategy, sourcePage, sourcePageHash: sha256(sourcePage), plan, conceptPolicy, allowlists }; };
const annotation = (claim_text, claim_kind, evidence_ids = [], founder_fact_ids = []) => ({ claim_text, claim_kind, evidence_ids, founder_fact_ids });
const strings = (value, output = []) => { if (typeof value === "string") output.push(value); else if (Array.isArray(value)) value.forEach((item) => strings(item, output)); else if (value && typeof value === "object") Object.values(value).forEach((item) => strings(item, output)); return output; };

function component(slot) {
  const ev = slot.evidence_ids.slice(0, 1); const common = { component_id: slot.component_id, component_type: slot.component_type, evidence_ids: slot.evidence_ids, product_ids: slot.product_ids, internal_link_ids: slot.internal_link_ids, media_requirements: slot.media_requirements, conversion_role: slot.conversion_role };
  const data = {
    hero: { h1: "Best Car Drying Towel: A Practical Guide to Choosing the Right One", supporting_copy: "A straightforward way to choose a towel that fits your car and the way you wash it.", trust_update_note: null },
    quick_answer: { heading: "The short answer", concise_answer: "For most people, I'd choose a drying towel by looking at the whole package: how it is made, whether it is manageable on the car and whether it suits the job. One headline number cannot make that decision for you.", supporting_points: ["Start with the job you need it to do.", "Choose something you can handle comfortably."] },
    criteria_cards: { heading: "What matters when choosing", cards: [{ title: "GSM", explanation: "GSM is the fabric weight per square metre, but that headline number only makes sense alongside how the towel is made.", evidence_ids: ev }, { title: "Size", explanation: "The towel's dimensions affect how much panel it covers and how easy it is to control.", evidence_ids: ev }, { title: "Edging", explanation: "The edge finish is part of the complete construction and should suit the surface and intended use.", evidence_ids: ev }, { title: "Construction", explanation: "The weave and microfibre pile describe how the towel is made; consider them as part of the whole towel.", evidence_ids: ev }] },
    rich_text_section: slot.component_id.includes("cfb") ? { heading: "Match it to your car", paragraphs: ["A larger format can cover broad panels, but it still needs to feel manageable once it has taken on water."], key_points: ["Think about the car you actually wash."] } : { heading: "A simple way to dry the car", paragraphs: ["Start with clean paint, remove standing water, lay the towel flat and drag gently or pat without pressure."], key_points: ["Follow the instructions supplied with your own towel."] },
    product_recommendation: { heading: "Where our 1200gsm towel fits", product_id: slot.product_ids[0], recommendation_context: "I obviously sell drying towels, so I'm not going to pretend I don't have a horse in the race. Our large microfibre option is worth a look if that is the kind of towel you want.", relevance_reason: "It measures 90 × 60 cm, uses dual-sided microfibre with soft microfibre edging and becomes heavier when saturated.", cta_direction: "Offer a low-pressure route to the product specifications.", cta_label: "See the 1200gsm towel" },
    key_takeaway: { heading: "Keep it simple", takeaway: "Wash on a cold gentle cycle with suitable detergent, avoid fabric softener and bleach, then air dry.", supporting_points: ["Keep it clean for the next wash."] },
    faq: { heading: "A few common questions", items: [{ question: "Does a drying towel work?", answer: "Yes, when it is used for the job it was made for and according to its instructions.", evidence_ids: ev, claim_kind: "evidenced_fact" }, { question: "What do professional detailers use?", answer: "There is no single professional choice established here, so I would not pretend one towel or method is the universal standard.", evidence_ids: ev, claim_kind: "bounded_inference" }, { question: "Is a higher GSM always better?", answer: "No single number tells you everything. Consider how the complete towel fits your car and routine.", evidence_ids: ev, claim_kind: "bounded_inference" }] },
    conclusion: { heading: "Choose what fits your routine", summary: "The right towel is the one that suits your car, feels manageable and fits the way you prefer to work.", next_step: "If our large microfibre option sounds right for you, take a look at its specifications before deciding." }
  }[slot.component_type];
  const claims = [];
  if (slot.component_type === "quick_answer") claims.push(annotation(data.concise_answer, "founder_opinion"));
  else if (slot.component_type === "product_recommendation") { claims.push(annotation(data.recommendation_context, "founder_opinion")); claims.push(annotation(data.relevance_reason, "evidence_bound_fact", ev)); }
  else if (!["hero", "conclusion"].includes(slot.component_type)) claims.push(annotation(strings(data).find((value) => value.length > 30), slot.component_type === "faq" ? "editorial_judgement" : "evidence_bound_fact", ev));
  return { ...common, data, claim_annotations: claims };
}

async function validRevision() {
  const context = await load(); const comparisonId = context.plan.components.find((item) => item.component_type === "comparison_table").component_id;
  const components = context.plan.components.filter((item) => item.component_id !== comparisonId).map(component);
  const page = { schema_version: "1.1.0", artifact_type: "structured_semantic_editorial_page", page_type: context.plan.page_type, topic: context.plan.topic, search_intent: context.plan.search_intent, title: "Best Car Drying Towel: A Practical Guide to Choosing the Right One", h1: context.plan.h1_direction, introduction_deck: "Choose a towel that works for your car and routine without getting buried in detailing jargon.", components, conclusion: "Choose for practical fit, then look at the product only if it suits you.", validation_metadata: { packet_id: context.plan.packet_id, strategy_id: context.plan.strategy_id, source_page_plan_id: context.plan.plan_id, source_page_plan_hash: context.plan.deterministic_content_sha256, source_semantic_page_hash: context.sourcePageHash } };
  return { ...context, revision: { revision_version: "1.0.0", comparison_component_decision: { decision: "remove", rationale: "The available material does not support a useful factual comparison.", evidence_ids: [], customer_value: "Removing it keeps the page focused on decisions the reader can actually make." }, founder_note_decision: { decision: "omit", rationale: "Natural founder voice in the existing components is enough.", evidence_ids: [] }, page } };
}

test("founder voice contract is generic across editorial workflows", () => { assert.ok(STREET_KINGZ_FOUNDER_VOICE.applies_to.includes("cornerstone")); assert.ok(STREET_KINGZ_FOUNDER_VOICE.applies_to.includes("category_support")); assert.equal(JSON.stringify(STREET_KINGZ_FOUNDER_VOICE).toLowerCase().includes("drying towel"), false); });
test("bounded founder opinion is accepted without invented history", async () => { const { revision } = await validRevision(); const result = validateFounderVoice(revision.page); assert.equal(result.status, "PASS"); assert.equal(result.metrics.founder_fact_registry_count, 0); });
test("bounded first-person advice using always is not misclassified as lived experience", async () => { const { revision } = await validRevision(); const criteria = revision.page.components.find((item) => item.component_type === "criteria_cards"); criteria.data.cards[0].explanation = "I would always consider it alongside the towel's size and construction."; criteria.claim_annotations[0] = annotation(criteria.data.cards[0].explanation, "founder_opinion"); assert.equal(validateFounderVoice(revision.page).errors.some((item) => item.code === "UNSUPPORTED_FIRST_PERSON_EXPERIENCE"), false); });
test("unknown first-person experience fails closed", async () => { const { revision } = await validRevision(); const product = revision.page.components.find((item) => item.component_type === "product_recommendation"); product.data.recommendation_context = "I've tested dozens of towels and this one is best."; product.claim_annotations[0] = annotation(product.data.recommendation_context, "founder_opinion"); assert.ok(validateFounderVoice(revision.page).errors.some((item) => item.code === "UNSUPPORTED_FIRST_PERSON_EXPERIENCE")); });
test("approved founder fact can support an experiential statement", async () => { const { revision } = await validRevision(); const product = revision.page.components.find((item) => item.component_type === "product_recommendation"); product.data.recommendation_context = "I've used this towel for three years."; product.claim_annotations[0] = annotation(product.data.recommendation_context, "founder_fact", [], ["founder_fact_1"]); assert.equal(validateFounderVoice(revision.page, { founderFactIds: ["founder_fact_1"] }).errors.some((item) => item.code === "UNSUPPORTED_FIRST_PERSON_EXPERIENCE"), false); });
test("customer copy exposing internal governance language fails", async () => { const { revision } = await validRevision(); revision.page.introduction_deck = "This approved registry follows the evidence packet."; assert.ok(validateFounderVoice(revision.page).errors.some((item) => item.code === "INTERNAL_SYSTEM_LANGUAGE")); });
test("revision schema is strict and binds the exact immediate source", async () => { const { plan, allowlists, sourcePageHash } = await load(); const schema = editorialRevisionJsonSchema({ plan, allowlists, sourcePageHash }); assert.equal(schema.additionalProperties, false); assert.deepEqual(schema.properties.page.properties.validation_metadata.properties.source_semantic_page_hash.enum, [sourcePageHash]); assert.equal(schema.properties.page.properties.components.minItems, plan.components.length - 1); assert.equal(schema.properties.page.properties.components.maxItems, plan.components.length + 1); });
test("valid revision may remove only the declared comparison", async () => { const { revision, sourcePageHash, plan, conceptPolicy, allowlists } = await validRevision(); const result = validateEditorialRevision(revision, { sourcePageHash, plan, conceptPolicy, allowlists }); assert.equal(result.status, "PASS", JSON.stringify(result.errors)); assert.equal(result.conceptOwnership.status, "PASS"); });
test("undeclared component removal and ordering changes fail", async () => { const { revision, sourcePageHash, plan, conceptPolicy, allowlists } = await validRevision(); revision.page.components.splice(2, 1); assert.ok(validateEditorialRevision(revision, { sourcePageHash, plan, conceptPolicy, allowlists }).errors.some((item) => item.code === "REVISION_COMPONENT_DEVIATION")); });
test("founder note decision cannot silently add commercial scope", async () => { const { revision, sourcePageHash, plan, conceptPolicy, allowlists } = await validRevision(); revision.founder_note_decision.decision = "add"; const productIndex = revision.page.components.findIndex((item) => item.component_type === "product_recommendation"); revision.page.components.splice(productIndex, 0, { component_id: "revision_founder_note_v1", component_type: "founder_note", evidence_ids: [], product_ids: [allowlists.product_ids[0]], internal_link_ids: [], media_requirements: [], conversion_role: "education", claim_annotations: [], data: { heading: "A note from me", opinion: "I would keep the decision simple.", attribution: "Street Kingz founder", fact_boundary: "This is an opinion." } }); assert.ok(validateEditorialRevision(revision, { sourcePageHash, plan, conceptPolicy, allowlists }).errors.some((item) => item.code === "FOUNDER_NOTE_SCOPE")); });
test("repeated concepts fail deterministic repetition controls", async () => { const { revision, sourcePageHash, plan, conceptPolicy, allowlists } = await validRevision(); for (const item of revision.page.components) if (item.component_type !== "hero") item.data.heading = `${item.data.heading || "Section"} GSM matters because this headline number affects what you should choose and needs a full explanation.`; assert.ok(validateEditorialRevision(revision, { sourcePageHash, plan, conceptPolicy, allowlists }).errors.some((item) => item.code === "CONCEPT_REPETITION")); });
test("qualitative review requires natural founder voice and customer-ready CTA", async () => { const { revision, sourcePageHash, plan, conceptPolicy, allowlists } = await validRevision(); const validation = validateEditorialRevision(revision, { sourcePageHash, plan, conceptPolicy, allowlists }); assert.equal(reviewFounderRevisionQuality(revision, validation).status, "PASS"); const product = revision.page.components.find((item) => item.component_type === "product_recommendation"); product.data.cta_label = ""; assert.equal(reviewFounderRevisionQuality(revision, validation).status, "FAIL"); });
test("controlled fixture revision writes immutable accepted artifacts", async () => { const { revision, sourcePage, sourcePageHash, packet, strategy, plan, conceptPolicy, allowlists } = await validRevision(); const outputDirectory = await mkdtemp(path.join(os.tmpdir(), "founder-revision-")); const provider = { id: "fixture", model: "fixture-model", settings: {}, requestPayload: () => ({}), generate: async () => ({ provider: "fixture", model: "fixture-model", rawText: JSON.stringify(revision), usage: {} }) }; const result = await runControlledFounderRevision({ sourcePage, sourcePageHash, packet, strategy, plan, conceptPolicy, allowlists, provider, outputDirectory, env: {} }); assert.equal(result.accepted, true); const files = await readdir(path.join(outputDirectory, "fixture-model", "call_001")); for (const name of ["revision-input.json", "revision-response-raw.json", "semantic-page.json", "semantic-page.md", "revision-validation.json", "founder-voice-validation.json", "repetition-validation.json", "concept-ownership-validation.json", "editorial-quality-review.json", "comparison-component-decision.json", "run-metadata.json"]) assert.ok(files.includes(name)); });

test("brief cross-reference is allowed without consuming a substantial budget", async () => { const { revision, conceptPolicy } = await validRevision(); revision.page.components.find((item) => item.component_type === "quick_answer").data.supporting_points.push("Check the GSM too."); const result = validateConceptOwnership(revision.page, conceptPolicy); assert.equal(result.concepts.gsm.brief_reference_count > 0, true); assert.equal(result.status, "PASS", JSON.stringify(result.errors)); });
test("reworded substantial explanation is detected outside the owner", async () => { const { revision, conceptPolicy } = await validRevision(); revision.page.components.find((item) => item.component_type === "conclusion").data.summary = "The fabric weight per square metre matters because it changes what you should choose, so compare that headline number carefully before deciding."; assert.ok(validateConceptOwnership(revision.page, conceptPolicy).errors.some((item) => item.code === "CONCEPT_OWNERSHIP_VIOLATION")); });
test("product specification and concise FAQ reference remain distinct", async () => { const { revision, conceptPolicy } = await validRevision(); const result = validateConceptOwnership(revision.page, conceptPolicy); assert.equal(result.concepts.dimensions.product_specification_count > 0, true); assert.equal(result.concepts.gsm.faq_direct_answer_count > 0, true); });
test("conclusion checklist rehash fails its component job", async () => { const { revision, conceptPolicy } = await validRevision(); revision.page.components.find((item) => item.component_type === "conclusion").data.summary = "GSM matters because it describes fabric weight; dimensions affect coverage; edging matters because it finishes the towel; construction tells you how it is made."; assert.ok(validateConceptOwnership(revision.page, conceptPolicy).errors.some((item) => item.code === "COMPONENT_JOB_VIOLATION")); });
test("synthetic non-towel policy can use unrelated concepts and budgets", () => { const page = { components: [{ component_id: "owner", component_type: "rich_text_section", data: { heading: "Water hardness", paragraphs: ["Water hardness matters because mineral content affects the cleaning decision."], key_points: [] } }, { component_id: "close", component_type: "conclusion", data: { heading: "Decide", summary: "Choose for your home.", next_step: "Check your water report." } }] }; const policy = { schema_version: "1.0.0", policy_id: "synthetic_glass_v1", concepts: [{ concept_id: "water_hardness", labels: ["water hardness", "mineral content"], primary_component_id: "owner", max_substantial_components: 1, secondary_component_ids: [], permitted_non_substantial_kinds: ["brief_reference"] }], component_jobs: [{ component_id: "owner", job: "Explain water hardness", owns_concepts: ["water_hardness"] }, { component_id: "close", job: "Decide", forbidden_substantial_concepts: ["water_hardness"] }] }; assert.equal(validateConceptOwnership(page, policy).status, "PASS"); assert.equal(JSON.stringify(policy).includes("gsm"), false); });

test("multi-step lineage binds an unaccepted valid intermediate as immediate source", async () => { const { revision: first, sourcePage } = await validRevision(); const firstHash = sha256(first.page); const second = structuredClone(first); second.page.validation_metadata.source_semantic_page_hash = sourcePage.validation_metadata?.source_semantic_page_hash || first.page.validation_metadata.source_semantic_page_hash; const visibleBefore = sha256(customerFacingProjection(second.page)); const result = bindRevisionToImmediateSource({ revision: second, immediateSourcePage: first.page, expectedImmediateSourceHash: firstHash }); assert.equal(result.revision.page.validation_metadata.source_semantic_page_hash, firstHash); assert.equal(result.audit.customer_facing_content_changed, false); assert.equal(sha256(customerFacingProjection(result.revision.page)), visibleBefore); });
test("acceptance status cannot redirect lineage to an older page", async () => { const { revision: first } = await validRevision(); first.page.acceptance_status = undefined; const second = structuredClone(first); const firstHash = sha256(first.page); const result = bindRevisionToImmediateSource({ revision: second, immediateSourcePage: first.page, expectedImmediateSourceHash: firstHash }); assert.equal(result.audit.immediate_source_hash, firstHash); });
test("stale unrelated source hashes fail closed", async () => { const { revision: first } = await validRevision(); const second = structuredClone(first); second.page.validation_metadata.source_semantic_page_hash = "f".repeat(64); assert.throws(() => bindRevisionToImmediateSource({ revision: second, immediateSourcePage: first.page, expectedImmediateSourceHash: sha256(first.page) }), /neither its immediate source/); });
test("metadata-only correction leaves exactly one auditable path", async () => { const { revision: first } = await validRevision(); const second = structuredClone(first); const result = bindRevisionToImmediateSource({ revision: second, immediateSourcePage: first.page, expectedImmediateSourceHash: sha256(first.page) }); assert.deepEqual(result.audit.changed_paths, ["$.page.validation_metadata.source_semantic_page_hash"]); assert.equal(result.audit.historical_artifacts_modified, false); });
test("historical candidate objects remain immutable during correction", async () => { const { revision: first } = await validRevision(); const second = structuredClone(first); const before = sha256(second); bindRevisionToImmediateSource({ revision: second, immediateSourcePage: first.page, expectedImmediateSourceHash: sha256(first.page) }); assert.equal(sha256(second), before); });
test("customer-facing projection is structurally exact after correction", async () => { const { revision: first } = await validRevision(); const second = structuredClone(first); const before = customerFacingProjection(second.page); const result = bindRevisionToImmediateSource({ revision: second, immediateSourcePage: first.page, expectedImmediateSourceHash: sha256(first.page) }); assert.deepEqual(customerFacingProjection(result.revision.page), before); });
test("already-correct immediate source binding passes without mutation", async () => { const { revision: first } = await validRevision(); const second = structuredClone(first); second.page.validation_metadata.source_semantic_page_hash = sha256(first.page); const result = bindRevisionToImmediateSource({ revision: second, immediateSourcePage: first.page, expectedImmediateSourceHash: sha256(first.page) }); assert.deepEqual(result.audit.changed_paths, []); assert.equal(result.audit.correction_required, false); });
test("lineage audit records immediate source separately from its parent", async () => { const { revision: first } = await validRevision(); const second = structuredClone(first); const result = bindRevisionToImmediateSource({ revision: second, immediateSourcePage: first.page, expectedImmediateSourceHash: sha256(first.page) }); assert.equal(result.audit.immediate_source_hash, sha256(first.page)); assert.equal(result.audit.immediate_source_parent_hash, first.page.validation_metadata.source_semantic_page_hash); assert.notEqual(result.audit.immediate_source_hash, result.audit.immediate_source_parent_hash); });
