import test from "node:test";
import assert from "node:assert/strict";
import { access, mkdtemp, readFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { DECISION_AREAS, DECISION_OUTCOMES, EVIDENCE_CATEGORIES, interpretationJsonSchema } from "../interpretation/contracts.js";
import { buildInterpretationContext, CONTEXT_CATEGORIES } from "../interpretation/context.js";
import { buildCurrentPageInventory, buildGapMatrix } from "../interpretation/inventory.js";
import { createOpenAIInterpretationProvider } from "../interpretation/providers/openai.js";
import { buildInterpretationPrompt } from "../interpretation/prompt.js";
import { runInterpretation } from "../interpretation/run.js";
import { deriveEvidenceUse, validateInterpretationOutput } from "../interpretation/validation.js";
import { assertInterpretationPreflight, measureInterpretationRequest } from "../interpretation/preflight.js";
import { benchmarkCallSummary, invokeControlledCall, writeImmutableArtifact } from "../interpretation/call-control.js";
import { calculateConfiguredCost, configuredModelPricing } from "../interpretation/cost.js";

const EVIDENCE_PATH = "artifacts/live-validation/dataforseo-keyword-ideas-2026-08-08/heavy-duty-drying-towel-1200gsm/run_2026-08-08T07-22-30-159Z_b9eff88a/evidence.json";
const STATE_PATH = "artifacts/live-validation/research-state-2026-08-08/heavy-duty-drying-towel-1200gsm/improve_existing_product_page/research_state_f85fd396bb023e960a17b3f2/research-state.json";
const FIXED_TIME = () => new Date("2026-08-08T08:00:00.000Z");
const inputs = async () => { const [evidence, researchState] = await Promise.all([readFile(EVIDENCE_PATH, "utf8").then(JSON.parse), readFile(STATE_PATH, "utf8").then(JSON.parse)]); return { evidence, researchState }; };
async function temporaryDirectory(t) { const directory = await mkdtemp(path.join(os.tmpdir(), "interpretation-")); t.after(() => rm(directory, { recursive: true, force: true })); return directory; }

function validOutput(context) {
  const byId = new Map(context.evidence.map((item) => [item.evidence_id, item]));
  const categoryRecord = (category) => context.evidence.find((item) => item.evidence_category === category);
  const assessments = EVIDENCE_CATEGORIES.map((category) => { const item = categoryRecord(category); return { category, assessment: `The supplied ${category} evidence was assessed against the deterministic page state.`, evidence_ids: [item.evidence_id], reason_no_action: null }; });
  const decisions = context.gap_matrix.decision_areas.map((gap) => {
    const current = gap.current_evidence_ids.find((id) => byId.has(id));
    const external = [...gap.external_evidence_ids, ...gap.first_party_evidence_ids].find((id) => byId.has(id));
    const evidenceIds = [current, external].filter(Boolean);
    const evidenceCategories = [...new Set(evidenceIds.map((id) => byId.get(id).evidence_category))].sort();
    let outcome = "no_change";
    let recommendation = "Keep the existing element unchanged because the supplied evidence gives no specific reason to alter it.";
    if (gap.decision_area === "comparisons") { outcome = "add"; recommendation = "Add a distinct comparison section addressing the cited external comparison topic without duplicating the existing FAQ content."; }
    if (gap.decision_area === "product_description_benefits") { outcome = "reposition"; recommendation = "Reposition the existing verified benefit beside the relevant cited search topic while preserving factual wording and avoiding unsupported claims."; }
    if (gap.current_state === "unknown") { outcome = "insufficient_evidence"; recommendation = "The current metadata state is unknown and cannot be determined from existing extraction, so no metadata change is recommended."; }
    return { area: gap.decision_area, outcome, current_state: gap.current_state, recommendation, evidence_ids: evidenceIds, evidence_categories: evidenceCategories, external_evidence_ids: external ? [external] : [], confidence: gap.current_state === "unknown" ? "low" : "medium", confidence_reason: "The decision follows direct deterministic page-state evidence and only the supplied external evidence where available.", limitations: [...gap.limitations] };
  });
  const product = categoryRecord("product_facts"); const keyword = categoryRecord("keyword_ideas");
  return { schema_version: "2.0.0", objective: "improve_existing_product_page", source_product: { subject_id: context.source_product.subject_id, product_name: context.source_product.product_name, product_url: context.source_product.product_url }, category_assessments: assessments, findings: [{ id: "finding_state", finding: "The deterministic inventory confirms existing page content and isolates review questions from element presence.", evidence_ids: [product.evidence_id, keyword.evidence_id], evidence_categories: ["keyword_ideas", "product_facts"], confidence: "high", confidence_reason: "Direct Product Facts establish current state and separate keyword evidence supports the external review context.", limitations: ["This finding does not prescribe final copy."] }], decision_areas: decisions, limitations: ["Interpretation remains constrained by extracted page state and cached evidence."], overall_assessment: "The matrix supports selective review without asking the model to rediscover page-element presence." };
}

test("current page inventory is deterministic and preserves source evidence", async () => { const { evidence, researchState } = await inputs(); const evidenceBefore = structuredClone(evidence); const stateBefore = structuredClone(researchState); const first = buildCurrentPageInventory({ evidence, researchState }); const second = buildCurrentPageInventory({ evidence, researchState }); assert.deepEqual(second, first); assert.deepEqual(evidence, evidenceBefore); assert.deepEqual(researchState, stateBefore); assert.equal(first.decision_areas.length, DECISION_AREAS.length); for (const area of first.decision_areas) { assert.ok(["present", "absent", "unknown"].includes(area.presence)); assert.ok(Array.isArray(area.current_evidence_ids)); assert.equal(area.source_provenance.evidence_artifact_id, evidence.evidence_artifact_id); } });

test("inventory marks care, specifications and FAQs present, comparisons absent, and metadata unknown", async () => { const { evidence, researchState } = await inputs(); const inventory = buildCurrentPageInventory({ evidence, researchState }); const state = Object.fromEntries(inventory.decision_areas.map((item) => [item.decision_area, item.presence])); assert.equal(state.care_usage_guidance, "present"); assert.equal(state.specifications, "present"); assert.equal(state.faqs_questions, "present"); assert.equal(state.comparisons, "absent"); assert.equal(state.metadata, "unknown"); for (const area of ["care_usage_guidance", "specifications", "faqs_questions"]) assert.ok(inventory.decision_areas.find((item) => item.decision_area === area).current_evidence_ids.length); });

test("reviewed inventory preserves nuanced comparison, links, positioning, headings and detailed content", async () => { const { evidence, researchState } = await inputs(); const inventory = buildCurrentPageInventory({ evidence, researchState }); const area = (name) => inventory.decision_areas.find((item) => item.decision_area === name); const values = (name) => area(name).current_page_fact_refs.map((item) => String(item.value)); const comparison = area("comparisons"); assert.equal(comparison.presence, "absent"); assert.equal(comparison.component_states.dedicated_comparison_section, "absent"); assert.equal(comparison.component_states.comparison_content_elsewhere, "present"); assert.ok(values("comparisons").some((value) => /XL 800GSM/i.test(value))); assert.ok(values("differentiation").some((value) => /XL 800GSM/i.test(value))); assert.ok(values("care_usage_guidance").some((value) => /fabric softener|air dry|detergent/i.test(value))); for (const expected of [/1200GSM/i, /90 × 60 cm/i, /Premium dual-sided microfibre/i, /Soft microfibre edging/i]) assert.ok(values("specifications").some((value) => expected.test(value))); for (const expected of [/difference.*XL 800GSM/i, /scratch my paint/i, /wash and store/i, /How many towels/i]) assert.ok(values("faqs_questions").some((value) => expected.test(value))); assert.ok(values("internal_linking").some((value) => /Origin Shampoo/i.test(value))); assert.equal(values("internal_linking").some((value) => /Microfibre Wash Mitt/i.test(value)), false); assert.deepEqual(values("title_headings"), ["Heavy Duty Drying Towel – 1200gsm"]); assert.equal(area("metadata").current_evidence_ids.length, 0); });

test("gap matrix is deterministic, factual, and does not score or recommend", async () => { const { evidence, researchState } = await inputs(); const context = buildInterpretationContext({ evidence, researchState, maxRecords: 24 }); const first = buildGapMatrix({ inventory: context.current_page_inventory, contextEvidence: context.evidence }); const second = buildGapMatrix({ inventory: context.current_page_inventory, contextEvidence: context.evidence }); assert.deepEqual(second, first); assert.equal(first.decision_areas.length, DECISION_AREAS.length); for (const area of first.decision_areas) { assert.ok(Array.isArray(area.potential_review_reason)); assert.equal("opportunity_score" in area, false); assert.equal("recommendation" in area, false); } assert.ok(first.decision_areas.some((item) => item.external_evidence_available)); assert.ok(first.decision_areas.some((item) => item.first_party_performance_evidence_available)); });

test("reviewed gap relationships are area-specific and preserve no-evidence internal linking", async () => { const { evidence, researchState } = await inputs(); const context = buildInterpretationContext({ evidence, researchState, maxRecords: 96 }); const gap = (name) => context.gap_matrix.decision_areas.find((item) => item.decision_area === name); const byId = new Map(context.evidence.map((item) => [item.evidence_id, item])); assert.equal(gap("internal_linking").external_evidence_available, false); assert.equal(gap("internal_linking").first_party_performance_evidence_available, false); assert.deepEqual(gap("internal_linking").potential_review_reason.slice(-1), ["no external evidence suggests a change"]); assert.ok(gap("faqs_questions").external_evidence_ids.every((id) => ["serp_people_also_ask", "serp_related_search"].includes(byId.get(id).evidence_type))); assert.ok(gap("metadata").external_evidence_ids.every((id) => byId.get(id).evidence_category === "keyword_ideas")); assert.ok(gap("comparisons").current_evidence_ids.some((id) => /XL 800GSM/i.test(String(byId.get(id)?.observation?.value || context.current_page_inventory.decision_areas.find((area) => area.decision_area === "comparisons").current_page_fact_refs.find((ref) => ref.evidence_id === id)?.value || "")))); });

test("context is deterministic, balanced and embeds inventory plus gap matrix", async () => { const { evidence, researchState } = await inputs(); const first = buildInterpretationContext({ evidence, researchState, maxRecords: 24 }); const second = buildInterpretationContext({ evidence, researchState, maxRecords: 24 }); assert.deepEqual(second, first); assert.deepEqual(CONTEXT_CATEGORIES, EVIDENCE_CATEGORIES); assert.deepEqual(first.evidence_categories_available, [...EVIDENCE_CATEGORIES].sort()); assert.equal(first.current_page_inventory.artifact_type, "current_page_inventory"); assert.equal(first.gap_matrix.artifact_type, "product_page_gap_matrix"); for (const category of EVIDENCE_CATEGORIES) assert.ok(first.evidence_summaries[category].length); });

test("prompt and strict schema share exact areas, outcomes and states", async () => { const { evidence, researchState } = await inputs(); const context = buildInterpretationContext({ evidence, researchState, maxRecords: 24 }); const prompt = JSON.parse(buildInterpretationPrompt(context)); const schema = interpretationJsonSchema(); assert.deepEqual(schema.properties.decision_areas.items.properties.area.enum, [...DECISION_AREAS]); assert.deepEqual(schema.properties.decision_areas.items.properties.outcome.enum, [...DECISION_OUTCOMES]); assert.deepEqual(prompt.required_decision_areas, [...DECISION_AREAS]); assert.deepEqual(prompt.allowed_outcomes, [...DECISION_OUTCOMES]); assert.deepEqual(prompt.context.decision_brief, context.decision_brief); assert.equal("current_page_inventory" in prompt.context, false); assert.equal("gap_matrix" in prompt.context, false); assert.equal("citation_registry" in prompt.context, false); });

test("decision brief is deterministic, complete, compact and source-immutable", async () => { const { evidence, researchState } = await inputs(); const evidenceBefore = structuredClone(evidence); const first = buildInterpretationContext({ evidence, researchState, maxRecords: 96 }); const second = buildInterpretationContext({ evidence, researchState, maxRecords: 96 }); assert.deepEqual(first.decision_brief, second.decision_brief); assert.deepEqual(evidence, evidenceBefore); assert.equal(first.decision_brief.decision_areas.length, 11); assert.deepEqual(first.decision_brief.evidence_categories, [...EVIDENCE_CATEGORIES]); for (const category of EVIDENCE_CATEGORIES) assert.ok(first.decision_brief.cross_cutting_signals[category].length); assert.ok(JSON.stringify(first.decision_brief).length < JSON.stringify(first).length / 2); });

test("decision brief preserves page-state nuance, unknowns and conflicts", async () => { const { evidence, researchState } = await inputs(); const context = buildInterpretationContext({ evidence, researchState, maxRecords: 96 }); const area = (name) => context.decision_brief.decision_areas.find((item) => item.area === name); assert.equal(area("specifications").current_state, "present"); assert.equal(area("faqs_questions").current_state, "present"); assert.equal(area("care_usage_guidance").current_state, "present"); assert.equal(area("comparisons").current_state, "absent"); assert.equal(area("comparisons").page_state_detail.comparison_content_elsewhere, "present"); assert.equal(area("metadata").current_state, "unknown"); assert.ok(context.decision_brief.unknowns.some((item) => item.area === "metadata")); assert.deepEqual(context.decision_brief.conflicts, context.conflicts); });

test("phrase families compress deterministically without aggregating volume", async () => { const { evidence, researchState } = await inputs(); const context = buildInterpretationContext({ evidence, researchState, maxRecords: 96 }); const families = context.decision_brief.cross_cutting_signals.keyword_ideas; assert.ok(families.some((family) => family.ids.length > 1)); for (const family of families) { assert.equal(family.volume_aggregation, "none"); assert.equal("total_volume" in family, false); assert.ok(family.variants.every((variant) => "volume" in variant)); } });

test("compact Search Console and SERP signals preserve metrics, relationships and supporting IDs", async () => { const { evidence, researchState } = await inputs(); const context = buildInterpretationContext({ evidence, researchState, maxRecords: 96 }); const search = context.decision_brief.cross_cutting_signals.search_console; const serp = context.decision_brief.cross_cutting_signals.serp_advanced; assert.ok(search.every((signal) => signal.ids.length && "impressions" in signal && "clicks" in signal && "ctr" in signal && "average_position" in signal && "keyword_relationship_count" in signal && "page_relationship_count" in signal)); assert.ok(serp.every((signal) => signal.ids.length)); assert.ok(serp.some((signal) => signal.question)); assert.ok(serp.some((signal) => signal.ranking_page)); });

test("every brief citation resolves canonically and unexposed evidence remains invalid", async () => { const { evidence, researchState } = await inputs(); const context = buildInterpretationContext({ evidence, researchState, maxRecords: 96 }); const registered = new Map(context.citation_registry.records.map((item) => [item.evidence_id, item])); assert.equal(context.decision_brief.citation_index.length, registered.size); for (const item of context.decision_brief.citation_index) assert.equal(registered.get(item.id)?.evidence_category, item.category); const exposed = new Set(context.decision_brief.citation_index.map((item) => item.id)); const unexposed = evidence.records.find((item) => !exposed.has(item.evidence_id)); assert.ok(unexposed); const output = validOutput(context); output.category_assessments[0].evidence_ids = [unexposed.evidence_id]; assert.ok(validateInterpretationOutput(output, context).some((error) => error.code === "UNKNOWN_EVIDENCE_ID")); });

test("request sizing is deterministic and configurable ceiling fails locally", () => { const input = { systemPrompt: "system", userPrompt: "user".repeat(100), responseSchema: interpretationJsonSchema(), model: "fixture", configuredModelContextWindow: 100000, configuredTpmLimit: 30000 }; const first = measureInterpretationRequest(input); const second = measureInterpretationRequest(input); assert.deepEqual(first, second); assert.equal(first.limits.model_context_window_tokens, 100000); assert.equal(first.limits.account_project_tpm, 30000); assert.doesNotThrow(() => assertInterpretationPreflight(first)); const blocked = measureInterpretationRequest({ ...input, configuredMaxInputTokens: 1 }); assert.throws(() => assertInterpretationPreflight(blocked), (error) => error.code === "INTERPRETATION_INPUT_BUDGET_EXCEEDED"); });

test("valid decisions cover all areas exactly once and use matrix current state", async () => { const { evidence, researchState } = await inputs(); const context = buildInterpretationContext({ evidence, researchState, maxRecords: 24 }); const output = validOutput(context); assert.equal(output.decision_areas.length, DECISION_AREAS.length); assert.deepEqual(validateInterpretationOutput(output, context), []); });

test("omitted, duplicate and mismatched decision state are rejected", async () => { const { evidence, researchState } = await inputs(); const context = buildInterpretationContext({ evidence, researchState, maxRecords: 24 }); const omitted = validOutput(context); omitted.decision_areas.pop(); assert.ok(validateInterpretationOutput(omitted, context).some((error) => error.code === "MISSING_DECISION_AREA")); const duplicate = validOutput(context); duplicate.decision_areas[1].area = duplicate.decision_areas[0].area; assert.ok(validateInterpretationOutput(duplicate, context).some((error) => error.code === "DUPLICATE_DECISION_AREA")); const mismatch = validOutput(context); mismatch.decision_areas[0].current_state = "absent"; assert.ok(validateInterpretationOutput(mismatch, context).some((error) => error.code === "CURRENT_STATE_MISMATCH")); });

test("present element cannot be labelled missing", async () => { const { evidence, researchState } = await inputs(); const context = buildInterpretationContext({ evidence, researchState, maxRecords: 24 }); const output = validOutput(context); const care = output.decision_areas.find((item) => item.area === "care_usage_guidance"); care.recommendation = "Care instructions are missing and should be added."; assert.ok(validateInterpretationOutput(output, context).some((error) => ["CURRENT_STATE_CONTRADICTION", "CLEAR_EVIDENCE_CONTRADICTION"].includes(error.code))); });

test("absent comparison may be added with external support", async () => { const { evidence, researchState } = await inputs(); const context = buildInterpretationContext({ evidence, researchState, maxRecords: 24 }); const output = validOutput(context); const comparison = output.decision_areas.find((item) => item.area === "comparisons"); assert.equal(comparison.current_state, "absent"); assert.equal(comparison.outcome, "add"); assert.ok(comparison.external_evidence_ids.length); assert.deepEqual(validateInterpretationOutput(output, context), []); });

test("comparison decision cannot erase existing XL 800GSM FAQ content", async () => { const { evidence, researchState } = await inputs(); const context = buildInterpretationContext({ evidence, researchState, maxRecords: 24 }); const output = validOutput(context); const comparison = output.decision_areas.find((item) => item.area === "comparisons"); comparison.recommendation = "No comparison content exists, so add a new section."; assert.ok(validateInterpretationOutput(output, context).some((error) => error.code === "COMPARISON_CONTENT_CONTRADICTION")); comparison.recommendation = "Add a distinct comparison section without acknowledging current material."; assert.ok(validateInterpretationOutput(output, context).some((error) => error.code === "COMPARISON_CONTEXT_OMITTED")); });

test("present element may be repositioned with external support", async () => { const { evidence, researchState } = await inputs(); const context = buildInterpretationContext({ evidence, researchState, maxRecords: 24 }); const output = validOutput(context); const description = output.decision_areas.find((item) => item.area === "product_description_benefits"); assert.equal(description.current_state, "present"); assert.equal(description.outcome, "reposition"); assert.ok(description.external_evidence_ids.length); assert.deepEqual(validateInterpretationOutput(output, context), []); });

test("present add must describe a distinct new element", async () => { const { evidence, researchState } = await inputs(); const context = buildInterpretationContext({ evidence, researchState, maxRecords: 24 }); const output = validOutput(context); const faq = output.decision_areas.find((item) => item.area === "faqs_questions"); faq.outcome = "add"; faq.recommendation = "Add FAQs."; assert.ok(validateInterpretationOutput(output, context).some((error) => error.code === "DUPLICATE_PRESENT_ELEMENT")); faq.recommendation = "Add a distinct new FAQ addressing the cited external question without duplicating existing FAQs."; assert.deepEqual(validateInterpretationOutput(output, context), []); });

test("no_change is valid when external evidence gives no alteration reason", async () => { const { evidence, researchState } = await inputs(); const context = buildInterpretationContext({ evidence, researchState, maxRecords: 24 }); const output = validOutput(context); const linking = output.decision_areas.find((item) => item.area === "internal_linking"); assert.equal(linking.outcome, "no_change"); assert.equal(linking.external_evidence_ids.length, 0); assert.deepEqual(validateInterpretationOutput(output, context), []); });

test("insufficient_evidence is valid for unknown state with no page or external evidence", async () => { const { evidence, researchState } = await inputs(); const context = buildInterpretationContext({ evidence, researchState, maxRecords: 24 }); const matrix = context.gap_matrix.decision_areas.find((item) => item.decision_area === "internal_linking"); matrix.current_state = "unknown"; matrix.current_evidence_ids = []; matrix.external_evidence_ids = []; matrix.first_party_evidence_ids = []; matrix.relevant_evidence_ids = []; const output = validOutput(context); const linking = output.decision_areas.find((item) => item.area === "internal_linking"); Object.assign(linking, { outcome: "insufficient_evidence", current_state: "unknown", recommendation: "The current internal-linking state is unknown and cannot be determined; no change is justified.", evidence_ids: [], evidence_categories: [], external_evidence_ids: [], confidence: "low" }); assert.deepEqual(validateInterpretationOutput(output, context), []); });

test("unknown state cannot be presented definitively", async () => { const { evidence, researchState } = await inputs(); const context = buildInterpretationContext({ evidence, researchState, maxRecords: 24 }); const output = validOutput(context); const metadata = output.decision_areas.find((item) => item.area === "metadata"); metadata.recommendation = "The metadata is already present and should remain."; assert.ok(validateInterpretationOutput(output, context).some((error) => error.code === "UNKNOWN_STATE_CERTAINTY")); });

test("derived evidence use ignores model self-report", async () => { const { evidence, researchState } = await inputs(); const context = buildInterpretationContext({ evidence, researchState, maxRecords: 24 }); const output = validOutput(context); output.evidence_use_report = { materially_used: ["false"] }; const derived = deriveEvidenceUse(output, context); assert.deepEqual(derived.categories_available, [...EVIDENCE_CATEGORIES].sort()); assert.deepEqual(derived.categories_assessed, [...EVIDENCE_CATEGORIES].sort()); assert.ok(derived.categories_materially_cited.length); });

test("citation registry is deterministic, canonical and keeps inventory outside the research budget", async () => { const { evidence, researchState } = await inputs(); const first = buildInterpretationContext({ evidence, researchState, maxRecords: 24 }); const second = buildInterpretationContext({ evidence, researchState, maxRecords: 24 }); assert.deepEqual(second.citation_registry, first.citation_registry); const { counts, records } = first.citation_registry; assert.equal(counts.budgeted_research_records, first.evidence.length); assert.ok(counts.budgeted_research_records <= 24); assert.ok(counts.deterministic_inventory_records > 0); assert.ok(counts.total_unique_citable_evidence_ids <= counts.budgeted_research_records + counts.deterministic_inventory_records); assert.ok(counts.total_unique_citable_evidence_ids < evidence.records.length); assert.equal(new Set(records.map((item) => item.evidence_id)).size, records.length); assert.ok(records.every((item) => EVIDENCE_CATEGORIES.includes(item.evidence_category))); });

test("inventory-only evidence exposed to the model is a valid citation", async () => { const { evidence, researchState } = await inputs(); const context = buildInterpretationContext({ evidence, researchState, maxRecords: 24 }); const selected = new Set(context.evidence.map((item) => item.evidence_id)); const inventoryOnly = context.citation_registry.records.find((item) => item.interpretation_input_paths.includes("inventory") && !selected.has(item.evidence_id)); assert.ok(inventoryOnly); const output = validOutput(context); const assessment = output.category_assessments.find((item) => item.category === inventoryOnly.evidence_category); assessment.evidence_ids = [inventoryOnly.evidence_id]; assert.equal(validateInterpretationOutput(output, context).some((error) => error.code === "UNKNOWN_EVIDENCE_ID"), false); });

test("context and exposed gap-matrix citations validate while unexposed evidence is rejected", async () => { const { evidence, researchState } = await inputs(); const context = buildInterpretationContext({ evidence, researchState, maxRecords: 24 }); const contextRecord = context.citation_registry.records.find((item) => item.interpretation_input_paths.includes("context")); const gapRecord = context.citation_registry.records.find((item) => item.interpretation_input_paths.includes("gap_matrix")); assert.ok(contextRecord && gapRecord); for (const record of [contextRecord, gapRecord]) { const output = validOutput(context); output.category_assessments.find((item) => item.category === record.evidence_category).evidence_ids = [record.evidence_id]; assert.equal(validateInterpretationOutput(output, context).some((error) => error.code === "UNKNOWN_EVIDENCE_ID"), false); } const registered = new Set(context.citation_registry.records.map((item) => item.evidence_id)); const unexposed = evidence.records.find((item) => researchState.source_evidence.evidence_ids.includes(item.evidence_id) && !registered.has(item.evidence_id)); assert.ok(unexposed); const output = validOutput(context); output.category_assessments[0].evidence_ids = [unexposed.evidence_id]; assert.ok(validateInterpretationOutput(output, context).some((error) => error.code === "UNKNOWN_EVIDENCE_ID")); });

test("duplicate evidence entry paths deduplicate IDs and preserve one canonical category", async () => { const { evidence, researchState } = await inputs(); const context = buildInterpretationContext({ evidence, researchState, maxRecords: 24 }); const duplicate = context.citation_registry.records.find((item) => item.interpretation_input_paths.length > 1); assert.ok(duplicate); assert.equal(context.citation_registry.records.filter((item) => item.evidence_id === duplicate.evidence_id).length, 1); const source = evidence.records.find((item) => item.evidence_id === duplicate.evidence_id); const expected = source.evidence_type === "product_fact" ? "product_facts" : source.evidence_type === "keyword_idea" ? "keyword_ideas" : source.evidence_type.startsWith("serp_") ? "serp_advanced" : "search_console"; assert.equal(duplicate.evidence_category, expected); });

test("vague keyword actions are rejected and specific constrained actions pass", async () => { const { evidence, researchState } = await inputs(); const context = buildInterpretationContext({ evidence, researchState, maxRecords: 24 }); const output = validOutput(context); const decision = output.decision_areas.find((item) => item.area === "search_positioning"); const keyword = context.citation_registry.records.find((item) => item.evidence_category === "keyword_ideas"); Object.assign(decision, { outcome: "improve", recommendation: "Add high-volume keywords to headings.", evidence_ids: [keyword.evidence_id], evidence_categories: ["keyword_ideas"], external_evidence_ids: [keyword.evidence_id] }); assert.ok(validateInterpretationOutput(output, context).some((error) => error.code === "VAGUE_ACTION")); decision.recommendation = `Evaluate using the '${keyword.observation.keyword}' phrase family more explicitly in the visible product heading because the cited demand supports search relevance. Preserve the Heavy Duty / 1200GSM differentiation and avoid keyword stuffing.`; assert.equal(validateInterpretationOutput(output, context).some((error) => error.code === "VAGUE_ACTION"), false); });

test("unsupported SERP expectations generalisation is rejected", async () => { const { evidence, researchState } = await inputs(); const context = buildInterpretationContext({ evidence, researchState, maxRecords: 24 }); const output = validOutput(context); const decision = output.decision_areas.find((item) => item.area === "specifications"); const product = context.citation_registry.records.find((item) => item.evidence_category === "product_facts"); const serp = context.citation_registry.records.find((item) => item.evidence_category === "serp_advanced"); Object.assign(decision, { outcome: "improve", recommendation: "All specifications match SERP expectations, so retain them.", evidence_ids: [product.evidence_id, serp.evidence_id], evidence_categories: ["product_facts", "serp_advanced"], external_evidence_ids: [serp.evidence_id] }); assert.ok(validateInterpretationOutput(output, context).some((error) => error.code === "UNSUPPORTED_SERP_GENERALISATION")); });

test("negated missing-specification and distinct-FAQ wording do not trigger contradictions", async () => { const { evidence, researchState } = await inputs(); const context = buildInterpretationContext({ evidence, researchState, maxRecords: 24 }); const output = validOutput(context); const specs = output.decision_areas.find((item) => item.area === "specifications"); specs.recommendation = "Retain existing specifications; the evidence does not justify adding further specifications or claiming a different pattern is required."; const faq = output.decision_areas.find((item) => item.area === "faqs_questions"); faq.outcome = "improve"; faq.recommendation = "In the existing FAQ block, consider one distinct question addressing a usage uncertainty not represented in the recorded FAQ set."; assert.equal(validateInterpretationOutput(output, context).some((error) => error.code === "CLEAR_EVIDENCE_CONTRADICTION" && /decision_areas\[(4|5)\]/.test(error.path)), false); });

test("specific Search Console-backed search action passes while generic action remains blocked", async () => { const { evidence, researchState } = await inputs(); const context = buildInterpretationContext({ evidence, researchState, maxRecords: 96 }); const output = validOutput(context); const decision = output.decision_areas.find((item) => item.area === "search_positioning"); const query = context.citation_registry.records.find((item) => item.evidence_category === "search_console" && /car drying towel/i.test(item.observation?.query || "")); const keyword = context.citation_registry.records.find((item) => item.evidence_category === "keyword_ideas"); Object.assign(decision, { outcome: "reposition", recommendation: "In the top-of-page positioning summary, make the 'car drying towel' phrase family the primary category signal. The strategic purpose is alignment with queries producing visibility while preserving Heavy Duty / 1200GSM differentiation and avoiding keyword stuffing.", evidence_ids: [query.evidence_id, keyword.evidence_id], evidence_categories: ["keyword_ideas", "search_console"], external_evidence_ids: [query.evidence_id, keyword.evidence_id] }); assert.equal(validateInterpretationOutput(output, context).some((error) => error.code === "VAGUE_ACTION"), false); decision.recommendation = "Use relevant keywords in the heading."; assert.ok(validateInterpretationOutput(output, context).some((error) => error.code === "VAGUE_ACTION")); });

test("bounded metadata evidence requests pass while invented state and speculative changes remain blocked", async () => {
  const { evidence, researchState } = await inputs();
  const context = buildInterpretationContext({ evidence, researchState, maxRecords: 24 });
  const accepted = [
    "Capture the actual title tag and meta description before deciding whether either should change.",
    "Inspect the current metadata before determining whether optimisation is warranted.",
    "Retrieve the current title tag before making a recommendation."
  ];
  const rejected = [
    "The metadata should be improved.",
    "The title tag is weak.",
    "The meta description is missing.",
    "Rewrite the metadata to target car drying towel.",
    "Metadata is not optimised.",
    "Inspect the weak title tag and improve it.",
    "Capture the missing meta description."
  ];
  for (const recommendation of accepted) {
    const output = validOutput(context);
    output.decision_areas.find((item) => item.area === "metadata").recommendation = recommendation;
    assert.equal(validateInterpretationOutput(output, context).some((error) => error.code === "UNKNOWN_STATE_CERTAINTY"), false, recommendation);
  }
  for (const recommendation of rejected) {
    const output = validOutput(context);
    output.decision_areas.find((item) => item.area === "metadata").recommendation = recommendation;
    assert.ok(validateInterpretationOutput(output, context).some((error) => error.code === "UNKNOWN_STATE_CERTAINTY"), recommendation);
  }
});

test("controlled calls enforce one start, zero retries and immutable artifacts", async (t) => { const directory = await temporaryDirectory(t); let release; const pending = new Promise((resolve) => { release = resolve; }); let signalStarted; const started = new Promise((resolve) => { signalStarted = resolve; }); let calls = 0; const first = invokeControlledCall({ benchmarkDirectory: directory, modelLabel: "sol", maxCalls: 1, invoke: async () => { calls += 1; signalStarted(); await pending; return "ok"; } }); await started; await assert.rejects(invokeControlledCall({ benchmarkDirectory: directory, modelLabel: "sol", maxCalls: 1, invoke: async () => { calls += 1; } }), (error) => error.code === "CONTROLLED_CALL_LIMIT_REACHED"); release(); const result = await first; assert.equal(result.result, "ok"); assert.equal(calls, 1); assert.equal(result.lifecycle.completed_calls, 1); assert.equal(result.lifecycle.failed_calls, 0); assert.equal(result.lifecycle.aborted_calls, 0); await writeImmutableArtifact(result.callDirectory, "raw.json", { value: 1 }); await assert.rejects(writeImmutableArtifact(result.callDirectory, "raw.json", { value: 2 }), (error) => error.code === "EEXIST"); const summary = await benchmarkCallSummary({ benchmarkDirectory: directory, modelLimits: { sol: 1 } }); assert.equal(summary.integrity, "pass"); assert.equal(summary.models.sol.started_calls, 1); });

test("controlled timeout aborts without retry and unexpected call count fails integrity", async (t) => { const directory = await temporaryDirectory(t); let calls = 0; await assert.rejects(invokeControlledCall({ benchmarkDirectory: directory, modelLabel: "slow", maxCalls: 2, timeoutMs: 5, invoke: ({ signal }) => new Promise((_, reject) => { calls += 1; signal.addEventListener("abort", () => reject(Object.assign(new Error("aborted"), { code: "ABORT_ERR" }))); }) }), (error) => error.code === "CONTROLLED_CALL_ABORTED"); assert.equal(calls, 1); const summary = await benchmarkCallSummary({ benchmarkDirectory: directory, modelLimits: { slow: 1 } }); assert.equal(summary.integrity, "pass"); assert.equal(summary.models.slow.aborted_calls, 1); await invokeControlledCall({ benchmarkDirectory: directory, modelLabel: "extra", maxCalls: 2, invoke: async () => "one" }); await invokeControlledCall({ benchmarkDirectory: directory, modelLabel: "extra", maxCalls: 2, invoke: async () => "two" }); const failed = await benchmarkCallSummary({ benchmarkDirectory: directory, modelLimits: { extra: 1 } }); assert.equal(failed.integrity, "failed"); });

test("call integrity follows the explicit authorised model plan", async (t) => {
  const solOnly = await temporaryDirectory(t);
  await invokeControlledCall({ benchmarkDirectory: solOnly, modelLabel: "gpt-5.6-sol", invoke: async () => "ok" });
  assert.equal((await benchmarkCallSummary({ benchmarkDirectory: solOnly, modelLimits: { "gpt-5.6-sol": 1 } })).integrity, "pass");

  const gptOnly = await temporaryDirectory(t);
  await invokeControlledCall({ benchmarkDirectory: gptOnly, modelLabel: "gpt-4.1", invoke: async () => "ok" });
  assert.equal((await benchmarkCallSummary({ benchmarkDirectory: gptOnly, modelLimits: { "gpt-4.1": 1 } })).integrity, "pass");

  const both = await temporaryDirectory(t);
  await invokeControlledCall({ benchmarkDirectory: both, modelLabel: "gpt-4.1", invoke: async () => "ok" });
  await invokeControlledCall({ benchmarkDirectory: both, modelLabel: "gpt-5.6-sol", invoke: async () => "ok" });
  assert.equal((await benchmarkCallSummary({ benchmarkDirectory: both, modelLimits: { "gpt-4.1": 1, "gpt-5.6-sol": 1 } })).integrity, "pass");
  assert.equal((await benchmarkCallSummary({ benchmarkDirectory: both, modelLimits: { "gpt-4.1": 1, "gpt-5.6-sol": 0 } })).integrity, "failed");

  const missing = await temporaryDirectory(t);
  assert.equal((await benchmarkCallSummary({ benchmarkDirectory: missing, modelLimits: { "gpt-5.6-sol": 1 } })).integrity, "failed");

  const duplicate = await temporaryDirectory(t);
  await invokeControlledCall({ benchmarkDirectory: duplicate, modelLabel: "gpt-5.6-sol", maxCalls: 2, invoke: async () => "one" });
  await invokeControlledCall({ benchmarkDirectory: duplicate, modelLabel: "gpt-5.6-sol", maxCalls: 2, invoke: async () => "two" });
  assert.equal((await benchmarkCallSummary({ benchmarkDirectory: duplicate, modelLimits: { "gpt-5.6-sol": 1 } })).integrity, "failed");

  const providerFailure = await temporaryDirectory(t);
  await assert.rejects(invokeControlledCall({ benchmarkDirectory: providerFailure, modelLabel: "gpt-5.6-sol", invoke: async () => { throw new Error("provider failed"); } }), /provider failed/);
  const failedLifecycle = await benchmarkCallSummary({ benchmarkDirectory: providerFailure, modelLimits: { "gpt-5.6-sol": 1 } });
  assert.equal(failedLifecycle.integrity, "pass");
  assert.equal(failedLifecycle.models["gpt-5.6-sol"].failed_calls, 1);
  assert.equal(failedLifecycle.models["gpt-5.6-sol"].started_calls, 1);
});

test("cost remains unknown without trusted pricing and calculates only from explicit configuration", () => { assert.deepEqual(calculateConfiguredCost({ inputTokens: 1000, outputTokens: 500, pricing: null }), { cost_usd: null, cost_status: "unknown" }); const pricing = configuredModelPricing({ OPENAI_INTERPRETATION_PRICING_JSON: JSON.stringify({ model_a: { input_per_million_tokens_usd: 2, output_per_million_tokens_usd: 8 } }) }, "model_a"); assert.deepEqual(calculateConfiguredCost({ inputTokens: 1000, outputTokens: 500, pricing }), { cost_usd: 0.006, cost_status: "calculated_from_explicit_configuration", pricing }); assert.equal(configuredModelPricing({}, "model_a"), null); });

test("strict Structured Output provider uses shared schema", async () => { let request; const provider = createOpenAIInterpretationProvider({ env: { OPENAI_API_KEY: "fixture-secret", OPENAI_INTERPRETATION_MODEL: "gpt-4.1" }, fetchImpl: async (_url, options) => { request = JSON.parse(options.body); return { ok: true, status: 200, async text() { return JSON.stringify({ model: "gpt-4.1", choices: [{ message: { content: "{}" } }] }); } }; } }); await provider.generate({ systemPrompt: "s", userPrompt: "u", responseSchema: interpretationJsonSchema() }); assert.equal(request.response_format.type, "json_schema"); assert.equal(request.response_format.json_schema.strict, true); assert.deepEqual(request.response_format.json_schema.schema, interpretationJsonSchema()); });

test("valid run writes inventory, brief, frozen request, preflight and review artifacts", async (t) => { const { evidence, researchState } = await inputs(); const context = buildInterpretationContext({ evidence, researchState, maxRecords: 24 }); const provider = { id: "fixture", model: "fixture", settings: { api: "fixture" }, async generate() { return { rawText: JSON.stringify(validOutput(context)), settings: this.settings }; } }; const result = await runInterpretation({ evidence, researchState, provider, outputRoot: await temporaryDirectory(t), maxRecords: 24, now: FIXED_TIME }); assert.equal(result.valid, true); for (const file of [result.files.inventory, result.files.gapMatrix, result.files.context, result.files.decisionBrief, result.files.requestPayload, result.files.preflight, result.files.interpretation, result.files.markdown]) await access(file); assert.equal(JSON.parse(await readFile(result.files.inventory)).artifact_type, "current_page_inventory"); assert.equal(JSON.parse(await readFile(result.files.gapMatrix)).artifact_type, "product_page_gap_matrix"); assert.equal(JSON.parse(await readFile(result.files.decisionBrief)).artifact_type, "interpretation_decision_brief"); });

test("run preflight ceiling blocks provider before any request", async (t) => { const { evidence, researchState } = await inputs(); let calls = 0; const provider = { id: "fixture", model: "fixture", async generate() { calls += 1; throw new Error("must not be called"); } }; await assert.rejects(runInterpretation({ evidence, researchState, provider, outputRoot: await temporaryDirectory(t), maxRecords: 24, now: FIXED_TIME, preflightConfig: { configuredMaxInputTokens: 1 } }), (error) => error.code === "INTERPRETATION_INPUT_BUDGET_EXCEEDED"); assert.equal(calls, 0); });

test("invalid output is preserved and blocked", async (t) => { const { evidence, researchState } = await inputs(); const provider = { id: "fixture", model: "fixture", async generate() { return { rawText: JSON.stringify({ schema_version: "2.0.0", findings: [] }) }; } }; const result = await runInterpretation({ evidence, researchState, provider, outputRoot: await temporaryDirectory(t), maxRecords: 24, now: FIXED_TIME }); assert.equal(result.valid, false); assert.equal(result.interpretation.human_review_state, "blocked_invalid"); await assert.rejects(access(result.files.markdown)); });
