import assert from "node:assert/strict";
import { test } from "node:test";
import { mkdtemp, readFile, rm, stat } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { buildProductPageEditorInput, buildProductPageProposal, normalizeProductPageContent, productPageMainDescriptionJsonSchema, renderProductPageReview, runProductPageEditorialWorkflow, validateMainDescription } from "../editorial/productPageWorkflow.js";

const contextPath = "artifacts/editorial-intelligence-context/heavy-duty-drying-towel-1200gsm/2026-08-15T13-45-00.000Z/editorial-intelligence-context.json";
const page = { title: "Heavy Duty Drying Towel – 1200gsm", excerpt: { rendered: "<ul><li>1200GSM dual layer thickness</li><li>Extreme absorbency</li><li>Soft premium feel</li><li>Safe on all paint</li><li>Ideal for larger vehicles</li></ul>" }, content: { rendered: "This Heavy Duty Drying Towel uses an ultra-dense 1200GSM dual-sided microfibre blend designed to pull water off the paint with almost no effort. Each pass removes a huge amount of water, making it ideal for larger vehicles." }, source: "fixture" };
const bullets = { short_description_bullets: ["Fast, streak-free drying without the usual fuss", "1200GSM dual-layer construction with strong water-holding capacity", "Soft, premium feel for paintwork-friendly drying", "Ideal for larger vehicles and bigger driveway drying jobs"] };
const main = { main_description: "Make post-wash drying easier with a substantial 1200GSM dual-layer towel that holds strong water capacity, feels soft in use and gives larger vehicles the coverage they need. It is a practical way to achieve a cleaner, more comfortable drying routine without unnecessary fuss." };
const load = async () => JSON.parse(await readFile(contextPath, "utf8"));

test("current product-page content is normalized separately from trusted intelligence", () => { const normalized = normalizeProductPageContent(page); assert.equal(normalized.title, page.title); assert.deepEqual(normalized.short_description, ["1200GSM dual layer thickness", "Extreme absorbency", "Soft premium feel", "Safe on all paint", "Ideal for larger vehicles"]); assert.match(normalized.main_description, /ultra-dense/); });
test("validated context is required for page input and proposal", async () => { const context = await load(); assert.throws(() => buildProductPageEditorInput({ context: { ...context, provenance_summary: { ...context.provenance_summary, business_validation_status: "awaiting_validation" } }, currentPage: page, proposedShortDescription: bullets.short_description_bullets })); assert.throws(() => buildProductPageProposal({ context, currentPage: page, shortDescriptionOutput: { short_description_bullets: ["one"] }, mainDescriptionOutput: main })); });
test("approved commercial editor output is reused as the short-description section", async () => { const context = await load(); const input = buildProductPageEditorInput({ context, currentPage: page, proposedShortDescription: bullets.short_description_bullets }); assert.deepEqual(input.approved_short_description, bullets.short_description_bullets); });
test("KEEP is valid and good existing content need not be rewritten", async () => { const context = await load(); const unchanged = { ...page, short_description: bullets.short_description_bullets, main_description: main.main_description }; const proposal = buildProductPageProposal({ context, currentPage: unchanged, shortDescriptionOutput: bullets, mainDescriptionOutput: main }); assert.equal(proposal.sections.find((entry) => entry.section === "title").decision, "KEEP"); assert.equal(proposal.sections.find((entry) => entry.section === "short_description").decision, "KEEP"); assert.equal(proposal.sections.find((entry) => entry.section === "main_description").decision, "KEEP"); });
test("main description requires Product Intelligence support and rejects unsupported claims", async () => { const context = await load(); assert.deepEqual(validateMainDescription(main, { context }), []); assert.ok(validateMainDescription({ main_description: "This product is guaranteed to absorb 5 litres and is scratch-proof on every surface." }, { context }).length > 0); });
test("caveats remain secondary and are not injected into prime bullets", async () => { const context = await load(); const proposal = buildProductPageProposal({ context, currentPage: page, shortDescriptionOutput: bullets, mainDescriptionOutput: main }); assert.ok(Array.isArray(proposal.assessment.caveats_too_prominent)); assert.ok(!proposal.sections.find((entry) => entry.section === "short_description").proposed.some((value) => /used correctly|clean, shampooed/i.test(value))); });
test("business guidance influences input without becoming mandatory literal copy", async () => { const context = await load(); const input = buildProductPageEditorInput({ context, currentPage: page, proposedShortDescription: bullets.short_description_bullets }); assert.ok(input.trusted_intelligence.business_guidance.audience); assert.doesNotMatch(JSON.stringify(bullets), /everyday UK drivers|professional detailers/); });
test("main-description input separates invisible business influence from product content", async () => { const context = await load(); const input = buildProductPageEditorInput({ context, currentPage: page, proposedShortDescription: bullets.short_description_bullets }); assert.equal(input.business_guidance_use.role, "prioritisation_and_framing_only"); assert.equal(input.business_guidance_use.literal_copy_is_optional, true); assert.match(input.instruction, /do not mechanically restate audience/i); });
test("missing optional sections are not automatically created", async () => { const context = await load(); const proposal = buildProductPageProposal({ context, currentPage: page, shortDescriptionOutput: bullets, mainDescriptionOutput: main }); assert.equal(proposal.sections.some((entry) => entry.section === "specifications"), false); assert.equal(proposal.sections.some((entry) => entry.section === "care_use"), false); });
test("development review hides technical metadata while JSON retains traceability", async () => { const context = await load(); const proposal = buildProductPageProposal({ context, currentPage: page, shortDescriptionOutput: bullets, mainDescriptionOutput: main }); const review = renderProductPageReview(proposal); assert.match(review, /Product Page Review/); assert.doesNotMatch(review, /evidence_refs|knowledge_type|confidence|assertion_scope/); assert.ok(proposal.sections.find((entry) => entry.section === "main_description").product_support.length > 0); });
test("main-description structured schema is bounded", () => { const schema = productPageMainDescriptionJsonSchema(); assert.equal(schema.additionalProperties, false); assert.equal(schema.required[0], "main_description"); });
test("rejected commercial generation cannot become an accepted proposal", async () => { const context = await load(); const root = await mkdtemp(path.join(os.tmpdir(), "product-page-rejected-")); const badCommercial = { model: "fixture", async generate() { return { provider: "fixture", model: "fixture", rawText: JSON.stringify({ short_description_bullets: ["Use only on clean paint", "Maximum absorbency", "A dependable choice"] }), usage: {} }; } }; const goodMain = { model: "fixture", async generate() { return { provider: "fixture", model: "fixture", rawText: JSON.stringify(main), usage: {} }; } }; try { await assert.rejects(() => runProductPageEditorialWorkflow({ context, currentPage: page, commercialProvider: badCommercial, mainDescriptionProvider: goodMain, outputRoot: root })); await assert.rejects(() => stat(path.join(root, "product-page-proposal.json"))); } finally { await rm(root, { recursive: true, force: true }); } });
test("mock full-page workflow uses two bounded calls and performs no network or writes", async () => { const context = await load(); const root = await mkdtemp(path.join(os.tmpdir(), "product-page-workflow-")); let calls = 0; const provider = { model: "fixture", async generate({ responseSchema }) { calls += 1; return responseSchema.required[0] === "short_description_bullets" ? { provider: "fixture", model: "fixture", rawText: JSON.stringify(bullets), usage: { input_tokens: 10, output_tokens: 20 } } : { provider: "fixture", model: "fixture", rawText: JSON.stringify(main), usage: { input_tokens: 20, output_tokens: 30 } }; } }; try { const result = await runProductPageEditorialWorkflow({ context, currentPage: page, commercialProvider: provider, mainDescriptionProvider: provider, outputRoot: root }); assert.equal(calls, 2); assert.equal(result.metadata.wordpress_writes, 0); assert.equal(result.proposal.validation.status, "PASS"); assert.match(await readFile(path.join(root, "product-page-review.md"), "utf8"), /Recommendation/); } finally { await rm(root, { recursive: true, force: true }); } });
