import assert from "node:assert/strict";
import test from "node:test";
import { createSourceEvidence } from "../product-intelligence/evidence.js";
import { applyApprovedKnowledgeArrayCorrection, createApprovedHumanCorrection } from "../product-intelligence/humanCorrection.js";
import { renderProductIntelligenceReviewReport } from "../product-intelligence/reviewReport.js";

const createdAt = "2026-08-14T09:00:00.000Z";
const evidence = createSourceEvidence({ sourceType: "rendered_product_page", sourceUriOrLocation: "https://streetkingz.co.uk/product/towel/", sourceField: "content.about", rawValue: "Vehicle drying towel", retrievedAt: createdAt });
const originalIdealCustomers = [
  { value: "Car enthusiasts", knowledge_type: "derived", evidence_refs: [evidence.id], confidence: 0.8, status: "inferred" },
  { value: "Detailers and professional car washers", knowledge_type: "derived", evidence_refs: [evidence.id], confidence: 0.8, status: "inferred" }
];
const correctedValue = "People who wash their own vehicle at home, care about keeping it looking good, spend money looking after it, value product quality and achieving a good result, and are willing to pay more for a better product that makes the job easier or gives a better result rather than simply choosing the cheapest option. They are primarily buying for their own vehicle. Professional detailers and professional car washers are not the intended target audience.";

function sourcePio() {
  const fact = (value) => ({ value, knowledge_type: "fact", evidence_refs: [evidence.id], confidence: 1, status: "extracted" });
  return { metadata: { object_id: "pio_towel", schema_version: "1.0.0", product_url: "https://streetkingz.co.uk/product/towel/", created_at: createdAt, updated_at: createdAt, ingestion_status: "interpreted_awaiting_human_validation", source_fingerprint: "fingerprint" }, product_identity: { product_name: fact("Heavy Duty Towel"), brand: fact("Street Kingz"), product_type: fact("Vehicle drying towel") }, customer_understanding: { problems_solved: [], objections: [], ideal_customers: structuredClone(originalIdealCustomers), customer_groups: [] }, usage_context: { use_cases: [], instructions: [], limitations: [], compatibility: [] }, knowledge_gaps: [], source_evidence: [evidence], conflicts: [], human_corrections: [], validation_status: "awaiting_validation", execution_metadata: { ai_calls: [] } };
}

function correction(pio) { return createApprovedHumanCorrection({ targetPath: "customer_understanding.ideal_customers", previousValue: pio.customer_understanding.ideal_customers, correctedValue, reason: "Founder confirmed the intended at-home owner audience and excluded professional buyers.", createdAt, supersedesEvidenceRefs: [] }); }

test("original AI understanding is preserved and approved founder correction becomes effective", () => { const source = sourcePio(); const approved = correction(source); const corrected = applyApprovedKnowledgeArrayCorrection(source, approved); assert.deepEqual(approved.previous_value, originalIdealCustomers); assert.equal(corrected.customer_understanding.ideal_customers[0].value, correctedValue); assert.equal(corrected.customer_understanding.ideal_customers[0].status, "human_corrected"); assert.equal(corrected.human_corrections[0].status, "approved"); assert.deepEqual(source.customer_understanding.ideal_customers, originalIdealCustomers); });
test("founder correction is not falsely attributed to source evidence", () => { const source = sourcePio(); const corrected = applyApprovedKnowledgeArrayCorrection(source, correction(source)); assert.deepEqual(corrected.customer_understanding.ideal_customers[0].evidence_refs, []); assert.deepEqual(corrected.human_corrections[0].supersedes_evidence_refs, []); });
test("professional targeting is superseded in effective knowledge but remains auditable", () => { const source = sourcePio(); const corrected = applyApprovedKnowledgeArrayCorrection(source, correction(source)); assert.equal(corrected.customer_understanding.ideal_customers.length, 1); assert.match(corrected.customer_understanding.ideal_customers[0].value, /not the intended target audience/); assert.equal(corrected.human_corrections[0].previous_value[1].value, "Detailers and professional car washers"); });
test("corrected founder understanding appears simply in the review report", () => { const source = sourcePio(); const corrected = applyApprovedKnowledgeArrayCorrection(source, correction(source)); const markdown = renderProductIntelligenceReviewReport(corrected); assert.match(markdown, new RegExp(correctedValue.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"))); assert.match(markdown, /Review note: \*\*Founder corrected\*\*/); assert.match(markdown, /Founder-supplied correction; no source evidence attribution/); assert.equal((markdown.match(/^### Ideal Customer$/gm) || []).length, 1); assert.doesNotMatch(markdown, /^### Customer Understanding › Ideal Customers$/gm); });
test("raw SourceEvidence remains unchanged", () => { const source = sourcePio(); const before = JSON.stringify(source.source_evidence); const corrected = applyApprovedKnowledgeArrayCorrection(source, correction(source)); assert.equal(JSON.stringify(corrected.source_evidence), before); assert.equal(JSON.stringify(source.source_evidence), before); });
test("founder correction and report rendering make no AI or network calls", () => { const source = sourcePio(); let calls = 0; const originalFetch = globalThis.fetch; globalThis.fetch = () => { calls += 1; throw new Error("network forbidden"); }; try { const corrected = applyApprovedKnowledgeArrayCorrection(source, correction(source)); renderProductIntelligenceReviewReport(corrected); assert.equal(calls, 0); assert.equal(corrected.execution_metadata.ai_calls.length, 0); } finally { globalThis.fetch = originalFetch; } });
