import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { deriveCornerstoneStrategyAllowlists } from "../cornerstone/strategy-allowlists.js";
import { renderSemanticPageHtml } from "../rendering/html.js";
import { STREET_KINGZ_THEME } from "../rendering/themes.js";
import { DEFAULT_SITE_STYLE_PROFILE, createSiteStyleProfile, validateSiteStyleProfile, contrastRatio } from "../rendering/site-style-profile.js";

const pagePath = "artifacts/cornerstone/best-car-drying-towel/final-human-approved-v3/semantic-page.json";
const packetPath = "artifacts/cornerstone/best-car-drying-towel/fixture-v1/research-packet.json";
const load = async () => { const [page, packet] = await Promise.all([readFile(pagePath, "utf8").then(JSON.parse), readFile(packetPath, "utf8").then(JSON.parse)]); return { page, allowlists: deriveCornerstoneStrategyAllowlists(packet) }; };

test("rendering is deterministic and emits exactly one H1", async () => { const { page, allowlists } = await load(); const first = renderSemanticPageHtml(page, { allowlists }); const second = renderSemanticPageHtml(page, { allowlists }); assert.equal(first, second); assert.equal((first.match(/<h1\b/g) || []).length, 1); assert.equal((first.match(/<h2\b/g) || []).length, 8); });
test("rendering escapes customer text and preserves canonical links", async () => { const { page, allowlists } = await load(); const copy = structuredClone(page); copy.introduction_deck = "<script>alert('x')</script> & safe"; const html = renderSemanticPageHtml(copy, { allowlists }); assert.equal(html.includes("<script>"), false); assert.match(html, /&lt;script&gt;/); const productUrl = allowlists.products[0].url; assert.match(html, new RegExp(productUrl.replace(/[.*+?^${}()|[\\]\\\\]/g, "\\\\$&"))); const linkUrl = allowlists.internal_links[0].destination_url; assert.match(html, new RegExp(linkUrl.replace(/[.*+?^${}()|[\\]\\\\]/g, "\\\\$&"))); });
test("missing required and optional media remain explicit placeholders", async () => { const { page, allowlists } = await load(); const html = renderSemanticPageHtml(page, { allowlists }); assert.match(html, /data-media-status="required_missing"/); assert.match(html, /data-media-status="optional_missing"/); assert.equal(/<img\b[^>]*src=/.test(html), false); });
test("zero-product pages and arbitrary supported component sequences render without article-specific assumptions", () => { const page = { h1: "A General Guide", introduction_deck: "Useful copy.", components: [{ component_id: "x", component_type: "quick_answer", data: { heading: "Answer", concise_answer: "A direct answer.", supporting_points: [] }, media_requirements: [] }, { component_id: "y", component_type: "rich_text_section", data: { heading: "Details", paragraphs: ["More detail."], key_points: [] }, media_requirements: [] }] }; const html = renderSemanticPageHtml(page, { allowlists: { products: [], internal_links: [] } }); assert.equal((html.match(/<h1\b/g) || []).length, 1); assert.match(html, /A General Guide/); assert.doesNotMatch(html, /Street Kingz|towel|Product 70/); });
test("alternate theme configuration changes presentation classes without changing semantic copy", async () => { const { page, allowlists } = await load(); const html = renderSemanticPageHtml(page, { allowlists, theme: { theme_id: "other-site-v1", class_prefix: "other", container: { max_width: "60rem", reading_width: "42rem", gutter: "1rem" }, breakpoints: { mobile: "0-40rem", desktop: "40rem+" }, typography: { body: "serif", heading: "serif", line_height: 1.7 }, primitives: { section: "section", card: "article", callout: "aside", table: "table", faq: "details" } } }); assert.match(html, /data-theme="other-site-v1"/); assert.match(html, /class="other-page\b/); assert.match(html, /Best Car Drying Towel/); });
test("Street Kingz theme uses site-level tokens and suppresses naked customer-facing URLs", async () => { const { page, allowlists } = await load(); const html = renderSemanticPageHtml(page, { allowlists, theme: STREET_KINGZ_THEME }); assert.equal(STREET_KINGZ_THEME.colors.dark, "#000000"); assert.equal(STREET_KINGZ_THEME.colors.accent, "#b81e0f"); assert.equal(STREET_KINGZ_THEME.shape.radius, "12px"); assert.match(html, /sk-editorial-product-recommendation/); assert.match(html, /1200gsm-Fold-scaled-.webp/); assert.doesNotMatch(html, />https:\/\/streetkingz\.co\.uk/); });
test("production media mode fails on required media and omits optional placeholders", async () => { const { page, allowlists } = await load(); assert.throws(() => renderSemanticPageHtml(page, { allowlists, theme: STREET_KINGZ_THEME, mode: "production" }), /Required media unresolved/); const optionalOnly = structuredClone(page); optionalOnly.components[0].media_requirements = []; const html = renderSemanticPageHtml(optionalOnly, { allowlists, theme: STREET_KINGZ_THEME, mode: "production" }); assert.doesNotMatch(html, /media required before publication|optional media not supplied/); });
test("SiteStyleProfile contract supports neutral and synthetic sites without Street Kingz defaults", () => { assert.equal(validateSiteStyleProfile(DEFAULT_SITE_STYLE_PROFILE).status, "PASS"); const synthetic = createSiteStyleProfile({ profile_id: "synthetic-site-v1", theme_id: "synthetic-theme", class_prefix: "synthetic", site_id: "example.test", colors: { ...DEFAULT_SITE_STYLE_PROFILE.colors, accent: "#345678" } }); assert.equal(synthetic.site_id, "example.test"); assert.equal(synthetic.colors.accent, "#345678"); assert.equal(synthetic.profile_id.includes("street"), false); });
test("surface roles pair background and foreground tokens with WCAG-safe contrast", () => { assert.equal(validateSiteStyleProfile(STREET_KINGZ_THEME).status, "PASS"); assert.ok(contrastRatio(STREET_KINGZ_THEME.surfaces.surface_dark.text, STREET_KINGZ_THEME.surfaces.surface_dark.background) >= 4.5); assert.ok(contrastRatio(STREET_KINGZ_THEME.surfaces.surface_dark.accent_text, STREET_KINGZ_THEME.surfaces.surface_dark.accent) >= 4.5); const bad = { ...DEFAULT_SITE_STYLE_PROFILE, profile_id: "bad-contrast", surfaces: { ...DEFAULT_SITE_STYLE_PROFILE.surfaces, surface: { ...DEFAULT_SITE_STYLE_PROFILE.surfaces.surface, text: "#eeeeee", background: "#ffffff" } } }; assert.equal(validateSiteStyleProfile(bad).status, "FAIL"); });
test("surface inheritance emits scoped tokens for light, dark and mixed sections", async () => { const { page, allowlists } = await load(); const html = renderSemanticPageHtml(page, { allowlists, theme: STREET_KINGZ_THEME }); assert.match(html, /data-surface-role="page"/); assert.match(html, /data-surface-role="surface_emphasis"/); assert.match(html, /data-surface-role="surface_dark"/); assert.match(html, /surface-surface_alt/); });
