import test from "node:test";
import assert from "node:assert/strict";
import { extractSiteDiscoveryObservation, discoverSiteStyleProfile } from "../rendering/site-style-discovery.js";
import { validateSiteStyleProfile } from "../rendering/site-style-profile.js";

const street = JSON.parse(await (await import("node:fs/promises")).readFile("artifacts/style-discovery/street-kingz-v1/discovery-v1/site-style-discovery.json", "utf8"));
test("Street Kingz discovery is multi-page, provenance-bearing and independently validated", () => { assert.equal(street.status, "PASS"); assert.equal(street.pages.length, 2); assert.ok(street.evidence.every((item) => item.supporting_urls.length)); assert.equal(validateSiteStyleProfile(street.profile).status, "PASS"); assert.ok(street.profile.provenance.length > 0); assert.equal(street.profile.design_grammar.page_geometry.canvas, "full_width_sections"); assert.equal(street.profile.design_grammar.section_geometry.split_layout, true); });
test("synthetic second site produces materially different design grammar", () => { const pages = [{ url: "https://example.test/", page_type: "homepage", html: "<main><h1>Example</h1><section><img src=\"a.jpg\"><h2>Welcome</h2></section></main>", stylesheets: [":root{font-family:Inter}body{background:#fefefe;color:#123456}section{max-width:720px;padding:80px; background:#eef5ff}a{color:#0055aa;border-radius:2px}" ] }, { url: "https://example.test/guide", page_type: "article", html: "<main><h1>Guide</h1><section><h2>Details</h2><p>Text</p></section></main>", stylesheets: ["body{font-family:Inter;color:#123456} @media(max-width:700px){main{padding:16px}}" ] }]; const result = discoverSiteStyleProfile({ site_id: "example.test", pages }); assert.equal(result.status, "PASS"); assert.equal(result.profile.site_id, "example.test"); assert.notEqual(result.profile.surfaces.page.background, street.profile.surfaces.page.background); assert.notEqual(result.profile.typography.body, street.profile.typography.body); assert.ok(result.profile.provenance.every((item) => item.supporting_urls.every((url) => url.includes("example.test")))); });
test("insufficient and conflicting evidence fail safely or retain low confidence", () => { const empty = discoverSiteStyleProfile({ site_id: "empty.test", pages: [] }); assert.equal(empty.status, "INSUFFICIENT_EVIDENCE"); const one = discoverSiteStyleProfile({ site_id: "one.test", pages: [{ url: "https://one.test", html: "<h1>One</h1>", stylesheets: ["body{color:#111111;background:#ffffff}"] }] }); assert.ok(one.evidence.some((item) => item.confidence === "low")); });
test("discovery core has no Street Kingz-specific dependency", async () => { const { readFile } = await import("node:fs/promises"); const source = (await readFile("rendering/site-style-discovery.js", "utf8")).toLowerCase(); for (const term of ["street kingz", "product 70", "drying towel"]) assert.equal(source.includes(term), false, term); });
