import test from "node:test";
import assert from "node:assert/strict";
import crypto from "node:crypto";
import express from "express";
import { createClient } from "@supabase/supabase-js";
import { createWooCommerceRouter } from "../routes/woocommerce.js";
import { loadCurrentCommerceSnapshot } from "../product-kernel/woocommerceRouteService.js";

const enabled = process.env.V1_03_INTEGRATION === "1";
const required = name => process.env[name] || (() => { throw new Error(`${name} required`); })();

test("V1-03 incremental candidate, LKG, and status stay tenant-scoped", { skip: !enabled }, async t => {
  const url = required("SUPABASE_URL"), publishable = required("SUPABASE_PUBLISHABLE_KEY"), service = required("SUPABASE_SERVICE_ROLE_KEY");
  const admin = createClient(url, service, { auth: { persistSession: false } });
  const email = `v103-incremental-${crypto.randomUUID()}@example.test`, password = `V1-03-${crypto.randomUUID()}!Aa`;
  const created = await admin.auth.admin.createUser({ email, password, email_confirm: true }); assert.ifError(created.error); const userId = created.data.user.id;
  const caller = createClient(url, publishable, { auth: { persistSession: false } }); const signed = await caller.auth.signInWithPassword({ email, password }); assert.ifError(signed.error); const accessToken = signed.data.session.access_token;
  t.after(async () => { await caller.rpc("product_transition_connection", { p_connection_id: connection?.id, p_status: "disconnected", p_consent_state: "revoked", p_correlation_id: crypto.randomUUID() }); await admin.auth.admin.deleteUser(userId); });
  const account = (await admin.from("accounts").insert({ auth_user_id: userId }).select().single()).data;
  const business = (await admin.from("businesses").insert({ account_id: account.id, name: "Incremental Synthetic", ecommerce_platform: "woocommerce" }).select().single()).data;
  const connection = (await admin.from("connections").insert({ business_id: business.id, provider_type: "woocommerce" }).select().single()).data;
  const attemptToken = `v103-incremental-${crypto.randomUUID()}`; const attempt = await admin.rpc("woo_create_auth_attempt", { p_user_id: attemptToken, p_account_id: account.id, p_business_id: business.id, p_connection_id: connection.id, p_canonical_base_url: "https://shop.example/", p_expires_at: new Date(Date.now() + 60000).toISOString() }); assert.ifError(attempt.error); assert.ifError((await admin.rpc("woo_claim_auth_attempt", { p_user_id: attemptToken })).error); assert.ifError((await admin.rpc("woo_capture_callback", { p_attempt_id: attempt.data, p_consumer_key: "ck_incremental", p_consumer_secret: "cs_incremental", p_key_permissions: "read" })).error);
  const established = await admin.rpc("woo_complete_connection", { p_attempt_id: attempt.data, p_home_url: "https://shop.example/", p_site_url: "https://shop.example/", p_version: "11", p_timezone: "UTC", p_currency: "GBP", p_correlation_id: crypto.randomUUID() }); assert.ifError(established.error);
  const store = (await admin.from("commerce_stores").select("id,current_generation").eq("id", established.data).single()).data;
  const generationA = await admin.rpc("commerce_begin_initial_sync", { p_store_id: store.id, p_correlation_id: crypto.randomUUID() }); assert.ifError(generationA.error);
  const payloadA = { products: [{ source_id: 1, name: "P1", slug: "p1", product_type: "simple", source_status: "publish", current_price: "10.00", source_modified_at: "2026-01-01T00:00:00Z" }], variations: [], categories: [{ source_id: 10, name: "Cat", slug: "cat", parent_source_id: null }], links: [{ product_source_id: 1, category_source_id: 10 }], orders: [{ source_id: 5, source_status: "completed", recognition_state: "recognised", currency: "GBP", source_created_at: "2025-12-01T00:00:00Z", source_modified_at: "2026-01-01T00:00:00Z", order_total: "10.00", tax_total: "2.00", shipping_total: "0", discount_total: "0", refund_total: "0", prices_include_tax: false }], lines: [{ order_source_id: 5, source_line_id: 50, product_source_id: 1, variation_source_id: null, quantity: 1, subtotal: "10.00", total: "10.00", tax: "2.00", refunded_quantity: 0, refund_total: "0", refund_tax: "0" }], adjustments: [] };
  assert.ifError((await admin.rpc("commerce_stage_initial_snapshot", { p_store_id: store.id, p_generation_id: generationA.data, p_products: payloadA.products, p_variations: payloadA.variations, p_categories: payloadA.categories, p_links: payloadA.links, p_orders: payloadA.orders, p_lines: payloadA.lines, p_adjustments: payloadA.adjustments })).error); assert.ifError((await admin.rpc("commerce_complete_initial_sync", { p_store_id: store.id, p_generation_id: generationA.data })).error);
  const loaded = await loadCurrentCommerceSnapshot(admin, { storeId: store.id, generationId: generationA.data }); assert.equal(loaded.products.length, 1); assert.equal(loaded.orders.length, 1); assert.equal(loaded.lines.length, 1); assert.equal(loaded.adjustments.length, 0);
  const generationB = await admin.rpc("commerce_begin_initial_sync", { p_store_id: store.id, p_correlation_id: crypto.randomUUID() }); assert.ifError(generationB.error);
  const payloadB = { ...payloadA, products: [{ ...payloadA.products[0], current_price: "12.00", source_modified_at: "2026-01-02T00:00:00Z" }], orders: [], lines: [], adjustments: [] };
  assert.ifError((await admin.rpc("commerce_stage_initial_snapshot", { p_store_id: store.id, p_generation_id: generationB.data, p_products: payloadB.products, p_variations: payloadB.variations, p_categories: payloadB.categories, p_links: [], p_orders: [], p_lines: [], p_adjustments: [] })).error); assert.ifError((await admin.rpc("commerce_complete_initial_sync", { p_store_id: store.id, p_generation_id: generationB.data })).error);
  assert.equal((await admin.from("commerce_stores").select("current_generation,sync_state").eq("id", store.id).single()).data.current_generation, generationB.data); assert.equal((await admin.from("commerce_products").select("source_id").eq("generation_id", generationA.data)).data.length, 1);
  const generationC = await admin.rpc("commerce_begin_initial_sync", { p_store_id: store.id, p_correlation_id: crypto.randomUUID() }); assert.ifError(generationC.error); assert.ifError((await admin.rpc("commerce_mark_sync_failed", { p_store_id: store.id, p_generation_id: generationC.data, p_error_code: "PROVIDER_UNAVAILABLE", p_partial: true })).error); const lkg = (await admin.from("commerce_stores").select("current_generation,sync_state,last_successful_at,last_attempted_at").eq("id", store.id).single()).data; assert.equal(lkg.current_generation, generationB.data); assert.equal(lkg.sync_state, "partial"); assert.ok(lkg.last_successful_at); assert.ok(lkg.last_attempted_at);
  const router = createWooCommerceRouter({ verifyIdentity: async () => ({ authUserId: userId }), callerClient: () => caller, privilegedClient: () => admin, loadWooStoreContext: async () => ({ store: { id: store.id, current_generation: generationB.data, canonical_base_url: "https://shop.example/" }, credentials: { consumerKey: "ck", consumerSecret: "cs" } }), loadCurrentCommerceSnapshot: async () => loaded, collectIncrementalCommerce: async () => ({ ...payloadA, orderWindowStart: "2025-01-01T00:00:00.000Z", orderWindowEnd: "2026-01-01T00:00:00.000Z", changes: { products_added: 0, products_refreshed: 0, products_removed: 0, variations_added_or_refreshed: 0, variations_removed: 0, orders_added: 0, orders_refreshed: 0, orders_expired_or_removed: 1 } }) });
  const app = express(); app.use(router); const server = await new Promise((resolve, reject) => { const value = app.listen(0, "127.0.0.1", () => resolve(value)); value.on("error", reject); }); t.after(() => server.close());
  const status = await fetch(`http://127.0.0.1:${server.address().port}/api/product/woocommerce/status?connection_id=${connection.id}`, { headers: { authorization: `Bearer ${accessToken}` } }); assert.equal(status.status, 200); const statusBody = await status.json(); assert.equal(statusBody.order_horizon_days, 365); assert.equal(statusBody.has_current_complete_generation, true); assert.equal(Object.hasOwn(statusBody, "secret_reference"), false);
  const sync = await fetch(`http://127.0.0.1:${server.address().port}/api/product/woocommerce/sync`, { method: "POST", headers: { authorization: `Bearer ${accessToken}`, "content-type": "application/json" }, body: JSON.stringify({ connection_id: connection.id }) }); assert.equal(sync.status, 201); const syncBody = await sync.json(); assert.equal(syncBody.sync_mode, "incremental"); assert.equal(syncBody.changes.orders_expired_or_removed, 1);
});
