import test from "node:test";
import assert from "node:assert/strict";
import crypto from "node:crypto";
import http from "node:http";
import express from "express";
import { createClient } from "@supabase/supabase-js";
import route from "../routes/googleSearchConsole.js";
import { setGoogleSearchConsoleTransportFactory } from "../product-kernel/googleSearchConsoleOAuth.js";

const enabled = process.env.V1_04_P2B_INTEGRATION === "1";
const required = name => process.env[name] || (() => { throw new Error(`${name} required`); })();
const request = (server, method, path, token, body) => new Promise((resolve, reject) => {
  const headers = { "content-type": "application/json" }; if (token) headers.authorization = `Bearer ${token}`;
  const req = http.request({ hostname: "127.0.0.1", port: server.address().port, method, path, headers }, res => { let text = ""; res.on("data", c => { text += c; }); res.on("end", () => { let parsed = null; try { parsed = text ? JSON.parse(text) : null; } catch {} resolve({ status: res.statusCode, body: parsed, text }); }); });
  req.on("error", reject); if (body !== undefined) req.write(JSON.stringify(body)); req.end();
});
const hashState = state => crypto.createHash("sha256").update(state).digest("base64url");
const safe = response => assert.doesNotMatch(response.text || "", /PostgREST|database error|Vault|secret_reference|pkce|verifier|refresh_token|access_token|state=/i);

test("P2-B replay, concurrency and activation-race matrix", { skip: !enabled }, async t => {
  const url = required("SUPABASE_URL"), publishable = required("SUPABASE_PUBLISHABLE_KEY"), service = required("SUPABASE_SERVICE_ROLE_KEY");
  const admin = createClient(url, service, { auth: { persistSession: false } });
  const password = `${crypto.randomUUID()}!Aa9`;
  const created = await admin.auth.admin.createUser({ email: `v104-p2b-${crypto.randomUUID()}@local.test`, password, email_confirm: true }); assert.ifError(created.error); const userId = created.data.user.id;
  const login = createClient(url, publishable, { auth: { persistSession: false } }); const signed = await login.auth.signInWithPassword({ email: created.data.user.email, password }); assert.ifError(signed.error); const token = signed.data.session.access_token;
  const caller = createClient(url, publishable, { global: { headers: { authorization: `Bearer ${token}` } }, auth: { persistSession: false } });
  assert.ifError((await caller.rpc("product_create_account", { p_correlation_id: crypto.randomUUID() })).error);
  const business = await caller.rpc("product_create_business", { p_name: "P2-B synthetic business", p_platform: "woocommerce", p_correlation_id: crypto.randomUUID() }); assert.ifError(business.error);
  const account = await admin.from("accounts").select("id").eq("auth_user_id", userId).single(); assert.ifError(account.error);
  const woo = await caller.rpc("product_create_connection", { p_provider_type: "woocommerce", p_correlation_id: crypto.randomUUID() }); assert.ifError(woo.error);
  const wooToken = `p2b-woo-${crypto.randomUUID()}`;
  const wooAttempt = await admin.rpc("woo_create_auth_attempt", { p_user_id: wooToken, p_account_id: account.data.id, p_business_id: business.data.id, p_connection_id: woo.data.id, p_canonical_base_url: "https://example.com/shop/", p_expires_at: new Date(Date.now() + 60000).toISOString() }); assert.ifError(wooAttempt.error);
  assert.ifError((await admin.rpc("woo_claim_auth_attempt", { p_user_id: wooToken })).error); assert.ifError((await admin.rpc("woo_capture_callback", { p_attempt_id: wooAttempt.data, p_consumer_key: "synthetic-key", p_consumer_secret: "synthetic-secret", p_key_permissions: "read" })).error); assert.ifError((await admin.rpc("woo_complete_connection", { p_attempt_id: wooAttempt.data, p_home_url: "https://example.com/shop/", p_site_url: "https://example.com/shop/", p_version: "local", p_timezone: "UTC", p_currency: "GBP", p_correlation_id: crypto.randomUUID() })).error);

  let exchangeCount = 0, exchangeGate = false, exchangeRelease; let probeGate = false, probeWaiters = []; let probeEntered = 0;
  setGoogleSearchConsoleTransportFactory(() => ({
    authorizationUrl: ({ state }) => `https://accounts.google.test/authorize?state=${encodeURIComponent(state)}`,
    async exchangeCode() { exchangeCount++; if (exchangeGate) await new Promise(resolve => { exchangeRelease = resolve; }); return { refresh_token: `synthetic-refresh-${exchangeCount}`, scope: "https://www.googleapis.com/auth/webmasters.readonly" }; },
    async accessToken() { return "synthetic-access"; },
    async sitesList() { return { siteEntry: [{ siteUrl: "https://example.com/shop/", permissionLevel: "siteOwner" }] }; },
    async site(_access, siteUrl) { probeEntered++; if (probeGate) await new Promise(resolve => probeWaiters.push(resolve)); return { siteUrl, permissionLevel: "siteOwner" }; }
  }));
  const app = express(); app.use(express.json()); app.use(route); const server = await new Promise((resolve, reject) => { const s = app.listen(0, "127.0.0.1", () => resolve(s)); s.on("error", reject); });
  const start = async () => { const r = await request(server, "POST", "/api/product/organic-evidence/search-console/connect", token, {}); assert.equal(r.status, 201, r.text); const u = new URL(r.body.authorization_url); return { state: u.searchParams.get("state"), connectionId: r.body.connection.id }; };
  const callback = state => request(server, "GET", `/api/product/organic-evidence/search-console/callback?state=${encodeURIComponent(state)}&code=synthetic-code`, null);
  const attempt = async state => { const r = await admin.from("gsc_oauth_attempts").select("id,status,staged_secret_reference").eq("state_hash", hashState(state)).single(); assert.ifError(r.error); return r.data; };
  const attemptsFor = async connectionId => { const r = await admin.from("gsc_oauth_attempts").select("id,status,staged_secret_reference").eq("connection_id", connectionId); assert.ifError(r.error); return r.data; };
  const expire = async state => { const a = await attempt(state); assert.ifError((await admin.rpc("gsc_expire_oauth_attempt", { p_attempt_id: a.id })).error); };
  const countPendingVault = async () => { const r = await admin.from("vault.secrets").select("id", { count: "exact", head: true }).like("name", "v1-04-google-search-console-pending-%"); assert.ifError(r.error); return r.count || 0; };
  const vaultBaseline = await countPendingVault();
  const waitFor = async predicate => { const deadline = Date.now() + 3000; while (!predicate() && Date.now() < deadline) await new Promise(resolve => setTimeout(resolve, 5)); assert.equal(predicate(), true, "barrier deadline exceeded"); };
  const releaseProbes = () => { const waiters = probeWaiters; probeWaiters = []; waiters.forEach(resolve => resolve()); };
  const cleanLive = async connectionId => { const rows = await attemptsFor(connectionId); for (const row of rows.filter(x => ["pending", "processing"].includes(x.status))) await admin.rpc("gsc_expire_oauth_attempt", { p_attempt_id: row.id }); };
  const select = connectionId => request(server, "POST", "/api/product/organic-evidence/search-console/select", token, { connection_id: connectionId, site_url: "https://example.com/shop/" });

  t.after(async () => { setGoogleSearchConsoleTransportFactory(undefined); await server.close(); const gsc = await admin.from("connections").select("id").eq("business_id", business.data.id).eq("provider_type", "google_search_console").maybeSingle(); if (gsc.data) await admin.rpc("gsc_disconnect", { p_business_id: business.data.id, p_connection_id: gsc.data.id }); await admin.auth.admin.deleteUser(userId); assert.equal(await countPendingVault(), vaultBaseline); });

  await t.test("P2-RACE-START-001 two simultaneous starts", async () => { const results = await Promise.all([start(), start()]); assert.equal(new Set(results.map(x => x.connectionId)).size, 1); const rows = await attemptsFor(results[0].connectionId); assert.equal(rows.filter(x => x.status === "pending").length, 1); assert.equal(rows.filter(x => x.status === "superseded").length, 1); const callbacks = await Promise.all(results.map(x => callback(x.state))); assert.equal(callbacks.filter(r => r.status === 200).length, 1); callbacks.filter(r => r.status !== 200).forEach(safe); const winner = results[callbacks.findIndex(r => r.status === 200)]; await expire(winner.state); await cleanLive(results[0].connectionId); });
  await t.test("P2-RACE-START-002 three simultaneous starts", async () => { const results = await Promise.all([start(), start(), start()]); const rows = await attemptsFor(results[0].connectionId); assert.equal(rows.filter(x => x.status === "pending").length, 1); assert.ok(rows.filter(x => x.status === "superseded").length >= 2); const callbacks = await Promise.all(results.map(result => callback(result.state))); assert.equal(callbacks.filter(r => r.status === 200).length, 1); callbacks.filter(r => r.status !== 200).forEach(safe); await expire(results.find((_, index) => callbacks[index].status === 200).state); });
  await t.test("P2-RACE-START-003 new start while pending", async () => { const old = await start(); const newer = await start(); assert.equal((await callback(old.state)).status, 400); assert.equal((await callback(newer.state)).status, 200); await expire(newer.state); });
  await t.test("P2-RACE-START-004 new start while processing", async () => { const old = await start(); assert.equal((await callback(old.state)).status, 200); const newer = await start(); const oldRow = await attempt(old.state); assert.equal(oldRow.status, "superseded"); assert.equal(oldRow.staged_secret_reference, null); assert.notEqual((await request(server, "GET", `/api/product/organic-evidence/search-console/properties?connection_id=${old.connectionId}`, token)).status, 200); await expire(newer.state); });

  await t.test("P2-RACE-CALLBACK-001 sequential replay", async () => { const s = await start(); exchangeCount = 0; assert.equal((await callback(s.state)).status, 200); assert.equal((await callback(s.state)).status, 400); assert.equal(exchangeCount, 1); await expire(s.state); });
  for (const [id, count] of [["P2-RACE-CALLBACK-002", 2], ["P2-RACE-CALLBACK-003", 3]]) await t.test(`${id} concurrent callback claim`, async () => { const s = await start(); exchangeCount = 0; exchangeGate = true; const calls = Array.from({ length: count }, () => callback(s.state)); await waitFor(() => exchangeCount === 1); exchangeRelease(); const results = await Promise.all(calls); assert.equal(results.filter(r => r.status === 200).length, 1); assert.equal(results.filter(r => r.status !== 200).length, count - 1); assert.equal(exchangeCount, 1); exchangeGate = false; await expire(s.state); });
  await t.test("P2-RACE-SUPERSEDE-001 processing callback superseded", async () => { const old = await start(); exchangeCount = 0; exchangeGate = true; const pending = callback(old.state); await waitFor(() => exchangeCount === 1); const newer = await start(); exchangeRelease(); const result = await pending; assert.notEqual(result.status, 200); const oldRow = await attempt(old.state); assert.equal(oldRow.status, "superseded"); assert.equal(oldRow.staged_secret_reference, null); await expire(newer.state); exchangeGate = false; });
  await t.test("P2-RACE-SUPERSEDE-002 pending superseded before claim", async () => { const old = await start(); const newer = await start(); const before = exchangeCount; assert.equal((await callback(old.state)).status, 400); assert.equal(exchangeCount, before); assert.equal((await callback(newer.state)).status, 200); await expire(newer.state); });

  await t.test("P2-RACE-EXPIRY-001 expiry before claim", async () => { const s = await start(); await expire(s.state); const before = exchangeCount; assert.equal((await callback(s.state)).status, 400); assert.equal(exchangeCount, before); });
  await t.test("P2-RACE-EXPIRY-002 expiry during exchange", async () => { const s = await start(); exchangeCount = 0; exchangeGate = true; const cb = callback(s.state); await waitFor(() => exchangeCount === 1); await expire(s.state); exchangeRelease(); const result = await cb; assert.notEqual(result.status, 200); assert.equal((await attempt(s.state)).status, "expired"); exchangeGate = false; });
  await t.test("P2-RACE-EXPIRY-003 expiry after staging before selection", async () => { const s = await start(); assert.equal((await callback(s.state)).status, 200); await expire(s.state); const props = await request(server, "GET", `/api/product/organic-evidence/search-console/properties?connection_id=${s.connectionId}`, token); assert.notEqual(props.status, 200); });

  await t.test("P2-RACE-ACTIVATE-001 activation before expiry", async () => { const s = await start(); assert.equal((await callback(s.state)).status, 200); assert.equal((await select(s.connectionId)).status, 200); const a = await attempt(s.state); assert.equal(a.status, "consumed"); assert.ifError((await admin.rpc("gsc_expire_oauth_attempt", { p_attempt_id: a.id })).error); const second = await select(s.connectionId); assert.notEqual(second.status, 200); });
  await t.test("P2-RACE-ACTIVATE-002 expiry before activation", async () => { const s = await start(); assert.equal((await callback(s.state)).status, 200); probeEntered = 0; probeGate = true; const selecting = select(s.connectionId); await waitFor(() => probeEntered > 0); await expire(s.state); releaseProbes(); const result = await selecting; assert.notEqual(result.status, 200); assert.equal((await attempt(s.state)).status, "expired"); probeGate = false; });
  await t.test("P2-RACE-ACTIVATE-003 competing activations", async () => { const s = await start(); assert.equal((await callback(s.state)).status, 200); probeEntered = 0; probeGate = true; const calls = [select(s.connectionId), select(s.connectionId)]; await waitFor(() => probeEntered >= 2); releaseProbes(); const results = await Promise.all(calls); assert.equal(results.filter(r => r.status === 200).length, 1); assert.equal(results.filter(r => r.status !== 200).length, 1); results.filter(r => r.status !== 200).forEach(safe); probeGate = false; });
  await t.test("P2-RACE-ACTIVATE-004 activation replay", async () => { const s = await start(); assert.equal((await callback(s.state)).status, 200); assert.equal((await select(s.connectionId)).status, 200); const before = await admin.from("organic_evidence_sources").select("id", { count: "exact", head: true }).eq("business_id", business.data.id).eq("source_kind", "search_console"); assert.ifError(before.error); const replay = await select(s.connectionId); assert.notEqual(replay.status, 200); const after = await admin.from("organic_evidence_sources").select("id", { count: "exact", head: true }).eq("business_id", business.data.id).eq("source_kind", "search_console"); assert.equal(after.count, before.count); });
  await t.test("P2-RACE-ACTIVATE-005 activation versus new start", async () => { const first = await start(); assert.equal((await callback(first.state)).status, 200); probeEntered = 0; probeGate = true; const activating = select(first.connectionId); await waitFor(() => probeEntered > 0); const newer = await start(); releaseProbes(); const activation = await activating; assert.notEqual(activation.status, 200); assert.equal((await attempt(first.state)).status, "superseded"); assert.equal((await attempt(newer.state)).status, "pending"); await expire(newer.state); probeGate = false;
    const second = await start(); assert.equal((await callback(second.state)).status, 200); const activationWins = await select(second.connectionId); assert.equal(activationWins.status, 200); const after = await start(); assert.equal((await attempt(after.state)).status, "pending"); await expire(after.state); });
});
