import test from "node:test";
import assert from "node:assert/strict";
import crypto from "node:crypto";
import http from "node:http";
import express from "express";
import { createClient } from "@supabase/supabase-js";
import route from "../routes/googleSearchConsole.js";
import { ProductError } from "../product-kernel/errors.js";
import { setGoogleSearchConsoleTransportFactory } from "../product-kernel/googleSearchConsoleOAuth.js";
import { setVaultAdapterForTests, createVaultSecretProduction, deleteVaultSecretProduction } from "../product-kernel/vault.js";

const enabled = process.env.V1_04_P3A1_INTEGRATION === "1";
const required = name => process.env[name] || (() => { throw new Error(`${name} required`); })();
const request = (server, method, path, token, body) => new Promise((resolve, reject) => { const headers = { "content-type": "application/json" }; if (token) headers.authorization = `Bearer ${token}`; const req = http.request({ hostname: "127.0.0.1", port: server.address().port, method, path, headers }, res => { let text = ""; res.on("data", c => { text += c; }); res.on("end", () => { let parsed = null; try { parsed = text ? JSON.parse(text) : null; } catch {} resolve({ status: res.statusCode, body: parsed, text }); }); }); req.on("error", reject); if (body) req.write(JSON.stringify(body)); req.end(); });

test("P3-A1 reconnect and property/evidence consistency matrix", { skip: !enabled }, async t => {
  const url = required("SUPABASE_URL"), publishable = required("SUPABASE_PUBLISHABLE_KEY"), service = required("SUPABASE_SERVICE_ROLE_KEY");
  const admin = createClient(url, service, { auth: { persistSession: false } });
  const email = `v104-p3a1-${crypto.randomUUID()}@local.test`, password = `${crypto.randomUUID()}!Aa9`;
  const made = await admin.auth.admin.createUser({ email, password, email_confirm: true }); assert.ifError(made.error); const userId = made.data.user.id;
  t.after(async () => { setGoogleSearchConsoleTransportFactory(undefined); setVaultAdapterForTests(undefined); await admin.auth.admin.deleteUser(userId); });
  const login = createClient(url, publishable, { auth: { persistSession: false } }); const signed = await login.auth.signInWithPassword({ email, password }); assert.ifError(signed.error); const token = signed.data.session.access_token;
  const caller = createClient(url, publishable, { global: { headers: { authorization: `Bearer ${token}` } }, auth: { persistSession: false } });
  assert.ifError((await caller.rpc("product_create_account", { p_correlation_id: crypto.randomUUID() })).error);
  const business = await caller.rpc("product_create_business", { p_name: "P3-A1 synthetic reconnect", p_platform: "woocommerce", p_correlation_id: crypto.randomUUID() }); assert.ifError(business.error);
  const woo = await caller.rpc("product_create_connection", { p_provider_type: "woocommerce", p_correlation_id: crypto.randomUUID() }); assert.ifError(woo.error);
  const account = await admin.from("accounts").select("id").eq("auth_user_id", userId).single(); assert.ifError(account.error);
  const wooUser = `p3a1-woo-${crypto.randomUUID()}`; const wa = await admin.rpc("woo_create_auth_attempt", { p_user_id: wooUser, p_account_id: account.data.id, p_business_id: business.data.id, p_connection_id: woo.data.id, p_canonical_base_url: "https://example.com/shop/", p_expires_at: new Date(Date.now() + 60000).toISOString() }); assert.ifError(wa.error);
  assert.ifError((await admin.rpc("woo_claim_auth_attempt", { p_user_id: wooUser })).error); assert.ifError((await admin.rpc("woo_capture_callback", { p_attempt_id: wa.data, p_consumer_key: "synthetic-key", p_consumer_secret: "synthetic-secret", p_key_permissions: "read" })).error); assert.ifError((await admin.rpc("woo_complete_connection", { p_attempt_id: wa.data, p_home_url: "https://example.com/shop/", p_site_url: "https://example.com/shop/", p_version: "synthetic", p_timezone: "UTC", p_currency: "GBP", p_correlation_id: crypto.randomUUID() })).error);
  let mode = "success", exchanges = 0, createBarrier = null, releaseCreate = null;
  setGoogleSearchConsoleTransportFactory(() => ({
    authorizationUrl: ({ state }) => `https://accounts.google.test/authorize?state=${state}`,
    async exchangeCode() { exchanges += 1; if (mode === "token-failure") throw new ProductError("GSC_TOKEN_EXCHANGE_FAILED", "Synthetic token failure.", 502); return { refresh_token: `synthetic-p3a1-refresh-${exchanges}`, scope: "https://www.googleapis.com/auth/webmasters.readonly" }; },
    async accessToken() { return "synthetic-access"; },
    async sitesList() { if (mode === "list-failure") throw new ProductError("GSC_PROVIDER_ERROR", "Synthetic list failure.", 502); return { siteEntry: [{ siteUrl: "https://example.com/shop/", permissionLevel: "siteOwner" }, { siteUrl: "sc-domain:example.com", permissionLevel: "siteFullUser" }] }; },
    async site(_access, siteUrl) { if (mode === "probe-failure") throw new ProductError("GSC_PROPERTY_INVALID", "Synthetic probe failure.", 409); if (mode === "probe-wrong") return { siteUrl: "https://example.com/", permissionLevel: "siteOwner" }; return { siteUrl, permissionLevel: "siteOwner" }; }
  }));
  const app = express(); app.use(express.json()); app.use(route); const server = await new Promise((resolve, reject) => { const s = app.listen(0, "127.0.0.1", () => resolve(s)); s.on("error", reject); }); t.after(() => server.close());
  const start = async () => { const r = await request(server, "POST", "/api/product/organic-evidence/search-console/connect", token, {}); assert.equal(r.status, 201, r.text); return { state: new URL(r.body.authorization_url).searchParams.get("state"), connectionId: r.body.connection.id }; };
  const callback = (state, query = "code=synthetic-code") => request(server, "GET", `/api/product/organic-evidence/search-console/callback?state=${encodeURIComponent(state)}&${query}`, null);
  const row = async (table, columns, value, column = "connection_id") => { const r = await admin.from(table).select(columns).eq(column, value).single(); assert.ifError(r.error); return r.data; };
  const connection = async () => row("connections", "id,status,consent_state,secret_reference,disconnected_at", connectionId, "id");
  const gsc = async () => row("gsc_connections", "connection_state,selected_site_url,property_type", connectionId);
  const source = async () => row("organic_evidence_sources", "id,evidence_state,current_complete_run,evidence_as_of,last_successful_at", sourceId, "id");
  let connectionId, sourceId, runId, evidenceAsOf, activeSecret, current;

  await t.test("P3A-STATE-001 initial start", async () => { current = await start(); connectionId = current.connectionId; const c = await connection(); assert.equal(c.status, "pending"); assert.equal(c.secret_reference, null); assert.equal((await admin.from("organic_evidence_sources").select("id").eq("connection_id", connectionId)).data.length, 0); });
  await t.test("P3A-STATE-002 callback awaiting property", async () => { assert.equal((await callback(current.state)).status, 200); const g = await gsc(); assert.equal(g.connection_state, "awaiting_property"); const a = await admin.from("gsc_oauth_attempts").select("status,staged_secret_reference").eq("connection_id", connectionId).eq("status", "processing").single(); assert.ifError(a.error); assert.ok(a.data.staged_secret_reference); assert.equal((await connection()).secret_reference, null); });
  await t.test("P3A-STATE-003 first activation", async () => { const r = await request(server, "POST", "/api/product/organic-evidence/search-console/select", token, { connection_id: connectionId, site_url: "https://example.com/shop/" }); assert.equal(r.status, 200, r.text); const c = await connection(); activeSecret = c.secret_reference; assert.equal(c.status, "connected"); assert.equal(c.disconnected_at, null); assert.equal((await gsc()).selected_site_url, "https://example.com/shop/"); const s = await admin.from("organic_evidence_sources").select("id,evidence_state,current_complete_run").eq("connection_id", connectionId).single(); assert.ifError(s.error); sourceId = s.data.id; assert.equal(s.data.evidence_state, "never_collected"); assert.equal(s.data.current_complete_run, null); });
  await t.test("P3A-STATE-004 first authorization failure", async () => { const s = await start(); const r = await callback(s.state, "error=access_denied"); assert.equal(r.status, 409); assert.equal(r.body.error.code, "GSC_AUTH_DENIED"); assert.equal((await connection()).secret_reference, activeSecret); });
  await t.test("P3A-RECONNECT-001 start while connected", async () => { const begun = await admin.rpc("organic_begin_run", { p_source_id: sourceId, p_retrieved_at: new Date().toISOString() }); assert.ifError(begun.error); runId = begun.data.id; evidenceAsOf = "2026-09-01T10:00:00Z"; assert.ifError((await admin.rpc("organic_finish_run", { p_run_id: runId, p_state: "complete", p_completeness_state: "complete", p_evidence_as_of: evidenceAsOf })).error); current = await start(); const c = await connection(); assert.equal(c.status, "connected"); assert.equal(c.secret_reference, activeSecret); assert.equal((await gsc()).selected_site_url, "https://example.com/shop/"); assert.equal((await source()).current_complete_run, runId); });
  await t.test("P3A-RECONNECT-002 callback stages replacement", async () => { assert.equal((await callback(current.state)).status, 200); const c = await connection(); assert.equal(c.secret_reference, activeSecret); const a = await admin.from("gsc_oauth_attempts").select("staged_secret_reference").eq("connection_id", connectionId).eq("status", "processing").single(); assert.ifError(a.error); assert.ok(a.data.staged_secret_reference); assert.equal((await source()).current_complete_run, runId); });
  await t.test("P3A-RECONNECT-003 same-property replacement preserves evidence", async () => { const r = await request(server, "POST", "/api/product/organic-evidence/search-console/select", token, { connection_id: connectionId, site_url: "https://example.com/shop/" }); assert.equal(r.status, 200, r.text); assert.equal(r.body.evidence_state, "complete"); assert.equal(r.body.has_current_complete_evidence, true); const c = await connection(); assert.notEqual(c.secret_reference, activeSecret); activeSecret = c.secret_reference; assert.equal((await source()).current_complete_run, runId); assert.equal(new Date((await source()).evidence_as_of).toISOString(), new Date(evidenceAsOf).toISOString()); });
  await t.test("P3A-RECONNECT-004 different-property replacement resets current view", async () => { current = await start(); assert.equal((await callback(current.state)).status, 200); const r = await request(server, "POST", "/api/product/organic-evidence/search-console/select", token, { connection_id: connectionId, site_url: "sc-domain:example.com" }); assert.equal(r.status, 200, r.text); assert.equal(r.body.evidence_state, "never_collected"); assert.equal(r.body.has_current_complete_evidence, false); const s = await source(); assert.equal(s.current_complete_run, null); assert.equal(s.evidence_state, "never_collected"); assert.equal((await admin.from("organic_evidence_runs").select("id").eq("id", runId)).data.length, 1); activeSecret = (await connection()).secret_reference; });
  await t.test("P3A-RECONNECT-005 denied reconnect preserves active state", async () => { const old = activeSecret, property = (await gsc()).selected_site_url; const s = await start(); const r = await callback(s.state, "error=access_denied"); assert.equal(r.status, 409); assert.equal((await connection()).secret_reference, old); assert.equal((await gsc()).selected_site_url, property); });
  await t.test("P3A-RECONNECT-006 token failure preserves active state", async () => { const old = activeSecret; mode = "token-failure"; const s = await start(); const r = await callback(s.state); assert.equal(r.status, 409); assert.equal(r.body.error.code, "GSC_TOKEN_EXCHANGE_FAILED"); assert.equal((await connection()).secret_reference, old); mode = "success"; });
  await t.test("P3A-RECONNECT-007 property-list failure preserves active state", async () => { const old = activeSecret; const s = await start(); assert.equal((await callback(s.state)).status, 200); mode = "list-failure"; const r = await request(server, "GET", `/api/product/organic-evidence/search-console/properties?connection_id=${connectionId}`, token); assert.equal(r.status, 502); assert.equal((await connection()).secret_reference, old); mode = "success"; });
  await t.test("P3A-RECONNECT-008 property-probe failure preserves active state", async () => { const old = activeSecret, property = (await gsc()).selected_site_url; const s = await start(); assert.equal((await callback(s.state)).status, 200); mode = "probe-failure"; const r = await request(server, "POST", "/api/product/organic-evidence/search-console/select", token, { connection_id: connectionId, site_url: "https://example.com/shop/" }); assert.equal(r.status, 409); assert.equal((await connection()).secret_reference, old); assert.equal((await gsc()).selected_site_url, property); mode = "success"; });
  await t.test("P3A-RECONNECT-009 pending reconnect expiry", async () => { const s = await start(); const hash = crypto.createHash("sha256").update(s.state).digest("base64url"); const a = await admin.from("gsc_oauth_attempts").select("id").eq("state_hash", hash).single(); assert.ifError(a.error); assert.ifError((await admin.rpc("gsc_expire_oauth_attempt", { p_attempt_id: a.data.id })).error); assert.equal((await callback(s.state)).status, 400); assert.equal((await connection()).secret_reference, activeSecret); });
  await t.test("P3A-RECONNECT-010 staged reconnect expiry", async () => { const s = await start(); assert.equal((await callback(s.state)).status, 200); const a = await admin.from("gsc_oauth_attempts").select("id,staged_secret_reference").eq("connection_id", connectionId).eq("status", "processing").single(); assert.ifError(a.error); assert.ok(a.data.staged_secret_reference); assert.ifError((await admin.rpc("gsc_expire_oauth_attempt", { p_attempt_id: a.data.id })).error); const expired = await admin.from("gsc_oauth_attempts").select("status,staged_secret_reference").eq("id", a.data.id).single(); assert.ifError(expired.error); assert.equal(expired.data.status, "expired"); assert.equal(expired.data.staged_secret_reference, null); assert.equal((await connection()).secret_reference, activeSecret); });
  await t.test("P3A-RECONNECT-011 repeated reconnect starts", async () => { const first = await start(); const second = await start(); const old = await admin.from("gsc_oauth_attempts").select("status,staged_secret_reference").eq("state_hash", crypto.createHash("sha256").update(first.state).digest("base64url")).single(); assert.ifError(old.error); assert.equal(old.data.status, "superseded"); assert.equal(old.data.staged_secret_reference, null); assert.notEqual(first.state, second.state); assert.equal((await connection()).secret_reference, activeSecret); });
  await t.test("P3A-RECONNECT-012 failed property change preserves old property", async () => { current = await start(); assert.equal((await callback(current.state)).status, 200); const before = await gsc(); mode = "probe-wrong"; const r = await request(server, "POST", "/api/product/organic-evidence/search-console/select", token, { connection_id: connectionId, site_url: "https://example.com/shop/" }); assert.equal(r.status, 409); assert.deepEqual(await gsc(), before); assert.equal((await connection()).secret_reference, activeSecret); mode = "success"; });
  await t.test("P3A-RECONNECT-013 staging versus new reconnect start", async () => { let reached; const reachedPromise = new Promise(resolve => { reached = resolve; }); setVaultAdapterForTests({ create: async (client, value, name) => { const made = await createVaultSecretProduction(client, value, name); reached(); await new Promise(resolve => { releaseCreate = resolve; }); return made; }, remove: deleteVaultSecretProduction }); const old = activeSecret; const first = await start(); const oldCallback = callback(first.state); await reachedPromise; const second = await start(); releaseCreate(); const oldResult = await oldCallback; assert.notEqual(oldResult.status, 200); const oldRow = await admin.from("gsc_oauth_attempts").select("status,staged_secret_reference").eq("state_hash", crypto.createHash("sha256").update(first.state).digest("base64url")).single(); assert.ifError(oldRow.error); assert.equal(oldRow.data.status, "superseded"); assert.equal(oldRow.data.staged_secret_reference, null); assert.equal((await connection()).secret_reference, old); assert.notEqual(first.state, second.state); setVaultAdapterForTests(undefined); });
});
