import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { loadPrivateConfig, validateManifest, validatePrivatePricing, validateBatchStates, isSuccessfulEvaluationResponse, createRecoveryDispatchGuard } from "../scripts/validation/v1-05-streetkingz-codex-off-recovery.mjs";

const manifest = extra => ({ schema_version: 1, actual_evidence_copy: true, original_run_state_copied: true, model: "gpt-5.6-sol", reasoning_effort: "medium", interpretation_version: "v1-05-interpretation-7", instruction_version: "v1-05-slice-b-instructions-6", authorization_baseline_dispatched_requests: 1, allowed_batch_indexes: [3, 4], max_additional_requests: 2, max_completion_tokens: 8000, deadline_ms: 180000, known_cost_usd: 0, reserved_unknown_cost_usd: 0, cumulative_upper_bound_usd: 0, original_unknown_outcome: true, original_request_count: 5, ...extra });
const pricing = { input_per_million_tokens_usd: 4, output_per_million_tokens_usd: 20 };

test("private config is required and never loaded from .env", () => { assert.throws(() => loadPrivateConfig("/definitely/not/a/private/config.json"), /RECOVERY_PRIVATE_CONFIG_REQUIRED/); });
test("manifest binds the exact recovery model, baseline and two-batch scope", () => { assert.equal(validateManifest(manifest()).authorization_baseline_dispatched_requests, 1); assert.equal(validateManifest(manifest()).max_additional_requests, 2); assert.throws(() => validateManifest(manifest({ model: "other" })), /INCOMPATIBLE/); assert.throws(() => validateManifest(manifest({ reserved_unknown_cost_usd: -1 })), /COST_RESERVATION/); });
test("recovery guard reserves before dispatch and blocks budget exhaustion", async () => { const state = { dispatched_requests: 0, actual_known_cost_usd: 0, cost_status: "calculated_from_explicit_configuration", remaining_request_bounds_usd: [0, 0] }; const writes = []; const guard = createRecoveryDispatchGuard({ state, manifest: manifest({ known_cost_usd: 4.99, reserved_unknown_cost_usd: 0 }), pricing, writeState: s => writes.push({ ...s }) }); await assert.rejects(() => guard({ model: "gpt-5.6-sol", messages: [{ role: "user", content: "x" }], response_format: {} }), /GLOBAL_RECOVERY_COST_BOUND/); assert.equal(state.dispatched_requests, 0); assert.equal(writes.length, 0); });
test("recovery guard consumes only additional requests after its baseline", async () => { const state = { dispatched_requests: 1, actual_known_cost_usd: 0, cost_status: "calculated_from_explicit_configuration", remaining_request_bounds_usd: [0, 0] }; const writes = []; const guard = createRecoveryDispatchGuard({ state, manifest: manifest(), pricing, writeState: s => writes.push({ ...s }) }); assert.equal(guard.additionalConsumed(), 0); await guard({ model: "gpt-5.6-sol", messages: [], response_format: {} }); assert.equal(state.dispatched_requests, 2); assert.equal(guard.additionalConsumed(), 1); await guard({ model: "gpt-5.6-sol", messages: [], response_format: {} }); assert.equal(state.dispatched_requests, 3); assert.equal(guard.additionalConsumed(), 2); await assert.rejects(() => guard({ model: "gpt-5.6-sol", messages: [], response_format: {} }), /GLOBAL_RECOVERY_REQUEST_BOUND/); assert.equal(guard.absoluteCeiling, 3); assert.equal(writes.length, 2); });
test("unknown outcome fails closed", async () => { const state = { dispatched_requests: 0, actual_known_cost_usd: 0, cost_status: "unknown", remaining_request_bounds_usd: [] }; const guard = createRecoveryDispatchGuard({ state, manifest: manifest(), pricing, writeState: () => {} }); await assert.rejects(() => guard({ model: "gpt-5.6-sol", messages: [], response_format: {} }), /GLOBAL_RECOVERY_COST_UNKNOWN/); });
test("dispatched reservation is retained until known usage is reconciled", async () => { const state = { dispatched_requests: 0, actual_known_cost_usd: 0, cost_status: "calculated_from_explicit_configuration", remaining_request_bounds_usd: [0] }; const writes = []; const guard = createRecoveryDispatchGuard({ state, manifest: manifest(), pricing, writeState: s => writes.push(JSON.parse(JSON.stringify(s))) }); const bound = await guard({ model: "gpt-5.6-sol", messages: [], response_format: {} }); assert.equal(state.pending_reservations.length, 1); assert.equal(state.pending_reservations[0], bound.maximum_request_cost_usd); guard.reconcileKnown({ inputTokens: 1000, outputTokens: 500 }); assert.equal(state.pending_reservations.length, 0); assert.equal(state.actual_known_cost_usd, 0.014); assert.equal(writes.length, 2); });
test("unknown post-dispatch outcome keeps exposure and blocks later dispatch", async () => { const state = { dispatched_requests: 0, actual_known_cost_usd: 0, cost_status: "calculated_from_explicit_configuration", remaining_request_bounds_usd: [0] }; const guard = createRecoveryDispatchGuard({ state, manifest: manifest(), pricing, writeState: () => {} }); await guard({ model: "gpt-5.6-sol", messages: [], response_format: {} }); guard.reconcileUnknown(); assert.equal(state.pending_reservations.length, 1); await assert.rejects(() => guard({ model: "gpt-5.6-sol", messages: [], response_format: {} }), /GLOBAL_RECOVERY_COST_UNKNOWN/); });
test("read validation permits completed recovery batches while run validation remains strict", () => { const batches = [0, 1, 2, 3, 4].map(batch_index => ({ batch_index, state: "complete", request_attempts: 1 })); assert.equal(validateBatchStates(batches, "read"), true); assert.throws(() => validateBatchStates(batches, "run"), /UNFINISHED/); });
test("all five complete batches are valid for cache-only resume", () => { const batches = [0, 1, 2, 3, 4].map(batch_index => ({ batch_index, state: "complete", request_attempts: batch_index === 3 ? 2 : 1 })); assert.equal(validateBatchStates(batches, "resume"), true); assert.equal(validateBatchStates(batches, "prepare"), true); assert.throws(() => validateBatchStates(batches.map(batch => batch.batch_index === 4 ? { ...batch, state: "pending", request_attempts: 0 } : batch), "resume"), /ALL_COMPLETE/); });
test("all-complete preparation has explicit zero future-bound semantics", () => { const source = fs.readFileSync("scripts/validation/v1-05-streetkingz-codex-off-recovery.mjs", "utf8"); assert.match(source, /const expectedBounds = actualBounds\.length \?/); assert.match(source, /: \[\];/); });
test("cache-only resume is explicit and hard-blocks provider dispatch", () => { const source = fs.readFileSync("scripts/validation/v1-05-streetkingz-codex-off-recovery.mjs", "utf8"); assert.match(source, /process\.argv\.includes\("--resume"\)/); assert.match(source, /OUTBOUND_PROVIDER_BLOCKED/); assert.match(source, /provider_calls_this_run/); });
test("resume accepts only the two valid evaluation success contracts", () => { assert.equal(isSuccessfulEvaluationResponse({ status: 200, body: { evaluation: { state: "interpretation_complete" }, reused: true } }), true); assert.equal(isSuccessfulEvaluationResponse({ status: 201, body: { evaluation: { state: "interpretation_complete" } } }), true); for (const response of [{ status: 200, body: { evaluation: { state: "interpretation_complete" } } }, { status: 200, body: { evaluation: { state: "failed" }, reused: true } }, { status: 201, body: { evaluation: { state: "failed" } } }, { status: 202, body: { evaluation: { state: "interpretation_complete" }, reused: true } }]) assert.equal(isSuccessfulEvaluationResponse(response), false); });
test("run validation preserves successful batch four and requires only batch five", () => { const batches = [0, 1, 2].map(batch_index => ({ batch_index, state: "complete", request_attempts: 1 })).concat([{ batch_index: 3, state: "complete", request_attempts: 2 }, { batch_index: 4, state: "pending", request_attempts: 0 }]); assert.equal(validateBatchStates(batches, "run"), true); });
test("recovery preflight rejects before reservation or provider claim", () => { const state = { dispatched_requests: 3, actual_known_cost_usd: 0, cost_status: "calculated_from_explicit_configuration", remaining_request_bounds_usd: [] }; const writes = []; const guard = createRecoveryDispatchGuard({ state, manifest: manifest(), pricing, writeState: s => writes.push(s) }); assert.throws(() => guard.preflight({ model: "gpt-5.6-sol", messages: [], response_format: {} }), /GLOBAL_RECOVERY_REQUEST_BOUND/); assert.equal(state.dispatched_requests, 3); assert.equal(writes.length, 0); });
test("pricing is self-contained and does not require parent shell pricing", () => { assert.deepEqual(validatePrivatePricing({ "gpt-5.6-sol": pricing }), pricing); assert.throws(() => validatePrivatePricing({}, "gpt-5.6-sol"), /PRICING_INVALID/); });
