import test from "node:test";
import assert from "node:assert/strict";
import crypto from "node:crypto";
import http from "node:http";
import express from "express";
import { createClient } from "@supabase/supabase-js";
import route from "../routes/googleSearchConsole.js";
import { setGoogleSearchConsoleTransportFactory } from "../product-kernel/googleSearchConsoleOAuth.js";
import { ProductError } from "../product-kernel/errors.js";

const enabled = process.env.V1_04_P3A_INTEGRATION === "1";
const required = name => process.env[name] || (() => { throw new Error(`${name} required`); })();
const request = (server, method, path, token, body) => new Promise((resolve, reject) => {
  const headers = { "content-type": "application/json" }; if (token) headers.authorization = `Bearer ${token}`;
  const req = http.request({ hostname: "127.0.0.1", port: server.address().port, method, path, headers }, res => { let text = ""; res.on("data", c => { text += c; }); res.on("end", () => { let body = null; try { body = text ? JSON.parse(text) : null; } catch {} resolve({ status: res.statusCode, body, text }); }); });
  req.on("error", reject); if (body) req.write(JSON.stringify(body)); req.end();
});

test("P3-A connection lifecycle and evidence-preservation matrix", { skip: !enabled }, async t => {
  const url = required("SUPABASE_URL"), publishable = required("SUPABASE_PUBLISHABLE_KEY"), service = required("SUPABASE_SERVICE_ROLE_KEY");
  const admin = createClient(url, service, { auth: { persistSession: false } });
  const email = `v104-p3a-${crypto.randomUUID()}@local.test`, password = `${crypto.randomUUID()}!Aa9`;
  const created = await admin.auth.admin.createUser({ email, password, email_confirm: true }); assert.ifError(created.error); const userId = created.data.user.id;
  t.after(async () => { setGoogleSearchConsoleTransportFactory(undefined); await admin.auth.admin.deleteUser(userId); });
  const login = createClient(url, publishable, { auth: { persistSession: false } }); const signed = await login.auth.signInWithPassword({ email, password }); assert.ifError(signed.error); const token = signed.data.session.access_token;
  const caller = createClient(url, publishable, { global: { headers: { authorization: `Bearer ${token}` } }, auth: { persistSession: false } });
  const account = await caller.rpc("product_create_account", { p_correlation_id: crypto.randomUUID() }); assert.ifError(account.error);
  const business = await caller.rpc("product_create_business", { p_name: "P3-A synthetic lifecycle", p_platform: "woocommerce", p_correlation_id: crypto.randomUUID() }); assert.ifError(business.error);
  const woo = await caller.rpc("product_create_connection", { p_provider_type: "woocommerce", p_correlation_id: crypto.randomUUID() }); assert.ifError(woo.error);
  const accountRow = await admin.from("accounts").select("id").eq("auth_user_id", userId).single(); assert.ifError(accountRow.error);
  const wooAttemptUser = `p3a-woo-${crypto.randomUUID()}`;
  const wooAttempt = await admin.rpc("woo_create_auth_attempt", { p_user_id: wooAttemptUser, p_account_id: accountRow.data.id, p_business_id: business.data.id, p_connection_id: woo.data.id, p_canonical_base_url: "https://example.com/shop/", p_expires_at: new Date(Date.now() + 60000).toISOString() }); assert.ifError(wooAttempt.error);
  assert.ifError((await admin.rpc("woo_claim_auth_attempt", { p_user_id: wooAttemptUser })).error);
  assert.ifError((await admin.rpc("woo_capture_callback", { p_attempt_id: wooAttempt.data, p_consumer_key: "synthetic-key", p_consumer_secret: "synthetic-secret", p_key_permissions: "read" })).error);
  assert.ifError((await admin.rpc("woo_complete_connection", { p_attempt_id: wooAttempt.data, p_home_url: "https://example.com/shop/", p_site_url: "https://example.com/shop/", p_version: "synthetic", p_timezone: "UTC", p_currency: "GBP", p_correlation_id: crypto.randomUUID() })).error);

  let exchangeCount = 0, mode = "success", accessBarrier = null, releaseAccess = null;
  setGoogleSearchConsoleTransportFactory(() => ({
    authorizationUrl: ({ state }) => `https://accounts.google.test/authorize?state=${state}`,
    async exchangeCode() { exchangeCount += 1; if (mode === "exchange-failure") { const e = new Error("synthetic exchange failure"); e.code = "GSC_TOKEN_EXCHANGE_FAILED"; throw e; } if (mode === "denied") throw new Error("not used"); return { refresh_token: `synthetic-refresh-${exchangeCount}`, scope: "https://www.googleapis.com/auth/webmasters.readonly" }; },
    async accessToken() { if (accessBarrier) { accessBarrier(); await new Promise(resolve => { releaseAccess = resolve; }); } if (mode === "invalid-grant") { const e = new Error("synthetic provider denial"); e.code = "GSC_REAUTH_REQUIRED"; throw e; } return "synthetic-access"; },
    async sitesList() { if (mode === "list-failure") throw new ProductError("GSC_PROVIDER_ERROR", "Synthetic provider failure.", 502); return { siteEntry: [{ siteUrl: "https://example.com/shop/", permissionLevel: "siteOwner" }, { siteUrl: "sc-domain:example.com", permissionLevel: "siteFullUser" }] }; },
    async site(_access, siteUrl) { if (mode === "probe-failure") throw new ProductError("GSC_PROPERTY_INVALID", "Synthetic property failure.", 409); if (mode === "probe-wrong") return { siteUrl: "https://example.com/", permissionLevel: "siteOwner" }; return { siteUrl, permissionLevel: "siteOwner" }; }
  }));
  const app = express(); app.use(express.json()); app.use(route); const server = await new Promise((resolve, reject) => { const s = app.listen(0, "127.0.0.1", () => resolve(s)); s.on("error", reject); });
  t.after(() => server.close());
  const stateFor = async () => { const r = await request(server, "POST", "/api/product/organic-evidence/search-console/connect", token, {}); assert.equal(r.status, 201, r.text); return { state: new URL(r.body.authorization_url).searchParams.get("state"), connectionId: r.body.connection.id }; };
  const callback = (state, query = "code=synthetic-code") => request(server, "GET", `/api/product/organic-evidence/search-console/callback?state=${encodeURIComponent(state)}&${query}`, null);
  const db = async (table, columns, id, column = "connection_id") => { const r = await admin.from(table).select(columns).eq(column, id).single(); assert.ifError(r.error); return r.data; };
  const status = async id => request(server, "GET", `/api/product/organic-evidence/search-console/status?connection_id=${id}`, token);

  let connectionId, activeSecret, sourceId, runId, evidenceAsOf;
  await t.test("P3A-STATE-001 initial start", async () => { const s = await stateFor(); connectionId = s.connectionId; const c = await db("connections", "status,consent_state,secret_reference,disconnected_at", connectionId, "id"); assert.equal(c.status, "pending"); assert.equal(c.secret_reference, null); assert.equal((await admin.from("organic_evidence_sources").select("id").eq("connection_id", connectionId)).data.length, 0); assert.equal((await status(connectionId)).body.connection_state, "pending"); });
  await t.test("P3A-STATE-002 callback awaiting property", async () => { const s = await callback("not-a-real-state"); assert.equal(s.status, 400); });
  // Obtain the browser-visible state only from the real start response for the valid callback.
  let pending = await stateFor(); connectionId = pending.connectionId; assert.equal((await callback(pending.state)).status, 200);
  await t.test("P3A-STATE-002 awaiting property durable state", async () => { const g = await db("gsc_connections", "connection_state,selected_site_url", connectionId); assert.equal(g.connection_state, "awaiting_property"); assert.equal(g.selected_site_url, null); const a = await admin.from("gsc_oauth_attempts").select("status,staged_secret_reference").eq("connection_id", connectionId).eq("status", "processing").single(); assert.ifError(a.error); assert.ok(a.data.staged_secret_reference); assert.equal((await db("connections", "secret_reference", connectionId, "id")).secret_reference, null); });
  await t.test("P3A-STATE-003 first activation", async () => { const selected = await request(server, "POST", "/api/product/organic-evidence/search-console/select", token, { connection_id: connectionId, site_url: "https://example.com/shop/" }); assert.equal(selected.status, 200, selected.text); const c = await db("connections", "status,consent_state,secret_reference,disconnected_at", connectionId, "id"); activeSecret = c.secret_reference; assert.equal(c.status, "connected"); assert.equal(c.consent_state, "granted"); assert.ok(activeSecret); assert.equal(c.disconnected_at, null); const g = await db("gsc_connections", "connection_state,selected_site_url", connectionId); assert.equal(g.connection_state, "connected"); assert.equal(g.selected_site_url, "https://example.com/shop/"); const source = await db("organic_evidence_sources", "id,evidence_state,current_complete_run", connectionId); sourceId = source.id; assert.equal(source.evidence_state, "never_collected"); assert.equal(source.current_complete_run, null); });
  await t.test("P3A-STATE-004 first authorization failure remains retryable", async () => { const s = await stateFor(); const denied = await callback(s.state, "error=access_denied&error_description=synthetic"); assert.equal(denied.status, 409); assert.equal(denied.body.error.code, "GSC_AUTH_DENIED"); const a = await admin.from("gsc_oauth_attempts").select("status,staged_secret_reference").eq("state_hash", crypto.createHash("sha256").update(s.state).digest("base64url")).single(); assert.ifError(a.error); assert.equal(a.data.status, "failed"); assert.equal(a.data.staged_secret_reference, null); assert.equal((await db("connections", "secret_reference", connectionId, "id")).secret_reference, activeSecret); });

  await t.test("P3A-RECONNECT-001/002 start and staged replacement preserve active state", async () => { pending = await stateFor(); const before = await db("connections", "secret_reference,status", connectionId, "id"); assert.equal(before.secret_reference, activeSecret); assert.equal(before.status, "connected"); assert.equal((await callback(pending.state)).status, 200); const staged = await admin.from("gsc_oauth_attempts").select("staged_secret_reference").eq("connection_id", connectionId).eq("status", "processing").single(); assert.ifError(staged.error); assert.ok(staged.data.staged_secret_reference); assert.equal((await db("connections", "secret_reference", connectionId, "id")).secret_reference, activeSecret); });
  await t.test("P3A-RECONNECT-003 same property replacement preserves LKG", async () => { const selected = await request(server, "POST", "/api/product/organic-evidence/search-console/select", token, { connection_id: connectionId, site_url: "https://example.com/shop/" }); assert.equal(selected.status, 200, selected.text); const current = await db("connections", "secret_reference,status,disconnected_at", connectionId, "id"); assert.notEqual(current.secret_reference, activeSecret); activeSecret = current.secret_reference; const run = await admin.rpc("organic_begin_run", { p_source_id: sourceId, p_retrieved_at: new Date().toISOString() }); assert.ifError(run.error); runId = run.data.id; evidenceAsOf = "2026-09-01T12:00:00Z"; assert.ifError((await admin.rpc("organic_finish_run", { p_run_id: runId, p_state: "complete", p_completeness_state: "complete", p_evidence_as_of: evidenceAsOf })).error); const after = await db("organic_evidence_sources", "evidence_state,current_complete_run,evidence_as_of", sourceId, "id"); assert.equal(after.evidence_state, "complete"); assert.equal(after.current_complete_run, runId); assert.equal(new Date(after.evidence_as_of).toISOString(), new Date(evidenceAsOf).toISOString()); });
  await t.test("P3A-RECONNECT-004 different property resets current view but preserves history", async () => { pending = await stateFor(); assert.equal((await callback(pending.state)).status, 200); const selected = await request(server, "POST", "/api/product/organic-evidence/search-console/select", token, { connection_id: connectionId, site_url: "sc-domain:example.com" }); assert.equal(selected.status, 200, selected.text); const g = await db("gsc_connections", "selected_site_url,property_type", connectionId); assert.equal(g.selected_site_url, "sc-domain:example.com"); assert.equal(g.property_type, "domain"); activeSecret = (await db("connections", "secret_reference", connectionId, "id")).secret_reference; const source = await db("organic_evidence_sources", "evidence_state,current_complete_run,evidence_as_of", sourceId, "id"); assert.equal(source.evidence_state, "never_collected"); assert.equal(source.current_complete_run, null); assert.equal(source.evidence_as_of, null); assert.equal((await admin.from("organic_evidence_runs").select("id").eq("id", runId)).data.length, 1); });
  await t.test("P3A-RECONNECT-005/006/007/008 failed replacement preserves active property and LKG", async () => { const oldSecret = activeSecret; const oldProperty = (await db("gsc_connections", "selected_site_url", connectionId)).selected_site_url; for (const [name, query, expected] of [["denial", "error=access_denied", "GSC_AUTH_DENIED"], ["exchange", "code=synthetic-code", "GSC_TOKEN_EXCHANGE_FAILED"], ["probe", "code=synthetic-code", "GSC_PROPERTY_INVALID"]]) { const s = await stateFor(); mode = name === "denial" ? "success" : name === "exchange" ? "exchange-failure" : "probe-failure"; const r = await callback(s.state, query); if (name !== "probe") { assert.equal(r.status, 409, `${name}: ${r.text}`); assert.equal(r.body.error.code, expected); } else { assert.equal(r.status, 200, `${name}: ${r.text}`); const p = await request(server, "POST", "/api/product/organic-evidence/search-console/select", token, { connection_id: connectionId, site_url: "https://example.com/shop/" }); assert.equal(p.status, 409, p.text); } assert.equal((await db("connections", "secret_reference", connectionId, "id")).secret_reference, oldSecret); assert.equal((await db("gsc_connections", "selected_site_url", connectionId)).selected_site_url, oldProperty); } mode = "success"; });
  await t.test("P3A-RECONNECT-009/010/011/012 expiry and repeated starts preserve old state", async () => { const oldSecret = activeSecret; const first = await stateFor(); const second = await stateFor(); assert.notEqual(first.state, second.state); const oldHash = crypto.createHash("sha256").update(first.state).digest("base64url"); const old = await admin.from("gsc_oauth_attempts").select("status,staged_secret_reference").eq("state_hash", oldHash).single(); assert.ifError(old.error); assert.equal(old.data.status, "superseded"); assert.equal(old.data.staged_secret_reference, null); assert.equal((await db("connections", "secret_reference", connectionId, "id")).secret_reference, oldSecret); });

  await t.test("P3A-REAUTH-001/002 active invalid_grant persists safely", async () => { const started = await admin.rpc("organic_begin_run", { p_source_id: sourceId, p_retrieved_at: new Date().toISOString() }); assert.ifError(started.error); runId = started.data.id; evidenceAsOf = "2026-09-01T12:00:00Z"; assert.ifError((await admin.rpc("organic_finish_run", { p_run_id: runId, p_state: "complete", p_completeness_state: "complete", p_evidence_as_of: evidenceAsOf })).error); mode = "invalid-grant"; const r = await request(server, "POST", "/api/product/organic-evidence/search-console/reauth-check", token, { connection_id: connectionId }); assert.equal(r.status, 409); assert.equal(r.body.error.code, "GSC_REAUTH_REQUIRED"); assert.doesNotMatch(r.text, /synthetic provider denial|synthetic-refresh|secret_reference/); const s = await status(connectionId); assert.equal(s.body.connection_state, "reauthentication_required"); assert.equal(s.body.has_current_complete_evidence, true); assert.equal(new Date(s.body.evidence_as_of).toISOString(), new Date(evidenceAsOf).toISOString()); mode = "success"; });
  await t.test("P3A-REAUTH-003/004/005/006 transient and missing credential handling is bounded", async () => { mode = "success"; const noRef = await admin.from("connections").update({ secret_reference: null, status: "connected", consent_state: "granted" }).eq("id", connectionId); assert.ifError(noRef.error); const r = await request(server, "POST", "/api/product/organic-evidence/search-console/reauth-check", token, { connection_id: connectionId }); assert.equal(r.status, 409); assert.equal(r.body.error.code, "GSC_REAUTH_REQUIRED"); assert.equal((await status(connectionId)).body.connection_state, "reauthentication_required"); });
  await t.test("P3A-DISCONNECT-001/005 LKG disconnect is idempotent and preserves run", async () => { const r = await request(server, "POST", "/api/product/organic-evidence/search-console/disconnect", token, { connection_id: connectionId }); assert.equal(r.status, 200, r.text); const s = await status(connectionId); assert.equal(s.body.connection_state, "disconnected"); assert.equal(s.body.evidence_state, "stale"); assert.equal(s.body.has_current_complete_evidence, true); assert.equal(new Date(s.body.evidence_as_of).toISOString(), new Date(evidenceAsOf).toISOString()); assert.equal((await db("connections", "secret_reference,consent_state,status", connectionId, "id")).secret_reference, null); const again = await request(server, "POST", "/api/product/organic-evidence/search-console/disconnect", token, { connection_id: connectionId }); assert.equal(again.status, 200, again.text); assert.equal((await db("organic_evidence_sources", "current_complete_run", sourceId, "id")).current_complete_run, runId); });
  await t.test("P3A-DISCONNECT-006 reconnect after disconnect clears contradictory marker", async () => { mode = "success"; const s = await stateFor(); assert.equal((await callback(s.state)).status, 200); const selected = await request(server, "POST", "/api/product/organic-evidence/search-console/select", token, { connection_id: connectionId, site_url: "sc-domain:example.com" }); assert.equal(selected.status, 200, selected.text); const c = await db("connections", "status,consent_state,disconnected_at", connectionId, "id"); assert.equal(c.status, "connected"); assert.equal(c.consent_state, "granted"); assert.equal(c.disconnected_at, null); const source = await db("organic_evidence_sources", "evidence_state,current_complete_run", sourceId, "id"); assert.equal(source.evidence_state, "stale"); assert.equal(source.current_complete_run, runId); });
  await t.test("P3A-REAUTH-007/008 reconnect remains possible from reauthentication state", async () => { const s = await stateFor(); assert.equal((await callback(s.state)).status, 200); const selected = await request(server, "POST", "/api/product/organic-evidence/search-console/select", token, { connection_id: connectionId, site_url: "https://example.com/shop/" }); assert.equal(selected.status, 200, selected.text); assert.equal((await status(connectionId)).body.connection_state, "connected"); });
  await t.test("P3A-REAUTH-009/010 stale health result cannot overwrite newer lifecycle", async () => { mode = "invalid-grant"; let reached; accessBarrier = () => { reached?.(); }; const reachedPromise = new Promise(resolve => { reached = resolve; }); const health = request(server, "POST", "/api/product/organic-evidence/search-console/reauth-check", token, { connection_id: connectionId }); await reachedPromise; const disconnected = await request(server, "POST", "/api/product/organic-evidence/search-console/disconnect", token, { connection_id: connectionId }); assert.equal(disconnected.status, 200); releaseAccess?.(); const healthResult = await health; assert.equal(healthResult.status, 200); assert.equal(healthResult.body.status, "disconnected"); assert.equal((await status(connectionId)).body.connection_state, "disconnected"); accessBarrier = null; releaseAccess = null; mode = "success"; });
});
