import test from "node:test";
import assert from "node:assert/strict";
import http from "node:http";
import crypto from "node:crypto";
import app from "../app.js";
import { createV104B1AcceptanceApp, assertV104B1AcceptanceEnvironment } from "../scripts/runV104B1Acceptance.js";
import { isLoopbackPeer } from "../routes/v1-04B1Acceptance.js";
import { setGoogleSearchConsoleTransportFactory } from "../product-kernel/googleSearchConsoleOAuth.js";
import { setV104B1AcceptanceProvisioningHookForTests } from "../routes/v1-04B1Acceptance.js";

const enabled = process.env.V1_04_P3B_HARNESS_INTEGRATION === "1";
const must = name => process.env[name] || (() => { throw new Error(`${name} required`); })();
const request = (server, method, path, headers = {}, body) => new Promise((resolve, reject) => { const req = http.request({ hostname: "127.0.0.1", port: server.address().port, method, path, headers: { ...(body ? { "content-type": "application/json" } : {}), ...headers } }, res => { let text = ""; res.on("data", chunk => { text += chunk; }); res.on("end", () => { let parsed = null; try { parsed = text ? JSON.parse(text) : null; } catch {} resolve({ status: res.statusCode, headers: res.headers, text, body: parsed }); }); }); req.on("error", reject); if (body) req.write(JSON.stringify(body)); req.end(); });
const listen = target => new Promise((resolve, reject) => { const server = target.listen(0, "127.0.0.1", () => resolve(server)); server.once("error", reject); });

test("P3-B acceptance-surface HTTP matrix", { skip: !enabled }, async t => {
  const url = must("SUPABASE_URL"), key = must("SUPABASE_PUBLISHABLE_KEY"), service = must("SUPABASE_SERVICE_ROLE_KEY");
  const env = { V1_04_B1_ACCEPTANCE: "1", NODE_ENV: "test", SUPABASE_URL: url, SUPABASE_PUBLISHABLE_KEY: key, SUPABASE_SERVICE_ROLE_KEY: service };
  setGoogleSearchConsoleTransportFactory(() => ({ authorizationUrl: ({ state }) => `https://accounts.google.test/authorize?state=${state}`, exchangeCode: async () => ({ refresh_token: "synthetic-harness-refresh", scope: "https://www.googleapis.com/auth/webmasters.readonly" }), accessToken: async () => "synthetic-harness-access", sitesList: async () => ({ siteEntry: [{ siteUrl: "https://journey.example/shop/", permissionLevel: "siteOwner" }] }), site: async (_token, siteUrl) => ({ siteUrl, permissionLevel: "siteOwner" }) }));
  const normal = await listen(app); const acceptance = await listen(createV104B1AcceptanceApp({ env, bootstrapToken: "synthetic-bootstrap" }));
  const host = `127.0.0.1:${acceptance.address().port}`;
  const makeSession = async site => { const r = await request(acceptance, "POST", "/internal/v1-04/session", { host, "x-v1-04-bootstrap": "synthetic-bootstrap" }, { canonical_base_url: site }); assert.equal(r.status, 200, JSON.stringify(r.body)); return r.body.access_token; };
  const admin = (await import("@supabase/supabase-js")).createClient(url, service, { auth: { persistSession: false } });
  const identity = async token => (await admin.auth.getUser(token)).data.user;
  const inventory = async userId => {
    const account = await admin.from("accounts").select("id").eq("auth_user_id", userId).maybeSingle();
    const businesses = account.data ? await admin.from("businesses").select("id").eq("account_id", account.data.id) : { data: [] };
    const businessIds = (businesses.data || []).map(row => row.id);
    const connections = businessIds.length ? await admin.from("connections").select("id,business_id,secret_reference").in("business_id", businessIds) : { data: [] };
    const connectionIds = (connections.data || []).map(row => row.id);
    const stores = connectionIds.length ? await admin.from("commerce_stores").select("id,connection_id").in("connection_id", connectionIds) : { data: [] };
    const wooAttempts = connectionIds.length ? await admin.from("woocommerce_auth_attempts").select("id,connection_id,credential_reference").in("connection_id", connectionIds) : { data: [] };
    const gscRows = connectionIds.length ? await admin.from("gsc_connections").select("connection_id").in("connection_id", connectionIds) : { data: [] };
    const gscConnectionIds = (gscRows.data || []).map(row => row.connection_id);
    const gscAttempts = connectionIds.length ? await admin.from("gsc_oauth_attempts").select("id,connection_id,staged_secret_reference").in("connection_id", connectionIds) : { data: [] };
    const sources = businessIds.length ? await admin.from("organic_evidence_sources").select("id,business_id,current_complete_run").in("business_id", businessIds) : { data: [] };
    const sourceIds = (sources.data || []).map(row => row.id);
    const runs = sourceIds.length ? await admin.from("organic_evidence_runs").select("id,source_id").in("source_id", sourceIds) : { data: [] };
    const refs = [...(connections.data || []).map(row => row.secret_reference), ...(wooAttempts.data || []).map(row => row.credential_reference), ...(gscAttempts.data || []).map(row => row.staged_secret_reference)].filter(Boolean);
    return { accountId: account.data?.id, businessIds, connectionIds, storeIds: (stores.data || []).map(row => row.id), wooAttemptIds: (wooAttempts.data || []).map(row => row.id), gscConnectionIds, gscAttemptIds: (gscAttempts.data || []).map(row => row.id), sourceIds, runIds: (runs.data || []).map(row => row.id), refs: [...new Set(refs)] };
  };
  const assertVaultPresent = async snapshot => { for (const ref of snapshot.refs) { const value = await admin.rpc("vault_read_secret", { secret_id: ref }); assert.equal(value.error, null); assert.notEqual(value.data, null); } };
  const absentInventory = async snapshot => { assert.equal((await admin.auth.admin.getUserById(snapshot.userId)).error?.status, 404); assert.equal((await admin.from("accounts").select("id").eq("id", snapshot.accountId).maybeSingle()).data, null); for (const [table, ids, column] of [["businesses", snapshot.businessIds, "id"], ["connections", snapshot.connectionIds, "id"], ["commerce_stores", snapshot.storeIds, "id"], ["woocommerce_auth_attempts", snapshot.wooAttemptIds, "id"], ["gsc_connections", snapshot.gscConnectionIds, "connection_id"], ["gsc_oauth_attempts", snapshot.gscAttemptIds, "id"], ["organic_evidence_sources", snapshot.sourceIds, "id"], ["organic_evidence_runs", snapshot.runIds, "id"]]) if (ids.length) assert.equal((await admin.from(table).select(column).in(column, ids)).data.length, 0, table); for (const ref of snapshot.refs) { const value = await admin.rpc("vault_read_secret", { secret_id: ref }); assert.ok(value.error || value.data === null || value.data === undefined); } };
  const cleanup = async token => request(acceptance, "POST", "/internal/v1-04/session/cleanup", { host, "x-v1-04-bootstrap": "synthetic-bootstrap", authorization: `Bearer ${token}` }, {});
  const completeGsc = async (token, site) => { const auth = { host, authorization: `Bearer ${token}` }; const started = await request(acceptance, "POST", "/api/product/organic-evidence/search-console/connect", auth, {}); assert.equal(started.status, 201, JSON.stringify(started.body)); const authUrl = new URL(started.body.authorization_url); const callback = await request(acceptance, "GET", `/api/product/organic-evidence/search-console/callback?state=${encodeURIComponent(authUrl.searchParams.get("state"))}&code=synthetic-code`, { host }); assert.equal(callback.status, 200, JSON.stringify(callback.body)); const listed = await request(acceptance, "GET", `/api/product/organic-evidence/search-console/properties?connection_id=${started.body.connection.id}`, auth); assert.equal(listed.status, 200, JSON.stringify(listed.body)); assert.deepEqual(listed.body.properties.map(p => p.siteUrl), [site]); const selected = await request(acceptance, "POST", "/api/product/organic-evidence/search-console/select", auth, { connection_id: started.body.connection.id, site_url: site }); assert.equal(selected.status, 200, JSON.stringify(selected.body)); return started.body.connection.id; };
  t.after(async () => { setV104B1AcceptanceProvisioningHookForTests(null); setGoogleSearchConsoleTransportFactory(undefined); await new Promise(resolve => normal.close(resolve)); await new Promise(resolve => acceptance.close(resolve)); });
  const cases = [
    ["P3B-HARNESS-001 normal app exposes no V1-04 routes", async () => { for (const p of ["/internal/v1-04", "/internal/v1-04/bootstrap", "/internal/v1-04/session", "/internal/v1-04/session/cleanup", "/internal/v1-04/harness.js", "/internal/v1-04/styles.css"]) assert.equal((await request(normal, "GET", p)).status, 404); }],
    ["P3B-HARNESS-002 explicit enable flag required", async () => assert.throws(() => assertV104B1AcceptanceEnvironment({ ...env, V1_04_B1_ACCEPTANCE: "0" }), /required/)],
    ["P3B-HARNESS-003 production rejected", async () => assert.throws(() => assertV104B1AcceptanceEnvironment({ ...env, NODE_ENV: "production" }), /production/)],
    ["P3B-HARNESS-004 hosted Supabase rejected", async () => assert.throws(() => assertV104B1AcceptanceEnvironment({ ...env, SUPABASE_URL: "https://hosted.supabase.co" }), /local/)],
    ["P3B-HARNESS-005 binds loopback", async () => assert.equal(acceptance.address().address, "127.0.0.1")],
    ["P3B-HARNESS-006 local index/bootstrap journey", async () => { const index = await request(acceptance, "GET", "/internal/v1-04", { host }); assert.equal(index.status, 200); const boot = await request(acceptance, "GET", "/internal/v1-04/bootstrap", { host }); assert.equal(boot.status, 200); assert.equal(boot.body.bootstrap, "synthetic-bootstrap"); }],
    ["P3B-HARNESS-007 non-loopback peer rejected", async () => assert.equal(isLoopbackPeer("203.0.113.10"), false)],
    ["P3B-HARNESS-008 forwarded headers cannot establish trust", async () => assert.equal((await request(acceptance, "GET", "/internal/v1-04/bootstrap", { host, "x-forwarded-for": "127.0.0.1", "x-real-ip": "127.0.0.1" })).status, 200)],
    ["P3B-HARNESS-009 foreign Origin rejected", async () => assert.equal((await request(acceptance, "GET", "/internal/v1-04/bootstrap", { host, origin: "https://evil.example" })).status, 404)],
    ["P3B-HARNESS-010 foreign and incorrect Host rejected", async () => { for (const badHost of ["attacker.example", "localhost:9999", "127.0.0.1:9999", "127.0.0.1"]) assert.equal((await request(acceptance, "GET", "/internal/v1-04/bootstrap", { host: badHost })).status, 404, badHost); }],
    ["P3B-HARNESS-011 hostile preflight has no grant", async () => { const r = await request(acceptance, "OPTIONS", "/internal/v1-04/session", { host, origin: "https://evil.example", "access-control-request-method": "POST" }); assert.equal(r.status, 404); assert.equal(r.headers["access-control-allow-origin"], undefined); }],
    ["P3B-HARNESS-012 static content is bounded", async () => { const r = await request(acceptance, "GET", "/internal/v1-04/harness.js", { host }); assert.equal(r.status, 200); assert.doesNotMatch(r.text, /service.role|publishableKey|refresh_token/); }],
    ["P3B-HARNESS-013 bootstrap header vectors", async () => { for (const value of [undefined, "", "%%%%", "wrong"]) { const headers = { host }; if (value !== undefined) headers["x-v1-04-bootstrap"] = value; assert.equal((await request(acceptance, "POST", "/internal/v1-04/session", headers, {})).status, 403); } }],
    ["P3B-HARNESS-014 bootstrap is non-cacheable and recreated", async () => { const r = await request(acceptance, "GET", "/internal/v1-04/bootstrap", { host }); assert.equal(r.headers["cache-control"], "no-store"); assert.doesNotMatch(r.text, /127\.0\.0\.1|54321/); const second = await listen(createV104B1AcceptanceApp({ env })); try { const secondHost = `127.0.0.1:${second.address().port}`; const s = await request(second, "GET", "/internal/v1-04/bootstrap", { host: secondHost }); assert.equal(s.status, 200); assert.notEqual(s.body.bootstrap, r.body.bootstrap); } finally { await new Promise(resolve => second.close(resolve)); } }],
    ["P3B-HARNESS-015 safe session response", async () => { const r = await request(acceptance, "POST", "/internal/v1-04/session", { host, "x-v1-04-bootstrap": "synthetic-bootstrap" }, { canonical_base_url: "https://harness.example/shop/" }); assert.equal(r.status, 200, JSON.stringify(r.body)); assert.equal(r.headers["cache-control"], "no-store"); assert.deepEqual(Object.keys(r.body).sort(), ["access_token", "account_ready", "business_ready", "canonical_base_url", "expires_at", "site_ready"].sort()); await request(acceptance, "POST", "/internal/v1-04/session/cleanup", { host, "x-v1-04-bootstrap": "synthetic-bootstrap", authorization: `Bearer ${r.body.access_token}` }, {}); }],
    ["P3B-HARNESS-016 synthetic site provisions locally and starts GSC journey", async () => { const token = await makeSession("https://journey.example/shop/"); const user = await identity(token); const auth = { host, authorization: `Bearer ${token}` }; const started = await request(acceptance, "POST", "/api/product/organic-evidence/search-console/connect", auth, {}); assert.equal(started.status, 201, JSON.stringify(started.body)); const authUrl = new URL(started.body.authorization_url); const callback = await request(acceptance, "GET", `/api/product/organic-evidence/search-console/callback?state=${encodeURIComponent(authUrl.searchParams.get("state"))}&code=synthetic-code`, { host }); assert.equal(callback.status, 200, JSON.stringify(callback.body)); const listed = await request(acceptance, "GET", `/api/product/organic-evidence/search-console/properties?connection_id=${started.body.connection.id}`, auth); assert.equal(listed.status, 200, JSON.stringify(listed.body)); assert.deepEqual(listed.body.properties.map(p => p.siteUrl), ["https://journey.example/shop/"]); const selected = await request(acceptance, "POST", "/api/product/organic-evidence/search-console/select", auth, { connection_id: started.body.connection.id, site_url: "https://journey.example/shop/" }); assert.equal(selected.status, 200, JSON.stringify(selected.body)); assert.equal(selected.body.evidence_state, "never_collected"); assert.equal(selected.body.has_current_complete_evidence, false); const before = { ...(await inventory(user.id)), userId: user.id }; await assertVaultPresent(before); assert.equal(before.sourceIds.length, 1); assert.equal(before.runIds.length, 0); assert.equal((await cleanup(token)).status, 200); await absentInventory(before); }],
    ["P3B-HARNESS-017 partial provisioning cleanup vectors", async () => { for (const point of ["after_user_created", "after_sign_in", "after_account_created", "after_business_created", "after_woo_connection_created", "after_woo_attempt_created", "after_woo_credential_captured", "after_woo_connection_completed", "before_session_response"]) { let snapshot; setV104B1AcceptanceProvisioningHookForTests(async (observed, context) => { if (observed === point) { snapshot = { ...(await inventory(context.userId)), userId: context.userId }; await assertVaultPresent(snapshot); throw new Error("synthetic provisioning failure"); } }); const r = await request(acceptance, "POST", "/internal/v1-04/session", { host, "x-v1-04-bootstrap": "synthetic-bootstrap" }, { canonical_base_url: `https://failure-${point.replaceAll("_", "-")}.example/shop/` }); assert.equal(r.status, 503, `${point}: ${JSON.stringify(r.body)}`); assert.ok(snapshot); await absentInventory(snapshot); setV104B1AcceptanceProvisioningHookForTests(null); } setV104B1AcceptanceProvisioningHookForTests(null); }],
    ["P3B-HARNESS-018 cleanup requires bootstrap and bearer vectors", async () => { assert.equal((await request(acceptance, "POST", "/internal/v1-04/session/cleanup", { host }, {})).status, 403); assert.equal((await request(acceptance, "POST", "/internal/v1-04/session/cleanup", { host, "x-v1-04-bootstrap": "wrong", authorization: "Bearer bad" }, {})).status, 403); assert.equal((await request(acceptance, "POST", "/internal/v1-04/session/cleanup", { host, "x-v1-04-bootstrap": "synthetic-bootstrap", authorization: "Bearer bad" }, {})).status, 401); const token = await makeSession("https://cleanup-vector.example/shop/"); const cleaned = await cleanup(token); assert.equal(cleaned.status, 200, JSON.stringify(cleaned.body)); }],
    ["P3B-HARNESS-019 normal user cannot cleanup", async () => { const normalAdmin = (await import("@supabase/supabase-js")).createClient(url, service, { auth: { persistSession: false } }); const email = `p3b-normal-${crypto.randomUUID()}@local.test`; const password = `${crypto.randomUUID()}!Aa9`; const created = await normalAdmin.auth.admin.createUser({ email, password, email_confirm: true }); assert.equal(created.error, null); const login = (await import("@supabase/supabase-js")).createClient(url, key, { auth: { persistSession: false } }); const signed = await login.auth.signInWithPassword({ email, password }); assert.equal(signed.error, null); assert.ok(signed.data.session?.access_token); const update = await login.auth.updateUser({ data: { app_metadata: { v104_b1_acceptance: true } } }); assert.ok(update.error || update.data.user?.app_metadata?.v104_b1_acceptance !== true); const r = await request(acceptance, "POST", "/internal/v1-04/session/cleanup", { host, "x-v1-04-bootstrap": "synthetic-bootstrap", authorization: `Bearer ${signed.data.session.access_token}` }, {}); assert.equal(r.status, 403); assert.equal((await normalAdmin.auth.admin.getUserById(created.data.user.id)).error, null); await normalAdmin.auth.admin.deleteUser(created.data.user.id); }],
    ["P3B-HARNESS-020 sessions cannot cross-clean", async () => { const a = await makeSession("https://session-a.example/shop/"); const b = await makeSession("https://session-b.example/shop/"); const aUser = await identity(a); const bUser = await identity(b); assert.ok(aUser?.id && bUser?.id); const rejected = await request(acceptance, "POST", "/internal/v1-04/session/cleanup", { host, "x-v1-04-bootstrap": "synthetic-bootstrap", authorization: `Bearer ${a}` }, { target_user_id: bUser.id }); assert.equal(rejected.status, 400); assert.equal((await identity(a)).id, aUser.id); assert.equal((await identity(b)).id, bUser.id); assert.equal((await cleanup(a)).status, 200); assert.equal((await identity(b)).id, bUser.id); assert.equal((await cleanup(b)).status, 200); }],
    ["P3B-HARNESS-021 complete cleanup and no residue", async () => { const token = await makeSession("https://journey.example/shop/"); const control = await makeSession("https://cleanup-control.example/shop/"); const user = await identity(token); const controlUser = await identity(control); const before = { ...(await inventory(user.id)), userId: user.id }; const controlBefore = { ...(await inventory(controlUser.id)), userId: controlUser.id }; await assertVaultPresent(before); await assertVaultPresent(controlBefore); assert.ok(before.storeIds.length >= 1); assert.ok(before.wooAttemptIds.length >= 1); await completeGsc(token, "https://journey.example/shop/"); const enriched = { ...(await inventory(user.id)), userId: user.id }; await assertVaultPresent(enriched); assert.ok(enriched.gscConnectionIds.length >= 1); assert.ok(enriched.sourceIds.length >= 1); assert.equal((await cleanup(token)).status, 200); await absentInventory(enriched); assert.equal((await admin.auth.admin.getUserById(controlUser.id)).error, null); const controlAfter = await inventory(controlUser.id); assert.deepEqual(controlAfter.businessIds, controlBefore.businessIds); assert.deepEqual(controlAfter.connectionIds, controlBefore.connectionIds); assert.deepEqual(controlAfter.storeIds, controlBefore.storeIds); await assertVaultPresent(controlAfter); assert.equal((await cleanup(control)).status, 200); }],
    ["P3B-HARNESS-022 repeated cleanup is bounded", async () => { const token = await makeSession("https://repeat-cleanup.example/shop/"); const user = await identity(token); const before = { ...(await inventory(user.id)), userId: user.id }; await assertVaultPresent(before); assert.equal((await cleanup(token)).status, 200); await absentInventory(before); const repeated = await cleanup(token); assert.ok([401, 403].includes(repeated.status)); assert.doesNotMatch(repeated.text, /postgres|postgrest|vault|secret_reference/i); await absentInventory(before); }]
  ];
  for (const [name, fn] of cases) await t.test(name, fn);
});
