import test from "node:test";
import assert from "node:assert/strict";
import crypto from "node:crypto";
import { createClient } from "@supabase/supabase-js";
import app from "../app.js";

const enabled = process.env.V1_03_ACCEPTANCE_HARNESS_INTEGRATION === "1";
const required = name => process.env[name] || (() => { throw new Error(`${name} required`); })();
const call = (base, path, token, method = "GET", body) => fetch(`${base}${path}`, { method, headers: { ...(token ? { authorization: `Bearer ${token}` } : {}), ...(body === undefined ? {} : { "content-type": "application/json" }) }, body: body === undefined ? undefined : JSON.stringify(body) }).then(async response => ({ status: response.status, body: response.status === 204 ? null : await response.json() }));

test("live local harness bootstraps, snapshots, isolates, and cleans up", { skip: !enabled }, async t => {
  const url = required("SUPABASE_URL"), publishable = required("SUPABASE_PUBLISHABLE_KEY"), service = required("SUPABASE_SERVICE_ROLE_KEY"); const admin = createClient(url, service, { auth: { autoRefreshToken: false, persistSession: false } });
  const server = app.listen(0, "127.0.0.1"); t.after(() => server.close()); await new Promise(resolve => server.once("listening", resolve)); const base = `http://127.0.0.1:${server.address().port}`;
  const boot = await call(base, "/internal/v1-03/bootstrap", null, "POST", {}); assert.equal(boot.status, 200); const token = boot.body.access_token; assert.ok(token); assert.equal(Object.hasOwn(boot.body, "password"), false); assert.equal(Object.hasOwn(boot.body, "service_role_key"), false); assert.equal(Object.hasOwn(boot.body, "SUPABASE_SERVICE_ROLE_KEY"), false);
  const account = await call(base, "/api/product/account", token, "POST", {}); assert.ok([200, 201].includes(account.status)); const business = await call(base, "/api/product/business", token, "POST", { name: "Street Kingz V1-03 Acceptance", ecommerce_platform: "woocommerce" }); assert.equal(business.status, 201); const connection = await call(base, "/api/product/connections", token, "POST", { provider_type: "woocommerce" }); assert.equal(connection.status, 201); const connectionId = connection.body.connection.id;
  const user = (await admin.auth.getUser(token)).data.user; const accountRow = (await admin.from("accounts").select("id").eq("auth_user_id", user.id).single()).data; const businessRow = (await admin.from("businesses").select("id").eq("account_id", accountRow.id).single()).data;
  const attemptToken = `harness-smoke-${crypto.randomUUID()}`; const attempt = await admin.rpc("woo_create_auth_attempt", { p_user_id: attemptToken, p_account_id: accountRow.id, p_business_id: businessRow.id, p_connection_id: connectionId, p_canonical_base_url: "https://shop.example", p_expires_at: new Date(Date.now() + 60000).toISOString() }); assert.ifError(attempt.error); assert.ifError((await admin.rpc("woo_claim_auth_attempt", { p_user_id: attemptToken })).error); assert.ifError((await admin.rpc("woo_capture_callback", { p_attempt_id: attempt.data, p_consumer_key: "local-smoke-key", p_consumer_secret: "local-smoke-secret", p_key_permissions: "read" })).error); const established = await admin.rpc("woo_complete_connection", { p_attempt_id: attempt.data, p_home_url: "https://shop.example", p_site_url: "https://shop.example", p_version: "local", p_timezone: "UTC", p_currency: "GBP", p_correlation_id: crypto.randomUUID() }); assert.ifError(established.error); const store = (await admin.from("commerce_stores").select().eq("id", established.data).single()).data; assert.ok(store);
  const generation = await admin.rpc("commerce_begin_initial_sync", { p_store_id: store.id, p_correlation_id: crypto.randomUUID() }); assert.ifError(generation.error); const products = [{ source_id: 123, name: "Synthetic" }]; const order = [{ source_id: 1, source_status: "completed", recognition_state: "recognised" }]; const lines = [{ order_source_id: 1, source_line_id: 10, product_source_id: 123, total: "10.00", tax: "2.00" }]; const adjustments = [{ order_source_id: 1, adjustment_type: "refund", provider_adjustment_id: "r1", amount: "-1.00" }]; assert.ifError((await admin.rpc("commerce_stage_initial_snapshot", { p_store_id: store.id, p_generation_id: generation.data, p_products: products, p_variations: [], p_categories: [], p_links: [], p_orders: order, p_lines: lines, p_adjustments: adjustments })).error); assert.ifError((await admin.rpc("commerce_complete_initial_sync", { p_store_id: store.id, p_generation_id: generation.data })).error);
  const snapshot = await call(base, `/internal/v1-03/product-snapshot?connection_id=${connectionId}`, token); assert.equal(snapshot.status, 200); assert.deepEqual(snapshot.body.counts, { products: 1, variations: 0, categories: 0, orders: 1, lines: 1, adjustments: 1 }); assert.equal(snapshot.body.rows.length, 1); assert.doesNotMatch(JSON.stringify(snapshot.body), /secret_reference|customer|billing|shipping|email|phone/);
  const otherBoot = await call(base, "/internal/v1-03/bootstrap", null, "POST", {}); const otherAccount = await call(base, "/api/product/account", otherBoot.body.access_token, "POST", {}); assert.ok([200, 201].includes(otherAccount.status)); const denied = await call(base, `/internal/v1-03/product-snapshot?connection_id=${connectionId}`, otherBoot.body.access_token); assert.equal(denied.status, 404);
  const deleteOne = await call(base, "/api/product/account", token, "DELETE"); assert.equal(deleteOne.status, 204, JSON.stringify(deleteOne.body)); assert.equal((await call(base, "/internal/v1-03/cleanup", token, "POST", {})).status, 204); const deleteTwo = await call(base, "/api/product/account", otherBoot.body.access_token, "DELETE"); assert.equal(deleteTwo.status, 204, JSON.stringify(deleteTwo.body)); assert.equal((await call(base, "/internal/v1-03/cleanup", otherBoot.body.access_token, "POST", {})).status, 204);
});
