import test from "node:test";
import assert from "node:assert/strict";
import express from "express";
import http from "node:http";
import { ProductError, safeError } from "../product-kernel/errors.js";
import { createWooCommerceRouter } from "../routes/woocommerce.js";
import { wooCommerceRouteConfig } from "../config/productKernel.js";

const ids={account:"11111111-1111-4111-8111-111111111111",business:"22222222-2222-4222-8222-222222222222",connection:"33333333-3333-4333-8333-333333333333"};
const token="Bearer synthetic-token";
function query(row,filter){return{select(){return this},eq(key,value){if(filter&&this.row!==null&&!filter(key,value))this.row=null;return this},not(){return this},async maybeSingle(){return{data:this.row===undefined?row:this.row,error:null}}};}
function fixture({provider="woocommerce",status="pending"}={}){const calls=[],attempt={id:"44444444-4444-4444-8444-444444444444",status,connection_id:ids.connection,canonical_base_url:"https://shop.example/wp",credential_reference:"55555555-5555-4555-8555-555555555555"};const client={from(table){if(table==="accounts")return query({id:ids.account,auth_user_id:"user-1",status:"active"});if(table==="businesses")return query({id:ids.business,account_id:ids.account});if(table==="connections")return query({id:ids.connection,business_id:ids.business,provider_type:provider,status:["connected","consumed"].includes(status)?"connected":"pending",consent_state:["connected","consumed"].includes(status)?"granted":"pending"},(key,value)=>key!=="id"||value===ids.connection);throw new Error(`unexpected caller table ${table}`);}};const admin={calls,from(table){if(table!=="woocommerce_auth_attempts")throw new Error(`unexpected admin table ${table}`);return{select(){return this},eq(key,value){this.filters??={};this.filters[key]=value;return this},not(){return this},async maybeSingle(){return{data:(this.filters?.user_id&&!this.filters.user_id.startsWith("known-user"))?null:attempt,error:null}}};},rpc:async(name,args)=>{calls.push({name,args});if(name==="woo_create_auth_attempt")return{data:attempt.id,error:null};if(name==="woo_deny_auth_attempt")return{data:status==="consumed"?false:true,error:null};if(name==="vault_read_secret")return{data:'{"consumerKey":"ck","consumerSecret":"cs"}',error:null};return{data:null,error:null};}};return{client,admin,calls,attempt};}
function makeApp(options={}){const f=fixture(options);const router=createWooCommerceRouter({verifyIdentity:async()=>({authUserId:"user-1"}),callerClient:()=>f.client,privilegedClient:()=>f.admin,wooCommerceRouteConfig:()=>({productOrigin:"https://product.example",appName:"Synthetic Woo App"}),validateWooOriginWithDeadline:async value=>{if(value.includes("private"))throw new ProductError("INVALID_STORE_URL","Store URL is not allowed.",400);if(value!=="https://shop.example/wp")throw new ProductError("INVALID_STORE_URL","Store URL is invalid.",400);return{url:new URL(value),addresses:[{address:"93.184.216.34",family:4}]}},createWooAuthUrl:options=>`https://shop.example/wp/wc-auth/v1/authorize?scope=read&user_id=${options.userId}&callback_url=${encodeURIComponent(options.callbackUrl)}&return_url=${encodeURIComponent(options.returnUrl)}`,newAttemptToken:()=>"synthetic-user-token-123456789",captureWooCallback:async(_admin,payload)=>{f.calls.push({name:"capture",payload});if(["unknown-user-12345678901234567890","expired-user-12345678901234567890","replay-user-12345678901234567890","denied-user-12345678901234567890"].includes(payload.userId))throw new ProductError("AUTH_ATTEMPT_INVALID","WooCommerce authorisation attempt is invalid.",409);f.attempt.status="callback_received";return{attemptId:f.attempt.id,acknowledge:true}},verifyWooConnection:async(_admin,verifyOptions)=>{f.calls.push({name:"verify",options:verifyOptions});if(options.verifyError)throw options.verifyError;return{storeId:ids.connection}},assertEstablishedWooConnection:options.assertEstablishedWooConnection|| (async()=>{throw new ProductError("WOO_CONNECTION_STATE_MANAGED","WooCommerce connection state is not established.",409)}),establishedWooStatus:options.establishedWooStatus|| (async()=>options.status==="consumed"?"disconnected":"failed")});const app=express();app.use(router);app.use((error,req,res,next)=>{if(res.headersSent)return next(error);const safe=safeError(error,req.correlationId);res.status(safe.status).json(safe.body);});return{app,f};}
function request(server,{method="GET",path,body,raw,headers={}}){const payload=raw??(body===undefined?undefined:JSON.stringify(body));return new Promise((resolve,reject)=>{const req=http.request({hostname:"127.0.0.1",port:server.address().port,method,path,headers:{...(payload!==undefined?{"content-type":"application/json","content-length":Buffer.byteLength(payload)}:{}),...headers}},res=>{let text="";res.setEncoding("utf8");res.on("data",chunk=>text+=chunk);res.on("end",()=>resolve({status:res.statusCode,text,body:text?JSON.parse(text):null,headers:res.headers}));});req.on("error",reject);if(payload!==undefined)req.write(payload);req.end();});}
async function withServer(app,fn){const server=await new Promise((resolve,reject)=>{const s=app.listen(0,"127.0.0.1",()=>resolve(s));s.on("error",reject)});try{return await fn(server)}finally{await new Promise((resolve,reject)=>server.close(e=>e?reject(e):resolve()))}}

test("V1-03 authorize requires authentication and tenant-owned Woo connection",async()=>{const {app}=makeApp();await withServer(app,async server=>{assert.equal((await request(server,{method:"POST",path:"/api/product/woocommerce/authorize",body:{connection_id:ids.connection,store_url:"https://shop.example/wp"}})).status,401);const wrong=await request(server,{method:"POST",path:"/api/product/woocommerce/authorize",headers:{authorization:token},body:{connection_id:"99999999-9999-4999-8999-999999999999",store_url:"https://shop.example/wp"}});assert.equal(wrong.body.error.code,"CONNECTION_NOT_FOUND");});});
test("V1-03 authorize rejects non-Woo and unsafe stores",async()=>{for(const options of[{provider:"synthetic"},{provider:"woocommerce"}]){const {app}=makeApp(options);await withServer(app,async server=>{const body={connection_id:ids.connection,store_url:options.provider==="synthetic"?"https://shop.example/wp":"https://private.example/wp"};const result=await request(server,{method:"POST",path:"/api/product/woocommerce/authorize",headers:{authorization:token},body});assert.equal(result.status,400);});}});
test("V1-03 authorize returns server-controlled read-only Woo URL without internal IDs",async()=>{const {app}=makeApp();await withServer(app,async server=>{const result=await request(server,{method:"POST",path:"/api/product/woocommerce/authorize",headers:{authorization:token},body:{connection_id:ids.connection,store_url:"https://shop.example/wp"}});assert.equal(result.status,201);const url=new URL(result.body.authorization_url);assert.equal(url.searchParams.get("scope"),"read");assert.equal(url.searchParams.get("callback_url"),"https://product.example/api/product/woocommerce/callback");assert.equal(url.searchParams.get("return_url"),"https://product.example/api/product/woocommerce/return");assert.equal(result.text.includes(ids.account),false);assert.equal(result.text.includes(ids.business),false);assert.equal(result.text.includes(ids.connection),false);assert.equal(result.text.includes("55555555"),false);});});
test("V1-03 current Woo callback shape accepts numeric key_id and charset content type",async()=>{const {app,f}=makeApp();await withServer(app,async server=>{const result=await request(server,{method:"POST",path:"/api/product/woocommerce/callback",headers:{"content-type":"application/json;charset=UTF-8"},body:{key_id:1,user_id:"known-user-12345678901234567890",consumer_key:"ck_synthetic",consumer_secret:"cs_synthetic",key_permissions:"read"}});assert.equal(result.status,200);assert.equal(result.text,"");assert.equal(result.headers["cache-control"],"no-store");assert.equal(f.calls[0].name,"capture");assert.equal(f.calls[0].payload.userId,"known-user-12345678901234567890");await new Promise(resolve=>setImmediate(resolve));assert.equal(f.calls.some(call=>call.name==="verify"),false);assert.doesNotMatch(result.text,/consumer|secret|55555555/);});});
test("V1-03 Woo config rejects empty trimmed app name",()=>{assert.throws(()=>wooCommerceRouteConfig({PRODUCT_PUBLIC_ORIGIN:"https://product.example",WOOCOMMERCE_APP_NAME:"   "}));});
test("V1-03 callback parser rejects malformed, oversized, wrong type and invalid fields safely",async()=>{const {app}=makeApp();await withServer(app,async server=>{const malformed=await request(server,{method:"POST",path:"/api/product/woocommerce/callback",raw:"{\"user_id\":"});assert.equal(malformed.status,400);const wrongType=await request(server,{method:"POST",path:"/api/product/woocommerce/callback",headers:{"content-type":"text/plain"},raw:"not-json"});assert.equal(wrongType.status,400);const oversized=await request(server,{method:"POST",path:"/api/product/woocommerce/callback",body:{consumer_secret:"x".repeat(9000)}});assert.equal(oversized.status,413);const invalid=await request(server,{method:"POST",path:"/api/product/woocommerce/callback",body:{user_id:"known-user-12345678901234567890",consumer_key:"ck",consumer_secret:"cs",key_permissions:"write"}});assert.equal(invalid.status,400);assert.doesNotMatch(invalid.text,/ck|cs|secret/);});});
test("V1-03 callback rejects missing values, unknown, expired, replay and denied attempts",async()=>{const {app}=makeApp();await withServer(app,async server=>{for(const body of[{consumer_key:"ck",consumer_secret:"cs",key_permissions:"read"},{user_id:"short",consumer_key:"ck",consumer_secret:"cs",key_permissions:"read"},{user_id:"unknown-user-12345678901234567890",consumer_key:"ck",consumer_secret:"cs",key_permissions:"read"},{user_id:"expired-user-12345678901234567890",consumer_key:"ck",consumer_secret:"cs",key_permissions:"read"},{user_id:"replay-user-12345678901234567890",consumer_key:"ck",consumer_secret:"cs",key_permissions:"read"},{user_id:"denied-user-12345678901234567890",consumer_key:"ck",consumer_secret:"cs",key_permissions:"read"}]){const result=await request(server,{method:"POST",path:"/api/product/woocommerce/callback",body});assert.notEqual(result.status,200);}});});
test("V1-03 return validates bounded success and safely handles denial and unknown tokens",async()=>{const {app,f}=makeApp();await withServer(app,async server=>{const bad=await request(server,{path:"/api/product/woocommerce/return?success=2&user_id=known-user-12345678901234567890"});assert.equal(bad.status,400);const denied=await request(server,{path:"/api/product/woocommerce/return?success=0&user_id=known-user-12345678901234567890"});assert.deepEqual(denied.body,{status:"denied"});assert.equal(denied.headers["cache-control"],"no-store");assert.equal(denied.headers["referrer-policy"],"no-referrer");assert.equal(f.calls[0].name,"woo_deny_auth_attempt");const unknown=await request(server,{path:"/api/product/woocommerce/return?success=1&user_id=unknown-user-12345678901234567890"});assert.deepEqual(unknown.body,{status:"processing"});});});
test("V1-03 return success cannot connect without callback and verify requires authentication",async()=>{const {app}=makeApp();await withServer(app,async server=>{const returned=await request(server,{path:"/api/product/woocommerce/return?success=1&user_id=known-user-12345678901234567890"});assert.deepEqual(returned.body,{status:"processing"});const verify=await request(server,{method:"POST",path:"/api/product/woocommerce/verify",body:{connection_id:ids.connection}});assert.equal(verify.status,401);});});
test("V1-03 callback-before-return and return-before-callback preserve safe ordering",async()=>{const first=makeApp();await withServer(first.app,async server=>{const callback=await request(server,{method:"POST",path:"/api/product/woocommerce/callback",body:{user_id:"known-user-12345678901234567890",consumer_key:"ck",consumer_secret:"cs",key_permissions:"read"}});assert.equal(callback.status,200);const returned=await request(server,{path:"/api/product/woocommerce/return?success=1&user_id=known-user-12345678901234567890"});assert.equal(returned.body.status,"connected");});const second=makeApp();await withServer(second.app,async server=>{const returned=await request(server,{path:"/api/product/woocommerce/return?success=1&user_id=known-user-12345678901234567890"});assert.equal(returned.body.status,"processing");const callback=await request(server,{method:"POST",path:"/api/product/woocommerce/callback",body:{user_id:"known-user-12345678901234567890",consumer_key:"ck",consumer_secret:"cs",key_permissions:"read"}});assert.equal(callback.status,200);});});
test("V1-03 callback acknowledgement followed by concurrent return and verify converges safely",async()=>{const {app,f}=makeApp();await withServer(app,async server=>{const callback=await request(server,{method:"POST",path:"/api/product/woocommerce/callback",body:{key_id:1,user_id:"known-user-12345678901234567890",consumer_key:"ck",consumer_secret:"cs",key_permissions:"read"}});assert.equal(callback.status,200);const [returned,verified]=await Promise.all([request(server,{path:"/api/product/woocommerce/return?success=1&user_id=known-user-12345678901234567890"}),request(server,{method:"POST",path:"/api/product/woocommerce/verify",headers:{authorization:token},body:{connection_id:ids.connection}})]);assert.equal(returned.body.status,"connected");assert.equal(verified.body.status,"connected");assert.ok(f.calls.filter(call=>call.name==="verify").length>=2);});});
test("V1-03 verify is tenant-scoped and does not expose credential or reference",async()=>{const {app,f}=makeApp({status:"callback_received"});await withServer(app,async server=>{const result=await request(server,{method:"POST",path:"/api/product/woocommerce/verify",headers:{authorization:token},body:{connection_id:ids.connection}});assert.deepEqual(result.body,{status:"connected"});assert.doesNotMatch(result.text,/consumer|secret|55555555/);assert.ok(f.calls.some(call=>call.name==="verify"));});});
test("V1-03 verify maps transient failures to processing and terminal failures safely",async()=>{const transient=makeApp({status:"callback_received",verifyError:new ProductError("PROVIDER_RATE_LIMITED","WooCommerce rate limit reached.",429)});await withServer(transient.app,async server=>{const result=await request(server,{method:"POST",path:"/api/product/woocommerce/verify",headers:{authorization:token},body:{connection_id:ids.connection}});assert.deepEqual(result.body,{status:"processing"});});const terminal=makeApp({status:"callback_received",verifyError:new ProductError("PROVIDER_AUTH_INVALID","WooCommerce credentials are invalid or revoked.",401)});await withServer(terminal.app,async server=>{const result=await request(server,{method:"POST",path:"/api/product/woocommerce/verify",headers:{authorization:token},body:{connection_id:ids.connection}});assert.equal(result.status,401);assert.equal(result.body.error.code,"PROVIDER_AUTH_INVALID");assert.doesNotMatch(result.text,/consumer|secret|55555555/);});});
test("V1-03 old consumed token after disconnect is not connected",async()=>{const {app}=makeApp({status:"consumed"});await withServer(app,async server=>{const result=await request(server,{path:"/api/product/woocommerce/return?success=1&user_id=known-user-12345678901234567890"});assert.deepEqual(result.body,{status:"disconnected"});});});
test("V1-03 verify rejects invalid legacy connected state instead of claiming connected",async()=>{const {app}=makeApp({status:"connected"});await withServer(app,async server=>{const result=await request(server,{method:"POST",path:"/api/product/woocommerce/verify",headers:{authorization:token},body:{connection_id:ids.connection}});assert.equal(result.status,409);assert.equal(result.body.error.code,"WOO_CONNECTION_STATE_MANAGED");});});
