import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { stripCommercial, commercialPacketInvariant, canRequestCase, recordAcceptanceAttempt, cacheMatches, accountProviderFailure, evaluateCommercialControls, formalQualityFails, acceptanceSessionPaths } from "../scripts/validation/v1-05-slice-b-harness-lib.js";

const frozenInputs = fs.readFileSync("artifacts/planning/v1-05/fixtures/evaluation-inputs.jsonl", "utf8").trim().split("\n").filter(Boolean).map(JSON.parse);
const frozenCorpus = JSON.parse(fs.readFileSync("artifacts/planning/v1-05/evaluation-corpus.json", "utf8")).cases;
const frozenExpectations = JSON.parse(fs.readFileSync("artifacts/planning/v1-05/evaluation-slice-b-expectations.json", "utf8")).cases;

test("commercial control removes only approved commercial fields", () => { const source = { name: "Product", price: 10, sales: 2, stock_status: "instock", query: "towel", clicks: 4 }; assert.deepEqual(stripCommercial(source), { name: "Product", query: "towel", clicks: 4 }); });
test("commercial invariance fails when a commercial field leaks", () => { assert.equal(commercialPacketInvariant({ name: "x" }, { name: "x", price: 1 }), false); });
test("commercial invariance passes identical stripped packets", () => { assert.equal(commercialPacketInvariant(stripCommercial({ name: "x", price: 1 }), stripCommercial({ name: "x", price: 2 })), true); });
test("preview acceptance remains provider-free and bounded", () => { const ledger = { total_request_count: 39, cases: {} }; assert.equal(canRequestCase(ledger, "case"), true); assert.equal(canRequestCase({ total_request_count: 40 }, "case"), false); });
test("smoke request accounting allows one request and no automatic second", () => { const first = recordAcceptanceAttempt({ total_request_count: 0, smoke_request_count: 0 }, "SMOKE", "smoke"); assert.equal(first.total_request_count, 1); assert.throws(() => recordAcceptanceAttempt(first, "SMOKE", "smoke")); });
test("known failure restart leaves one case attempt", () => { const first = recordAcceptanceAttempt({ total_request_count: 0 }, "A"); const second = recordAcceptanceAttempt(first, "A"); assert.equal(second.cases.A.actual_request_attempts, 2); assert.throws(() => recordAcceptanceAttempt(second, "A")); });
test("unknown outcome cannot be resumed", () => { assert.equal(canRequestCase({ total_request_count: 1, cases: { A: { actual_request_attempts: 1, state: "unknown_provider_outcome" } } }, "A"), false); });
test("twenty completed cache entries require no request eligibility", () => { const ledger = { total_request_count: 20, cases: Object.fromEntries(Array.from({ length: 20 }, (_, i) => [`C${i}`, { actual_request_attempts: 1, state: "complete" }])) }; assert.equal(Object.entries(ledger.cases).every(([caseId]) => canRequestCase(ledger, caseId) === false), true); assert.equal(canRequestCase({ total_request_count: 1, cases: { A: { actual_request_attempts: 1, state: "complete" } } }, "A"), false); });
test("cache identity rejects session, SHA, model, and benchmark mismatch", () => { const identity = Object.fromEntries(["session_id", "committed_sha", "provider", "model", "input_hash", "expectation_hash", "corpus_hash", "evaluation_version", "interpretation_version", "instruction_version", "packet_hash", "primary_candidate_identity"].map(key => [key, key])); assert.equal(cacheMatches(identity, identity), true); assert.equal(cacheMatches({ ...identity, model: "other" }, identity), false); });
test("request 41 is denied before provider work", () => { assert.equal(canRequestCase({ total_request_count: 40 }, "A"), false); });
test("unknown provider outcome forces unknown cost", () => { const result = accountProviderFailure({ cost_status: "calculated_from_explicit_configuration", estimated_cost_usd: 2 }, { code: "PROVIDER_OUTCOME_UNKNOWN" }, 0, {}); assert.equal(result.cost_status, "unknown"); assert.equal(result.estimated_cost_usd, null); });
test("known priced response retains calculated cost", () => { const result = accountProviderFailure({ cost_status: "calculated_from_explicit_configuration", estimated_cost_usd: 1 }, { code: "PROVIDER_HTTP_ERROR" }, 0.25, { input_tokens: 10, output_tokens: 5 }); assert.equal(result.estimated_cost_usd, 1.25); });
test("formal quality predicate requires all semantic gates", () => { const base = { intent_applicable_count: 38, intent_accuracy: 1, high_impact_intent_errors: 0, high_impact_target_errors: 0, required_gates: { mixed_uncertain_preservation: true, brand_navigation: true, wrong_page_type: true, high_volume_irrelevant: true, low_volume_preservation: true, commercial_invariance: true } }; assert.equal(formalQualityFails(base), false); for (const key of Object.keys(base.required_gates)) assert.equal(formalQualityFails({ ...base, required_gates: { ...base.required_gates, [key]: false } }), true); assert.equal(formalQualityFails({ ...base, intent_accuracy: 0.84 }), true); assert.equal(formalQualityFails({ ...base, high_impact_intent_errors: 1 }), true); assert.equal(formalQualityFails({ ...base, high_impact_target_errors: 1 }), true); assert.equal(formalQualityFails({ ...base, intent_applicable_count: 37 }), true); assert.equal(formalQualityFails(null), true); });
test("formal quality predicate rejects a missing required gate", () => { const gates = { mixed_uncertain_preservation: true, brand_navigation: true, wrong_page_type: true, high_volume_irrelevant: true, low_volume_preservation: true }; assert.equal(formalQualityFails({ intent_applicable_count: 38, intent_accuracy: 1, high_impact_intent_errors: 0, high_impact_target_errors: 0, required_gates: gates }), true); });
test("frozen commercial controls evaluate ten candidate cases and one run-level case", () => { const proof = evaluateCommercialControls({ corpus: frozenCorpus, expectations: frozenExpectations, inputs: frozenInputs }); assert.equal(proof.commercial_sensitive_cases, 11); assert.equal(proof.candidate_level_cases, 10); assert.equal(proof.run_level_cases, 1); assert.equal(proof.expectation_matches, 10); assert.equal(proof.evaluated, 11); assert.equal(proof.not_applicable, 0); assert.equal(proof.passed, 11); assert.deepEqual(proof.failures, []); assert.deepEqual(proof.run_level_case_ids, ["V105-EVAL-021"]); const runLevel = proof.results.find(result => result.case_id === "V105-EVAL-021"); assert.equal(runLevel.control_mode, "run_level_insufficient_evidence_control"); assert.equal(runLevel.evaluated, true); assert.equal(runLevel.pass, true); });
test("run-level commercial control detects organic preparation leakage", () => { const proof = evaluateCommercialControls({ corpus: frozenCorpus, expectations: frozenExpectations, inputs: frozenInputs, controlPacketTransform: (packet, caseId) => caseId === "V105-EVAL-021" ? { ...stripCommercial(packet), business: { ...stripCommercial(packet.business), name: `${packet.business.name} changed` } } : stripCommercial(packet) }); const result = proof.results.find(item => item.case_id === "V105-EVAL-021"); assert.equal(result.pass, false); assert.ok(result.failed_dimensions.includes("candidate_universe") || result.failed_dimensions.includes("model_input")); });
test("candidate-level commercial control detects model input leakage", () => { const proof = evaluateCommercialControls({ corpus: frozenCorpus, expectations: frozenExpectations, inputs: frozenInputs, controlPacketTransform: (packet, caseId) => caseId === "V105-EVAL-001" ? { ...stripCommercial(packet), business: { ...stripCommercial(packet.business), name: `${packet.business.name} changed` } } : stripCommercial(packet) }); const result = proof.results.find(item => item.case_id === "V105-EVAL-001"); assert.equal(result.pass, false); assert.ok(result.failed_dimensions.includes("model_input") || result.failed_dimensions.includes("interpretation_input_hash")); });
test("live harness imports the authoritative helper without duplicate commercial orchestration", () => { const source = fs.readFileSync("scripts/v1-05-slice-b-live-evaluation.js", "utf8"); assert.match(source, /evaluateCommercialControls.*v1-05-slice-b-harness-lib\.js/); assert.doesNotMatch(source, /function commercialInvariant/); assert.doesNotMatch(source, /const COMMERCIAL_KEYS/); assert.doesNotMatch(source, /function stripCommercial/); });
test("acceptance sessions are isolated and reject traversal", () => { const a = acceptanceSessionPaths("v6-session-a"); const b = acceptanceSessionPaths("v6-session-b"); assert.notEqual(a.ledgerPath, b.ledgerPath); assert.deepEqual(a, acceptanceSessionPaths("v6-session-a")); assert.throws(() => acceptanceSessionPaths("../legacy"), /INVALID_ACCEPTANCE_SESSION_ID/); assert.throws(() => acceptanceSessionPaths("session/path"), /INVALID_ACCEPTANCE_SESSION_ID/); });
test("acceptance session paths require a real child directory", () => { for (const id of [".", "..", "../x", "x/..", "/tmp/x", "foo/bar", "foo\\bar", "", "x".repeat(65)]) assert.throws(() => acceptanceSessionPaths(id), /INVALID_ACCEPTANCE_SESSION_ID/); for (const id of ["slice-b-v6-acceptance-001", "v6.001", "test_session-1"]) { const paths = acceptanceSessionPaths(id); assert.match(paths.directory, /^artifacts\/validation\/v1-05\/live-sessions\//); assert.notEqual(paths.directory, "artifacts/validation/v1-05/live-sessions"); assert.match(paths.ledgerPath, /\/ledger\.json$/); assert.match(paths.caseCachePath, /\/formal-case-cache\.json$/); } });
