import test from "node:test";
import assert from "node:assert/strict";
import crypto from "node:crypto";
import { createClient } from "@supabase/supabase-js";

const enabled = process.env.V1_03_INTEGRATION === "1";
const required = name => process.env[name] || (() => { throw new Error(`${name} required`); })();

test("V1-03 initial snapshot RPC stages, promotes, derives sales, and preserves LKG", { skip: !enabled }, async t => {
  const url = required("SUPABASE_URL"), publishable = required("SUPABASE_PUBLISHABLE_KEY"), service = required("SUPABASE_SERVICE_ROLE_KEY");
  const admin = createClient(url, service, { auth: { persistSession: false } });
  const email = `v103-commerce-${crypto.randomUUID()}@example.test`;
  const password = `V1-03-${crypto.randomUUID()}!Aa`;
  const created = await admin.auth.admin.createUser({ email, password, email_confirm: true });
  assert.ifError(created.error);
  const userId = created.data.user.id;
  t.after(() => admin.auth.admin.deleteUser(userId));
  const caller = createClient(url, publishable, { auth: { persistSession: false } });
  assert.ifError((await caller.auth.signInWithPassword({ email, password })).error);
  const account = (await admin.from("accounts").insert({ auth_user_id: userId }).select().single()).data;
  const business = (await admin.from("businesses").insert({ account_id: account.id, name: "Synthetic Commerce", ecommerce_platform: "woocommerce" }).select().single()).data;
  const connection = (await admin.from("connections").insert({ business_id: business.id, provider_type: "woocommerce" }).select().single()).data;
  const attemptToken = `v103-commerce-${crypto.randomUUID()}`;
  const attempt = await admin.rpc("woo_create_auth_attempt", { p_user_id: attemptToken, p_account_id: account.id, p_business_id: business.id, p_connection_id: connection.id, p_canonical_base_url: "https://shop.example/", p_expires_at: new Date(Date.now() + 60000).toISOString() });
  assert.ifError(attempt.error);
  assert.ifError((await admin.rpc("woo_claim_auth_attempt", { p_user_id: attemptToken })).error);
  assert.ifError((await admin.rpc("woo_capture_callback", { p_attempt_id: attempt.data, p_consumer_key: "ck_synthetic", p_consumer_secret: "cs_synthetic", p_key_permissions: "read" })).error);
  const established = await admin.rpc("woo_complete_connection", { p_attempt_id: attempt.data, p_home_url: "https://shop.example/", p_site_url: "https://shop.example/", p_version: "9", p_timezone: "UTC", p_currency: "GBP", p_correlation_id: crypto.randomUUID() });
  assert.ifError(established.error);
  const store = (await admin.from("commerce_stores").select().eq("id", established.data).single()).data;
  const products = [{ source_id: 10, name: "Synthetic Product", slug: "synthetic-product", product_type: "simple", source_status: "publish", current_price: "12.10" }];
  const categories = [{ source_id: 20, name: "Synthetic Category", slug: "synthetic-category", parent_source_id: null }];
  const orders = [{ source_id: 30, source_status: "completed", recognition_state: "recognised", currency: "GBP", order_total: "10.00", tax_total: "2.00", shipping_total: "0", discount_total: "0", refund_total: "2.00", prices_include_tax: false }];
  const lines = [{ order_source_id: 30, source_line_id: 300, product_source_id: 10, variation_source_id: null, quantity: 1, subtotal: "10.00", total: "10.00", tax: "2.00", refunded_quantity: 1, refund_total: "2.00", refund_tax: "0.40" }];
  const generation = await admin.rpc("commerce_begin_initial_sync", { p_store_id: store.id, p_correlation_id: crypto.randomUUID() });
  assert.ifError(generation.error);
  const concurrent = await admin.rpc("commerce_begin_initial_sync", { p_store_id: store.id, p_correlation_id: crypto.randomUUID() });
  assert.ok(concurrent.error?.message.includes("SYNC_ALREADY_RUNNING"));
  assert.equal((await admin.from("commerce_stores").select("current_generation,sync_state").eq("id", store.id).single()).data.sync_state, "pending");
  const staged = await admin.rpc("commerce_stage_initial_snapshot", { p_store_id: store.id, p_generation_id: generation.data, p_products: products, p_variations: [], p_categories: categories, p_links: [{ product_source_id: 10, category_source_id: 20 }], p_orders: orders, p_lines: lines, p_adjustments: [] });
  assert.ifError(staged.error);
  assert.equal((await admin.from("commerce_products").select("source_id").eq("generation_id", generation.data)).data.length, 1);
  assert.deepEqual((await caller.from("commerce_products").select("source_id").eq("generation_id", generation.data)).data, []);
  assert.ifError((await admin.rpc("commerce_complete_initial_sync", { p_store_id: store.id, p_generation_id: generation.data })).error);
  const promoted = (await admin.from("commerce_stores").select("current_generation,sync_state,last_successful_at").eq("id", store.id).single()).data;
  assert.equal(promoted.current_generation, generation.data);
  assert.equal(promoted.sync_state, "complete");
  assert.ok(promoted.last_successful_at);
  const derivedResult = await admin.from("commerce_product_net_sales").select("product_source_id,product_net_sales_ex_tax").eq("generation_id", generation.data);
  assert.ifError(derivedResult.error);
  assert.equal(derivedResult.data.length, 1);
  const derived = derivedResult.data[0];
  assert.equal(String(derived.product_net_sales_ex_tax), "8");
  const failedGeneration = await admin.rpc("commerce_begin_initial_sync", { p_store_id: store.id, p_correlation_id: crypto.randomUUID() });
  assert.ifError(failedGeneration.error);
  assert.ifError((await admin.rpc("commerce_mark_sync_failed", { p_store_id: store.id, p_generation_id: failedGeneration.data, p_error_code: "PROVIDER_MALFORMED_RESPONSE", p_partial: true })).error);
  const lkg = (await admin.from("commerce_stores").select("current_generation,sync_state").eq("id", store.id).single()).data;
  assert.equal(lkg.current_generation, generation.data);
  assert.equal(lkg.sync_state, "partial");
  assert.equal((await admin.from("commerce_products").select("source_id").eq("generation_id", generation.data)).data.length, 1);
  const aggregate = (await admin.from("commerce_product_net_sales_by_generation").select("product_source_id,product_net_sales_ex_tax").eq("generation_id", generation.data).single()).data;
  assert.equal(String(aggregate.product_net_sales_ex_tax), "8");
});
