import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {PassThrough} from 'node:stream';
import {appendStorePath,validateWooOrigin,wooRequest} from '../product-kernel/woocommerceEgress.js';
import {newAttemptToken,createWooAuthUrl,createValidatedWooAuthUrl} from '../product-kernel/woocommerceAuth.js';
import {verifyWooIdentity} from '../product-kernel/woocommerceIdentity.js';

const publicLookup=async()=>[{address:'93.184.216.34',family:4}];
function transport({status=200,headers={'content-type':'application/json'},body='{}',error,timeout=false}={}){const calls=[];const request=(url,options,callback)=>{calls.push({url,options});const req=new EventEmitter();req.end=()=>{if(error)return queueMicrotask(()=>req.emit('error',error));if(timeout)return queueMicrotask(()=>req.emit('timeout'));const res=new PassThrough();res.statusCode=status;res.headers=headers;callback(res);res.end(body);};req.destroy=e=>queueMicrotask(()=>req.emit('error',e));return req;};return{request,calls};}
const run=(response,options={})=>{const t=transport(response);return{promise:wooRequest('https://shop.example/wp','wp-json/wc/v3/system_status',{lookup:publicLookup,request:t.request,...options}),calls:t.calls};};

test('V1-03 opaque auth token has high entropy',()=>{const a=newAttemptToken(),b=newAttemptToken();assert.ok(a.length>=40);assert.notEqual(a,b);});
test('V1-03 trusted auth URL is read-only and preserves subdirectory',()=>{const u=new URL(createWooAuthUrl({origin:'https://shop.example/wp',appName:'Product',returnUrl:'https://product.example/return',callbackUrl:'https://product.example/callback',productOrigin:'https://product.example',userId:'opaque'}));assert.equal(u.pathname,'/wp/wc-auth/v1/authorize');assert.equal(u.searchParams.get('scope'),'read');assert.deepEqual([...u.searchParams.keys()].sort(),['app_name','callback_url','return_url','scope','user_id']);});
test('V1-03 Product callback and return origins cannot be customer-selected',()=>assert.throws(()=>createWooAuthUrl({origin:'https://shop.example',appName:'P',returnUrl:'https://evil.example',callbackUrl:'https://product.example/c',productOrigin:'https://product.example',userId:'x'}),/Product URL/));
test('V1-03 Product callback URL requires HTTPS and no userinfo',()=>assert.throws(()=>createWooAuthUrl({origin:'https://shop.example',appName:'P',returnUrl:'https://product.example/r',callbackUrl:'https://u:p@product.example/c',productOrigin:'https://product.example',userId:'x'})));
test('V1-03 store is DNS validated before redirect generation',async()=>assert.match(await createValidatedWooAuthUrl({origin:'https://shop.example/wp',appName:'P',returnUrl:'https://product.example/r',callbackUrl:'https://product.example/c',productOrigin:'https://product.example',userId:'x'},{lookup:publicLookup}),/\/wp\/wc-auth/));
test('V1-03 subdirectory base composes REST paths',()=>assert.equal(appendStorePath('https://shop.example/wordpress','wp-json/wc/v3/products').pathname,'/wordpress/wp-json/wc/v3/products'));
test('V1-03 rejects unsafe origins',async()=>{for(const v of['http://shop.example','https://localhost','https://127.0.0.1','https://user:pass@shop.example','https://shop.example:8443'])await assert.rejects(validateWooOrigin(v,{lookup:publicLookup}));});
test('V1-03 rejects private DNS answers',async()=>assert.rejects(validateWooOrigin('https://shop.example',{lookup:async()=>[{address:'10.0.0.1',family:4}]})));
test('V1-03 DNS socket remains pinned to validated A despite later B',async()=>{let n=0;const lookup=async()=>[{address:++n===1?'93.184.216.34':'93.184.216.35',family:4}],t=transport();await wooRequest('https://shop.example/wp','status',{lookup,request:t.request});let socket;t.calls[0].options.lookup('',{},(_e,a)=>socket=a);assert.equal(socket,'93.184.216.34');});
test('V1-03 TLS, SNI and Host semantics remain enabled',async()=>{const{promise,calls}=run();await promise;assert.equal(calls[0].options.rejectUnauthorized,true);assert.equal(calls[0].options.servername,'shop.example');assert.equal(calls[0].options.headers.host,'shop.example');});
test('V1-03 production transport is GET-only with no method override',async()=>{const{promise,calls}=run();await promise;assert.equal(calls[0].options.method,'GET');assert.equal(calls[0].options.headers['x-http-method-override'],undefined);assert.equal(calls[0].url.searchParams.get('_method'),null);});
test('V1-03 caller cannot inject dangerous query parameters',async()=>assert.rejects(wooRequest('https://shop.example/wp','status?_method=POST',{lookup:publicLookup,request:transport().request}),/Store URL/));
test('V1-03 identity uses Basic Auth without URL credentials',async()=>{const response={environment:{home_url:'https://shop.example/',site_url:'https://shop.example/wp',version:'9.0',default_timezone:'Europe/London'},settings:{currency:'GBP'}},t=transport({body:JSON.stringify(response)});const identity=await verifyWooIdentity('https://shop.example/wp',{consumerKey:'ck_test',consumerSecret:'cs_test'},{lookup:publicLookup,request:t.request});assert.equal(t.calls[0].options.headers.authorization,`Basic ${Buffer.from('ck_test:cs_test').toString('base64')}`);assert.doesNotMatch(t.calls[0].url.toString(),/ck_test|cs_test/);assert.equal(identity.currency,'GBP');});
test('V1-03 identity missing required values fails closed',async()=>{const t=transport({body:JSON.stringify({environment:{site_url:'https://shop.example/wp',version:'9'}})});await assert.rejects(verifyWooIdentity('https://shop.example/wp',{consumerKey:'ck',consumerSecret:'cs'},{lookup:publicLookup,request:t.request}),e=>e.code==='PROVIDER_IDENTITY_INVALID');});
test('V1-03 wrong authenticated Store fails closed',async()=>{const t=transport({body:JSON.stringify({environment:{home_url:'https://evil.example',site_url:'https://evil.example',version:'9'},settings:{currency:'GBP'}})});await assert.rejects(verifyWooIdentity('https://shop.example/wp',{consumerKey:'ck',consumerSecret:'cs'},{lookup:publicLookup,request:t.request}),e=>e.code==='WOO_STORE_IDENTITY_MISMATCH');});
for(const[status,code]of[[401,'PROVIDER_AUTH_INVALID'],[403,'PROVIDER_AUTH_INVALID'],[429,'PROVIDER_RATE_LIMITED'],[503,'PROVIDER_UNAVAILABLE']])test(`V1-03 provider ${status} maps to safe ${code}`,async()=>{const{promise}=run({status});await assert.rejects(promise,e=>e.code===code&&!/socket|ECONN/i.test(e.message));});
test('V1-03 request timeout is bounded and safe',async()=>{const{promise}=run({timeout:true});await assert.rejects(promise,e=>e.code==='PROVIDER_TIMEOUT');});
test('V1-03 response size is bounded',async()=>{const{promise}=run({body:'x'.repeat(20)},{maxBytes:10});await assert.rejects(promise,e=>e.code==='PROVIDER_RESPONSE_TOO_LARGE');});
test('V1-03 malformed JSON is rejected',async()=>{const{promise}=run({body:'{'});await assert.rejects(promise,e=>e.code==='PROVIDER_MALFORMED_RESPONSE');});
test('V1-03 non-JSON is rejected',async()=>{const{promise}=run({headers:{'content-type':'text/html'},body:'no'});await assert.rejects(promise,e=>e.code==='PROVIDER_MALFORMED_RESPONSE');});
test('V1-03 private redirect is rejected',async()=>{const t=transport({status:302,headers:{location:'https://127.0.0.1/internal'}});await assert.rejects(wooRequest('https://shop.example/wp','status',{lookup:publicLookup,request:t.request}));});
test('V1-03 host-changing redirect is rejected',async()=>{const t=transport({status:302,headers:{location:'https://other.example/wp/status'}});await assert.rejects(wooRequest('https://shop.example/wp','status',{lookup:publicLookup,request:t.request}));});
test('V1-03 redirect loop is bounded',async()=>{const t=transport({status:302,headers:{location:'/wp/status'}});await assert.rejects(wooRequest('https://shop.example/wp','status',{lookup:publicLookup,request:t.request,maxRedirects:1}),e=>e.code==='PROVIDER_REDIRECT_LIMIT');});
test('V1-03 raw network errors are mapped',async()=>{const{promise}=run({error:new Error('ECONNRESET raw socket')});await assert.rejects(promise,e=>e.code==='PROVIDER_UNAVAILABLE'&&!/ECONNRESET/.test(e.message));});
