import test from "node:test";
import assert from "node:assert/strict";
import crypto from "node:crypto";
import http from "node:http";
import { createClient } from "@supabase/supabase-js";
import app from "../app.js";
import { setGoogleSearchConsoleTransportFactory } from "../product-kernel/googleSearchConsoleOAuth.js";

const enabled = process.env.V1_04_P3B_TENANT_INTEGRATION === "1";
const required = name => process.env[name] || (() => { throw new Error(`${name} required`); })();
const request = (server, method, path, token, body, extra = {}) => new Promise((resolve, reject) => {
  const headers = { ...(body === undefined ? {} : { "content-type": "application/json" }), ...extra };
  if (token) headers.authorization = `Bearer ${token}`;
  const req = http.request({ hostname: "127.0.0.1", port: server.address().port, method, path, headers }, res => { let text = ""; res.on("data", c => { text += c; }); res.on("end", () => { let parsed = null; try { parsed = text ? JSON.parse(text) : null; } catch {} resolve({ status: res.statusCode, body: parsed, text, headers: res.headers }); }); });
  req.on("error", reject); if (body !== undefined) req.write(JSON.stringify(body)); req.end();
});
const listen = target => new Promise((resolve, reject) => { const server = target.listen(0, "127.0.0.1", () => resolve(server)); server.once("error", reject); });
const safeText = response => { assert.doesNotMatch(response.text, /refresh_token|access_token|secret_reference|pkce|state_hash|postgres|postgrest|vault/i); };

test("P3-B tenant-isolation matrix", { skip: !enabled }, async t => {
  const url = required("SUPABASE_URL"), publishable = required("SUPABASE_PUBLISHABLE_KEY"), service = required("SUPABASE_SERVICE_ROLE_KEY");
  const admin = createClient(url, service, { auth: { persistSession: false } });
  const appServer = await listen(app);
  const users = [];
  const counters = { authorization: 0, exchange: 0, access: 0, list: 0, probe: 0 };
  setGoogleSearchConsoleTransportFactory(() => ({
    authorizationUrl: ({ state }) => { counters.authorization++; return `https://accounts.google.test/authorize?state=${state}`; },
    exchangeCode: async () => { counters.exchange++; return { refresh_token: "synthetic-tenant-refresh", scope: "https://www.googleapis.com/auth/webmasters.readonly" }; },
    accessToken: async () => { counters.access++; return "synthetic-tenant-access"; },
    sitesList: async () => { counters.list++; return { siteEntry: [{ siteUrl: "https://tenant-a.example/shop/", permissionLevel: "siteOwner" }, { siteUrl: "https://tenant-b.example/store/", permissionLevel: "siteOwner" }] }; },
    site: async (_token, siteUrl) => { counters.probe++; return { siteUrl, permissionLevel: "siteOwner" }; }
  }));
  const createTenant = async (label, site) => {
    const email = `p3b-tenant-${label}-${crypto.randomUUID()}@local.test`, password = `${crypto.randomUUID()}!Aa9`;
    const made = await admin.auth.admin.createUser({ email, password, email_confirm: true }); assert.ifError(made.error); users.push(made.data.user.id);
    const login = createClient(url, publishable, { auth: { persistSession: false } }); const signed = await login.auth.signInWithPassword({ email, password }); assert.ifError(signed.error); const token = signed.data.session.access_token;
    const caller = createClient(url, publishable, { global: { headers: { authorization: `Bearer ${token}` } }, auth: { persistSession: false } });
    assert.ifError((await caller.rpc("product_create_account", { p_correlation_id: crypto.randomUUID() })).error);
    const business = await caller.rpc("product_create_business", { p_name: `P3-B tenant ${label}`, p_platform: "woocommerce", p_correlation_id: crypto.randomUUID() }); assert.ifError(business.error);
    const woo = await caller.rpc("product_create_connection", { p_provider_type: "woocommerce", p_correlation_id: crypto.randomUUID() }); assert.ifError(woo.error);
    const account = await admin.from("accounts").select("id").eq("auth_user_id", made.data.user.id).single(); assert.ifError(account.error);
    const wu = `p3b-tenant-woo-${crypto.randomUUID()}`; const attempt = await admin.rpc("woo_create_auth_attempt", { p_user_id: wu, p_account_id: account.data.id, p_business_id: business.data.id, p_connection_id: woo.data.id, p_canonical_base_url: site, p_expires_at: new Date(Date.now() + 60000).toISOString() }); assert.ifError(attempt.error);
    assert.ifError((await admin.rpc("woo_claim_auth_attempt", { p_user_id: wu })).error); assert.ifError((await admin.rpc("woo_capture_callback", { p_attempt_id: attempt.data, p_consumer_key: `tenant-${label}-key`, p_consumer_secret: `tenant-${label}-secret`, p_key_permissions: "read" })).error); assert.ifError((await admin.rpc("woo_complete_connection", { p_attempt_id: attempt.data, p_home_url: site, p_site_url: site, p_version: "synthetic", p_timezone: "UTC", p_currency: "GBP", p_correlation_id: crypto.randomUUID() })).error);
    const start = await request(appServer, "POST", "/api/product/organic-evidence/search-console/connect", token, {}); assert.equal(start.status, 201, start.text); const state = new URL(start.body.authorization_url).searchParams.get("state");
    const callback = await request(appServer, "GET", `/api/product/organic-evidence/search-console/callback?state=${encodeURIComponent(state)}&code=synthetic-code`, null); assert.equal(callback.status, 200, callback.text);
    const selected = await request(appServer, "POST", "/api/product/organic-evidence/search-console/select", token, { connection_id: start.body.connection.id, site_url: site }); assert.equal(selected.status, 200, selected.text);
    const source = await admin.from("organic_evidence_sources").select("id").eq("business_id", business.data.id).single(); assert.ifError(source.error); const run = await admin.rpc("organic_begin_run", { p_source_id: source.data.id, p_retrieved_at: new Date().toISOString() }); assert.ifError(run.error); assert.ifError((await admin.rpc("organic_finish_run", { p_run_id: run.data.id, p_state: "complete", p_completeness_state: "complete", p_evidence_as_of: "2026-09-02T00:00:00Z" })).error);
    const gsc = await admin.from("gsc_connections").select("connection_id").eq("connection_id", start.body.connection.id).single(); assert.ifError(gsc.error);
    return { label, userId: made.data.user.id, token, caller, accountId: account.data.id, businessId: business.data.id, connectionId: start.body.connection.id, sourceId: source.data.id, runId: run.data.id, site };
  };
  const a = await createTenant("a", "https://tenant-a.example/shop/"); const b = await createTenant("b", "https://tenant-b.example/store/");
  const inventory = async tenant => { const connections = await admin.from("connections").select("id,secret_reference").eq("id", tenant.connectionId); const source = await admin.from("organic_evidence_sources").select("id,current_complete_run,evidence_state").eq("id", tenant.sourceId); const gscAttempts = await admin.from("gsc_oauth_attempts").select("id,status").eq("connection_id", tenant.connectionId); return { connection: connections.data?.[0], source: source.data?.[0], gscAttempts: gscAttempts.data || [] }; };
  const beforeA = await inventory(a), beforeB = await inventory(b);
  const protectedRoutes = [
    ["POST", "/api/product/organic-evidence/search-console/connect", {}], ["POST", "/api/product/organic-evidence/search-console/reconnect", {}], ["GET", "/api/product/organic-evidence/search-console/properties", undefined], ["POST", "/api/product/organic-evidence/search-console/select", { connection_id: a.connectionId, site_url: a.site }], ["POST", "/api/product/organic-evidence/search-console/disconnect", { connection_id: a.connectionId }], ["POST", "/api/product/organic-evidence/search-console/reauth-check", { connection_id: a.connectionId }], ["GET", "/api/product/organic-evidence/search-console/status", undefined]
  ];
  const foreign = async (tenant, other, method, path, body) => { const r = await request(appServer, method, `${path}${path.endsWith("properties") ? `?connection_id=${other.connectionId}` : ""}`, tenant.token, body); safeText(r); return r; };
  t.after(async () => { setGoogleSearchConsoleTransportFactory(undefined); for (const id of users) await admin.auth.admin.deleteUser(id); await new Promise(resolve => appServer.close(resolve)); });
  const denied = async r => { assert.ok([400, 401, 403, 404, 409].includes(r.status), `${r.status} ${r.text}`); safeText(r); };
  const cases = [
    ["P3B-TENANT-001 own-tenant positive controls", async () => { for (const tenant of [a, b]) { const status = await request(appServer, "GET", "/api/product/organic-evidence/search-console/status", tenant.token); assert.equal(status.status, 200); assert.equal(status.body.selected_property, tenant.site); assert.equal(status.body.evidence_state, "complete"); const health = await request(appServer, "POST", "/api/product/organic-evidence/search-console/reauth-check", tenant.token, { connection_id: tenant.connectionId }); assert.equal(health.status, 200); safeText(status); safeText(health); } }],
    ["P3B-TENANT-002 authentication failures", async () => { for (const token of [undefined, "Bearer malformed", "not-a-token"]) for (const [method, path, body] of protectedRoutes) { const r = await request(appServer, method, path + (path.endsWith("properties") ? `?connection_id=${a.connectionId}` : ""), token, body); denied(r); } const deleted = await admin.auth.admin.createUser({ email: `deleted-${crypto.randomUUID()}@local.test`, password: `${crypto.randomUUID()}!Aa9`, email_confirm: true }); assert.ifError(deleted.error); const login = createClient(url, publishable, { auth: { persistSession: false } }); const signed = await login.auth.signInWithPassword({ email: deleted.data.user.email, password: "invalid" }); assert.ok(signed.error); await admin.auth.admin.deleteUser(deleted.data.user.id); }],
    ["P3B-TENANT-003 foreign property discovery", async () => { const before = counters.list; denied(await foreign(a, b, "GET", "/api/product/organic-evidence/search-console/properties")); assert.equal(counters.list, before); assert.deepEqual(await inventory(b), beforeB); }],
    ["P3B-TENANT-004 foreign property selection", async () => { for (const site of [b.site, a.site, "https://other.example/"]) denied(await foreign(a, b, "POST", "/api/product/organic-evidence/search-console/select", { connection_id: b.connectionId, site_url: site })); assert.deepEqual(await inventory(b), beforeB); }],
    ["P3B-TENANT-005 foreign disconnect and nonexistent comparison", async () => { const foreignResult = await foreign(a, b, "POST", "/api/product/organic-evidence/search-console/disconnect", { connection_id: b.connectionId }); const missing = await request(appServer, "POST", "/api/product/organic-evidence/search-console/disconnect", a.token, { connection_id: crypto.randomUUID() }); assert.equal(foreignResult.status, missing.status); assert.equal(foreignResult.body.error?.code, missing.body.error?.code); denied(foreignResult); assert.deepEqual(await inventory(b), beforeB); }],
    ["P3B-TENANT-006 foreign reauth-check", async () => { const access = counters.access; denied(await foreign(a, b, "POST", "/api/product/organic-evidence/search-console/reauth-check", { connection_id: b.connectionId })); assert.equal(counters.access, access); assert.deepEqual(await inventory(b), beforeB); }],
    ["P3B-TENANT-007 symmetric foreign route controls", async () => { for (const [method, path, body] of [["GET", "/api/product/organic-evidence/search-console/properties", undefined], ["POST", "/api/product/organic-evidence/search-console/select", { connection_id: a.connectionId, site_url: a.site }], ["POST", "/api/product/organic-evidence/search-console/disconnect", { connection_id: a.connectionId }], ["POST", "/api/product/organic-evidence/search-console/reauth-check", { connection_id: a.connectionId }]]) denied(await foreign(b, a, method, path, body)); assert.deepEqual(await inventory(a), beforeA); }],
    ["P3B-TENANT-008 connect/reconnect identifier injection", async () => { const keys = ["account_id", "business_id", "connection_id", "provider_id", "auth_user_id"]; for (const key of keys) { const body = { [key]: b.businessId }; const r = await request(appServer, "POST", "/api/product/organic-evidence/search-console/connect", a.token, body); assert.equal(r.status, 201); assert.equal(r.body.connection.id, a.connectionId); const q = await request(appServer, "POST", "/api/product/organic-evidence/search-console/reconnect", a.token, body); assert.equal(q.status, 201); assert.equal(q.body.connection.id, a.connectionId); } assert.deepEqual(await inventory(b), beforeB); }],
    ["P3B-TENANT-009 status cannot be rebound", async () => { for (const key of ["account_id", "business_id", "connection_id", "selected_property"]) { const r = await request(appServer, "GET", `/api/product/organic-evidence/search-console/status?${key}=${encodeURIComponent(b[key === "connection_id" ? "connectionId" : key === "business_id" ? "businessId" : key === "account_id" ? "accountId" : "site"])}`, a.token); assert.equal(r.status, 200); assert.equal(r.body.selected_property, a.site); assert.doesNotMatch(JSON.stringify(r.body), new RegExp(b.site)); } }],
    ["P3B-TENANT-010 callback cannot be rebound", async () => { const start = await request(appServer, "POST", "/api/product/organic-evidence/search-console/reconnect", a.token, {}); assert.equal(start.status, 201); const state = new URL(start.body.authorization_url).searchParams.get("state"); const before = counters.exchange; const bad = await request(appServer, "GET", `/api/product/organic-evidence/search-console/callback?state=${encodeURIComponent(state)}&code=synthetic-code&business_id=${b.businessId}`, null); denied(bad); assert.equal(counters.exchange, before); const good = await request(appServer, "GET", `/api/product/organic-evidence/search-console/callback?state=${encodeURIComponent(state)}&code=synthetic-code`, null); assert.equal(good.status, 200); assert.equal((await request(appServer, "GET", `/api/product/organic-evidence/search-console/status`, a.token)).body.selected_property, a.site); const unknown = await request(appServer, "GET", `/api/product/organic-evidence/search-console/callback?state=${crypto.randomBytes(32).toString("base64url")}&code=synthetic-code`, null); denied(unknown); }],
    ["P3B-TENANT-011 Account/Business/audit RLS", async () => { for (const [own, other] of [[a, b], [b, a]]) { assert.equal((await own.caller.from("accounts").select("id").eq("id", own.accountId)).data.length, 1); assert.equal((await own.caller.from("accounts").select("id").eq("id", other.accountId)).data.length, 0); assert.equal((await own.caller.from("businesses").select("id").eq("id", own.businessId)).data.length, 1); assert.equal((await own.caller.from("businesses").select("id").eq("id", other.businessId)).data.length, 0); assert.equal((await own.caller.from("audit_events").select("id").eq("business_id", other.businessId)).data.length, 0); } }],
    ["P3B-TENANT-012 base Connection RLS and safe columns", async () => { for (const [own, other] of [[a, b], [b, a]]) { assert.equal((await own.caller.from("connections").select("id,status,consent_state").eq("id", own.connectionId)).data.length, 1); assert.equal((await own.caller.from("connections").select("id").eq("id", other.connectionId)).data.length, 0); const secret = await own.caller.from("connections").select("secret_reference").eq("id", own.connectionId); assert.ok(secret.error); } }],
    ["P3B-TENANT-013 GSC Connection RLS", async () => { for (const [own, other] of [[a, b], [b, a]]) { assert.equal((await own.caller.from("gsc_connections").select("connection_id,selected_site_url,connection_state").eq("connection_id", own.connectionId)).data.length, 1); assert.equal((await own.caller.from("gsc_connections").select("connection_id").eq("connection_id", other.connectionId)).data.length, 0); const write = await own.caller.from("gsc_connections").update({ selected_site_url: "https://foreign.example/" }).eq("connection_id", own.connectionId); assert.ok(write.error); } }],
    ["P3B-TENANT-014 organic source/run and commerce identity RLS", async () => { for (const [own, other] of [[a, b], [b, a]]) { const ownSource = await own.caller.from("organic_evidence_sources").select("id,current_complete_run").eq("id", own.sourceId); assert.equal(ownSource.data?.length, 1); const foreignSource = await own.caller.from("organic_evidence_sources").select("id").eq("id", other.sourceId); assert.equal(foreignSource.data?.length || 0, 0); const foreignRun = await own.caller.from("organic_evidence_runs").select("id").eq("id", other.runId); assert.equal(foreignRun.data?.length || 0, 0); const foreignStore = await own.caller.from("commerce_stores").select("id").eq("business_id", other.businessId); assert.equal(foreignStore.data?.length || 0, 0); } }],
    ["P3B-TENANT-015 OAuth attempts service-only", async () => { for (const own of [a, b]) { const r = await own.caller.from("gsc_oauth_attempts").select("id,state_hash,pkce_verifier,staged_secret_reference"); assert.ok(r.error || r.data.length === 0); } }],
    ["P3B-TENANT-016 secret references not customer-readable", async () => { for (const own of [a, b]) { assert.ok((await own.caller.from("connections").select("secret_reference").eq("id", own.connectionId)).error); assert.ok((await own.caller.from("woocommerce_auth_attempts").select("credential_reference")).error); assert.ok((await own.caller.from("gsc_oauth_attempts").select("staged_secret_reference")).error); } }],
    ["P3B-TENANT-017 Vault inaccessible", async () => { for (const own of [a, b]) { assert.ok((await own.caller.schema("vault").from("secrets").select("id")).error); assert.ok((await own.caller.schema("vault").from("decrypted_secrets").select("id")).error); for (const [name, args] of [["vault_read_secret", { secret_id: beforeA.connection.secret_reference }], ["vault_create_secret", { p_value: "nope", p_name: "nope" }], ["vault_delete_secret", { secret_id: beforeA.connection.secret_reference }]]) assert.ok((await own.caller.rpc(name, args)).error); } }],
    ["P3B-TENANT-018 service-only lifecycle RPCs", async () => { const calls = [["gsc_ensure_connection", { p_business_id: a.businessId }], ["gsc_begin_oauth_attempt", { p_account_id: a.accountId, p_business_id: a.businessId, p_state_hash: "x", p_pkce_verifier: "x", p_expires_at: new Date(Date.now() + 60000).toISOString() }], ["gsc_claim_oauth_attempt", { p_state_hash: "x" }], ["gsc_stage_oauth_secret", { p_attempt_id: crypto.randomUUID(), p_secret_reference: crypto.randomUUID() }], ["gsc_fail_oauth_attempt", { p_attempt_id: crypto.randomUUID(), p_code: "X" }], ["gsc_expire_oauth_attempt", { p_attempt_id: crypto.randomUUID() }], ["gsc_activate_property", { p_attempt_id: crypto.randomUUID(), p_site_url: a.site, p_property_type: "url_prefix", p_permission_level: "siteOwner" }], ["gsc_try_mark_reauthentication_required", { p_business_id: a.businessId, p_connection_id: a.connectionId, p_expected_secret_reference: null }], ["gsc_confirm_credential_health", { p_business_id: a.businessId, p_connection_id: a.connectionId, p_expected_secret_reference: null }], ["gsc_disconnect", { p_business_id: a.businessId, p_connection_id: a.connectionId }], ["organic_ensure_source", { p_business_id: a.businessId, p_source_class: "customer_connected", p_source_kind: "search_console", p_provider_id: "google_search_console", p_connection_id: a.connectionId }], ["organic_begin_run", { p_source_id: a.sourceId }], ["organic_finish_run", { p_run_id: a.runId, p_state: "complete" }]]; for (const own of [a, b]) for (const [name, args] of calls) assert.ok((await own.caller.rpc(name, args)).error, name); }],
    ["P3B-TENANT-019 direct DML denied", async () => { for (const own of [a, b]) { const mutations = [["accounts", "id", own.accountId, { status: "active" }], ["businesses", "id", own.businessId, { name: `tampered-${own.label}` }], ["connections", "id", own.connectionId, { status: "connected" }], ["gsc_connections", "connection_id", own.connectionId, { selected_site_url: own.site }], ["organic_evidence_sources", "id", own.sourceId, { evidence_state: "complete" }], ["organic_evidence_runs", "id", own.runId, { state: "failed" }]]; for (const [table, key, id, change] of mutations) { assert.ok((await own.caller.from(table).insert({})).error, `${table} insert`); assert.ok((await own.caller.from(table).update(change).eq(key, id)).error, `${table} update`); assert.ok((await own.caller.from(table).delete().eq(key, id)).error, `${table} delete`); } const attempts = await admin.from("gsc_oauth_attempts").select("id").eq("connection_id", own.connectionId).limit(1); assert.ifError(attempts.error); if (attempts.data?.[0]) { for (const action of ["insert", "update", "delete"]) { const result = action === "insert" ? own.caller.from("gsc_oauth_attempts").insert({}) : action === "update" ? own.caller.from("gsc_oauth_attempts").update({ status: "failed" }).eq("id", attempts.data[0].id) : own.caller.from("gsc_oauth_attempts").delete().eq("id", attempts.data[0].id); assert.ok((await result).error, `gsc_oauth_attempts ${action}`); } } } }],
    ["P3B-TENANT-020 final foreign-attack side-effect audit", async () => { for (const [own, before] of [[a, beforeA], [b, beforeB]]) { const after = await inventory(own); assert.deepEqual(after.connection, before.connection); assert.deepEqual(after.source, before.source); const status = await request(appServer, "GET", "/api/product/organic-evidence/search-console/status", own.token); assert.equal(status.status, 200); assert.equal(status.body.selected_property, own.site); assert.equal(status.body.evidence_state, "complete"); const health = await request(appServer, "POST", "/api/product/organic-evidence/search-console/reauth-check", own.token, { connection_id: own.connectionId }); assert.equal(health.status, 200); } assert.equal(counters.exchange, 3); }]
  ];
  for (const [name, fn] of cases) await t.test(name, fn);
});
