import test from "node:test";
import assert from "node:assert/strict";
import crypto from "node:crypto";
import http from "node:http";
import express from "express";
import { createClient } from "@supabase/supabase-js";
import route from "../routes/googleSearchConsole.js";
import { setGoogleSearchConsoleTransportFactory } from "../product-kernel/googleSearchConsoleOAuth.js";

const enabled = process.env.V1_04_P3A3_INTEGRATION === "1";
const required = n => process.env[n] || (() => { throw new Error(`${n} required`); })();
const req = (server, method, path, token, body) => new Promise((resolve, reject) => { const headers = { "content-type": "application/json" }; if (token) headers.authorization = `Bearer ${token}`; const r = http.request({ hostname: "127.0.0.1", port: server.address().port, method, path, headers }, res => { let text = ""; res.on("data", c => { text += c; }); res.on("end", () => { let parsed = null; try { parsed = text ? JSON.parse(text) : null; } catch {} resolve({ status: res.statusCode, body: parsed, text }); }); }); r.on("error", reject); if (body) r.write(JSON.stringify(body)); r.end(); });

test("P3-A3 disconnect and lifecycle-race matrix", { skip: !enabled }, async t => {
  const url = required("SUPABASE_URL"), key = required("SUPABASE_PUBLISHABLE_KEY"), service = required("SUPABASE_SERVICE_ROLE_KEY"); const admin = createClient(url, service, { auth: { persistSession: false } }); let exchange = 0;
  setGoogleSearchConsoleTransportFactory(() => ({ authorizationUrl: ({ state }) => `https://accounts.google.test/authorize?state=${state}`, exchangeCode: async () => ({ refresh_token: `synthetic-p3a3-${++exchange}`, scope: "https://www.googleapis.com/auth/webmasters.readonly" }), accessToken: async () => "synthetic-access", sitesList: async () => ({ siteEntry: [{ siteUrl: "https://example.com/shop/", permissionLevel: "siteOwner" }, { siteUrl: "sc-domain:example.com", permissionLevel: "siteFullUser" }] }), site: async (_a, siteUrl) => ({ siteUrl, permissionLevel: "siteOwner" }) }));
  async function active() {
    const email = `v104-p3a3-${crypto.randomUUID()}@local.test`, password = `${crypto.randomUUID()}!Aa9`; const u = await admin.auth.admin.createUser({ email, password, email_confirm: true }); assert.ifError(u.error); const userId = u.data.user.id; const client = createClient(url, key, { auth: { persistSession: false } }); const signed = await client.auth.signInWithPassword({ email, password }); assert.ifError(signed.error); const token = signed.data.session.access_token; const caller = createClient(url, key, { global: { headers: { authorization: `Bearer ${token}` } }, auth: { persistSession: false } }); assert.ifError((await caller.rpc("product_create_account", { p_correlation_id: crypto.randomUUID() })).error); const b = await caller.rpc("product_create_business", { p_name: "P3-A3 synthetic disconnect", p_platform: "woocommerce", p_correlation_id: crypto.randomUUID() }); assert.ifError(b.error); const wc = await caller.rpc("product_create_connection", { p_provider_type: "woocommerce", p_correlation_id: crypto.randomUUID() }); assert.ifError(wc.error); const a = await admin.from("accounts").select("id").eq("auth_user_id", userId).single(); assert.ifError(a.error); const wu = `p3a3-${crypto.randomUUID()}`; const wa = await admin.rpc("woo_create_auth_attempt", { p_user_id: wu, p_account_id: a.data.id, p_business_id: b.data.id, p_connection_id: wc.data.id, p_canonical_base_url: "https://example.com/shop/", p_expires_at: new Date(Date.now() + 60000).toISOString() }); assert.ifError(wa.error); assert.ifError((await admin.rpc("woo_claim_auth_attempt", { p_user_id: wu })).error); assert.ifError((await admin.rpc("woo_capture_callback", { p_attempt_id: wa.data, p_consumer_key: "synthetic-key", p_consumer_secret: "synthetic-secret", p_key_permissions: "read" })).error); assert.ifError((await admin.rpc("woo_complete_connection", { p_attempt_id: wa.data, p_home_url: "https://example.com/shop/", p_site_url: "https://example.com/shop/", p_version: "synthetic", p_timezone: "UTC", p_currency: "GBP", p_correlation_id: crypto.randomUUID() })).error);
    const app = express(); app.use(express.json()); app.use(route); const server = await new Promise((resolve, reject) => { const s = app.listen(0, "127.0.0.1", () => resolve(s)); s.on("error", reject); }); const start = async () => { const r = await req(server, "POST", "/api/product/organic-evidence/search-console/connect", token, {}); assert.equal(r.status, 201, r.text); return new URL(r.body.authorization_url).searchParams.get("state"); }; const connect = async site => { const state = await start(); assert.equal((await req(server, "GET", `/api/product/organic-evidence/search-console/callback?state=${encodeURIComponent(state)}&code=synthetic`, null)).status, 200); const g = await admin.from("gsc_connections").select("connection_id").eq("business_id", b.data.id).single(); assert.ifError(g.error); const selected = await req(server, "POST", "/api/product/organic-evidence/search-console/select", token, { connection_id: g.data.connection_id, site_url: site }); assert.equal(selected.status, 200, selected.text); return g.data.connection_id; }; const id = await connect("https://example.com/shop/"); const run = await admin.rpc("organic_begin_run", { p_source_id: (await admin.from("organic_evidence_sources").select("id").eq("connection_id", id).single()).data.id, p_retrieved_at: new Date().toISOString() }); assert.ifError(run.error); assert.ifError((await admin.rpc("organic_finish_run", { p_run_id: run.data.id, p_state: "complete", p_completeness_state: "complete", p_evidence_as_of: "2026-09-01T10:00:00Z" })).error); return { userId, businessId: b.data.id, token, server, id, start, connect, cleanup: async () => { await new Promise(resolve => server.close(resolve)); await admin.auth.admin.deleteUser(userId); } }; }
  t.after(() => setGoogleSearchConsoleTransportFactory(undefined));
  const disconnect = async f => req(f.server, "POST", "/api/product/organic-evidence/search-console/disconnect", f.token, { connection_id: f.id });
  const state = async f => { const c = await admin.from("connections").select("status,consent_state,secret_reference,disconnected_at").eq("id", f.id).single(); const g = await admin.from("gsc_connections").select("connection_state,selected_site_url").eq("connection_id", f.id).single(); const s = await admin.from("organic_evidence_sources").select("evidence_state,current_complete_run,evidence_as_of").eq("connection_id", f.id).single(); return { c: c.data, g: g.data, s: s.data }; };
  await t.test("P3A-DISCONNECT-001 active connection with LKG", async () => { const f = await active(); const before = await state(f); const r = await disconnect(f); assert.equal(r.status, 200); assert.equal(r.body.remote_google_revocation_requested, false); const after = await state(f); assert.equal(after.c.status, "disconnected"); assert.equal(after.c.secret_reference, null); assert.equal(after.g.connection_state, "disconnected"); assert.equal(after.s.evidence_state, "stale"); assert.equal(after.s.current_complete_run, before.s.current_complete_run); assert.equal(after.s.evidence_as_of, before.s.evidence_as_of); await f.cleanup(); });
  await t.test("P3A-DISCONNECT-002 pending reconnect", async () => { const f = await active(); const s = await f.start(); const r = await disconnect(f); assert.equal(r.status, 200); assert.equal((await req(f.server, "GET", `/api/product/organic-evidence/search-console/callback?state=${encodeURIComponent(s)}&code=synthetic`, null)).status, 400); assert.equal((await state(f)).c.status, "disconnected"); await f.cleanup(); });
  await t.test("P3A-DISCONNECT-003 staged reconnect and references", async () => { const f = await active(); const s = await f.start(); assert.equal((await req(f.server, "GET", `/api/product/organic-evidence/search-console/callback?state=${encodeURIComponent(s)}&code=synthetic`, null)).status, 200); assert.equal((await disconnect(f)).status, 200); const attempts = await admin.from("gsc_oauth_attempts").select("status,staged_secret_reference").eq("connection_id", f.id).in("status", ["pending", "processing"]); assert.equal(attempts.data.length, 0); await f.cleanup(); });
  await t.test("P3A-DISCONNECT-004 from reauthentication_required", async () => { const f = await active(); const c = await admin.from("connections").select("secret_reference").eq("id", f.id).single(); assert.ifError(c.error); assert.ifError((await admin.rpc("gsc_mark_reauthentication_required", { p_business_id: f.businessId, p_connection_id: f.id, p_expected_secret_reference: c.data.secret_reference })).error); assert.equal((await disconnect(f)).status, 200); assert.equal((await state(f)).g.connection_state, "disconnected"); await f.cleanup(); });
  await t.test("P3A-DISCONNECT-005 repeated disconnect", async () => { const f = await active(); const first = await disconnect(f); const firstState = await state(f); const second = await disconnect(f); const secondState = await state(f); assert.equal(first.status, 200); assert.equal(second.status, 200); assert.equal(secondState.c.disconnected_at, firstState.c.disconnected_at); assert.deepEqual(secondState.s, firstState.s); await f.cleanup(); });
  await t.test("P3A-DISCONNECT-006 reconnect after disconnect", async () => { const f = await active(); await disconnect(f); const id = await f.connect("https://example.com/shop/"); const now = await state(f); assert.equal(id, f.id); assert.equal(now.c.status, "connected"); assert.equal(now.c.disconnected_at, null); assert.equal(now.s.evidence_state, "stale"); await f.cleanup(); });
  await t.test("P3A-DISCONNECT-007 property change after disconnect", async () => { const f = await active(); const before = await state(f); await disconnect(f); await f.connect("sc-domain:example.com"); const after = await state(f); assert.equal(after.g.selected_site_url, "sc-domain:example.com"); assert.equal(after.s.current_complete_run, null); assert.equal(after.s.evidence_state, "never_collected"); assert.notEqual(before.s.current_complete_run, null); await f.cleanup(); });
  await t.test("P3A-DISCONNECT-008 no remote Google revocation claim", async () => { const f = await active(); const r = await disconnect(f); assert.equal(r.body.remote_google_revocation_requested, false); assert.equal(r.body.local_credential_removed, true); await f.cleanup(); });
  await t.test("P3A-RACE-001 reconnect start versus disconnect", async () => { const f = await active(); const results = await Promise.all([f.start(), disconnect(f)]); assert.ok(results[0] === undefined || typeof results[0] === "string"); const s = await state(f); assert.ok(["connected", "disconnected"].includes(s.c.status)); await f.cleanup(); });
  await t.test("P3A-RACE-002 activation versus disconnect", async () => { const f = await active(); const s = await f.start(); await new Promise(resolve => req(f.server, "GET", `/api/product/organic-evidence/search-console/callback?state=${encodeURIComponent(s)}&code=synthetic`, null).then(resolve)); const [a, d] = await Promise.all([req(f.server, "POST", "/api/product/organic-evidence/search-console/select", f.token, { connection_id: f.id, site_url: "https://example.com/shop/" }), disconnect(f)]); assert.ok([200, 409].includes(a.status)); assert.equal(d.status, 200); assert.equal((await state(f)).c.status, "disconnected"); await f.cleanup(); });
  await t.test("P3A-RACE-003 reauth mark versus reconnect activation", async () => { const f = await active(); const old = (await state(f)).c.secret_reference; const s = await f.start(); await req(f.server, "GET", `/api/product/organic-evidence/search-console/callback?state=${encodeURIComponent(s)}&code=synthetic`, null); await req(f.server, "POST", "/api/product/organic-evidence/search-console/select", f.token, { connection_id: f.id, site_url: "https://example.com/shop/" }); const stale = await admin.rpc("gsc_try_mark_reauthentication_required", { p_business_id: f.businessId, p_connection_id: f.id, p_expected_secret_reference: old }); assert.ifError(stale.error); assert.equal(stale.data, false); assert.equal((await state(f)).g.connection_state, "connected"); await f.cleanup(); });
  await t.test("P3A-RACE-004 reauth mark versus disconnect", async () => { const f = await active(); const old = (await state(f)).c.secret_reference; await disconnect(f); const stale = await admin.rpc("gsc_try_mark_reauthentication_required", { p_business_id: f.businessId, p_connection_id: f.id, p_expected_secret_reference: old }); assert.ifError(stale.error); assert.equal(stale.data, false); assert.equal((await state(f)).g.connection_state, "disconnected"); await f.cleanup(); });
});
