import test from "node:test";
import assert from "node:assert/strict";
import crypto from "node:crypto";
import http from "node:http";
import express from "express";
import { createClient } from "@supabase/supabase-js";
import route from "../routes/googleSearchConsole.js";
import { ProductError } from "../product-kernel/errors.js";
import { setGoogleSearchConsoleTransportFactory } from "../product-kernel/googleSearchConsoleOAuth.js";

const enabled = process.env.V1_04_P3A2_INTEGRATION === "1";
const required = name => process.env[name] || (() => { throw new Error(`${name} required`); })();
const request = (server, method, path, token, body) => new Promise((resolve, reject) => { const headers = { "content-type": "application/json" }; if (token) headers.authorization = `Bearer ${token}`; const req = http.request({ hostname: "127.0.0.1", port: server.address().port, method, path, headers }, res => { let text = ""; res.on("data", c => { text += c; }); res.on("end", () => { let body = null; try { body = text ? JSON.parse(text) : null; } catch {} resolve({ status: res.statusCode, body, text }); }); }); req.on("error", reject); if (body) req.write(JSON.stringify(body)); req.end(); });

test("P3-A2 reauthentication and credential-health matrix", { skip: !enabled }, async t => {
  const url = required("SUPABASE_URL"), key = required("SUPABASE_PUBLISHABLE_KEY"), service = required("SUPABASE_SERVICE_ROLE_KEY");
  const admin = createClient(url, service, { auth: { persistSession: false } });
  let mode = "success", exchanges = 0, held = null, release = null;
  setGoogleSearchConsoleTransportFactory(() => ({
    authorizationUrl: ({ state }) => `https://accounts.google.test/authorize?state=${state}`,
    async exchangeCode() { exchanges += 1; return { refresh_token: `synthetic-p3a2-${exchanges}`, scope: "https://www.googleapis.com/auth/webmasters.readonly" }; },
    async accessToken() { const gate = held; held = null; if (gate) { gate(); await new Promise(resolve => { release = resolve; }); } if (mode === "invalid-grant") throw new ProductError("GSC_REAUTH_REQUIRED", "Synthetic reconnect required.", 409); if (mode === "transient") throw new ProductError("GSC_PROVIDER_ERROR", "Synthetic temporary failure.", 502); return "synthetic-access"; },
    async sitesList() { return { siteEntry: [{ siteUrl: "https://example.com/shop/", permissionLevel: "siteOwner" }] }; },
    async site(_access, siteUrl) { return { siteUrl, permissionLevel: "siteOwner" }; }
  }));

  async function fixture() {
    const email = `v104-p3a2-${crypto.randomUUID()}@local.test`, password = `${crypto.randomUUID()}!Aa9`;
    const made = await admin.auth.admin.createUser({ email, password, email_confirm: true }); assert.ifError(made.error); const userId = made.data.user.id;
    const client = createClient(url, key, { auth: { persistSession: false } }); const signed = await client.auth.signInWithPassword({ email, password }); assert.ifError(signed.error); const token = signed.data.session.access_token;
    const caller = createClient(url, key, { global: { headers: { authorization: `Bearer ${token}` } }, auth: { persistSession: false } });
    assert.ifError((await caller.rpc("product_create_account", { p_correlation_id: crypto.randomUUID() })).error);
    const b = await caller.rpc("product_create_business", { p_name: "P3-A2 synthetic health", p_platform: "woocommerce", p_correlation_id: crypto.randomUUID() }); assert.ifError(b.error);
    const wc = await caller.rpc("product_create_connection", { p_provider_type: "woocommerce", p_correlation_id: crypto.randomUUID() }); assert.ifError(wc.error);
    const account = await admin.from("accounts").select("id").eq("auth_user_id", userId).single(); assert.ifError(account.error);
    const wu = `p3a2-${crypto.randomUUID()}`; const wa = await admin.rpc("woo_create_auth_attempt", { p_user_id: wu, p_account_id: account.data.id, p_business_id: b.data.id, p_connection_id: wc.data.id, p_canonical_base_url: "https://example.com/shop/", p_expires_at: new Date(Date.now() + 60000).toISOString() }); assert.ifError(wa.error); assert.ifError((await admin.rpc("woo_claim_auth_attempt", { p_user_id: wu })).error); assert.ifError((await admin.rpc("woo_capture_callback", { p_attempt_id: wa.data, p_consumer_key: "synthetic-key", p_consumer_secret: "synthetic-secret", p_key_permissions: "read" })).error); assert.ifError((await admin.rpc("woo_complete_connection", { p_attempt_id: wa.data, p_home_url: "https://example.com/shop/", p_site_url: "https://example.com/shop/", p_version: "synthetic", p_timezone: "UTC", p_currency: "GBP", p_correlation_id: crypto.randomUUID() })).error);
    const app = express(); app.use(express.json()); app.use(route); const server = await new Promise((resolve, reject) => { const s = app.listen(0, "127.0.0.1", () => resolve(s)); s.on("error", reject); });
    const start = async () => { const r = await request(server, "POST", "/api/product/organic-evidence/search-console/connect", token, {}); assert.equal(r.status, 201, r.text); const state = new URL(r.body.authorization_url).searchParams.get("state"); const hash = crypto.createHash("sha256").update(state).digest("base64url"); const a = await admin.from("gsc_oauth_attempts").select("id").eq("state_hash", hash).single(); assert.ifError(a.error); assert.ifError((await admin.rpc("gsc_claim_oauth_attempt", { p_state_hash: hash })).error); assert.ifError((await admin.rpc("gsc_stage_oauth_secret", { p_attempt_id: a.data.id, p_secret_reference: null })).error); return a.data.id; };
    const cleanup = async () => { await new Promise(resolve => server.close(resolve)); await admin.auth.admin.deleteUser(userId); };
    return { userId, b: b.data.id, token, caller, server, start, cleanup };
  }
  t.after(() => setGoogleSearchConsoleTransportFactory(undefined));

  async function active() {
    const f = await fixture(); const started = await request(f.server, "POST", "/api/product/organic-evidence/search-console/connect", f.token, {}); assert.equal(started.status, 201, started.text); const state = new URL(started.body.authorization_url).searchParams.get("state"); const cb = await request(f.server, "GET", `/api/product/organic-evidence/search-console/callback?state=${encodeURIComponent(state)}&code=synthetic`, null); assert.equal(cb.status, 200, cb.text); const gsc = await admin.from("gsc_connections").select("connection_id").eq("business_id", f.b).single(); assert.ifError(gsc.error); const id = gsc.data.connection_id; const sel = await request(f.server, "POST", "/api/product/organic-evidence/search-console/select", f.token, { connection_id: id, site_url: "https://example.com/shop/" }); assert.equal(sel.status, 200, sel.text); return { ...f, id }; }

  await t.test("P3A-REAUTH-001 valid active credential", async () => { const f = await active(); const r = await request(f.server, "POST", "/api/product/organic-evidence/search-console/reauth-check", f.token, { connection_id: f.id }); assert.equal(r.status, 200, r.text); assert.equal(r.body.status, "connected"); await f.cleanup(); });
  await t.test("P3A-REAUTH-002 current invalid_grant", async () => { const f = await active(); mode = "invalid-grant"; const r = await request(f.server, "POST", "/api/product/organic-evidence/search-console/reauth-check", f.token, { connection_id: f.id }); assert.equal(r.status, 409); assert.equal(r.body.error.code, "GSC_REAUTH_REQUIRED"); const g = await admin.from("gsc_connections").select("connection_state").eq("connection_id", f.id).single(); assert.equal(g.data.connection_state, "reauthentication_required"); mode = "success"; await f.cleanup(); });
  await t.test("P3A-REAUTH-003 transient provider failure", async () => { const f = await active(); mode = "transient"; const r = await request(f.server, "POST", "/api/product/organic-evidence/search-console/reauth-check", f.token, { connection_id: f.id }); assert.equal(r.status, 502); assert.equal(r.body.error.code, "GSC_PROVIDER_ERROR"); const g = await admin.from("gsc_connections").select("connection_state").eq("connection_id", f.id).single(); assert.equal(g.data.connection_state, "connected"); mode = "success"; await f.cleanup(); });
  await t.test("P3A-REAUTH-004 no active secret reference", async () => { const f = await active(); assert.ifError((await admin.from("connections").update({ secret_reference: null }).eq("id", f.id)).error); const r = await request(f.server, "POST", "/api/product/organic-evidence/search-console/reauth-check", f.token, { connection_id: f.id }); assert.equal(r.status, 409); assert.equal(r.body.error.code, "GSC_REAUTH_REQUIRED"); await f.cleanup(); });
  await t.test("P3A-REAUTH-005 missing Vault value", async () => { const f = await active(); assert.ifError((await admin.from("connections").update({ secret_reference: crypto.randomUUID() }).eq("id", f.id)).error); const r = await request(f.server, "POST", "/api/product/organic-evidence/search-console/reauth-check", f.token, { connection_id: f.id }); assert.equal(r.status, 409); assert.equal(r.body.error.code, "GSC_REAUTH_REQUIRED"); await f.cleanup(); });
  await t.test("P3A-REAUTH-006 malformed stored credential vectors", async () => { const f = await active(); const c = await admin.from("connections").select("secret_reference").eq("id", f.id).single(); assert.ifError(c.error); for (const value of ["not-json", JSON.stringify({}), JSON.stringify({ refresh_token: "" }), JSON.stringify([])]) { const replacement = await admin.rpc("vault_create_secret", { secret_value: value, secret_name: "synthetic-p3a2-malformed" }); assert.ifError(replacement.error); assert.ifError((await admin.from("connections").update({ secret_reference: replacement.data }).eq("id", f.id)).error); const r = await request(f.server, "POST", "/api/product/organic-evidence/search-console/reauth-check", f.token, { connection_id: f.id }); assert.equal(r.status, 409); assert.equal(r.body.error.code, "GSC_REAUTH_REQUIRED"); await admin.rpc("vault_delete_secret", { secret_id: replacement.data }); } await admin.from("connections").update({ secret_reference: c.data.secret_reference }).eq("id", f.id); await f.cleanup(); });
  await t.test("P3A-REAUTH-007 failed reconnect from reauthentication_required", async () => { const f = await active(); mode = "invalid-grant"; await request(f.server, "POST", "/api/product/organic-evidence/search-console/reauth-check", f.token, { connection_id: f.id }); const r = await request(f.server, "POST", "/api/product/organic-evidence/search-console/reconnect", f.token, {}); assert.equal(r.status, 201); mode = "success"; await f.cleanup(); });
  await t.test("P3A-REAUTH-008 successful reconnect from reauthentication_required", async () => { const f = await active(); mode = "invalid-grant"; await request(f.server, "POST", "/api/product/organic-evidence/search-console/reauth-check", f.token, { connection_id: f.id }); mode = "success"; const r = await request(f.server, "POST", "/api/product/organic-evidence/search-console/reconnect", f.token, {}); assert.equal(r.status, 201); await f.cleanup(); });
  await t.test("P3A-REAUTH-009 stale invalid_grant after reconnect", async () => { const f = await active(); const before = await admin.from("connections").select("secret_reference").eq("id", f.id).single(); assert.ifError(before.error); const started = await request(f.server, "POST", "/api/product/organic-evidence/search-console/reconnect", f.token, {}); assert.equal(started.status, 201); const state = new URL(started.body.authorization_url).searchParams.get("state"); assert.equal((await request(f.server, "GET", `/api/product/organic-evidence/search-console/callback?state=${encodeURIComponent(state)}&code=synthetic`, null)).status, 200); assert.equal((await request(f.server, "POST", "/api/product/organic-evidence/search-console/select", f.token, { connection_id: f.id, site_url: "https://example.com/shop/" })).status, 200); const stale = await admin.rpc("gsc_try_mark_reauthentication_required", { p_business_id: f.b, p_connection_id: f.id, p_expected_secret_reference: before.data.secret_reference }); assert.ifError(stale.error); assert.equal(stale.data, false); const g = await admin.from("gsc_connections").select("connection_state").eq("connection_id", f.id).single(); assert.equal(g.data.connection_state, "connected"); await f.cleanup(); });
  await t.test("P3A-REAUTH-010 stale invalid_grant after disconnect", async () => { const f = await active(); const before = await admin.from("connections").select("secret_reference").eq("id", f.id).single(); assert.ifError(before.error); assert.equal((await request(f.server, "POST", "/api/product/organic-evidence/search-console/disconnect", f.token, { connection_id: f.id })).status, 200); const stale = await admin.rpc("gsc_try_mark_reauthentication_required", { p_business_id: f.b, p_connection_id: f.id, p_expected_secret_reference: before.data.secret_reference }); assert.ifError(stale.error); assert.equal(stale.data, false); const g = await admin.from("gsc_connections").select("connection_state").eq("connection_id", f.id).single(); assert.equal(g.data.connection_state, "disconnected"); await f.cleanup(); });
  await t.test("P3A-REAUTH-011 stale no-secret observation after reconnect", async () => { const f = await active(); assert.ifError((await admin.from("connections").update({ secret_reference: null }).eq("id", f.id)).error); const started = await request(f.server, "POST", "/api/product/organic-evidence/search-console/reconnect", f.token, {}); assert.equal(started.status, 201); const state = new URL(started.body.authorization_url).searchParams.get("state"); assert.equal((await request(f.server, "GET", `/api/product/organic-evidence/search-console/callback?state=${encodeURIComponent(state)}&code=synthetic`, null)).status, 200); assert.equal((await request(f.server, "POST", "/api/product/organic-evidence/search-console/select", f.token, { connection_id: f.id, site_url: "https://example.com/shop/" })).status, 200); const stale = await admin.rpc("gsc_try_mark_reauthentication_required", { p_business_id: f.b, p_connection_id: f.id, p_expected_secret_reference: null }); assert.ifError(stale.error); assert.equal(stale.data, false); const g = await admin.from("gsc_connections").select("connection_state").eq("connection_id", f.id).single(); assert.equal(g.data.connection_state, "connected"); await f.cleanup(); });
  await t.test("P3A-REAUTH-012 stale successful health check after disconnect", async () => { const f = await active(); const before = await admin.from("connections").select("secret_reference").eq("id", f.id).single(); assert.ifError(before.error); assert.equal((await request(f.server, "POST", "/api/product/organic-evidence/search-console/disconnect", f.token, { connection_id: f.id })).status, 200); const current = await admin.rpc("gsc_confirm_credential_health", { p_business_id: f.b, p_connection_id: f.id, p_expected_secret_reference: before.data.secret_reference }); assert.ifError(current.error); assert.equal(current.data, false); const g = await admin.from("gsc_connections").select("connection_state").eq("connection_id", f.id).single(); assert.equal(g.data.connection_state, "disconnected"); await f.cleanup(); });
});
