import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { GSC_SCOPE, createGscTransport, normalizeProperty, propertyMatches, publicSuffixRegistrableDomain } from "../product-kernel/googleSearchConsoleOAuth.js";

const env={GOOGLE_SEARCH_CONSOLE_CLIENT_ID:"client",GOOGLE_SEARCH_CONSOLE_CLIENT_SECRET:"secret",GOOGLE_SEARCH_CONSOLE_CALLBACK_URL:"https://product.example/api/product/organic-evidence/search-console/callback"};
test("B1 OAuth URL is exact-scope offline PKCE",()=>{const t=createGscTransport({env,fetchImpl:async()=>{throw new Error("network not allowed");}});const u=new URL(t.authorizationUrl({state:"state",verifier:"verifier"}));assert.equal(u.searchParams.get("scope"),GSC_SCOPE);assert.equal(u.searchParams.get("response_type"),"code");assert.equal(u.searchParams.get("access_type"),"offline");assert.equal(u.searchParams.get("include_granted_scopes"),"false");assert.equal(u.searchParams.get("code_challenge_method"),"S256");assert.equal(u.searchParams.get("redirect_uri"),env.GOOGLE_SEARCH_CONSOLE_CALLBACK_URL);});
test("B1 property normalisation is PSL-aware",()=>{assert.equal(publicSuffixRegistrableDomain("streetkingz.co.uk"),"streetkingz.co.uk");assert.equal(publicSuffixRegistrableDomain("shop.example.co.uk"),"example.co.uk");assert.equal(normalizeProperty("sc-domain:streetkingz.co.uk").type,"domain");assert.equal(normalizeProperty("sc-domain:localhost"),null);assert.equal(normalizeProperty("sc-domain:example.co.uk.evil"),null);});
test("B1 URL-prefix and domain matching is strict",()=>{assert.equal(propertyMatches("https://example.com/","https://example.com/shop/"),true);assert.equal(propertyMatches("https://example.com/shop/","https://example.com/shop/products"),true);assert.equal(propertyMatches("https://example.com/shop/","https://example.com/blog/"),false);assert.equal(propertyMatches("https://www.example.com/","https://example.com/"),false);assert.equal(propertyMatches("http://example.com/","https://example.com/"),false);assert.equal(propertyMatches("sc-domain:example.co.uk","https://shop.example.co.uk/"),true);assert.equal(propertyMatches("sc-domain:example.co.uk","https://example.com/"),false);});
test("B1 is connection/property selection only and does not collect evidence",()=>{const route=fs.readFileSync(new URL("../routes/googleSearchConsole.js",import.meta.url),"utf8");const migration=fs.readFileSync(new URL("../supabase/migrations/20260904000000_v1_04_gsc_connection.sql",import.meta.url),"utf8");assert.match(route,/gsc_oauth_attempts/);assert.match(route,/organic_ensure_source/);assert.doesNotMatch(route,/searchAnalytics|querySearchAnalytics/);assert.match(migration,/connection_state/);assert.match(migration,/gsc_oauth_attempts/);});
