import test from "node:test";
import assert from "node:assert/strict";
import http from "node:http";
import express from "express";
import { createV103AcceptanceHarnessRouter } from "../routes/v1-03AcceptanceHarness.js";

const ids = { account: "11111111-1111-4111-8111-111111111111", business: "22222222-2222-4222-8222-222222222222", connection: "33333333-3333-4333-8333-333333333333", store: "44444444-4444-4444-8444-444444444444", generation: 17, user: "user-acceptance" };
function chain(data, error = null) { const state = { data, error }; const query = { select() { return this; }, eq() { return this; }, maybeSingle() { return Promise.resolve(state); }, then(resolve, reject) { return Promise.resolve(state).then(resolve, reject); } }; return query; }
function fixture({ businesses = [{ id: ids.business, account_id: ids.account }], connection = {}, store = {}, generation = {} } = {}) { const calls = []; const admin = { from(table) { calls.push(table); if (table === "businesses") return chain(businesses); if (table === "accounts") return chain({ id: ids.account, auth_user_id: ids.user, status: "active" }); if (table === "connections") return chain([{ id: ids.connection, business_id: ids.business, provider_type: "woocommerce", status: "connected", consent_state: "granted", ...connection }]); if (table === "commerce_stores") return chain(store === null ? [] : [{ id: ids.store, connection_id: ids.connection, current_generation: ids.generation, canonical_base_url: "https://streetkingz.co.uk/", ...store }]); if (table === "commerce_sync_generations") return chain(generation === null ? null : { id: ids.generation, state: "complete", ...generation }); throw new Error(`unexpected table ${table}`); }, auth: { admin: { async getUserById() { return { data: { user: { email: "acceptance@example.test" } }, error: null }; }, async updateUserById() { calls.push("password-update"); return { data: {}, error: null }; } } } }; const client = { auth: { async signInWithPassword({ email }) { assert.equal(email, "acceptance@example.test"); calls.push("sign-in"); return { data: { session: { access_token: "temporary-local-token", expires_at: 1900000000, expires_in: 3600 } }, error: null }; } } }; return { calls, adminFactory: () => admin, clientFactory: () => client }; }
function serverFor(router) { return new Promise((resolve, reject) => { const app = express(); app.use(router); const server = app.listen(0, "127.0.0.1", () => resolve(server)); server.once("error", reject); }); }
function request(server, { path = "/internal/v1-03/resume", host = "localhost" } = {}) { return new Promise((resolve, reject) => { const address = server.address(); const req = http.request({ hostname: "127.0.0.1", port: address.port, path, method: "POST", headers: { host, "content-type": "application/json" } }, res => { let text = ""; res.on("data", chunk => text += chunk); res.on("end", () => resolve({ status: res.statusCode, body: text ? JSON.parse(text) : null })); }); req.on("error", reject); req.end("{}"); }); }

test("resume is unavailable through public Host", async t => { const server = await serverFor(createV103AcceptanceHarnessRouter()); t.after(() => server.close()); assert.equal((await request(server, { host: "public-tunnel.example" })).status, 404); });
test("resume refuses hosted Supabase before tenant lookup", async t => { const fixture = { calls: [], adminFactory: () => { throw new Error("must not create admin"); } }; const server = await serverFor(createV103AcceptanceHarnessRouter({ config: () => ({ url: "https://hosted.supabase.co", privilegedKey: "service", publishableKey: "publishable" }), ...fixture })); t.after(() => server.close()); const result = await request(server); assert.equal(result.status, 403); assert.equal(result.body.error.code, "LOCAL_SUPABASE_REQUIRED"); });
test("resume rejects zero and multiple matching acceptance tenants without mutation", async t => { for (const businesses of [[], [{ id: ids.business, account_id: ids.account }, { id: "55555555-5555-4555-8555-555555555555", account_id: ids.account }]]) { const testFixture = fixtureFor(businesses); const server = await serverFor(createV103AcceptanceHarnessRouter({ config: () => ({ url: "http://127.0.0.1:54321", privilegedKey: "service", publishableKey: "publishable" }), ...testFixture })); const result = await request(server); t.after(() => server.close()); assert.equal(result.status, businesses.length > 1 ? 409 : 404); assert.equal(result.body.error.code, businesses.length > 1 ? "ACCEPTANCE_SESSION_AMBIGUOUS" : "ACCEPTANCE_SESSION_NOT_FOUND"); assert.equal(testFixture.calls.includes("password-update"), false); assert.equal(testFixture.calls.includes("sign-in"), false); } });
test("resume signs into the exact existing connected acceptance tenant", async t => { const fixture = fixtureFor([ { id: ids.business, account_id: ids.account } ]); const server = await serverFor(createV103AcceptanceHarnessRouter({ config: () => ({ url: "http://127.0.0.1:54321", privilegedKey: "service", publishableKey: "publishable" }), ...fixture })); t.after(() => server.close()); const result = await request(server); assert.equal(result.status, 200); assert.deepEqual(result.body, { access_token: "temporary-local-token", expires_at: 1900000000, expires_in: 3600 }); assert.deepEqual(fixture.calls, ["businesses", "accounts", "connections", "commerce_stores", "commerce_sync_generations", "password-update", "sign-in"]); });

test("resume ignores incomplete and synthetic candidates and selects exact Street Kingz URL", async t => { for (const store of [{ canonical_base_url: "https://shop.example/" }, { canonical_base_url: "https://www.streetkingz.co.uk/" }, { canonical_base_url: "http://streetkingz.co.uk/" }, { canonical_base_url: "https://streetkingz.co.uk/shop/" }]) { const testFixture = fixture({ store }); const server = await serverFor(createV103AcceptanceHarnessRouter({ config: () => ({ url: "http://127.0.0.1:54321", privilegedKey: "service", publishableKey: "publishable" }), ...testFixture })); const result = await request(server); t.after(() => server.close()); assert.equal(result.status, 404); assert.equal(testFixture.calls.includes("password-update"), false); } });
test("pending and no-store same-name businesses are ignored", async t => { for (const options of [{ connection: { status: "pending", consent_state: "pending" } }, { store: null }]) { const testFixture = fixture(options); const server = await serverFor(createV103AcceptanceHarnessRouter({ config: () => ({ url: "http://127.0.0.1:54321", privilegedKey: "service", publishableKey: "publishable" }), ...testFixture })); const result = await request(server); t.after(() => server.close()); assert.equal(result.status, 404); assert.equal(testFixture.calls.includes("password-update"), false); } });
test("resume uses readiness predicates, not counts or timestamps", async t => { const testFixture = fixture({ store: { canonical_base_url: "https://streetkingz.co.uk/" } }); const server = await serverFor(createV103AcceptanceHarnessRouter({ config: () => ({ url: "http://127.0.0.1:54321", privilegedKey: "service", publishableKey: "publishable" }), ...testFixture })); t.after(() => server.close()); assert.equal((await request(server)).status, 200); assert.ok(testFixture.calls.includes("password-update")); });
test("two exact valid Street Kingz candidates remain ambiguous", async t => { const testFixture = fixture({ businesses: [{ id: ids.business, account_id: ids.account }, { id: "55555555-5555-4555-8555-555555555555", account_id: ids.account }] }); const server = await serverFor(createV103AcceptanceHarnessRouter({ config: () => ({ url: "http://127.0.0.1:54321", privilegedKey: "service", publishableKey: "publishable" }), ...testFixture })); t.after(() => server.close()); const result = await request(server); assert.equal(result.status, 409); assert.equal(result.body.error.code, "ACCEPTANCE_SESSION_AMBIGUOUS"); assert.equal(testFixture.calls.includes("password-update"), false); });

function fixtureFor(businesses) { const base = fixture({ businesses }); return base; }
