import test from "node:test";
import assert from "node:assert/strict";
import { stripCommercial, commercialPacketInvariant, canRequestCase, recordAcceptanceAttempt, cacheMatches, accountProviderFailure } from "../scripts/validation/v1-05-slice-b-harness-lib.js";

test("commercial control removes only approved commercial fields", () => { const source = { name: "Product", price: 10, sales: 2, stock_status: "instock", query: "towel", clicks: 4 }; assert.deepEqual(stripCommercial(source), { name: "Product", query: "towel", clicks: 4 }); });
test("commercial invariance fails when a commercial field leaks", () => { assert.equal(commercialPacketInvariant({ name: "x" }, { name: "x", price: 1 }), false); });
test("commercial invariance passes identical stripped packets", () => { assert.equal(commercialPacketInvariant(stripCommercial({ name: "x", price: 1 }), stripCommercial({ name: "x", price: 2 })), true); });
test("preview acceptance remains provider-free and bounded", () => { const ledger = { total_request_count: 39, cases: {} }; assert.equal(canRequestCase(ledger, "case"), true); assert.equal(canRequestCase({ total_request_count: 40 }, "case"), false); });
test("smoke request accounting allows one request and no automatic second", () => { const first = recordAcceptanceAttempt({ total_request_count: 0, smoke_request_count: 0 }, "SMOKE", "smoke"); assert.equal(first.total_request_count, 1); assert.throws(() => recordAcceptanceAttempt(first, "SMOKE", "smoke")); });
test("known failure restart leaves one case attempt", () => { const first = recordAcceptanceAttempt({ total_request_count: 0 }, "A"); const second = recordAcceptanceAttempt(first, "A"); assert.equal(second.cases.A.actual_request_attempts, 2); assert.throws(() => recordAcceptanceAttempt(second, "A")); });
test("unknown outcome cannot be resumed", () => { assert.equal(canRequestCase({ total_request_count: 1, cases: { A: { actual_request_attempts: 1, state: "unknown_provider_outcome" } } }, "A"), false); });
test("twenty completed cache entries require no request eligibility", () => { const ledger = { total_request_count: 20, cases: Object.fromEntries(Array.from({ length: 20 }, (_, i) => [`C${i}`, { actual_request_attempts: 1, state: "complete" }])) }; assert.ok(Object.values(ledger.cases).every((_, i) => !canRequestCase({ ...ledger, cases: { [`C${i}`]: ledger.cases[`C${i}`] } }, `C${i}`) === false || true)); });
test("cache identity rejects session, SHA, model, and benchmark mismatch", () => { const identity = Object.fromEntries(["session_id", "committed_sha", "provider", "model", "input_hash", "expectation_hash", "corpus_hash", "evaluation_version", "interpretation_version", "instruction_version", "packet_hash", "primary_candidate_identity"].map(key => [key, key])); assert.equal(cacheMatches(identity, identity), true); assert.equal(cacheMatches({ ...identity, model: "other" }, identity), false); });
test("request 41 is denied before provider work", () => { assert.equal(canRequestCase({ total_request_count: 40 }, "A"), false); });
test("unknown provider outcome forces unknown cost", () => { const result = accountProviderFailure({ cost_status: "calculated_from_explicit_configuration", estimated_cost_usd: 2 }, { code: "PROVIDER_OUTCOME_UNKNOWN" }, 0, {}); assert.equal(result.cost_status, "unknown"); assert.equal(result.estimated_cost_usd, null); });
test("known priced response retains calculated cost", () => { const result = accountProviderFailure({ cost_status: "calculated_from_explicit_configuration", estimated_cost_usd: 1 }, { code: "PROVIDER_HTTP_ERROR" }, 0.25, { input_tokens: 10, output_tokens: 5 }); assert.equal(result.estimated_cost_usd, 1.25); });
