import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { canonicalize, sha256 } from "../research/core/canonical.js";
import { validateVoiceCorpusArtifact, importVoiceCorpus } from "../voice/import.js";
import { analyzeVoiceSources } from "../voice/analysis.js";
import { buildExpandedStreetKingzFounderProfile, STREET_KINGZ_VOICE_SOURCES } from "../voice/street-kingz.js";
import { validateVoiceProfile } from "../voice/profile.js";

const load = () => readFile("imports/voice/street-kingz/voice-corpus.json", "utf8").then(JSON.parse);
const rehash = (artifact) => { const value = structuredClone(artifact); delete value.semantic_sha256; artifact.semantic_sha256 = sha256(canonicalize(value)); return artifact; };

test("valid Voice Corpus v1 import verifies hashes counts provenance and boundaries", async () => { const artifact = await load(); const result = validateVoiceCorpusArtifact(artifact); assert.equal(result.status, "PASS", JSON.stringify(result.errors)); assert.equal(result.observed_semantic_sha256, "8514eb2c52735720e6f06af2515a5a167356d80e75250b3161baa7758c90a3bf"); assert.deepEqual(result.metrics, { sources: 24, words: 4205, spoken_sources: 24, written_sources: 0, duplicate_ids: 0, duplicate_texts: 0, excluded_upstream: 408 }); });
test("invalid schema rejects", async () => { const artifact = await load(); artifact.schema_version = "2.0.0"; rehash(artifact); assert.ok(validateVoiceCorpusArtifact(artifact).errors.some((item) => item.code === "SCHEMA_VERSION")); });
test("semantic hash mismatch rejects", async () => { const artifact = await load(); artifact.corpus_id = "changed"; assert.ok(validateVoiceCorpusArtifact(artifact).errors.some((item) => item.code === "SEMANTIC_HASH_MISMATCH")); });
test("individual source hash mismatch rejects", async () => { const artifact = await load(); artifact.sources[0].text += " changed"; rehash(artifact); assert.ok(validateVoiceCorpusArtifact(artifact).errors.some((item) => item.code === "SOURCE_HASH_MISMATCH")); });
test("duplicate source IDs reject", async () => { const artifact = await load(); artifact.sources[1].source_id = artifact.sources[0].source_id; rehash(artifact); assert.ok(validateVoiceCorpusArtifact(artifact).errors.some((item) => item.code === "DUPLICATE_OR_MISSING_SOURCE_ID")); });
test("AI-generated exported evidence rejects even when internally rehashed", async () => { const artifact = await load(); artifact.sources[0].authorship_classification = "AI_GENERATED"; rehash(artifact); assert.ok(validateVoiceCorpusArtifact(artifact).errors.some((item) => item.code === "INELIGIBLE_EXPORTED_SOURCE")); });
test("third-party exported evidence rejects by default", async () => { const artifact = await load(); artifact.sources[0].authorship_classification = "THIRD_PARTY"; rehash(artifact); assert.ok(validateVoiceCorpusArtifact(artifact).errors.some((item) => item.code === "INELIGIBLE_EXPORTED_SOURCE")); });
test("import preserves modality provenance and text hashes", async () => { const imported = importVoiceCorpus(await load()); const source = imported.sources[0]; assert.equal(source.mode, "spoken"); assert.equal(source.provenance.original_media_filename, "Shampoo lance.mov"); assert.equal(source.text_sha256, "a8539b84667e496a5053487d45df6b648ffe077cdb2a2cdaaf3332134b027c64"); });
test("deterministic analyzer supports spoken-only written-only and mixed corpora", async () => { const imported = importVoiceCorpus(await load()); const written = STREET_KINGZ_VOICE_SOURCES.filter((source) => source.eligible_for_voice_analysis); assert.equal(analyzeVoiceSources(imported.sources).modalities.written.sources, 0); assert.equal(analyzeVoiceSources(written).modalities.spoken.sources, 0); const mixed = analyzeVoiceSources([...imported.sources, ...written]); assert.deepEqual(mixed.modalities, { spoken: { sources: 24, words: 4205 }, written: { sources: 3, words: 409 } }); });
test("expanded observations cite eligible genuine sources", async () => { const imported = importVoiceCorpus(await load()); const { profile, sources } = buildExpandedStreetKingzFounderProfile(imported.sources); assert.equal(validateVoiceProfile(profile, sources).status, "PASS"); for (const observation of profile.observations.filter((item) => item.classification.includes("OBSERVED"))) assert.ok(observation.source_ids.length); });
test("human rules and founder facts remain separate from observed corpus", async () => { const imported = importVoiceCorpus(await load()); const { profile } = buildExpandedStreetKingzFounderProfile(imported.sources); assert.equal(profile.human_rules.length, 0); assert.equal(profile.founder_fact_policy.voice_profile_is_fact_source, false); assert.equal(profile.founder_fact_policy.founder_fact_registry.length, 0); assert.equal(profile.founder_fact_policy.transcript_claims_imported_as_facts, false); assert.ok(profile.observations.filter((item) => item.classification === "EXPLICIT_HUMAN_RULE").every((item) => item.source_ids.length === 0)); });
test("profile construction is deterministic", async () => { const imported = importVoiceCorpus(await load()); const first = buildExpandedStreetKingzFounderProfile(imported.sources).profile; const second = buildExpandedStreetKingzFounderProfile(imported.sources).profile; assert.equal(sha256(first), sha256(second)); });
test("synthetic non-site spoken corpus imports through generic core", async () => { const artifact = await load(); artifact.corpus_id = "north-star-bakery-owner-v1"; artifact.identity = { id: "north-star-owner", display_name: "Owner", brand: "North Star Bakery" }; artifact.sources = [artifact.sources[0]]; artifact.sources[0].source_id = "bakery-audio:1"; artifact.sources[0].provenance = { collection: "bakery-interviews", record_key: "one", derivation: "Owner interview transcript" }; artifact.export_summary = { records_inspected: 1, spoken_sources: 1, written_sources: 0, excluded: { AI_GENERATED: 0, AI_TRANSFORMED: 0, THIRD_PARTY: 0, UNCERTAIN_AUTHORSHIP: 0 }, candidate_sources: 1, eligible_sources_exported: 1, duplicates_excluded: 0, total_words: artifact.sources[0].word_count }; rehash(artifact); assert.equal(importVoiceCorpus(artifact).sources[0].voice_identity, "north-star-owner"); });
test("generic importer and analysis core contain no site identity topic platform or product coupling", async () => { const files = await Promise.all(["voice/import.js", "voice/analysis.js", "voice/corpus.js", "voice/profile.js"].map((file) => readFile(file, "utf8"))); const code = files.join(" ").toLowerCase(); for (const term of ["street kingz", "ben", "tiktok", "car care", "drying towel", "product 70"]) assert.equal(code.includes(term), false, term); });
