import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { createVoiceSource, assessCorpus, validateVoiceSource } from "../voice/corpus.js";
import { approveVoiceProfile, resolveSiteVoiceProfile, validateVoiceProfile, validateVoiceTransformation } from "../voice/profile.js";
import { diagnoseVoiceMismatch } from "../voice/diagnostic.js";
import { STREET_KINGZ_VOICE_SOURCES, buildStreetKingzFounderProfile } from "../voice/street-kingz.js";

const genuine = (overrides = {}) => createVoiceSource({ source_id: "source_1", source_type: "writing_sample", voice_identity: "person-a", authorship_class: "GENUINE_AUTHOR_CONTENT", mode: "written", source_reference: "fixture", content: "A natural sample with enough words to show how this person explains an ordinary decision clearly and directly.", voice_confidence: "high", naturalness: "natural", ...overrides });
const profile = (sources, overrides = {}) => ({ schema_version: "1.0.0", artifact_type: "site_voice_profile", profile_id: "profile-a-v1", site_id: "site-a", voice_identity: "person-a", state: "awaiting_human_review", corpus_assessment: assessCorpus(sources, { minimumWords: 1, minimumEligibleSources: 1 }), observations: [{ observation_id: "obs_1", dimension: "directness", classification: "WEAK_OBSERVED_PATTERN", confidence: "medium", rule: "Be direct.", source_ids: [sources[0].source_id], mode_scope: "both" }], human_rules: [], founder_fact_policy: { voice_profile_is_fact_source: false }, approval: null, limitations: [], ...overrides });

test("video-only genuine speech corpus is supported", () => { const source = genuine({ source_type: "video_transcript", authorship_class: "TRANSCRIBED_GENUINE_SPEECH", mode: "spoken", naturalness: "free_speech" }); const result = assessCorpus([source], { minimumWords: 1, minimumEligibleSources: 1 }); assert.equal(result.sufficient, true); assert.ok(result.spoken_words > 0); });
test("written-only corpus is supported", () => { const result = assessCorpus([genuine()], { minimumWords: 1, minimumEligibleSources: 1 }); assert.equal(result.sufficient, true); assert.ok(result.written_words > 0); });
test("mixed corpus retains spoken and written distinction", () => { const result = assessCorpus([genuine(), genuine({ source_id: "spoken", source_type: "audio_transcript", authorship_class: "TRANSCRIBED_GENUINE_SPEECH", mode: "spoken" })], { minimumWords: 1, minimumEligibleSources: 1 }); assert.ok(result.spoken_words && result.written_words); assert.equal(result.source_type_diversity, 2); });
test("transcript-heavy corpus reports weak written construction", () => { const result = assessCorpus([genuine({ source_type: "video_transcript", authorship_class: "TRANSCRIBED_GENUINE_SPEECH", mode: "spoken" })], { minimumWords: 1, minimumEligibleSources: 1 }); assert.ok(result.weak_areas.includes("long-form written construction")); });
test("insufficient corpus offers collection or default fallback", () => { const result = assessCorpus([]); assert.equal(result.strength, "insufficient"); assert.match(result.recommendation, /configurable default/); });
test("AI-generated and AI-transformed material is excluded", () => { for (const authorship_class of ["AI_GENERATED", "AI_TRANSFORMED"]) { const source = createVoiceSource({ source_id: authorship_class, source_type: "article", voice_identity: "x", authorship_class, mode: "written", source_reference: "fixture", content: "Generated copy", voice_confidence: "low", exclusion_reason: "AI is not voice evidence." }); assert.equal(source.eligible_for_voice_analysis, false); } });
test("uncertain authorship is excluded and must explain why", () => { const source = createVoiceSource({ source_id: "uncertain", source_type: "website_copy", voice_identity: "x", authorship_class: "UNCERTAIN_AUTHORSHIP", mode: "written", source_reference: "fixture", content: "Unknown copy", voice_confidence: "low", exclusion_reason: "Author unknown." }); assert.equal(source.influence_tier, "excluded"); });
test("source quality keeps constrained samples below natural sources", () => { const natural = genuine({ naturalness: "natural" }); const constrained = genuine({ source_id: "marketplace", source_type: "product_description", platform_constraints: ["marketplace bullets"] }); assert.equal(natural.influence_tier, "primary"); assert.equal(constrained.influence_tier, "limited"); });
test("malformed provenance fails", () => { const source = genuine(); source.approximate_words += 1; assert.equal(validateVoiceSource(source).status, "FAIL"); });
test("strong and weak observations require eligible source references", () => { const source = genuine(); assert.equal(validateVoiceProfile(profile([source]), [source]).status, "PASS"); const invalid = profile([source]); invalid.observations[0].source_ids = ["missing"]; assert.equal(validateVoiceProfile(invalid, [source]).status, "FAIL"); });
test("explicit human rules stay separate from observations", () => { const source = genuine(); const observed = profile([source]); const approved = approveVoiceProfile(observed, [{ rule: "Never use this phrase." }], { reviewer: "owner", reviewedAt: "2026-08-10T12:00:00Z" }); assert.equal(observed.state, "awaiting_human_review"); assert.equal(approved.state, "approved"); assert.equal(approved.human_rules[0].classification, "EXPLICIT_HUMAN_RULE"); });
test("site configuration selects any approved profile without Ben assumptions", () => { const source = genuine(); const approved = approveVoiceProfile(profile([source], { profile_id: "north-star-bakery-v1", site_id: "north-star-bakery", voice_identity: "owner-b" }), [], { reviewer: "owner-b", reviewedAt: "2026-08-10T12:00:00Z" }); assert.equal(resolveSiteVoiceProfile({ editorial: { voice_profile_id: "north-star-bakery-v1" } }, [approved]).profile.site_id, "north-star-bakery"); assert.throws(() => resolveSiteVoiceProfile({ editorial: { voice_profile_id: "profile-a-v1" } }, [profile([source])]), /not human-approved/); });
test("voice transformation preserves product evidence link IDs and component jobs", () => { const before = { components: [{ component_id: "a", component_type: "text", product_ids: ["p1"], evidence_ids: ["e1"], internal_link_ids: ["l1"], media_requirements: [] , data: { copy: "Formal copy." } }] }; const after = structuredClone(before); after.components[0].data.copy = "Plain copy."; assert.equal(validateVoiceTransformation({ before, after }).status, "PASS"); after.components[0].product_ids.push("p2"); assert.equal(validateVoiceTransformation({ before, after }).status, "FAIL"); });
test("voice profile cannot authorise unsupported personal experience", () => { const before = { components: [{ component_id: "a", component_type: "text", product_ids: [], evidence_ids: [], internal_link_ids: [], media_requirements: [], data: { copy: "Choose carefully." } }] }; const after = structuredClone(before); after.components[0].data.copy = "I've tested it for two years."; assert.ok(validateVoiceTransformation({ before, after }).errors.some((item) => item.code === "UNSUPPORTED_PERSONAL_EXPERIENCE")); });
test("Street Kingz profile excludes AI page and uncertain catalogue", () => { const profileValue = buildStreetKingzFounderProfile(); assert.equal(profileValue.profile_id, "street-kingz-founder-v1"); assert.equal(profileValue.founder_fact_policy.voice_profile_is_fact_source, false); assert.equal(STREET_KINGZ_VOICE_SOURCES.filter((item) => !item.eligible_for_voice_analysis).length, 2); assert.equal(validateVoiceProfile(profileValue, STREET_KINGZ_VOICE_SOURCES).status, "PASS"); });
test("current article diagnostic identifies style mismatch without rewriting", async () => { const page = JSON.parse(await readFile("artifacts/cornerstone/best-car-drying-towel/component-revision-v1/deterministic-acceptance-001/semantic-page.json", "utf8")); const result = diagnoseVoiceMismatch(page, buildStreetKingzFounderProfile()); assert.equal(result.customer_copy_modified, false); assert.ok(result.findings.length >= 2); assert.ok(result.findings.every((item) => item.factual_meaning_status === "preserve")); });
test("generic contracts contain no Street Kingz Product 70 template or towel dependency", async () => { const code = await Promise.all(["contracts.js", "corpus.js", "profile.js", "diagnostic.js"].map((name) => readFile(`voice/${name}`, "utf8"))); const joined = code.join(" ").toLowerCase(); for (const forbidden of ["street kingz", "product 70", "template 2003", "drying towel", "ben"]) assert.equal(joined.includes(forbidden), false, forbidden); });
