import test from "node:test";
import assert from "node:assert/strict";
import { renderSemanticPageToWordPressBlocks, STREET_KINGZ_WORDPRESS_MAPPING } from "../rendering/wordpress-native.js";
import { canonicalJson, sha256 } from "../research/core/canonical.js";

const page = { h1: "Native article", introduction_deck: "Intro", components: [{ component_id: "r", component_type: "rich_text_section", data: { heading: "Read", paragraphs: ["Text & detail"] } }, { component_id: "p", component_type: "product_recommendation", data: { product_id: "p1", recommendation_context: "Context", relevance_reason: "Reason", cta_label: "See it" } }, { component_id: "f", component_type: "faq", data: { heading: "Questions", items: [{ question: "Q?", answer: "A" }] } }] };
test("SemanticPage maps deterministically to editable Gutenberg markup", () => { const output = renderSemanticPageToWordPressBlocks(page, { productRegistry: new Map([["p1", { name: "Product", url: "https://example.test/product" }]]) }); assert.equal(output.semantic_content_modified, false); assert.equal(output.semantic_page_sha256, sha256(canonicalJson(page))); assert.equal((output.markup.match(/<h1>/g) || []).length, 1); assert.match(output.markup, /wp:paragraph/); assert.ok(output.markup.includes('href="https://example.test/product"')); assert.match(output.markup, /&amp;/); });
test("native mapping does not require Elementor and unsupported mappings fail safely", () => { const unsupported = { ...STREET_KINGZ_WORDPRESS_MAPPING, faq: { state: "UNSUPPORTED" } }; assert.throws(() => renderSemanticPageToWordPressBlocks(page, { mapping: unsupported }), /Unsupported WordPress mapping/); });
test("WordPress prototype preserves semantic order and has no live side effect", () => { const output = renderSemanticPageToWordPressBlocks(page); assert.ok(output.markup.indexOf("semantic-rich_text_section") < output.markup.indexOf("semantic-product_recommendation")); assert.equal(output.wordpress_writes, 0); assert.equal(output.ai_calls, 0); });
