import { readFile, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { canonicalJson, sha256 } from "../research/core/canonical.js";
import { deriveCornerstoneStrategyAllowlists } from "../cornerstone/strategy-allowlists.js";
import { buildDryingTowelConceptPolicy, validateConceptOwnership } from "../editorial/concept-ownership.js";
import { validateEditorialRevision } from "../editorial/revision-validation.js";
import { validateFounderVoice } from "../editorial/founder-voice.js";
import { validateVoiceTransformation } from "../voice/profile.js";
import { validateGeneratedVoiceTransformation, reviewVoiceTransformationQuality } from "../voice/transformation-validation.js";
import { renderEditorialDraftMarkdown } from "../editorial/draft-render.js";

const root = path.resolve("artifacts/cornerstone/best-car-drying-towel");
const sourcePath = path.join(root, "final-human-approved-v2/semantic-page.json");
const inputPath = path.join(root, "voice-transformation-v1/preparation-003/transformation-input.json");
const planPath = path.join(root, "component-draft-v1/approved-page-plan.json");
const outputDirectory = path.join(root, "final-human-approved-v3");
const [source, input, plan] = await Promise.all([sourcePath, inputPath, planPath].map((file) => readFile(file, "utf8").then(JSON.parse)));
if (sha256(canonicalJson(source)) !== "22a7bc8d9fbef4a38f8afd69462297e44cfc3e52078fe7f155d2f7c151bd9b47") throw new Error("Final approved source hash mismatch.");
const page = structuredClone(source); const hero = page.components.find((component) => component.component_type === "hero");
const removed = "This is a practical fit guide, not a head-to-head test, and I’m not claiming one towel works best for everyone.";
if (hero.data.trust_update_note !== removed) throw new Error("Authorised disclaimer not found.");
hero.data.trust_update_note = null; hero.claim_annotations = (hero.claim_annotations || []).filter((annotation) => annotation.claim_text !== removed);
const before = structuredClone(source); const sanitise = (value) => { const clone = structuredClone(value); for (const component of clone.components) delete component.claim_annotations; delete clone.validation_metadata; return clone; };
const expected = structuredClone(before); const expectedHero = expected.components.find((component) => component.component_type === "hero"); expectedHero.data.trust_update_note = null;
if (canonicalJson(sanitise(page)) !== canonicalJson(sanitise(expected))) throw new Error("Unexpected content change.");
const allowlists = deriveCornerstoneStrategyAllowlists(input.strategy.research_packet); const conceptPolicy = buildDryingTowelConceptPolicy(plan); const revision = { revision_version: "1.0.0", comparison_component_decision: { decision: "remove", rationale: "Preserved.", evidence_ids: [], customer_value: "Preserved." }, founder_note_decision: { decision: "omit", rationale: "Preserved.", evidence_ids: [] }, page };
const generated = validateGeneratedVoiceTransformation(revision, { input, plan, conceptPolicy, allowlists });
const validation = { status: generated.status, errors: generated.errors, generated, voice: validateVoiceTransformation({ before, after: page, founderFactIds: [] }), founderVoice: validateFounderVoice(page, { founderFactIds: [] }), conceptOwnership: validateConceptOwnership(page, conceptPolicy), editorial: reviewVoiceTransformationQuality(revision, generated) };
if (validation.status === "FAIL" || validation.voice.status === "FAIL" || validation.founderVoice.status === "FAIL" || validation.conceptOwnership.status === "FAIL" || validation.editorial.status === "FAIL") throw new Error(JSON.stringify(validation));
await mkdir(outputDirectory, { recursive: false });
await writeFile(path.join(outputDirectory, "semantic-page.json"), `${JSON.stringify(page, null, 2)}\n`);
await writeFile(path.join(outputDirectory, "semantic-page.md"), `${renderEditorialDraftMarkdown(page, allowlists)}\n`);
await writeFile(path.join(outputDirectory, "final-approval-validation.json"), `${JSON.stringify({ artifact_type: "final_human_approved_semantic_page_validation", status: "PASS", authorised_change: "Hero disclaimer removal only.", validation }, null, 2)}\n`);
await writeFile(path.join(outputDirectory, "approval.json"), `${JSON.stringify({ artifact_type: "human_approved_semantic_page", approval_state: "HUMAN_APPROVED", source_semantic_page_sha256: sha256(canonicalJson(source)), final_semantic_page_sha256: sha256(canonicalJson(page)), ai_calls: 0, wordpress_writes: 0, publication_attempts: 0 }, null, 2)}\n`);
console.log(JSON.stringify({ outputDirectory, status: "PASS", semantic_page_sha256: sha256(canonicalJson(page)), ai_calls: 0 }));
