import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { diffElementorDocuments } from "../lib/elementorNormalizationIncident.js";

const envKeys=["WORDPRESS_BASE_URL","WORDPRESS_READ_USERNAME","WORDPRESS_READ_APPLICATION_PASSWORD","WORDPRESS_WRITE_USERNAME","WORDPRESS_WRITE_APPLICATION_PASSWORD","WORDPRESS_RECOVERY_USERNAME","WORDPRESS_RECOVERY_APPLICATION_PASSWORD"];
for(const key of envKeys) if(!process.env[key]?.trim()) throw new Error(`MISSING_${key}`);
if(new Set([process.env.WORDPRESS_READ_USERNAME,process.env.WORDPRESS_WRITE_USERNAME,process.env.WORDPRESS_RECOVERY_USERNAME]).size!==3) throw new Error("IDENTITIES_NOT_DISTINCT");
const root=process.cwd(), runDir=path.join(root,"artifacts/incidents/template-2003-elementor-normalization-2026-08-09/live-recovery-validation-v0.1.2-001");
if(fs.existsSync(runDir)) throw new Error("IMMUTABLE_RUN_EXISTS"); fs.mkdirSync(runDir,{recursive:true});
const base=process.env.WORDPRESS_BASE_URL.replace(/\/$/,"");
const auth={reader:[process.env.WORDPRESS_READ_USERNAME,process.env.WORDPRESS_READ_APPLICATION_PASSWORD],writer:[process.env.WORDPRESS_WRITE_USERNAME,process.env.WORDPRESS_WRITE_APPLICATION_PASSWORD],recovery:[process.env.WORDPRESS_RECOVERY_USERNAME,process.env.WORDPRESS_RECOVERY_APPLICATION_PASSWORD]};
const u={discovery:`${base}/wp-json/`,reader:`${base}/wp-json/streetkingz-ai/v1/products/70/authoritative`,recover:`${base}/wp-json/streetkingz-ai/v1/incidents/template-2003-elementor-normalization/recover`,manifest:`${base}/wp-json/streetkingz-ai/v1/incidents/template-2003-elementor-normalization/validation-manifest`,status:`${base}/wp-json/streetkingz-ai/v1/incidents/template-2003-elementor-normalization/validation/status`,dry:`${base}/wp-json/streetkingz-ai/v1/incidents/template-2003-elementor-normalization/validation/dry-run`};
const requests=[];const sha=s=>crypto.createHash("sha256").update(s).digest("hex");
const cache=h=>Object.fromEntries(["cache-control","x-litespeed-cache","x-litespeed-cache-control","age"].flatMap(k=>h.get(k)===null?[]:[[k,h.get(k)]]));
async function request(label,url,{identity=null,method="GET",body=null}={}){const pair=identity?auth[identity]:null;const response=await fetch(url,{method,headers:{accept:"application/json",...(body?{"content-type":"application/json"}:{}),...(pair?{authorization:`Basic ${Buffer.from(pair.join(":" )).toString("base64")}`}:{})},...(body?{body:JSON.stringify(body)}:{})});const text=await response.text();let parsed={};try{parsed=JSON.parse(text)}catch{}requests.push({label,method,identity:identity||"anonymous",status:response.status,error_code:parsed.code||null,response_size:Buffer.byteLength(text),cache_headers:cache(response.headers)});return {status:response.status,text,body:parsed,headers:cache(response.headers)};}
const write=(name,data)=>fs.writeFileSync(path.join(runDir,name),JSON.stringify(data,null,2)+"\n",{flag:"wx"});
write("preflight.json",{tests:"332/332 PASS",credentials:{reader:true,writer:true,recovery:true},identities_distinct:true,retries:0,run_directory_created_before_requests:true,credentials_persisted:false,authorization_headers_persisted:false});
const discovery=await request("route_discovery",u.discovery);const routes=discovery.body.routes||{};write("route-discovery.json",{namespace_present:discovery.body.namespaces?.includes("streetkingz-ai/v1")||false,validation_manifest:routes["/streetkingz-ai/v1/incidents/template-2003-elementor-normalization/validation-manifest"]||null,validation_status:routes["/streetkingz-ai/v1/incidents/template-2003-elementor-normalization/validation/status"]||null,validation_dry_run:routes["/streetkingz-ai/v1/incidents/template-2003-elementor-normalization/validation/dry-run"]||null,production_recovery:routes["/streetkingz-ai/v1/incidents/template-2003-elementor-normalization/recover"]||null});
const initialProduction=await request("initial_production_status",u.recover,{identity:"recovery"});const initialValidation=await request("initial_validation_status",u.status,{identity:"recovery"});if(initialProduction.body.status!=="locked"||initialValidation.body.status!=="validation_absent") throw new Error("UNSAFE_INITIAL_CONTROL_STATE");
const cycles=[];for(let n=1;n<=2;n++){const c={cycle:n};for(const id of [null,"reader","writer","recovery",null,"reader","writer"]){const r=await request(`cache_${n}_${id||"anonymous"}`,u.status,{identity:id});(c[id||"anonymous"]??=[]).push({status:r.status,error_code:r.body.code||null,body_status:r.body.status||null,headers:r.headers});}cycles.push(c);}const cachePass=cycles.every(c=>c.recovery.every(x=>x.status===200)&&[...c.anonymous,...c.reader,...c.writer].every(x=>x.status===403));write("cache-security-validation.json",{pass:cachePass,cycles});if(!cachePass) throw new Error("CACHE_SECURITY_FAILURE");
const baseline=await request("baseline_authoritative",u.reader,{identity:"reader"});if(baseline.status!==200)throw new Error("BASELINE_READ_FAILED");write("baseline-authoritative-state.json",baseline.body);
const currentRaw=baseline.body.elementor_template.raw_elementor_data;const targetResponse=JSON.parse(fs.readFileSync(path.join(root,"artifacts/implementation/heavy-duty-drying-towel-1200gsm/production-v1/guarded-write-execution-v0.1.9-001/pre-write-authoritative-response.json"),"utf8"));const targetRaw=targetResponse.elementor_template.raw_elementor_data;const changes=diffElementorDocuments(JSON.parse(currentRaw),JSON.parse(targetRaw));const typeReversions=changes.filter(x=>x.original_type==="string"&&x.current_type==="number"&&x.original_value===String(x.current_value));const incident={current_raw_sha256:sha(currentRaw),target_raw_sha256:sha(targetRaw),current_raw_length:Buffer.byteLength(currentRaw),target_raw_length:Buffer.byteLength(targetRaw),differing_paths:changes.length,string_to_number_reversions:typeReversions.length,other_differences:changes.length-typeReversions.length,widget_content_changes:changes.filter(x=>x.property_family==="widget content").length};write("live-diff-validation.json",{...incident,safety_changes:changes.filter(x=>x.element_id==="43d7d6f0")});if(incident.current_raw_sha256!=="e0a329efe268638edfbb3d6274512c26aeb0da835e4a9279a1d088d0d562de00"||incident.target_raw_sha256!=="81991fbccece6edcedb9cd84fc4d8dca99765b473cf24b2f8df26b5946f91c01"||changes.length!==140||typeReversions.length!==140)throw new Error("INCIDENT_STATE_MISMATCH");
const manifest={schema_version:1,status:"validation_only",incident_id:"template-2003-elementor-normalization-2026-08-09",template_id:2003,meta_key:"_elementor_data",operation:"validate_exact_raw_recovery_plan",expected_current_raw_sha256:"e0a329efe268638edfbb3d6274512c26aeb0da835e4a9279a1d088d0d562de00",target_raw_sha256:"81991fbccece6edcedb9cd84fc4d8dca99765b473cf24b2f8df26b5946f91c01",target_raw_elementor_data:targetRaw,expected_diff_sha256:"401ec670e2a443d7ec904edbb43964ebf39862256198c9c2d79c50293662c80b",expected_diff_count:140,expected_diff_type:"equal_valued_string_to_number_only",unexpected_diff_count:0,product_70_protected:true,other_templates_protected:true,other_meta_protected:true};write("validation-manifest.json",manifest);
const installed=await request("validation_install",u.manifest,{identity:"recovery",method:"POST",body:{manifest}});write("validation-install-result.json",installed.body);if(installed.status!==200||installed.body.execution_capable!==false||installed.body.recovery_id_present!==false||installed.body.claim_possible!==false)throw new Error("VALIDATION_INSTALL_FAILURE");
const status=await request("validation_status",u.status,{identity:"recovery"});const productionDuring=await request("production_status_during_validation",u.recover,{identity:"recovery"});write("validation-status.json",{validation:status.body,production:productionDuring.body});if(status.body.status!=="validation_installed"||productionDuring.body.status!=="locked")throw new Error("STATE_ISOLATION_FAILURE");
const variants={wrong_incident:{incident_id:"wrong"},wrong_post:{template_id:70},template_2002:{template_id:2002},template_2004:{template_id:2004},wrong_meta:{meta_key:"other"},wrong_current:{expected_current_raw_sha256:"0".repeat(64)},wrong_target:{target_raw_sha256:"0".repeat(64)},wrong_diff:{expected_diff_count:139},unexpected_diff:{unexpected_diff_count:1},arbitrary_target:{target_raw_elementor_data:"[]"},extra_operation:{operation:"execute"},publication:{publication_authorised:true},slug:{slug_authorised:true},title:{post_title:"x"},excerpt:{post_excerpt:"x"}};const negatives=[];for(const [name,change] of Object.entries(variants)){const bad={...manifest,...change};const r=await request(`negative_${name}`,u.manifest,{identity:"recovery",method:"POST",body:{manifest:bad}});negatives.push({name,status:r.status,error_code:r.body.code||null});}
for(const identity of [null,"reader","writer"]){for(const [name,url,method,body] of [["status",u.status,"GET",null],["install",u.manifest,"POST",{manifest:{}}],["dry_run",u.dry,"POST",{mode:"validation_dry_run"}],["remove",u.manifest,"DELETE",null]]){const r=await request(`denied_${identity||"anonymous"}_${name}`,url,{identity,method,body});negatives.push({name:`${identity||"anonymous"}_${name}`,status:r.status,error_code:r.body.code||null});}}
const silent=await request("silent_replacement",u.manifest,{identity:"recovery",method:"POST",body:{manifest}});negatives.push({name:"silent_replacement",status:silent.status,error_code:silent.body.code||null});write("negative-security-tests.json",negatives);if(negatives.some(x=>![400,403,409].includes(x.status)))throw new Error("NEGATIVE_TEST_ACCEPTED");
const dry=await request("validation_dry_run",u.dry,{identity:"recovery",method:"POST",body:{mode:"validation_dry_run"}});write("validation-dry-run.json",dry.body);if(dry.status!==200||dry.body.execution_capable!==false||dry.body.recovery_id_present!==false||dry.body.claim_possible!==false||dry.body.content_mutation_possible!==false||dry.body.diff_count!==140||dry.body.unexpected_diff_count!==0)throw new Error("DRY_RUN_FAILURE");
const productionReject=await request("production_rejects_validation",u.recover,{identity:"recovery",method:"POST",body:{action:"install_contract",contract:manifest}});const productionAfterReject=await request("production_status_after_rejection",u.recover,{identity:"recovery"});write("execution-isolation.json",{production_rejection:{status:productionReject.status,error_code:productionReject.body.code||null},production_status:productionAfterReject.body,validation_has_recovery_id:Object.hasOwn(manifest,"one_time_recovery_id"),validation_has_human_approval:Object.hasOwn(manifest,"human_recovery_approval"),promotion_endpoint:false});if(productionReject.status!==409||productionAfterReject.body.status!=="locked")throw new Error("PRODUCTION_ISOLATION_FAILURE");
const removed=await request("validation_remove",u.manifest,{identity:"recovery",method:"DELETE"});const finalValidationStatus=await request("validation_status_after_remove",u.status,{identity:"recovery"});const finalProductionStatus=await request("production_status_after_remove",u.recover,{identity:"recovery"});write("validation-removal.json",{removal:removed.body,validation_status:finalValidationStatus.body,production_status:finalProductionStatus.body});if(removed.status!==200||finalValidationStatus.body.status!=="validation_absent"||finalProductionStatus.body.status!=="locked")throw new Error("CLEANUP_FAILURE");
const final=await request("final_authoritative",u.reader,{identity:"reader"});write("final-authoritative-state.json",{response:final.body,byte_identical_to_baseline:final.text===baseline.text,current_raw_sha256:sha(final.body.elementor_template.raw_elementor_data)});if(final.text!==baseline.text)throw new Error("CONTENT_DRIFT");
const finalCache=[];for(const id of ["recovery",null,"reader","writer"]){const r=await request(`final_cache_${id||"anonymous"}`,u.status,{identity:id});finalCache.push({identity:id||"anonymous",status:r.status,error_code:r.body.code||null,body_status:r.body.status||null,headers:r.headers});}const finalCachePass=finalCache[0].status===200&&finalCache.slice(1).every(x=>x.status===403);write("final-cache-check.json",{pass:finalCachePass,calls:finalCache});if(!finalCachePass)throw new Error("FINAL_CACHE_FAILURE");
write("zero-content-mutation-proof.json",{total_requests:requests.length,get_requests:requests.filter(x=>x.method==="GET").length,validation_post_requests:requests.filter(x=>x.method==="POST"&&x.label!=="production_rejects_validation").length,production_schema_negative_requests:1,delete_requests:requests.filter(x=>x.method==="DELETE").length,execute_requests:0,production_contracts_created:0,recovery_ids_created:0,claims:0,update_metadata_calls:0,update_post_meta_calls:0,wp_update_post_calls:0,elementor_save_calls:0,revisions:0,content_mutations:0});
const installMissingMutationPossible=installed.body.content_mutation_possible!==false;
write("validation-report.json",{decision:installMissingMutationPossible?"PASS_WITH_RESPONSE_SCHEMA_GAP":"PASS",cache_security:true,incident_state:true,validation_install:true,validation_dry_run:true,execution_isolation:true,cleanup:true,content_unchanged:true,install_response_content_mutation_possible_field:installed.body.content_mutation_possible??"missing",ready_for_human_recovery_authorisation:!installMissingMutationPossible});
write("run-metadata.json",{run_id:"live-recovery-validation-v0.1.2-001",created_at:new Date().toISOString(),requests,credentials_persisted:false,authorization_headers_persisted:false,retries:0,live_content_writes:0,ai_calls:0,dataforseo_calls:0,search_console_calls:0});
