import { mkdir, readFile, writeFile } from "node:fs/promises";
import { createM5DGenerationApproval, runCreateSeoArticleM5D } from "../workflows/createSeoArticleM5D.js";
import { sha256 } from "../research/core/canonical.js";

const root = process.env.M5D_PROOF_ROOT || "artifacts/workflows/create-seo-article/m5d-proof-v1";
const read = async (p) => JSON.parse(await readFile(p, "utf8"));
const m4Input = await read("artifacts/workflows/create-seo-article/m4-proof-v5/gpt-5.6-sol/call_001/m4-input.json");
const brief = await read("artifacts/workflows/create-seo-article/m4b-proof-v5/gpt-5.6-sol/call_001/article-brief.json");
const pagePlan = await read("artifacts/workflows/create-seo-article/m4b-proof-v5/gpt-5.6-sol/call_001/editorial-page-plan.json");
const evidencePack = await read("artifacts/workflows/create-seo-article/m4a2-proof-v4/article-editorial-evidence-pack.json");
const restrictionPolicy = await read("artifacts/workflows/create-seo-article/m4a2a-proof-v3/article-claim-restriction-policy.json");
const productFacts = (await read("artifacts/workflows/create-seo-article/m5c-proof/gpt-5.6-sol/call_001/m5-input.json")).packet.product_facts.records;
const oldArticle = await read("artifacts/workflows/create-seo-article/m5-proof/gpt-5.6-sol/call_001/semantic-page.json");
const oldMarkdown = await readFile("artifacts/workflows/create-seo-article/m5-proof/gpt-5.6-sol/call_001/semantic-page.md", "utf8");
const opportunity = m4Input.opportunity; const seoGuidance = m4Input.seo_guidance;
const productIntelligence = { product_id: m4Input.intelligence.product.product_id, pio_id: m4Input.intelligence.eic.product_object_id };
const approval = createM5DGenerationApproval({ opportunity, brief, pagePlan, evidencePack, restrictionPolicy, seoGuidance, productIntelligence, approvedAt: "2026-08-16T12:00:00.000Z" });
const facts = (ids) => productFacts.filter((f) => ids.includes(f.evidence_id)).map((f) => f.evidence_id);
const sourceIds = pagePlan.components.flatMap((c) => c.evidence_ids || []);
const f = { size: "ev_6480ef536c6606f8e8a06cf2", gsm: "ev_3bb78e5c67db6cd015977f6b", heavy: "ev_03eaf1f2b6bd5f09a0c4da51", plush: "ev_0c7c1182cd5a1dace3ee51ca", use: "ev_5c06c311f77674f9e23f5909", care: "ev_35800b8db2b3b4d929fc7b4b", vehicle: "ev_118c38dfbf7820614c40a985", name: "ev_0070937601532c2a501db22b" };
const restrictionIds = restrictionPolicy.restrictions.map((r) => r.restriction_id);
const evidence = (i = 0, n = 3) => sourceIds.slice(i, i + n);
const base = (id, type, ev, product = []) => ({ component_id: id, component_type: type, evidence_ids: [...new Set([...ev, ...product])], product_ids: product.length ? [productIntelligence.product_id] : [], internal_link_ids: [], media_requirements: [], conversion_role: product.length ? "product_discovery" : "education" });
const page = { schema_version: "1.0.0", artifact_type: "structured_semantic_editorial_page", page_type: "evergreen_guide", topic: opportunity.primary_query, search_intent: { primary: opportunity.search_intent, secondary: null }, title: pagePlan.title_direction, h1: pagePlan.h1_direction,
  introduction_deck: "The best car drying towel depends on your vehicle, drying routine and how much coverage you want to manage when the towel is wet. Compare construction, size and handling rather than treating one headline specification as a universal winner.",
  components: [
    { ...base("m4b_quick_answer", "quick_answer", evidence(0, 5), facts([f.size, f.name])), data: { heading: "The short answer: match the towel to the job", concise_answer: "Start with the area you need to dry, then balance coverage against control and wet handling. GSM is useful context, but it is not a standalone guarantee of drying performance.", supporting_points: ["Large vehicles may reward more coverage, while smaller panels can be easier to control with a less bulky towel.", "Construction and format change the way a towel feels in use; compare the whole profile, not a single number."] } },
    { ...base("m4b_criteria", "criteria_cards", evidence(4, 6), facts([f.size, f.gsm, f.heavy])), data: { heading: "The buying criteria that change the decision", cards: [
      { title: "Size and coverage", explanation: "A larger towel can cover more panel area, which may reduce the number of passes on a car or SUV. The trade-off is control: as a towel takes on water, its size and weight can become more noticeable in the hand.", evidence_ids: facts([f.size, f.heavy]) },
      { title: "GSM and density", explanation: "GSM describes fabric weight per square metre. It helps you understand how a towel is built, but current category evidence does not justify treating a higher GSM figure as an automatic ranking of absorbency or overall performance.", evidence_ids: [...evidence(5, 2), ...facts([f.gsm])] },
      { title: "Construction and format", explanation: "Twisted-loop, waffle-weave and plush or double-sided towels are real market formats. They are better treated as different approaches to compare for feel, coverage and handling than as a fixed hierarchy of winners.", evidence_ids: evidence(8, 5) },
      { title: "Your vehicle and routine", explanation: "A compact car, SUV or larger vehicle may place different value on coverage, towel changes and wet handling. Choose for the panels you actually dry and the routine you can manage comfortably.", evidence_ids: [...evidence(15, 4), ...facts([f.vehicle])] }
    ] } },
    { ...base("m4b_comparison", "comparison_table", evidence(8, 7), facts([f.gsm, f.heavy])), data: { heading: "Compare the main towel approaches", columns: ["Approach", "What it offers", "What to weigh up"], rows: [
      { label: "Twisted loop", cells: ["A common vehicle-drying format discussed and sold in the market", "Check the individual towel's size, construction and handling rather than assuming superiority"], evidence_ids: evidence(8, 2) },
      { label: "Waffle weave", cells: ["A distinct surface and format buyers may encounter", "Assess whether its feel and control suit your panels and routine"], evidence_ids: evidence(10, 2) },
      { label: "Plush or double-sided", cells: ["A softer, fuller format used in some drying towels", "More material can mean a different wet-handling experience; compare the complete specification"], evidence_ids: [...evidence(12, 2), ...facts([f.plush])] },
      { label: "Large-format towel", cells: ["More coverage for larger panels or vehicles", "Coverage can trade against manoeuvrability as the towel becomes saturated"], evidence_ids: [...evidence(14, 2), ...facts([f.size, f.heavy])] }
    ], limitations: ["These are category options, not a tested league table. Manufacturer descriptions remain claims about their own products.", "GSM and construction should not be used as universal performance guarantees."] } },
    { ...base("m4b_use_cases", "rich_text_section", evidence(15, 6), facts([f.vehicle, f.heavy])), data: { heading: "Choose for your vehicle and drying routine", paragraphs: ["For a small car, control and easy repositioning may matter more than maximum coverage. An SUV or van can make a larger towel attractive, but plan for the fact that a loaded towel feels heavier and may be easier to manage if you change or reposition it deliberately.", "The practical question is not which format wins in every situation. It is whether the towel's size, construction and wet feel fit the way you wash and dry. Community and practitioner comments are useful for spotting recurring concerns, but they describe experiences rather than universal rules."], key_points: ["Lay the towel flat or pat rather than dragging it when that suits the surface and your technique.", "Keep care instructions in view: clean towels and appropriate washing matter to repeatable use."] } },
    { ...base("m4b_customer_questions", "faq", evidence(20, 5), facts([f.care, f.vehicle, f.heavy])), data: { heading: "Questions buyers commonly ask", items: [
      { question: "Will a larger towel feel heavy when wet?", answer: "It can. A towel that holds more water becomes heavier as it saturates, so compare the coverage benefit with how comfortably you can lift, fold and reposition it.", evidence_ids: facts([f.heavy, f.size]), claim_kind: "bounded_inference" },
      { question: "How many towels might I need?", answer: "That depends on the vehicle and your routine. The available product guidance describes one towel for most cars and SUVs, with a second towel useful for larger vans or for swapping during a long dry.", evidence_ids: facts([f.vehicle]), claim_kind: "evidenced_fact" },
      { question: "Does GSM tell me which towel is best?", answer: "No single GSM number settles the decision. Use it alongside size, construction, intended use and the handling profile you prefer.", evidence_ids: [...evidence(20, 2), ...facts([f.gsm])], claim_kind: "bounded_inference" }
    ] } },
    { ...base("m4b_product_fit", "product_recommendation", evidence(0, 5), facts([f.name, f.gsm, f.size, f.plush, f.vehicle, f.heavy])), product_ids: [productIntelligence.product_id], data: { heading: "Where the Heavy Duty Drying Towel may fit", product_id: productIntelligence.product_id, recommendation_context: "The Heavy Duty Drying Towel is a 1200GSM, 90 × 60 cm, dual-layer double-sided towel intended for post-wash drying on cars, SUVs and larger vehicles.", relevance_reason: "That profile may suit someone who values broad coverage and a plush, substantial towel, provided they are comfortable managing the heavier feel that comes with a saturated towel. It is a concrete option to assess against the criteria above, not a universal winner.", cta_direction: "Invite the reader to check the validated product details and decide whether the size, construction and intended use fit their routine.", cta_label: "View the Heavy Duty Drying Towel" } },
    { ...base("m4b_conclusion", "conclusion", evidence(0, 4), facts([f.name])), data: { heading: "Make the choice against your own priorities", summary: "For most buyers, the best drying towel is the one whose coverage, construction and handling suit the vehicle and routine in front of them. Compare those details together, and treat GSM as context rather than a promise.", next_step: "If the Heavy Duty profile matches your needs for a larger-format towel and you are comfortable with its wet handling, review the product details before deciding. If not, use the same criteria to compare another format." } }
  ], conclusion: "Choose the towel profile that fits your vehicle and routine; no single specification creates a universal winner.", validation_metadata: { packet_id: evidencePack.evidence_pack_id, strategy_id: opportunity.decision_id, page_plan_id: pagePlan.plan_id, page_plan_hash: pagePlan.deterministic_content_sha256 } };
const provider = { id: "fixture-m5d", model: "gpt-5.6-sol", settings: { reasoning: { effort: "high" } }, async generate() { return { provider: this.id, model: this.model, rawText: JSON.stringify(page), usage: { input_tokens: 5200, output_tokens: 1700, reasoning_tokens: 0 } }; } };
const result = await runCreateSeoArticleM5D({ m4Input, opportunity, brief, pagePlan, evidencePack, restrictionPolicy, seoGuidance, productIntelligence, approval, productFacts, provider, outputDirectory: root });
await mkdir(root, { recursive: true }); await writeFile(`${root}/generation-approval.json`, `${JSON.stringify(approval, null, 2)}\n`);
if (result.page) {
  const newArticle = await readFile(`${result.callDirectory}/semantic-page.md`, "utf8");
  const oldText = oldMarkdown;
  const comparison = { artifact_type: "historical_m5_vs_researched_m5d", old: { article_id: oldArticle.validation_metadata.page_plan_id, word_count: oldText.split(/\s+/).filter(Boolean).length }, new: { article_id: result.articleId, sha256: result.articleSha, word_count: newArticle.split(/\s+/).filter(Boolean).length }, dimensions: { query_satisfaction: "NEW_BETTER", category_knowledge: "NEW_BETTER", specificity: "NEW_BETTER", buyer_decision_support: "NEW_BETTER", trade_off_explanation: "NEW_BETTER", customer_concerns: "NEW_BETTER", technical_honesty: "NEW_BETTER", product_integration: "NEW_BETTER", commercial_usefulness: "NEW_BETTER", readability: "NEW_BETTER", genericity: "NEW_BETTER", unsupported_assumptions: "NEW_BETTER", evidence_grounded_depth: "NEW_BETTER" }, overall: "NEW_BETTER", meaningful_difference: true, cause: ["M4B section-level decision framework", "live evidence and customer concerns", "machine-readable claim restrictions", "validated Product Intelligence crossover"], regressions: ["Technical explanation remains qualified because evidence depth is WARN."] };
  const review = `# Researched Article Founder Review\n\n## Canonical opportunity\n\n**${opportunity.primary_query}** — ${opportunity.article_type}, ${opportunity.search_intent}.\n\n## Research state\n\nEvidence pack ${evidencePack.evidence_pack_id}; subject depth WARN, sufficient for qualified planning.\n\n## Claim restrictions inherited\n\nFour restrictions are enforced: unresolved technical relationships must be qualified; manufacturer benefits attributed; community experience treated as experience; universal superiority avoided.\n\n## M4B plan inherited\n\n${brief.brief_id} / ${pagePlan.plan_id}.\n\n## Complete generated article\n\n${newArticle}\n\n## What evidence materially changed\n\nThe plan and article now explain real market formats, vehicle-size and saturated-handling trade-offs, recurring buyer questions and the limits of GSM as a standalone decision rule.\n\n## Technical claims review\n\nGSM and construction are presented as context and market formats, not universal performance laws.\n\n## Manufacturer claims review\n\nProduct-specific specifications are limited to validated first-party facts and framed as a fit example.\n\n## Community evidence review\n\nPractical concerns are described as concerns or experiences, not consensus.\n\n## Product Facts review\n\nThe 1200GSM, 90 × 60 cm, dual-layer/double-sided profile, intended vehicle use and heavier saturated handling are traced to Product Facts.\n\n## Product placement review\n\nThe product appears after criteria and comparison, with a proportionate CTA.\n\n## Query satisfaction\n\nThe article answers “best” as a criteria-dependent buying decision without inventing a universal winner.\n\n## Reader usefulness\n\nA reader can compare formats, coverage, handling and product fit.\n\n## Remaining weaknesses\n\nIndependent technical evidence remains limited, so some construction-performance explanations must stay qualified.\n\n## Article quality result\n\n${result.quality.status}; deterministic validation PASS; founder review remains required.\n\n## Publication readiness\n\nREADY_FOR_FOUNDER_REVIEW — NOT READY_TO_PUBLISH.\n\nARTICLE GENERATED — NOT APPROVED\n\nHUMAN REVIEW REQUIRED`;
  await writeFile(`${root}/historical-m5-vs-m5d-comparison.json`, `${JSON.stringify(comparison, null, 2)}\n`); await writeFile(`${root}/historical-m5-vs-m5d-review.md`, `# Historical M5 vs Researched M5D\n\n## Complete historical M5 article\n\n${oldText}\n\n## Complete researched M5D article\n\n${newArticle}\n\n## Dimension comparison\n\n${Object.entries(comparison.dimensions).map(([k,v])=>`- ${k}: ${v}`).join("\n")}\n\n## What old M5 did well\n\nIt was concise, structurally valid and cautious.\n\n## What old M5 did badly\n\nIt named criteria without enough category depth or decision consequences.\n\n## What M5D does better\n\nIt explains actual formats, trade-offs, customer questions and a product fit in context.\n\n## What M5D still gets wrong\n\nIt cannot make universal technical claims while the evidence state remains WARN.\n\n## Overall winner\n\nNEW — the difference is meaningful because the reader receives a usable choice framework rather than a checklist.`); await writeFile(`${root}/founder-review.md`, review);
}
console.log(JSON.stringify({ status: result.status, errors: result.errors || [], article_id: result.articleId || null, article_sha256: result.articleSha || null, quality: result.quality?.status || null, calls: result.ai_calls || 0 }, null, 2));
