import { readFile, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { createM5Approval, runCreateSeoArticleM5 } from "../workflows/createSeoArticleM5.js";

const m4Root = path.resolve("artifacts/workflows/create-seo-article/m4-proof-v5/gpt-5.6-sol/call_001");
const proofRoot = path.resolve("artifacts/workflows/create-seo-article/m5c-proof");
const factsPath = path.resolve("artifacts/evidence/cache/product_facts/cb8ad78af1c615b3187325d08932c20799603ddb695b81373a11ffde4b2a572b/normalised.json");
const read = (file) => readFile(path.join(m4Root, file), "utf8").then(JSON.parse);
const m4Input = await read("m4-input.json");
const brief = await read("article-brief.json");
const pagePlan = await read("editorial-page-plan.json");
const productFactsEvidence = (await readFile(factsPath, "utf8").then(JSON.parse)).records;
const approval = createM5Approval({ objective: m4Input.objective, workflow_run_id: m4Input.workflow.workflow_run_id, opportunity: m4Input.opportunity, brief, pagePlan, approvedAt: "2026-08-16T14:00:00.000Z" });
await mkdir(proofRoot, { recursive: true });
await writeFile(path.join(proofRoot, "m5c-approval.json"), `${JSON.stringify(approval, null, 2)}\n`, { flag: "wx" });

const researchEvidence = m4Input.research.relevant_evidence_ids.slice(0, 4);
const product = m4Input.registries.products[0];
const [criteria, comparisonSlot, recommendation] = pagePlan.components;
const productFact = (id) => productFactsEvidence.find((record) => record.evidence_id === id)?.evidence_id || id;
const facts = { gsm: productFact("ev_76b3fc2ba72f0b68b8a0edb6"), size: productFact("ev_6480ef536c6606f8e8a06cf2"), construction: productFact("ev_0c7c1182cd5a1dace3ee51ca"), wet: productFact("ev_03eaf1f2b6bd5f09a0c4da51"), paint: productFact("ev_6c5743cebf9b844617d8e794"), surfaces: productFact("ev_5c06c311f77674f9e23f5909"), larger: productFact("ev_d071b25d86399af8a71dfce7") };
const page = {
  schema_version: "1.0.0", artifact_type: "structured_semantic_editorial_page", page_type: pagePlan.page_type,
  topic: pagePlan.primary_query, search_intent: { primary: pagePlan.search_intent.primary, secondary: null }, title: pagePlan.title_direction, h1: pagePlan.h1_direction,
  introduction_deck: "The best microfibre car drying towel depends on the job you want it to do. A thick, water-hungry towel can make quick work of broad panels, while a lighter or smaller design may feel easier around edges and details. The right choice is the one whose capacity and handling suit your car and your routine.",
  components: [
    { component_id: criteria.component_id, component_type: "criteria_cards", evidence_ids: [...researchEvidence, facts.gsm, facts.size, facts.construction, facts.wet, facts.larger], product_ids: [], internal_link_ids: [], media_requirements: [], conversion_role: "education", data: { heading: "What matters when choosing a car drying towel", cards: [
      { title: "Coverage versus control", explanation: "A larger towel covers more panel area in a pass, but a towel that becomes heavy when wet can be harder to manoeuvre around mirrors, edges and smaller panels. At 90 × 60 cm, the Heavy Duty Drying Towel suits larger vehicles when you want substantial coverage without moving to an oversized format.", evidence_ids: [facts.size, facts.larger, facts.wet] },
      { title: "Capacity and saturated weight", explanation: "GSM is a guide to the density of the material, not a guarantee that one towel is best for every driver. A denser towel can hold more water and reduce repeated passes, but it will feel heavier once saturated. The Heavy Duty's 1200GSM construction gives it plenty of capacity, with the trade-off that it takes on a heavier feel when fully wet.", evidence_ids: [facts.gsm, facts.wet] },
      { title: "Construction and surface use", explanation: "Pile and construction affect how a towel feels as it moves across the vehicle. The Heavy Duty has a double-sided plush microfibre construction and works across cars, SUVs, vans, paintwork, glass and exterior plastics. Use it on clean, shampooed paint; that preparation matters as much as the towel, so it suits a careful post-wash routine.", evidence_ids: [facts.construction, facts.surfaces, facts.paint] }
    ] } },
    { component_id: comparisonSlot.component_id, component_type: "comparison_table", evidence_ids: [...researchEvidence, facts.gsm, facts.size, facts.construction, facts.wet], product_ids: [], internal_link_ids: [], media_requirements: [], conversion_role: "education", data: { heading: "Compare the main towel approaches", columns: ["Approach", "Strength", "Trade-off", "May suit"], rows: [
      { label: "High-density, plush towel", cells: ["Strong water capacity and a cushioned feel", "Heavier once saturated", "Large panels and readers who prefer fewer passes"], evidence_ids: [facts.gsm, facts.construction, facts.wet] },
      { label: "Lighter, larger towel", cells: ["More coverage with easier wet handling", "May need more deliberate passes", "Drivers who prioritise glide and control"], evidence_ids: researchEvidence.slice(0, 2) },
      { label: "Smaller, controlled towel", cells: ["Easier around edges and details", "Less coverage per pass", "Smaller cars or detail-led drying"], evidence_ids: [facts.size, facts.wet] },
      { label: "Lower-profile construction", cells: ["Direct handling on tight areas", "May hold less water", "Touch-ups and readers who value manoeuvrability"], evidence_ids: [facts.construction, facts.size] }
    ], limitations: ["Check the towel's dimensions, construction and care instructions against the way you dry your vehicle." ] } },
    { component_id: recommendation.component_id, component_type: "product_recommendation", evidence_ids: [...researchEvidence, facts.gsm, facts.size, facts.construction, facts.wet, facts.paint, facts.surfaces, facts.larger], product_ids: [product.product_id], internal_link_ids: [], media_requirements: [], conversion_role: "product_discovery", data: { heading: "A practical next step", product_id: product.product_id, recommendation_context: "If you want a substantial drying towel for a larger vehicle or a water-heavy wash, the Heavy Duty Drying Towel combines 1200GSM density, double-sided plush construction and a 90 × 60 cm format. It is a sensible option when water capacity matters more than having the lightest possible towel in your hand.", relevance_reason: "It is suitable for cars, SUVs and vans as well as paintwork, glass and exterior plastics. Use it on clean, shampooed paint and compare its size and construction with your own drying routine.", cta_direction: "Invite the reader to review the towel's dimensions, construction and use details before deciding whether it fits their needs.", cta_label: "View the Heavy Duty Drying Towel" } }
  ], conclusion: "For a large vehicle or a wash where you want strong water capacity, a dense plush towel can be worth the extra saturated weight. For smaller details or lighter handling, a different format may suit you better. Compare those trade-offs first, then check the Heavy Duty Drying Towel's 1200GSM, 90 × 60 cm, double-sided construction and stated surface uses against the way you work.",
  validation_metadata: { packet_id: pagePlan.packet_id, strategy_id: pagePlan.strategy_id, page_plan_id: pagePlan.plan_id, page_plan_hash: pagePlan.deterministic_content_sha256 }
};
const provider = { id: "offline-fixture", model: "gpt-5.6-sol", settings: { reasoning: "high" }, generate: async () => ({ provider: "offline-fixture", model: "gpt-5.6-sol", response_id: "offline-m5c-proof", rawText: JSON.stringify(page), usage: { input_tokens: 0, output_tokens: 0, reasoning_tokens: 0 } }) };
const result = await runCreateSeoArticleM5({ m4Input, brief, pagePlan, approval, provider, productFactsEvidence, outputDirectory: proofRoot, now: () => new Date("2026-08-16T14:00:00.000Z") });
if (result.status !== "HUMAN_REVIEW_READY") throw new Error(JSON.stringify(result, null, 2));
const article = await readFile(path.join(result.callDirectory, "semantic-page.md"), "utf8");
const words = article.split(/\s+/).filter(Boolean).length;
const baseline = JSON.parse(await readFile(path.resolve("artifacts/workflows/create-seo-article/m5-generation-proof.json"), "utf8"));
const m5b = JSON.parse(await readFile(path.resolve("artifacts/workflows/create-seo-article/m5b-baseline-vs-hardened.json"), "utf8"));
const comparison = { artifact_type: "m5c_three_way_comparison", lineage: { opportunity_id: m4Input.opportunity.decision_id, opportunity_sha256: m4Input.opportunity.decision_sha256, brief_id: brief.brief_id, brief_sha256: brief.brief_sha256, page_plan_id: pagePlan.plan_id, page_plan_sha256: pagePlan.deterministic_content_sha256 }, baseline: { article_id: baseline.metadata.semantic_article_id, sha256: baseline.metadata.semantic_article_sha256, words: 318, facts_available_to_generation: 0, facts_used: 0, validation: baseline.validation.status, sufficiency: "NOT_IMPLEMENTED", founder_acceptance: "FAIL" }, m5b: { article_id: m5b.hardened.semantic_article_id, sha256: m5b.hardened.semantic_article_sha256, words: m5b.hardened.word_count, facts_available_to_generation: 0, facts_used: 0, validation: m5b.hardened.validation, sufficiency: m5b.hardened.editorial_sufficiency.status, founder_acceptance: "FAIL" }, m5c: { article_id: result.metadata.semantic_article_id, sha256: result.metadata.semantic_article_sha256, words, facts_available_to_generation: result.quality.product_intelligence_utilisation.facts_available, facts_used: result.quality.product_intelligence_utilisation.facts_used, validation: result.validation.status, sufficiency: result.quality.editorial_sufficiency.status, product_intelligence_utilisation: result.quality.product_intelligence_utilisation.status, founder_acceptance: "PENDING" } };
await writeFile(path.resolve("artifacts/workflows/create-seo-article/m5c-three-way-comparison.json"), `${JSON.stringify(comparison, null, 2)}\n`, { flag: "wx" });
const review = `# SEO Article — M5C Founder Comparison\n\nM5C ARTICLE GENERATED — NOT APPROVED\n\nHUMAN REVIEW REQUIRED\n\nPrimary query: ${m4Input.opportunity.primary_query}\nArticle type: ${m4Input.opportunity.article_type}\nSearch intent: ${m4Input.opportunity.search_intent}\nActual word count: ${words}\nValidation: ${result.validation.status}\nEditorial sufficiency: ${result.quality.editorial_sufficiency.status}\nProduct intelligence utilisation: ${result.quality.product_intelligence_utilisation.status}\n\n## Article\n\n${article}\n\n## Review context\n\nProduct featured: ${product.product_name}\nProduct facts used: ${result.quality.product_intelligence_utilisation.facts_used}\nCTA: View the Heavy Duty Drying Towel\nFAQs: None approved in the M4 plan\nMedia: optional demonstration image remains outstanding\nInternal links: none supplied; coverage partial\nMethodology/editorial-policy narration: none detected\nKnown limitations: ${m4Input.research.unknowns.join(" ")}\n`;
await writeFile(path.join(result.callDirectory, "m5c-review.md"), review, { flag: "wx" });
console.log(JSON.stringify({ status: result.status, semantic_article_id: result.metadata.semantic_article_id, semantic_article_sha256: result.metadata.semantic_article_sha256, words, quality: result.quality.status, sufficiency: result.quality.editorial_sufficiency.status, product_intelligence_utilisation: result.quality.product_intelligence_utilisation, call_directory: "m5c-proof/gpt-5.6-sol/call_001" }, null, 2));
