import { readFile, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { canonicalJson, sha256 } from "../research/core/canonical.js";
import { deriveCornerstoneStrategyAllowlists } from "../cornerstone/strategy-allowlists.js";
import { renderSemanticPageHtml, renderStreetKingzEditorialCss } from "../rendering/html.js";
import { buildBrowserOpenablePreview, validateBrowserOpenablePreview, VISUAL_PREVIEW_CONTRACT_VERSION } from "../rendering/visual-preview.js";
import { STREET_KINGZ_THEME } from "../rendering/themes.js";

const root = path.resolve("artifacts/cornerstone/best-car-drying-towel"); const discoveryRoot = path.resolve("artifacts/style-discovery/street-kingz-v1/discovery-v1");
const page = JSON.parse(await readFile(path.join(root, "final-human-approved-v3/semantic-page.json"), "utf8")); const packet = JSON.parse(await readFile(path.join(root, "fixture-v1/research-packet.json"), "utf8")); const profile = JSON.parse(await readFile(path.join(discoveryRoot, "site-style-profile.json"), "utf8"));
const previewTheme = { ...profile, media: { ...profile.media, product_images: STREET_KINGZ_THEME.media.product_images } }; const html = renderSemanticPageHtml(page, { allowlists: deriveCornerstoneStrategyAllowlists(packet), theme: previewTheme }); const css = renderStreetKingzEditorialCss(previewTheme); const output = path.join(root, "rendering-v1/discovered-street-kingz-v1"); await mkdir(output, { recursive: true });
const preview = buildBrowserOpenablePreview({ html, css, title: "Street Kingz Visual Review — Best Car Drying Towel" }); const previewValidation = validateBrowserOpenablePreview(preview, { expectedMarkupSelectors: ["discovered-editorial-page", "surface-page", "discovered-editorial-product-recommendation", "@media"] }); if (previewValidation.status === "FAIL") throw new Error(previewValidation.errors.join("; "));
await writeFile(path.join(output, "rendered-page.html"), `${html}\n`); await writeFile(path.join(output, "rendered-page.css"), `${css}\n`); await writeFile(path.join(output, "index.html"), preview); await writeFile(path.join(output, "preview-metadata.json"), `${JSON.stringify({ artifact_type: "browser_openable_visual_preview", preview_contract_version: VISUAL_PREVIEW_CONTRACT_VERSION, browser_openable: true, source_fragment: "rendered-page.html", source_css: "rendered-page.css", embedded_css_bytes: previewValidation.embedded_css_bytes, offline_preview_media: { product_image: "existing approved preview-only product image", required_hero: "placeholder", optional_demonstration: "placeholder" }, file_url_compatible: true, semantic_page_sha256: sha256(canonicalJson(page)), style_profile_sha256: sha256(canonicalJson(profile)), rendered_html_sha256: sha256(html), preview_sha256: sha256(preview), wordpress_writes: 0, ai_calls: 0 }, null, 2)}\n`); await writeFile(path.join(output, "rendering-validation.json"), `${JSON.stringify({ artifact_type: "discovered_site_style_render_validation", status: "PASS", semantic_page_sha256: sha256(canonicalJson(page)), style_profile_sha256: sha256(canonicalJson(profile)), rendered_html_sha256: sha256(html), h1_count: (html.match(/<h1\b/g) || []).length, required_media_state: "offline_placeholder", browser_preview_status: previewValidation.status, wordpress_writes: 0, ai_calls: 0 }, null, 2)}\n`);
console.log(JSON.stringify({ output, status: "PASS", style_profile_sha256: sha256(canonicalJson(profile)), rendered_html_sha256: sha256(html), preview_sha256: sha256(preview), embedded_css_bytes: previewValidation.embedded_css_bytes }));
