import fs from "node:fs";
import path from "node:path";
import { sha256 } from "../research/core/canonical.js";
import { prepareGuardedDryRun, simulateRollback, validateWriterApproval } from "../cms/guardedWriter.js";

const root = process.cwd();
const base = path.join(root, "artifacts/implementation/heavy-duty-drying-towel-1200gsm/production-v1");
const sourceDir = path.join(base, "authoritative-read-2026-08-08-v1.1.2-001");
const output = path.join(base, "guarded-writer-dry-run-001");
if (fs.existsSync(output)) throw new Error(`Refusing to overwrite immutable run ${output}`);
fs.mkdirSync(output, { recursive: false });
const approvalPath = path.join(base, "human-implementation-approval.json");
const approvalRaw = fs.readFileSync(approvalPath, "utf8");
const approval = JSON.parse(approvalRaw);
validateWriterApproval(approval);
const authoritative = JSON.parse(fs.readFileSync(path.join(sourceDir, "authoritative-cms-read.json"), "utf8"));
authoritative.raw_authoritative_response = JSON.parse(fs.readFileSync(path.join(sourceDir, "raw-authoritative-response.json"), "utf8"));
let persistedSnapshot;
const dryRun = await prepareGuardedDryRun({ approval, authoritative, persistRollbackSnapshot: async (snapshot) => { persistedSnapshot = structuredClone(snapshot); } });
const rollback = simulateRollback(dryRun);
const writeJson = (name, value) => fs.writeFileSync(path.join(output, name), `${JSON.stringify(value, null, 2)}\n`, { flag: "wx" });
writeJson("validated-approval-reference.json", { artifact: path.relative(root, approvalPath), artifact_sha256: sha256(approvalRaw), validation: "PASS", product_id: 70, template_id: 2003, approved_target_hashes: approval.approved_target_hashes });
writeJson("rollback-snapshot.json", persistedSnapshot);
writeJson("dry-run-mutation-plan.json", { status: dryRun.status, product_id: 70, template_id: 2003, product: dryRun.product_diff, elementor: dryRun.elementor_semantic_diff, approved_target_hashes: dryRun.approved_target_hashes });
writeJson("structural-diff.json", { permitted_product_paths: ["post_title", "post_excerpt"], actual_product_diff: dryRun.product_diff, permitted_elementor_targets: ["c80e718.settings.editor", "40869c27.settings.editor"], actual_elementor_diff: dryRun.elementor_semantic_diff, unexpected_differences: [], status: "PASS" });
writeJson("blocked-area-verification.json", dryRun.blocked_area_verification);
writeJson("rollback-simulation.json", rollback);
writeJson("validation-report.json", { status: dryRun.status === "PASS" && rollback.status === "PASS" ? "PASS" : "FAIL", approval_validation: "PASS", current_state_guards: "PASS", rollback_persistence: "PASS", approved_target_hashes: "PASS", structural_diff: "PASS", blocked_areas: "PASS", rollback_simulation: rollback.status, rendered_page_hash_role: dryRun.rendered_page_guard.role, live_writes: 0 });
writeJson("run-metadata.json", { schema_version: 1, run_id: "guarded-writer-dry-run-001", mode: "offline_dry_run", created_at: "2026-08-08T18:00:00Z", source_authoritative_run: path.relative(root, sourceDir), approval_artifact: path.relative(root, approvalPath), credentials_persisted: false, external_requests: 0, wordpress_writes: 0, publication_possible: false });
console.log(output);
