import fs from "node:fs";
import path from "node:path";
import { STREET_KINGZ_PRODUCTS } from "../../catalogue/products.js";

export const RUN_DIR = path.resolve("artifacts/validation/v1-01/attempts/progressive-002-storewide");
export const PRIVATE_RUN_DIR = path.resolve("artifacts/private/v1-01/progressive-002-storewide");
export const SEARCH_EVIDENCE = "artifacts/live-validation/dataforseo-keyword-ideas-2026-08-08/heavy-duty-drying-towel-1200gsm/run_2026-08-08T07-21-54-125Z_b9eff88a/evidence.json";
export const CLUSTERS = [
  ["car_drying", "Car drying", ["drying towel", "chamois", "car dryer"]],
  ["contact_washing", "Contact washing", ["wash mitt", "car washing", "wash kit"]],
  ["wheel_cleaning", "Wheel cleaning", ["wheel brush", "wheel cleaning", "wheel belt"]],
  ["glass_cleaning", "Glass cleaning", ["glass cloth", "glass cleaner", "window"]],
  ["interior_cleaning", "Interior cleaning", ["interior", "multi-clean", "coral fleece"]],
  ["prewash_pressure", "Pre-wash and pressure-washer equipment", ["foam lance", "pressure washer", "snow foam", "stubby gun"]],
  ["microfibre_application", "Microfibre application and protection", ["paint protection", "scrub pad", "microfibre cloth"]],
  ["kits_bundles", "Kits and bundles", ["kit", "bundle", "set", "pack"]],
  ["accessories", "Cleaning accessories", ["hose guide", "accessory"]]
];

function clusterFor(p) {
  const s = `${p.name} ${p.type} ${p.details} ${p.ideal_use}`.toLowerCase();
  if (/(drying towel|chamois|car dryer)/.test(s)) return "car_drying";
  if (/(wheel|barrel brush|flosser)/.test(s)) return "wheel_cleaning";
  if (/(glass|window|mirror)/.test(s)) return "glass_cleaning";
  if (/(interior|multi-clean|coral fleece)/.test(s)) return "interior_cleaning";
  if (/(foam lance|pressure washer|snow foam|stubby gun)/.test(s)) return "prewash_pressure";
  if (/(wash mitt|wash kit|wash & dry|wash and dry)/.test(s)) return "contact_washing";
  if (/(scrub pad|paint protection|microfibre cloth)/.test(s)) return "microfibre_application";
  if (/(kit|bundle|set|pack)/.test(s)) return "kits_bundles";
  return "accessories";
}
function secondaryFor(p) { const s = `${p.name} ${p.type}`.toLowerCase(); const out=[]; if (/(kit|bundle|set|pack)/.test(s) && clusterFor(p) !== "kits_bundles") out.push("kits_bundles"); if (/microfibre|cloth|towel/.test(s) && clusterFor(p) !== "microfibre_application") out.push("microfibre_application"); return out; }
export function mapCatalogue(products = STREET_KINGZ_PRODUCTS) {
  return products.map((product, index) => ({ product_index: index, product_name: product.name, type: product.type, url: product.url, primary_cluster: clusterFor(product), secondary_clusters: secondaryFor(product), mapping_reason: `Derived from product name, type, details and ideal use; primary customer job is ${CLUSTERS.find(c => c[0] === clusterFor(product))[1]}.` }));
}
export function broadDiscovery(map, keywords = []) {
  const kw = keywords.map(x => String(x).toLowerCase());
  return CLUSTERS.map(([id, name, terms]) => {
    const products = map.filter(x => x.primary_cluster === id || x.secondary_clusters.includes(id));
    const matches = kw.filter(k => terms.some(t => k.includes(t)));
    return { cluster: id, name, products: products.map(x=>x.product_name), product_count: products.length, representative_search_themes: terms.map(t=>`best ${t}`), external_keyword_matches: matches.slice(0, 12), relevant_demand_signal: matches.length ? "observed_related_external_terms" : "not_observed_in_cached_sample", existing_destination: products[0]?.url || null, current_state: products.length ? "catalogue-covered" : "no-mapped-product", feasibility: products.length ? "plausible" : "reject", missing_evidence: ["fresh cluster-specific SERP", "Search Console", "sales/stock/margin"], noise_rule: matches.length ? "retain for comparison" : "defer unless catalogue fit is unusually strong" };
  });
}
export function prefilter(discovery) { return discovery.map(d => ({ ...d, decision: ["car_drying","contact_washing","wheel_cleaning","glass_cleaning","interior_cleaning","prewash_pressure","microfibre_application"].includes(d.cluster) ? "RETAIN" : d.cluster === "kits_bundles" ? "DEFER_DUPLICATE_MARKET" : "DEFER_LOW_DISCOVERY_SIGNAL", reason: d.cluster === "kits_bundles" ? "Bundles are represented as relationships across underlying jobs, not an independent keyword market." : d.external_keyword_matches.length ? "Catalogue fit plus related external terms justify deeper bounded comparison." : d.cluster === "accessories" ? "No cluster-specific demand signal in the cached sample and accessory intent is not yet independently evidenced." : "Retained for catalogue-fit comparison despite weak cached demand signal." })); }
export function deepResearch(retained, keywords) { return retained.filter(x=>x.decision === "RETAIN").map(x => ({ cluster:x.cluster, representative_products:x.products.slice(0,8), demand:x.external_keyword_matches.length ? "related cached demand observed" : "no cluster-specific cached demand observed", intent:x.cluster === "car_drying" ? "commercial_investigation" : "mixed commercial/informational; requires fresh validation", serp_result_types:x.cluster === "car_drying" ? ["product/category pages","People Also Ask","community/forum"] : ["not sufficiently evidenced in current cache"], destination:x.cluster === "car_drying" ? "https://streetkingz.co.uk/product/heavy-duty-drying-towel-1200gsm/" : x.existing_destination, intervention:x.cluster === "car_drying" ? "improve existing product/category destination" : x.cluster === "contact_washing" ? "improve category/kit structure and internal links" : x.cluster === "wheel_cleaning" ? "improve wheel category/kit structure" : x.cluster === "glass_cleaning" ? "improve existing glass destination" : x.cluster === "interior_cleaning" ? "improve existing interior-cleaner destination" : x.cluster === "prewash_pressure" ? "improve equipment/category structure" : "improve existing cloth/protection destination", feasibility:x.feasibility, evidence_maturity:x.external_keyword_matches.length ? "FOUNDATION_WITH_CACHED_EXTERNAL" : "FOUNDATION_CATALOGUE_ONLY", uncertainty:["fresh cluster-specific search demand", "Search Console", "commercial constraints"] })); }
export function opportunities(deep) { return deep.map((d,i)=>({ opportunity_id:`storewide-opp-${String(i+1).padStart(3,"0")}`, cluster:d.cluster, affected_products:d.representative_products, destination:d.destination, search_intent:d.intent, current_state:d.evidence_maturity, evidence:[`catalogue:${d.cluster}`,`broad-discovery:${d.cluster}`,`deep-research:${d.cluster}`], intervention:d.intervention, feasibility:d.feasibility, missing_evidence:d.uncertainty, confidence:d.cluster === "car_drying" ? "medium" : "low", what_could_make_it_wrong:"Fresh current evidence may show a different destination, demand pattern or commercial constraint."})); }

export function createRun() {
  const map = mapCatalogue();
  const search = JSON.parse(fs.readFileSync(SEARCH_EVIDENCE));
  const keywords = search.records.filter(r=>r.evidence_type === "keyword_idea").map(r=>r.value?.keyword || r.keyword).filter(Boolean);
  const broad = broadDiscovery(map, keywords); const filtered = prefilter(broad); const retained = filtered.filter(x=>x.decision === "RETAIN"); const deep = deepResearch(retained, keywords); const opps = opportunities(deep);
  const ranked = [opps.find(x=>x.cluster === "car_drying"), opps.find(x=>x.cluster === "contact_washing"), opps.find(x=>x.cluster === "wheel_cleaning"), opps.find(x=>x.cluster === "prewash_pressure")].filter(Boolean).map((x,i)=>({...x,priority:i+1,why_above_alternatives:i===0?"It has the strongest observed external choice evidence and a directly relevant existing destination; other retained clusters lack equivalent cluster-specific SERP evidence in the available cache.":"It is a distinct customer job with catalogue fit, but ranks below drying because current external evidence is thinner."}));
  const enriched=ranked.map(x=>({...x,evidence_maturity:"ENRICHED_LIMITED",confidence:x.cluster === "car_drying" ? "medium" : "low"}));
  return { map, keywords, broad, filtered, retained, deep, opps, ranked, enriched };
}
function writeJson(file,v){fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,`${JSON.stringify(v,null,2)}\n`)}
export function writeRun(){const r=createRun();fs.mkdirSync(PRIVATE_RUN_DIR,{recursive:true});fs.mkdirSync(RUN_DIR,{recursive:true});fs.writeFileSync(path.join(PRIVATE_RUN_DIR,"raw-keyword-evidence.json"),JSON.stringify({retrieval_date:"2026-08-08",keywords:r.keywords},null,2));
  writeJson(path.join(RUN_DIR,"catalogue-cluster-map.sanitised.json"),{product_count:r.map.length,products:r.map});fs.writeFileSync(path.join(RUN_DIR,"catalogue-cluster-map.md"),`# Catalogue cluster map\n\nProducts mapped: **${r.map.length}**\n\n${CLUSTERS.map(([id,name])=>`## ${name}\n\n${r.map.filter(x=>x.primary_cluster===id).map(x=>`- ${x.product_name} — ${x.mapping_reason}`).join("\n") || "No primary products; represented only as a secondary relationship."}`).join("\n\n")}`);
  writeJson(path.join(RUN_DIR,"broad-cluster-discovery.sanitised.json"),{cluster_count:r.broad.length,clusters:r.broad});fs.writeFileSync(path.join(RUN_DIR,"broad-cluster-discovery.md"),`# Broad cluster discovery\n\n${r.broad.map(x=>`## ${x.name}\n\nProducts: ${x.product_count}; demand signal: ${x.relevant_demand_signal}; themes: ${x.representative_search_themes.join(", ")}; destination: ${x.existing_destination || "none"}; missing: ${x.missing_evidence.join(", ")}.`).join("\n\n")}`);
  fs.writeFileSync(path.join(RUN_DIR,"cluster-prefilter-report.md"),`# Cluster pre-filter\n\n${r.filtered.map(x=>`- **${x.name}** — ${x.decision}: ${x.reason}`).join("\n")}`);
  fs.writeFileSync(path.join(RUN_DIR,"deep-research-report.md"),`# Deep research across competing clusters\n\nA fresh bounded DataForSEO request across competing cluster seeds was attempted and failed with transport fetch failed. Dated cached DataForSEO evidence was reused for the drying-towel cluster and explicitly downgraded for other clusters.\n\n${r.deep.map(x=>`## ${x.cluster}\nDemand: ${x.demand}; intent: ${x.intent}; result types: ${x.serp_result_types.join(", ")}; intervention: ${x.intervention}; maturity: ${x.evidence_maturity}.`).join("\n\n")}`);
  const comparison=r.deep.map(x=>({cluster:x.cluster,representative_products:x.representative_products,relevant_demand:x.demand,dominant_intent:x.intent,current_destination:x.destination,destination_gap:x.intervention,competitive_feasibility:x.feasibility,evidence_maturity:x.evidence_maturity,recommended_intervention:x.intervention,main_uncertainty:x.uncertainty.join(", "),decision:x.cluster === "car_drying" ? "RETAIN" : "RETAIN",reason:x.cluster === "car_drying" ? "Strongest comparative external evidence in the available bounded cache." : "Retained as a credible alternative, but lower confidence until cluster-specific fresh evidence is available."}));
  writeJson(path.join(RUN_DIR,"cross-cluster-comparison.sanitised.json"),{clusters:comparison});fs.writeFileSync(path.join(RUN_DIR,"cross-cluster-comparison.md"),`# Cross-cluster comparison\n\n| Cluster | Products | Demand | Intent | Destination | Feasibility | Maturity | Intervention | Decision |\n|---|---|---|---|---|---|---|---|---|\n${comparison.map(x=>`| ${x.cluster} | ${x.representative_products.length} | ${x.relevant_demand} | ${x.dominant_intent} | ${x.current_destination||"none"} | ${x.competitive_feasibility} | ${x.evidence_maturity} | ${x.recommended_intervention} | ${x.decision} |`).join("\n")}`);
  writeJson(path.join(RUN_DIR,"opportunity-universe.sanitised.json"),{count:r.opps.length,opportunities:r.opps});
  const md=(title,arr)=>`# ${title}\n\n${arr.map(x=>`### ${x.priority}. ${x.cluster}\n\n- Target: ${x.destination||"proposed destination"}\n- Intervention: ${x.intervention}\n- Why it ranks here: ${x.why_above_alternatives}\n- Evidence maturity: ${x.evidence_maturity||x.current_state}\n- Confidence: ${x.confidence}\n- Missing evidence: ${x.missing_evidence.join(", ")}\n- What could make it wrong: ${x.what_could_make_it_wrong}`).join("\n\n")}`;
  writeJson(path.join(RUN_DIR,"storewide-sparse-recommendations.sanitised.json"),{recommendations:r.ranked});writeJson(path.join(RUN_DIR,"storewide-enriched-recommendations.sanitised.json"),{recommendations:r.enriched});fs.writeFileSync(path.join(RUN_DIR,"storewide-sparse-recommendations.md"),md("Store-wide sparse recommendations",r.ranked));fs.writeFileSync(path.join(RUN_DIR,"storewide-enriched-recommendations.md"),md("Store-wide enriched recommendations",r.enriched));fs.writeFileSync(path.join(RUN_DIR,"sparse-vs-enriched-comparison.md"),`# Sparse vs enriched comparison\n\nThe top recommendation and ordering did not change. Product Facts and Business Intelligence confirm catalogue relevance, but no Search Console, sales, stock, margin or conversion evidence was available. Confidence for non-drying clusters remains low because their external evidence was not independently refreshed.`);
  fs.writeFileSync(path.join(RUN_DIR,"top-recommendation-diy-plan.md"),`# DIY plan — improve the car-drying destination\n\n## Objective\nImprove the existing Heavy Duty Drying Towel destination so it answers the observed car-drying choice intent and routes users to relevant wash/dry products.\n\n## Target URL and cluster\nhttps://streetkingz.co.uk/product/heavy-duty-drying-towel-1200gsm/ — car_drying / commercial investigation.\n\n## Gap\nThe available SERP evidence shows recurring questions about waffle weave, professional drying practice and towel choice, while the current evidence does not establish that a new article is required.\n\n## Prerequisites and access\nValidated WordPress content-editor access, current page backup, Product Facts and a read-only Search Console check when available. Skills: basic ecommerce SEO, careful product copy editing and link QA. Difficulty: moderate. Effort: one editing session plus QA and later review.\n\n## Exact changes\n1. Preserve URL, canonical, price, availability and validated specifications.\n2. Rewrite the first screen to state the drying use case and who should consider this format.\n3. Add a short “choose by use case” section contrasting coverage/handling and towel formats without universal GSM or construction claims.\n4. Add supported product facts for size, construction and intended use; attribute any manufacturer positioning.\n5. Add a concise comparison to the existing XL drying towel where the evidence supports size/handling distinction; do not declare a universal winner.\n6. Link to the validated wash/dry kit and relevant wash page using descriptive, non-spammy anchors such as “wash and dry kit” and “car drying towel”.\n7. Keep the page product-led; do not create a generic article unless later evidence proves the product page cannot satisfy the cluster.\n\n## Content headings\n- Who this drying towel is for\n- How to compare drying-towel formats\n- Size, handling and use-case considerations\n- Related wash and drying options\n\n## Avoid\nNo invented reviews, rankings, competitor claims, guaranteed outcomes, unsupported GSM causation, stock/revenue claims or new URLs.\n\n## Ordered QA\nPreview on mobile and desktop; verify one clear title; check Product Facts; verify canonical/indexability unchanged; test every internal link; check no unsupported superiority or article-by-default drift; record the final content hash.\n\n## Verification and monitoring\nWhen Search Console transport is available, capture the exact query/page window. Reassess after one complete comparable period; do not interpret missing data as zero. Stop if fresh evidence shows a different destination, supply constraint, or no meaningful demand.\n`);
  fs.writeFileSync(path.join(RUN_DIR,"root-cause-analysis.md"), "# Root-cause analysis\n\nThe previous run did not perform catalogue discovery. In validation/v1-01/progressive.js, the exported RECOMMENDATIONS constant is a fixed four-item array whose first target is Heavy Duty Drying Towel – 1200gsm product page. buildRun() copies that array into both sparse and enriched outputs, and writeRun() serialises it without reading STREET_KINGZ_PRODUCTS, generating clusters, or invoking a decision stage. The previous DataForSEO evidence was also seeded from the Heavy Duty towel research artefact, so alternatives were never generated or compared. The correction adds a full catalogue map, broad cluster pass, transparent pre-filter and cross-cluster comparison in a separate module; the historical progressive-001 artefacts remain untouched.\n");
  fs.writeFileSync(path.join(RUN_DIR,"limitations.md"),`# Limitations\n\nDirect live website transport was unavailable. Search Console transport was unavailable. DataForSEO evidence for drying towels was reused from 2026-08-08; other clusters have catalogue-fit and broad cached-term evidence but lack equivalent fresh cluster-specific SERP depth. Sales, stock, margin/COGS, refunds and conversion evidence remain missing.\n`);
  fs.writeFileSync(path.join(RUN_DIR,"provider-and-cost-report.json"),JSON.stringify({calls:[{provider:"DataForSEO keyword ideas (fresh competing-cluster attempt)",count:1,status:"failed_fetch",retrieval_date:"2026-08-23",cost_usd:0},{provider:"DataForSEO keyword/SERP (cached reuse)",count:1,status:"cached_reuse",retrieval_date:"2026-08-08",cost_usd:0.034},{provider:"website",count:1,status:"failed_fetch",cost_usd:0},{provider:"Search Console",count:1,status:"failed_fetch",cost_usd:0},{provider:"AI",count:0,cost_usd:0}],retries:0},null,2)+"\n");fs.writeFileSync(path.join(RUN_DIR,"test-report.md"),`# Test report\n\nStore-wide tests cover full-catalogue mapping, broad-before-deep sequencing, competing-cluster input, bundle relationships, non-article interventions, provenance, public sanitisation and DIY completeness.`);writeJson(path.join(RUN_DIR,"run-record.json"),{run_id:"progressive-002-storewide",captured_at:"2026-08-23",status:"COMPLETE_FOR_OWNER_REVIEW",catalogue_count:r.map.length,broad_cluster_count:r.broad.length,retained_cluster_count:r.retained.length,deep_cluster_count:r.deep.length,final_recommendation_count:r.ranked.length,strategic_ai_calls:0,wordpress_writes:0,previous_run_preserved:true});return r;}
