-- Destination-only clone of the preserved interrupted run. Execute only in the
-- disposable recovery database as its administrative role.
begin;
create temp table recovery_ids(recovery_run_id uuid, recovery_eval_id uuid);
create temp table candidate_map(old_id uuid primary key, new_id uuid);
insert into candidate_map select candidate_id,gen_random_uuid() from public.organic_opportunity_candidates where decision_run_id='ba588084-b023-49f6-85ac-07412a23aff9';
with new_run as (select gen_random_uuid() id), inserted as (insert into public.organic_decision_runs (id,business_id,snapshot_fingerprint,input_hash,source_references,discovery_version,state,outcome,candidate_count,discovery_completeness,limitation_codes,correlation_id,started_at,completed_at,created_at) select n.id,r.business_id,encode(digest(r.snapshot_fingerprint || ':recovery','sha256'),'hex'),r.input_hash,r.source_references,r.discovery_version,'discovery_complete',r.outcome,r.candidate_count,r.discovery_completeness,r.limitation_codes,r.correlation_id,now(),now(),now() from public.organic_decision_runs r cross join new_run n where r.id='ba588084-b023-49f6-85ac-07412a23aff9' returning id) insert into recovery_ids(recovery_run_id) select id from inserted;
insert into public.organic_opportunity_candidates (candidate_id,business_id,decision_run_id,candidate_identity,candidate_type,target_resources,target_resource_type,discovery_sources,evidence_refs,direct_derived_relationships,market,language,freshness_state,completeness,limitations,overlap_group_id,candidate_status,rejection_reason_codes,snapshot_id,candidate_version,evaluated_at,created_at,allowed_target_refs) select cm.new_id,business_id,(select recovery_run_id from recovery_ids),candidate_identity,candidate_type,target_resources,target_resource_type,discovery_sources,evidence_refs,direct_derived_relationships,market,language,freshness_state,completeness,limitations,overlap_group_id,candidate_status,rejection_reason_codes,snapshot_id,candidate_version,evaluated_at,created_at,allowed_target_refs from public.organic_opportunity_candidates c join candidate_map cm on cm.old_id=c.candidate_id where decision_run_id='ba588084-b023-49f6-85ac-07412a23aff9';
with new_eval as (select gen_random_uuid() id), inserted as (insert into public.organic_candidate_evaluation_runs (id,business_id,decision_run_id,evaluation_version,input_hash,filter_version,interpretation_version,instruction_version,state,discovered_count,deterministic_rejected_count,post_filter_count,bounded_out_count,interpreted_count,interpretive_rejected_count,overlap_group_count,model_provider,model_name,model_request_attempts,input_tokens,output_tokens,limitation_codes,correlation_id,started_at,completed_at,created_at,retry_used,estimated_cost_usd,cost_status) select n.id,e.business_id,(select recovery_run_id from recovery_ids),e.evaluation_version,e.input_hash,e.filter_version,e.interpretation_version,e.instruction_version,'filter_complete',e.discovered_count,e.deterministic_rejected_count,e.post_filter_count,e.bounded_out_count,e.interpreted_count,e.interpretive_rejected_count,e.overlap_group_count,e.model_provider,e.model_name,0,0,0,e.limitation_codes,e.correlation_id,now(),null,now(),false,null,'unknown' from public.organic_candidate_evaluation_runs e cross join new_eval n where e.id='494d0f4a-6306-4dd1-ac97-14a8a843d42c' returning id) update recovery_ids set recovery_eval_id=(select id from inserted);
insert into public.organic_candidate_evaluations (business_id,evaluation_run_id,decision_run_id,candidate_id,evaluation_version,deterministic_disposition,deterministic_reason_codes,overlap_group_id,target_attribution_state,attributed_target_resources,customer_job,intent_class,intent_confidence,page_type_fit,relevance_state,new_asset_fit,interpretation_state,interpretive_disposition,interpretive_reason_codes,evidence_refs,limitations,interpretation_input_hash,model_provider,model_name,instruction_version,provider_response_id,input_tokens,output_tokens,created_at,completed_at) select e.business_id,(select recovery_eval_id from recovery_ids),(select recovery_run_id from recovery_ids),cm.new_id,e.evaluation_version,e.deterministic_disposition,e.deterministic_reason_codes,e.overlap_group_id,e.target_attribution_state,e.attributed_target_resources,e.customer_job,e.intent_class,e.intent_confidence,e.page_type_fit,e.relevance_state,e.new_asset_fit,e.interpretation_state,e.interpretive_disposition,e.interpretive_reason_codes,e.evidence_refs,e.limitations,e.interpretation_input_hash,e.model_provider,e.model_name,e.instruction_version,e.provider_response_id,e.input_tokens,e.output_tokens,now(),now() from public.organic_candidate_evaluations e join candidate_map cm on cm.old_id=e.candidate_id where e.evaluation_run_id='494d0f4a-6306-4dd1-ac97-14a8a843d42c' and e.candidate_id in (select unnest(candidate_ids) from public.organic_candidate_interpretation_batches where evaluation_run_id='494d0f4a-6306-4dd1-ac97-14a8a843d42c' and batch_index<3);
insert into public.organic_candidate_interpretation_batches (id,business_id,evaluation_run_id,batch_index,candidate_ids,input_hash,state,request_attempts,provider,model,response_id,input_tokens,output_tokens,safe_error_code,created_at,completed_at,claim_token,claimed_at,claim_expires_at,estimated_cost_usd,cost_status,attempt_started_at,last_attempt_response_id,last_attempt_input_tokens,last_attempt_output_tokens,last_attempt_cost_usd,last_attempt_cost_status,outcome_state) select gen_random_uuid(),business_id,(select recovery_eval_id from recovery_ids),batch_index,array(select cm.new_id from unnest(b.candidate_ids) u(old_id) join candidate_map cm on cm.old_id=u.old_id),input_hash,case when batch_index<3 then 'complete' else 'pending' end,case when batch_index<3 then 1 else 0 end,case when batch_index<3 then provider else null end,case when batch_index<3 then model else null end,case when batch_index<3 then response_id else null end,case when batch_index<3 then input_tokens else 0 end,case when batch_index<3 then output_tokens else 0 end,null,now(),case when batch_index<3 then now() else null end,null,null,null,case when batch_index<3 then estimated_cost_usd else null end,case when batch_index<3 then cost_status else 'unknown' end,null,null,0,0,null,'unknown',case when batch_index<3 then 'complete' else 'not_started' end from public.organic_candidate_interpretation_batches b where evaluation_run_id='494d0f4a-6306-4dd1-ac97-14a8a843d42c';
select recovery_run_id,recovery_eval_id from recovery_ids;
commit;
