import { ProductError } from "../../product-kernel/errors.js";
import { loadWooStoreContext } from "../../product-kernel/woocommerceRouteService.js";
import { wooCollectionRequest, wooRequest } from "../../product-kernel/woocommerceEgress.js";

const FIELDS = {
  products: ["id", "type"],
  variations: ["id", "parent_id"],
  categories: ["id"],
  orders: ["id", "status", "date_created_gmt", "line_items", "refunds"],
  refunds: ["id", "amount", "line_items", "shipping_lines", "fee_lines"],
};
const MAX_PAGES = 10000;
const money = (value, label) => {
  if (typeof value !== "string" || !/^-?(?:0|[1-9][0-9]*)(?:\.[0-9]+)?$/.test(value)) {
    throw new ProductError("REFERENCE_BLOCKED", `WooCommerce ${label} was malformed.`, 502);
  }
  return value;
};
export function refundMagnitude(value, label) { const decimal = money(value, label); return decimal.startsWith("-") ? decimal.slice(1) : decimal; }
function parts(value) { const negative = String(value).startsWith("-"); const [i, f = ""] = String(value).replace(/^-/, "").split("."); return { negative, i, f }; }
export function addDecimal(a = "0", b = "0") { const x = parts(a), y = parts(b), scale = Math.max(x.f.length, y.f.length), factor = 10n ** BigInt(scale); const signed = z => (z.negative ? -1n : 1n) * (BigInt(z.i) * factor + BigInt(z.f.padEnd(scale, "0") || "0")); const n = signed(x) + signed(y), neg = n < 0n, abs = neg ? -n : n, i = abs / factor, f = abs % factor; return `${neg ? "-" : ""}${i}${scale ? `.${String(f).padStart(scale, "0")}` : ""}`; }
export function subtractDecimal(a, b) { return addDecimal(a, `-${b}`); }
const equalDecimal = (a, b) => a !== null && b !== null && /^0(?:\.0+)?$/.test(subtractDecimal(String(a), String(b)));
const positive = value => Number.isSafeInteger(value) && value > 0 ? value : null;
const statusClass = status => ["processing", "completed", "refunded"].includes(status) ? "recognised" : ["cancelled", "failed"].includes(status) ? "excluded" : ["pending", "on-hold"].includes(status) ? "unknown" : "unclassified";
export function classifyReferenceStatus(status) { return statusClass(status); }
function pageNumber(headers, key) { const value = headers?.[key] ?? headers?.[key.toLowerCase()]; if (typeof value !== "string" || !/^(?:0|[1-9][0-9]{0,5})$/.test(value)) throw new ProductError("REFERENCE_BLOCKED", "WooCommerce pagination was malformed.", 502); return Number(value); }
async function paginate(provider, path, fields, query = {}, perPage = 100) { const rows = []; let pages = null; for (let page = 1; page <= MAX_PAGES; page += 1) { const result = await provider.collection(path, { fields, query: { ...query, page, per_page: perPage } }); if (!Array.isArray(result.data)) throw new ProductError("REFERENCE_BLOCKED", "WooCommerce collection was malformed.", 502); const total = pageNumber(result.headers, "x-wp-total"), totalPages = pageNumber(result.headers, "x-wp-totalpages"); if (totalPages > MAX_PAGES || totalPages < Math.ceil(total / perPage) || pages !== null && pages !== totalPages || total === 0 && totalPages !== 0) throw new ProductError("REFERENCE_BLOCKED", "WooCommerce pagination was malformed.", 502); pages = totalPages; if (!totalPages) return rows; rows.push(...result.data); if (page === totalPages) { if (rows.length !== total) throw new ProductError("REFERENCE_BLOCKED", "WooCommerce collection was incomplete.", 502); return rows; } } throw new ProductError("REFERENCE_BLOCKED", "WooCommerce pagination exceeded its bound.", 502); }
export function parseReferenceRefund(refund, orderId) { const id = positive(refund.id); if (!id) throw new ProductError("REFERENCE_BLOCKED", "WooCommerce refund identity was malformed.", 502); const total = refundMagnitude(refund.amount, "refund amount"); const lines = []; for (const line of Array.isArray(refund.line_items) ? refund.line_items : []) { const meta = Array.isArray(line.meta_data) ? line.meta_data.find(item => item?.key === "_refunded_item_id") : null; const lineId = positive(Number(meta?.value)); if (line.total === undefined || line.total_tax === undefined) throw new ProductError("REFERENCE_BLOCKED", "WooCommerce refund line money was malformed.", 502); if (lineId) lines.push({ lineId, total: refundMagnitude(line.total, "refund line total"), tax: refundMagnitude(line.total_tax, "refund line tax") }); }
  let knownGross = "0"; for (const line of lines) knownGross = addDecimal(knownGross, addDecimal(line.total, line.tax)); let components = "0"; for (const item of [...(refund.shipping_lines || []), ...(refund.fee_lines || [])]) { if (item.total === undefined) throw new ProductError("REFERENCE_BLOCKED", "WooCommerce refund component money was malformed.", 502); components = addDecimal(components, addDecimal(refundMagnitude(item.total, "refund component total"), item.total_tax === undefined ? "0" : refundMagnitude(item.total_tax, "refund component tax"))); } const remainder = subtractDecimal(total, addDecimal(knownGross, components)); if (remainder.startsWith("-")) throw new ProductError("REFERENCE_BLOCKED", "WooCommerce refund components conflicted with the provider total.", 502); return { id, orderId, lines, unattributed: remainder };
}
export async function collectReference({ admin, connectionId, orderWindow, perPage = 100, transport = {} }) {
  if (!orderWindow || typeof orderWindow.start !== "string" || typeof orderWindow.end !== "string") throw new ProductError("INVALID_REQUEST", "The exact Product order window is required.", 400);
  const context = await loadWooStoreContext(admin, connectionId);
  const requestCollection = transport.collection || ((path, options) => wooCollectionRequest(context.store.canonical_base_url, `wp-json/wc/v3/${path}`, { ...options, credentials: context.credentials }));
  const requestGet = transport.get || ((path, options) => wooRequest(context.store.canonical_base_url, `wp-json/wc/v3/${path}`, { ...options, credentials: context.credentials }));
  const provider = { collection: requestCollection, get: requestGet };
  const products = await paginate(provider, "products", FIELDS.products, {}, perPage);
  const variations = []; for (const product of products.filter(row => row.type === "variable")) variations.push(...await paginate(provider, `products/${positive(product.id)}/variations`, FIELDS.variations, {}, perPage));
  const categories = await paginate(provider, "products/categories", FIELDS.categories, {}, perPage);
  const orders = await paginate(provider, "orders", FIELDS.orders, { after: orderWindow.start, before: orderWindow.end, dates_are_gmt: "true", status: "any", orderby: "date", order: "asc" }, perPage);
  const refunds = []; for (const order of orders) for (const summary of Array.isArray(order.refunds) ? order.refunds : []) refunds.push(parseReferenceRefund(await provider.get(`orders/${positive(order.id)}/refunds/${positive(summary.id || summary.refund_id)}`, { fields: FIELDS.refunds }), positive(order.id)));
  const source = { products: products.length, variations: variations.length, categories: categories.length, orders: orders.length }; const expected = calculateExpected({ orders, refunds });
  return { source, expected, source_signature: JSON.stringify({ source, expected }), window: { start: orderWindow.start, end: orderWindow.end } };
}
export function calculateExpected({ orders = [], refunds = [] }) { const expected = new Map(); for (const order of orders) { if (statusClass(order.status) !== "recognised") continue; for (const line of Array.isArray(order.line_items) ? order.line_items : []) { const productId = positive(Number(line.product_id)); if (line.total === undefined || line.total_tax === undefined) throw new ProductError("REFERENCE_BLOCKED", "WooCommerce recognised order line money was malformed.", 502); const variationId = positive(Number(line.variation_id)); const key = `${productId}/${variationId || "null"}`; const prior = expected.get(key) || { product_source_id: productId, variation_source_id: variationId, product_net_sales_ex_tax: "0", product_tax: "0" }; prior.product_net_sales_ex_tax = addDecimal(prior.product_net_sales_ex_tax, money(line.total, "order line total")); prior.product_tax = addDecimal(prior.product_tax, money(line.total_tax, "order line tax")); expected.set(key, prior); } }
  for (const refund of refunds) for (const line of refund.lines || []) { const order = orders.find(item => positive(item.id) === refund.orderId); const sourceLine = order?.line_items?.find(item => positive(Number(item.id)) === line.lineId); if (!sourceLine) continue; const key = `${positive(Number(sourceLine.product_id))}/${positive(Number(sourceLine.variation_id)) || "null"}`; const row = expected.get(key); if (row) { row.product_net_sales_ex_tax = subtractDecimal(row.product_net_sales_ex_tax, line.total); row.product_tax = subtractDecimal(row.product_tax, line.tax); } }
  return [...expected.values()].sort((a, b) => `${a.product_source_id}/${a.variation_source_id}`.localeCompare(`${b.product_source_id}/${b.variation_source_id}`)); }
export function compareReference(expected, product) { const keys = new Set([...expected.expected, ...(product.rows || [])].map(row => `${row.product_source_id}/${row.variation_source_id || "null"}`)); const rows = [...keys].sort().map(key => { const e = expected.expected.find(row => `${row.product_source_id}/${row.variation_source_id || "null"}` === key); const p = (product.rows || []).find(row => `${row.product_source_id}/${row.variation_source_id || "null"}` === key); const expectedExTax = e?.product_net_sales_ex_tax ?? null, productExTax = p?.product_net_sales_ex_tax ?? null, expectedTax = e?.product_tax ?? null, productTax = p?.product_tax ?? null; return { product_source_id: e?.product_source_id ?? p?.product_source_id, variation_source_id: e?.variation_source_id ?? p?.variation_source_id, expected_product_net_sales_ex_tax: expectedExTax, product_net_sales_ex_tax: productExTax, difference: expectedExTax === null || productExTax === null ? null : subtractDecimal(String(expectedExTax), String(productExTax)), expected_product_tax: expectedTax, product_tax: productTax, result: equalDecimal(expectedExTax, productExTax) && equalDecimal(expectedTax, productTax) ? "PASS" : "FAIL" }; }); return { rows, overall: rows.some(row => row.result === "FAIL") ? "FAIL" : "PASS" }; }
export { statusClass };
