import { ProductError } from "../../product-kernel/errors.js";
import { loadWooStoreContext } from "../../product-kernel/woocommerceRouteService.js";
import { wooCollectionRequest, wooRequest } from "../../product-kernel/woocommerceEgress.js";

const FIELDS = {
  products: ["id", "type", "categories"],
  variations: ["id", "parent_id"],
  categories: ["id"],
  orders: ["id", "status", "date_created_gmt", "line_items", "refunds"],
  refunds: ["id", "amount", "line_items", "shipping_lines", "fee_lines"],
};
const MAX_PAGES = 10000;
const money = (value, label) => {
  if (typeof value !== "string" || !/^-?(?:0|[1-9][0-9]*)(?:\.[0-9]+)?$/.test(value)) {
    throw new ProductError("REFERENCE_BLOCKED", `WooCommerce ${label} was malformed.`, 502);
  }
  return value;
};
export function refundMagnitude(value, label) { const decimal = money(value, label); return decimal.startsWith("-") ? decimal.slice(1) : decimal; }
function parts(value) { const negative = String(value).startsWith("-"); const [i, f = ""] = String(value).replace(/^-/, "").split("."); return { negative, i, f }; }
export function addDecimal(a = "0", b = "0") { const x = parts(a), y = parts(b), scale = Math.max(x.f.length, y.f.length), factor = 10n ** BigInt(scale); const signed = z => (z.negative ? -1n : 1n) * (BigInt(z.i) * factor + BigInt(z.f.padEnd(scale, "0") || "0")); const n = signed(x) + signed(y), neg = n < 0n, abs = neg ? -n : n, i = abs / factor, f = abs % factor; return `${neg ? "-" : ""}${i}${scale ? `.${String(f).padStart(scale, "0")}` : ""}`; }
export function subtractDecimal(a, b) { return addDecimal(a, `-${b}`); }
const equalDecimal = (a, b) => a !== null && b !== null && /^0(?:\.0+)?$/.test(subtractDecimal(String(a), String(b)));
const positive = value => Number.isSafeInteger(value) && value > 0 ? value : null;
const statusClass = status => ["processing", "completed", "refunded"].includes(status) ? "recognised" : ["cancelled", "failed"].includes(status) ? "excluded" : ["pending", "on-hold"].includes(status) ? "unknown" : "unclassified";
export function classifyReferenceStatus(status) { return statusClass(status); }
function referenceProductCategoryIds(product) {
  if (!Array.isArray(product?.categories)) throw new ProductError("REFERENCE_BLOCKED", "WooCommerce Product categories were malformed.", 502);
  const ids = product.categories.map(category => positive(Number(category?.id)));
  if (ids.some(id => !id)) throw new ProductError("REFERENCE_BLOCKED", "WooCommerce Product category identity was malformed.", 502);
  return [...new Set(ids)].sort((a, b) => a - b);
}
function pageNumber(headers, key) { const value = headers?.[key] ?? headers?.[key.toLowerCase()]; if (typeof value !== "string" || !/^(?:0|[1-9][0-9]{0,5})$/.test(value)) throw new ProductError("REFERENCE_BLOCKED", "WooCommerce pagination was malformed.", 502); return Number(value); }
async function paginate(provider, path, fields, query = {}, perPage = 100) { const rows = []; let pages = null; for (let page = 1; page <= MAX_PAGES; page += 1) { const result = await provider.collection(path, { fields, query: { ...query, page, per_page: perPage } }); if (!Array.isArray(result.data)) throw new ProductError("REFERENCE_BLOCKED", "WooCommerce collection was malformed.", 502); const total = pageNumber(result.headers, "x-wp-total"), totalPages = pageNumber(result.headers, "x-wp-totalpages"); if (totalPages > MAX_PAGES || totalPages < Math.ceil(total / perPage) || pages !== null && pages !== totalPages || total === 0 && totalPages !== 0) throw new ProductError("REFERENCE_BLOCKED", "WooCommerce pagination was malformed.", 502); pages = totalPages; if (!totalPages) return rows; rows.push(...result.data); if (page === totalPages) { if (rows.length !== total) throw new ProductError("REFERENCE_BLOCKED", "WooCommerce collection was incomplete.", 502); return rows; } } throw new ProductError("REFERENCE_BLOCKED", "WooCommerce pagination exceeded its bound.", 502); }
export function parseReferenceRefund(refund, orderId) { const id = positive(refund.id); if (!id) throw new ProductError("REFERENCE_BLOCKED", "WooCommerce refund identity was malformed.", 502); const total = refundMagnitude(refund.amount, "refund amount"); const lines = []; for (const line of Array.isArray(refund.line_items) ? refund.line_items : []) { const meta = Array.isArray(line.meta_data) ? line.meta_data.find(item => item?.key === "_refunded_item_id") : null; const lineId = positive(Number(meta?.value)); if (line.total === undefined || line.total_tax === undefined) throw new ProductError("REFERENCE_BLOCKED", "WooCommerce refund line money was malformed.", 502); if (lineId) lines.push({ lineId, total: refundMagnitude(line.total, "refund line total"), tax: refundMagnitude(line.total_tax, "refund line tax") }); }
  let knownGross = "0"; for (const line of lines) knownGross = addDecimal(knownGross, addDecimal(line.total, line.tax)); const components = []; let componentTotal = "0"; for (const item of [...(refund.shipping_lines || []), ...(refund.fee_lines || [])]) { if (item.total === undefined) throw new ProductError("REFERENCE_BLOCKED", "WooCommerce refund component money was malformed.", 502); const component = { total: refundMagnitude(item.total, "refund component total"), tax: item.total_tax === undefined ? "0" : refundMagnitude(item.total_tax, "refund component tax") }; components.push(component); componentTotal = addDecimal(componentTotal, addDecimal(component.total, component.tax)); } const remainder = subtractDecimal(total, addDecimal(knownGross, componentTotal)); if (remainder.startsWith("-")) throw new ProductError("REFERENCE_BLOCKED", "WooCommerce refund components conflicted with the provider total.", 502); return { id, orderId, total, lines, components, unattributed: remainder };
}
export async function collectReference({ admin, connectionId, orderWindow, perPage = 100, transport = {} }) {
  if (!orderWindow || typeof orderWindow.start !== "string" || typeof orderWindow.end !== "string") throw new ProductError("INVALID_REQUEST", "The exact Product order window is required.", 400);
  const context = await loadWooStoreContext(admin, connectionId);
  const requestCollection = transport.collection || ((path, options) => wooCollectionRequest(context.store.canonical_base_url, `wp-json/wc/v3/${path}`, { ...options, credentials: context.credentials }));
  const requestGet = transport.get || ((path, options) => wooRequest(context.store.canonical_base_url, `wp-json/wc/v3/${path}`, { ...options, credentials: context.credentials }));
  const provider = { collection: requestCollection, get: requestGet };
  const products = await paginate(provider, "products", FIELDS.products, {}, perPage);
  const variations = []; for (const product of products.filter(row => row.type === "variable")) variations.push(...await paginate(provider, `products/${positive(product.id)}/variations`, FIELDS.variations, {}, perPage));
  const categories = await paginate(provider, "products/categories", FIELDS.categories, {}, perPage);
  const orders = await paginate(provider, "orders", FIELDS.orders, { after: orderWindow.start, before: orderWindow.end, dates_are_gmt: "true", status: "any", orderby: "date", order: "asc" }, perPage);
  const refunds = []; for (const order of orders) for (const summary of Array.isArray(order.refunds) ? order.refunds : []) refunds.push(parseReferenceRefund(await provider.get(`orders/${positive(order.id)}/refunds/${positive(summary.id || summary.refund_id)}`, { fields: FIELDS.refunds }), positive(order.id)));
  const categoryIds = new Set(categories.map(row => positive(Number(row.id))));
  if ([...categoryIds].some(id => !id)) throw new ProductError("REFERENCE_BLOCKED", "WooCommerce category identity was malformed.", 502);
  const productCategoryLinks = products.flatMap(product => { const productId = positive(Number(product.id)); if (!productId) throw new ProductError("REFERENCE_BLOCKED", "WooCommerce Product identity was malformed.", 502); return referenceProductCategoryIds(product).map(categoryId => { if (!categoryIds.has(categoryId)) throw new ProductError("REFERENCE_BLOCKED", "WooCommerce Product referenced an unavailable category.", 502); return { product_source_id: productId, category_source_id: categoryId }; }); });
  const source = { products: products.length, variations: variations.length, categories: categories.length, product_category_links: productCategoryLinks.length, orders: orders.length, links: productCategoryLinks }; const expected = calculateExpected({ orders, refunds });
  return { source, expected, source_signature: buildSourceSignature({ products, variations, categories, orders, refunds }), window: { start: orderWindow.start, end: orderWindow.end } };
}
export function buildSourceSignature({ products = [], variations = [], categories = [], orders = [], refunds = [] }) { const safe = { products: products.map(row => ({ id: positive(Number(row.id)), type: row.type ?? null, category_ids: referenceProductCategoryIds(row) })).sort((a, b) => `${a.id}/${a.type}`.localeCompare(`${b.id}/${b.type}`)), variations: variations.map(row => ({ id: positive(Number(row.id)), parent_id: positive(Number(row.parent_id)) })).sort((a, b) => `${a.id}/${a.parent_id}`.localeCompare(`${b.id}/${b.parent_id}`)), categories: categories.map(row => ({ id: positive(Number(row.id)) })).sort((a, b) => a.id - b.id), orders: orders.map(row => ({ id: positive(Number(row.id)), status: row.status ?? null, date_created_gmt: row.date_created_gmt ?? null, lines: (Array.isArray(row.line_items) ? row.line_items : []).map(line => ({ id: positive(Number(line.id)), product_id: positive(Number(line.product_id)), variation_id: positive(Number(line.variation_id)), total: line.total ?? null, total_tax: line.total_tax ?? null })).sort((a, b) => `${a.id}/${a.product_id}/${a.variation_id}`.localeCompare(`${b.id}/${b.product_id}/${b.variation_id}`)), refund_ids: (Array.isArray(row.refunds) ? row.refunds : []).map(refund => positive(Number(refund.id || refund.refund_id))).sort((a, b) => a - b) })).sort((a, b) => a.id - b.id), refunds: refunds.map(refund => ({ id: refund.id, order_id: refund.orderId, total: refund.total, lines: refund.lines.map(line => ({ line_id: line.lineId, total: line.total, tax: line.tax })).sort((a, b) => a.line_id - b.line_id), components: refund.components, unattributed: refund.unattributed })).sort((a, b) => `${a.order_id}/${a.id}`.localeCompare(`${b.order_id}/${b.id}`)) }; return JSON.stringify(safe); }
export function calculateExpected({ orders = [], refunds = [] }) { const expected = new Map(); for (const order of orders) { if (statusClass(order.status) !== "recognised") continue; for (const line of Array.isArray(order.line_items) ? order.line_items : []) { const productId = positive(Number(line.product_id)); if (line.total === undefined || line.total_tax === undefined) throw new ProductError("REFERENCE_BLOCKED", "WooCommerce recognised order line money was malformed.", 502); const variationId = positive(Number(line.variation_id)); const key = `${productId}/${variationId || "null"}`; const prior = expected.get(key) || { product_source_id: productId, variation_source_id: variationId, product_net_sales_ex_tax: "0", product_tax: "0" }; prior.product_net_sales_ex_tax = addDecimal(prior.product_net_sales_ex_tax, money(line.total, "order line total")); prior.product_tax = addDecimal(prior.product_tax, money(line.total_tax, "order line tax")); expected.set(key, prior); } }
  for (const refund of refunds) for (const line of refund.lines || []) { const order = orders.find(item => positive(item.id) === refund.orderId); const sourceLine = order?.line_items?.find(item => positive(Number(item.id)) === line.lineId); if (!sourceLine) continue; const key = `${positive(Number(sourceLine.product_id))}/${positive(Number(sourceLine.variation_id)) || "null"}`; const row = expected.get(key); if (row) { row.product_net_sales_ex_tax = subtractDecimal(row.product_net_sales_ex_tax, line.total); row.product_tax = subtractDecimal(row.product_tax, line.tax); } }
  return [...expected.values()].sort((a, b) => `${a.product_source_id}/${a.variation_source_id}`.localeCompare(`${b.product_source_id}/${b.variation_source_id}`)); }
function canonicalLinks(links = []) { return links.map(link => ({ product_source_id: positive(Number(link.product_source_id)), category_source_id: positive(Number(link.category_source_id)) })).filter(link => link.product_source_id && link.category_source_id).sort((a, b) => a.product_source_id - b.product_source_id || a.category_source_id - b.category_source_id); }
function sameLinks(left, right) { const a = canonicalLinks(left), b = canonicalLinks(right); return a.length === b.length && a.every((link, index) => link.product_source_id === b[index].product_source_id && link.category_source_id === b[index].category_source_id); }
export function compareReference(expected, product) { const keys = new Set([...expected.expected, ...(product.rows || [])].map(row => `${row.product_source_id}/${row.variation_source_id || "null"}`)); const rows = [...keys].sort().map(key => { const e = expected.expected.find(row => `${row.product_source_id}/${row.variation_source_id || "null"}` === key); const p = (product.rows || []).find(row => `${row.product_source_id}/${row.variation_source_id || "null"}` === key); const expectedExTax = e?.product_net_sales_ex_tax ?? null, productExTax = p?.product_net_sales_ex_tax ?? null, expectedTax = e?.product_tax ?? null, productTax = p?.product_tax ?? null; const expectedNumeric = e && expectedExTax !== null && expectedTax !== null; const productNullAggregate = p && productExTax === null && productTax === null; const result = !e ? (productNullAggregate ? "PASS" : "FAIL") : expectedNumeric ? (p && productExTax !== null && productTax !== null && equalDecimal(expectedExTax, productExTax) && equalDecimal(expectedTax, productTax) ? "PASS" : "FAIL") : "FAIL"; return { product_source_id: e?.product_source_id ?? p?.product_source_id, variation_source_id: e?.variation_source_id ?? p?.variation_source_id, expected_product_net_sales_ex_tax: expectedExTax, product_net_sales_ex_tax: productExTax, difference: expectedExTax === null || productExTax === null ? null : subtractDecimal(String(expectedExTax), String(productExTax)), expected_product_tax: expectedTax, product_tax: productTax, result, ...(result === "PASS" && !e ? { reason: "NO_RECOGNISED_SALES" } : {}) }; }); const linksPass = sameLinks(expected.source?.links || [], product.links || []); return { rows, links: { source: expected.source?.product_category_links || 0, product: (product.links || []).length, result: linksPass ? "PASS" : "FAIL" }, overall: rows.every(row => row.result === "PASS") && linksPass ? "PASS" : "FAIL" }; }
export { statusClass };
